Repository Arize-ai/phoenix, pull requests merged in 2024-11, with the labels that each got.

#5251 feat: Only show providers if dependencies are installed
  app/schema.graphql
  src/phoenix/server/api/helpers/playground_clients.py
  src/phoenix/server/api/helpers/playground_registry.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/GenerativeProvider.py
Labels: size:M

#5256 feat: Provide and then parse invocation params from Span into Playground page store
  app/schema.graphql
  app/src/pages/playground/InvocationParametersForm.tsx
  app/src/pages/playground/__generated__/spanPlaygroundPageLoaderQuery.graphql.ts
  app/src/pages/playground/__tests__/fixtures.ts
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/playground/spanPlaygroundPageLoader.ts
  pyproject.toml
  src/phoenix/server/api/types/Span.py
  uv.lock
Labels: size:L

#5206 feat: convert tool call schemas between providers
  app/src/components/code/JSONEditor.tsx
  app/src/pages/playground/ChatMessageToolCallsEditor.tsx
  app/src/pages/playground/ModelConfigButton.tsx
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/PlaygroundTool.tsx
  app/src/pages/playground/PlaygroundToolCall.tsx
  app/src/pages/playground/PlaygroundTools.tsx
  app/src/pages/playground/__tests__/fixtures.ts
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/playground/schemas.ts
  app/src/schemas/__tests__/fixtures.ts
  app/src/schemas/__tests__/toolCallSchemas.test.ts
  app/src/schemas/__tests__/toolSchemas.test.ts
  app/src/schemas/index.ts
  app/src/schemas/toolCallSchemas.ts
  app/src/schemas/toolSchemas.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
  app/src/typeUtils.ts
Labels: size:XXL

#5255 feat: Add chat completion mutation
  app/schema.graphql
  src/phoenix/server/api/mutations/__init__.py
  src/phoenix/server/api/mutations/chat_mutations.py
Labels: size:L

#5270 fix: use truncatedValue for descendant span input output values
  app/src/pages/project/TracesTable.tsx
  app/src/pages/project/__generated__/ProjectPageQuery.graphql.ts
  app/src/pages/project/__generated__/TracesTableQuery.graphql.ts
  app/src/pages/project/__generated__/TracesTable_spans.graphql.ts
Labels: size:L

#5273 chore: collect customer issues pending triage and send them to slack
  .github/workflows/collect-customer-issues.yaml
Labels: size:L

#5237 feat(playground): streaming chat completion over a dataset
  app/schema.graphql
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  src/phoenix/server/api/helpers/playground_clients.py
  src/phoenix/server/api/helpers/playground_registry.py
  src/phoenix/server/api/helpers/playground_spans.py
  src/phoenix/server/api/input_types/ChatCompletionInput.py
  src/phoenix/server/api/mutations/chat_mutations.py
  src/phoenix/server/api/schema.py
  src/phoenix/server/api/subscriptions.py
  src/phoenix/server/api/types/ChatCompletionSubscriptionPayload.py
  src/phoenix/server/app.py
  src/phoenix/utilities/template_formatters.py
  tests/unit/server/api/cassettes/test_subscriptions/TestChatCompletionOverDatasetSubscription.test_emits_expected_payloads_and_records_expected_spans_and_experiment[sqlite].yaml
  tests/unit/server/api/test_subscriptions.py
  tests/unit/utilities/test_template_formatters.py
  tox.ini
Labels: size:XXL

#5275 feat: Add environment configuration for fastapi + gql extensions
  src/phoenix/config.py
  src/phoenix/server/app.py
Labels: size:M

#5221 chore(main): release arize-phoenix 5.7.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#5280 feat: Add env var configuration for grpc interceptor extensions
  src/phoenix/config.py
  src/phoenix/server/app.py
  src/phoenix/server/grpc_server.py
Labels: size:M

#5287 fix(evals): only allow keyword arguments for model instantiation
  packages/phoenix-evals/src/phoenix/evals/models/base.py
  packages/phoenix-evals/tests/phoenix/evals/models/test_bedrock.py
  packages/phoenix-evals/tests/phoenix/evals/models/test_litellm.py
  packages/phoenix-evals/tests/phoenix/evals/models/test_mistralai.py
  packages/phoenix-evals/tests/phoenix/evals/models/test_openai.py
Labels: size:S

#5290 chore(main): release arize-phoenix-evals 0.17.3
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#5291 feat: Add empty state, helper tooltips, when provider clients are not installed in Playground
  app/src/components/code/PythonBlock.tsx
  app/src/pages/playground/ModelConfigButton.tsx
  app/src/pages/playground/ModelProviderPicker.tsx
  app/src/pages/playground/NoInstalledProvider.tsx
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/__generated__/ModelConfigButtonDialogQuery.graphql.ts
  app/src/pages/playground/__generated__/ModelProviderPickerFragment.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundQuery.graphql.ts
Labels: size:L

#5289 feat: Add rate limiters to playground clients
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:L

#5296 feat: Support playground anthropic tool calls
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/playground/schemas.ts
  app/src/schemas/toolChoiceSchemas.ts
  requirements/dev.txt
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:L

#5259 feat: Support Response Format in Playground
  .pre-commit-config.yaml
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/PlaygroundResponseFormat.tsx
  app/src/pages/playground/__tests__/fixtures.ts
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/constants.tsx
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/playground/schemas.ts
  app/src/schemas/toolChoiceSchemas.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
Labels: size:XL

#5295 chore: increase look back period for customer issues needing triage
  .eslintignore
  .github/.scripts/collect-customer-issues.js
  .github/workflows/collect-customer-issues.yaml
Labels: size:L

#5297 feat(playground): add dataset selector and dataset examples table to playground
  app/src/components/dataset/CreateDatasetForm.tsx
  app/src/components/dataset/DatasetPicker.tsx
  app/src/components/dataset/NewDatasetButton.tsx
  app/src/components/dataset/__generated__/DatasetPickerQuery.graphql.ts
  app/src/components/dataset/index.tsx
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
  app/src/pages/playground/PlaygroundDatasetPicker.tsx
  app/src/pages/playground/PlaygroundInputModeRadioGroup.tsx
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableFragment.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableQuery.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableRefetchQuery.graphql.ts
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/trace/DatasetPicker.tsx
  app/src/pages/trace/SpanToDatasetExampleDialog.tsx
  app/src/pages/trace/__generated__/DatasetPickerRefetchQuery.graphql.ts
  app/src/pages/trace/__generated__/DatasetPicker__datasets.graphql.ts
  app/src/pages/trace/__generated__/SpanToDatasetExampleDialogQuery.graphql.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
  js/examples/notebooks/tracing_openai_node_tutorial.ipynb
Labels: size:XXL

#5277 refactor(playground): improve streaming experience for chat completions over datasets
  app/schema.graphql
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  src/phoenix/server/api/helpers/playground_spans.py
  src/phoenix/server/api/subscriptions.py
  src/phoenix/server/api/types/ChatCompletionSubscriptionPayload.py
  tests/unit/server/api/cassettes/test_subscriptions/TestChatCompletionOverDatasetSubscription.test_all_spans_yielded_when_number_of_examples_exceeds_batch_size[sqlite].yaml
  tests/unit/server/api/test_subscriptions.py
Labels: size:XXL

#5305 fix: update 2nd slack link in readme
  README.md
Labels: size:XS

#5298 test(playground): organize vcr utilities
  tests/unit/conftest.py
  tests/unit/server/api/cassettes/test_subscriptions/TestChatCompletionOverDatasetSubscription.test_all_spans_yielded_when_number_of_examples_exceeds_batch_size.yaml
  tests/unit/server/api/cassettes/test_subscriptions/TestChatCompletionOverDatasetSubscription.test_emits_expected_payloads_and_records_expected_spans_and_experiment.yaml
  tests/unit/server/api/cassettes/test_subscriptions/TestChatCompletionSubscription.test_anthropic_text_response_emits_expected_payloads_and_records_expected_span.yaml
  tests/unit/server/api/cassettes/test_subscriptions/TestChatCompletionSubscription.test_openai_emits_expected_payloads_and_records_expected_span_on_error.yaml
  tests/unit/server/api/cassettes/test_subscriptions/TestChatCompletionSubscription.test_openai_text_response_emits_expected_payloads_and_records_expected_span.yaml
  tests/unit/server/api/cassettes/test_subscriptions/TestChatCompletionSubscription.test_openai_tool_call_messages_emits_expected_payloads_and_records_expected_span.yaml
  tests/unit/server/api/cassettes/test_subscriptions/TestChatCompletionSubscription.test_openai_tool_call_response_emits_expected_payloads_and_records_expected_span.yaml
  tests/unit/server/api/test_subscriptions.py
  tests/unit/vcr.py
Labels: size:L

#5306 test: use async graphql client in tests
  tests/unit/conftest.py
  tests/unit/graphql.py
  tests/unit/server/api/mutations/test_dataset_mutations.py
  tests/unit/server/api/mutations/test_experiment_mutations.py
  tests/unit/server/api/test_queries.py
  tests/unit/server/api/test_subscriptions.py
Labels: size:XL

#5308 test: move fixtures from `test_subscriptions.py` to `conftest.py`
  tests/unit/server/api/conftest.py
  tests/unit/server/api/test_subscriptions.py
Labels: size:L

#5309 test: use graphql client in unit tests
  pyproject.toml
  tests/unit/graphql.py
  tests/unit/server/api/mutations/test_dataset_mutations.py
  tests/unit/server/api/mutations/test_experiment_mutations.py
  tests/unit/server/api/routers/v1/test_annotations.py
  tests/unit/server/api/test_subscriptions.py
  tests/unit/server/api/types/test_Dataset.py
  tests/unit/server/api/types/test_DatasetExample.py
  tests/unit/server/api/types/test_Experiment.py
  tests/unit/server/api/types/test_ExperimentRun.py
  tests/unit/server/api/types/test_Project.py
  tests/unit/server/api/types/test_Span.py
  tests/unit/server/api/types/test_SpanAnnotation.py
  tests/unit/server/api/types/test_TraceAnnotation.py
Labels: size:XXL

#5316 chore: include customer issues from openinference repo
  .github/.scripts/collect-customer-issues.js
Labels: size:M

#5315 fix: make playground prompts accordion the proper size when collapsed
  app/src/pages/playground/Playground.tsx
Labels: size:XS

#5320 fix(playground): allow scroll in playground prompts
  app/src/pages/playground/Playground.tsx
Labels: size:XS

#5319 feat: route to the projects page as the default
  app/global-setup.ts
  app/src/pages/home/__generated__/homeLoaderQuery.graphql.ts
  app/src/pages/home/homeLoader.ts
  app/tests/admin-access.ts
  app/tests/member-access.spec.ts
  app/tests/user-management.spec.ts
Labels: size:L

#5288 chore(main): release arize-phoenix 5.8.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#5318 feat(playground): display streaming outputs for playground runs on datasets
  app/src/components/code/JSONText.tsx
  app/src/components/dataset/DatasetPicker.tsx
  app/src/components/dataset/__generated__/DatasetPickerQuery.graphql.ts
  app/src/components/table/CellWithControlsWrapper.tsx
  app/src/components/table/index.tsx
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
  app/src/pages/playground/PlaygroundDatasetSection.tsx
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableSubscription.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundDatasetSectionQuery.graphql.ts
  app/src/pages/playground/playgroundUtils.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
Labels: size:XXL

#5322 docs: add multi agent example projects to agent comparison repo
  examples/agent_framework_comparison/autogen_multi_agent/calculator.py
  examples/agent_framework_comparison/autogen_multi_agent/main.py
  examples/agent_framework_comparison/autogen_multi_agent/router.py
  examples/agent_framework_comparison/autogen_multi_agent/sql_query.py
  examples/agent_framework_comparison/crewai_multi_agent/calculator.py
  examples/agent_framework_comparison/crewai_multi_agent/main.py
  examples/agent_framework_comparison/crewai_multi_agent/router.py
  examples/agent_framework_comparison/crewai_multi_agent/sql_query.py
  examples/agent_framework_comparison/db/database.py
  examples/agent_framework_comparison/db/example_traces.db
  examples/agent_framework_comparison/requirements.txt
  examples/agent_framework_comparison/utils/instrument.py
Labels: size:L

#5326 chore: fix formatting
  .github/workflows/python-CI.yml
  examples/agent_framework_comparison/autogen_multi_agent/main.py
  examples/agent_framework_comparison/autogen_multi_agent/router.py
  examples/agent_framework_comparison/autogen_multi_agent/sql_query.py
  examples/agent_framework_comparison/crewai_multi_agent/calculator.py
  examples/agent_framework_comparison/crewai_multi_agent/main.py
  examples/agent_framework_comparison/crewai_multi_agent/router.py
  examples/agent_framework_comparison/crewai_multi_agent/sql_query.py
  examples/agent_framework_comparison/utils/instrument.py
  pyproject.toml
  tox.ini
Labels: size:L

#5329 fix(docs): update dspy install in tutorial notebook
  tutorials/tracing/dspy_tracing_tutorial.ipynb
Labels: size:XS

#5335 chore: fix issues script
  .github/.scripts/collect-customer-issues.js
Labels: size:S

#5339 fix(evals): increase default max tokens
  packages/phoenix-evals/src/phoenix/evals/models/bedrock.py
  packages/phoenix-evals/src/phoenix/evals/models/litellm.py
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
  packages/phoenix-evals/src/phoenix/evals/models/vertex.py
  packages/phoenix-evals/src/phoenix/evals/models/vertexai.py
Labels: size:S

#5340 chore(main): release arize-phoenix-evals 0.17.4
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#5325 feat(playground): graphql mutation for chat completion over dataset
  app/schema.graphql
  src/phoenix/db/helpers.py
  src/phoenix/server/api/mutations/chat_mutations.py
  tests/unit/server/api/mutations/cassettes/test_chat_mutations/TestChatCompletionMutationMixin.test_chat_completion_over_dataset.yaml
  tests/unit/server/api/mutations/test_chat_mutations.py
  tests/unit/vcr.py
Labels: size:L

#5324 feat(playground): add playground dataset example slideover
  app/src/Routes.tsx
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
  app/src/pages/playground/PlaygroundDatasetPicker.tsx
  app/src/pages/playground/PlaygroundExamplePage.tsx
  app/src/store/playground/types.ts
Labels: size:M

#5338 fix(playground): fix dataset picker styles and error handling
  app/src/components/table/styles.ts
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
  app/src/pages/playground/PlaygroundDatasetPicker.tsx
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
  src/phoenix/server/api/queries.py
Labels: size:L

#5342 feat(playground): update PlaygroundDatasetExamplesTable UI to support mutation (in addition to subscription)
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableMutation.graphql.ts
Labels: size:XL

#5336 feat: Render field for JSON invocation params
  app/src/components/code/JSONEditor.tsx
  app/src/pages/playground/InvocationParameterJsonEditor.tsx
  app/src/pages/playground/InvocationParametersForm.tsx
  app/src/pages/playground/__generated__/InvocationParametersFormQuery.graphql.ts
  app/src/utils/jsonUtils.ts
Labels: size:L

#5345 fix(playground): experiment run for chat completion over dataset mutation
  src/phoenix/server/api/mutations/chat_mutations.py
Labels: size:S

#5352 fix(playground): add tooltip for dataset examples
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
Labels: size:M

#5359 feat: Add Google AI Studio support (for Gemini models w/ an API key)
  app/schema.graphql
  app/src/@types/generative.d.ts
  app/src/constants/generativeConstants.ts
  app/src/pages/playground/ChatMessageToolCallsEditor.tsx
  app/src/pages/playground/InvocationParametersForm.tsx
  app/src/pages/playground/PlaygroundCredentialsDropdown.tsx
  app/src/pages/playground/PlaygroundTool.tsx
  app/src/pages/playground/__generated__/InvocationParametersFormQuery.graphql.ts
  app/src/pages/playground/__generated__/ModelConfigButtonDialogQuery.graphql.ts
  app/src/pages/playground/__generated__/ModelProviderPickerFragment.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableMutation.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableSubscription.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundOutputMutation.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/constants.tsx
  app/src/pages/playground/playgroundUtils.ts
  app/src/schemas/toolCallSchemas.ts
  app/src/schemas/toolChoiceSchemas.ts
  app/src/schemas/toolSchemas.ts
  app/src/utils/generativeUtils.ts
  requirements/dev.txt
  src/phoenix/server/api/helpers/playground_clients.py
  src/phoenix/server/api/types/GenerativeProvider.py
Labels: size:L

#5366 fix(auth): allow login form scroll
  app/src/pages/auth/AuthLayout.tsx
Labels: size:XS

#5404 fix(playground): fix pagination on playground dataset examples table
  app/src/pages/dataset/DatasetPage.tsx
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
  app/src/pages/playground/PlaygroundDatasetSection.tsx
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableFragment.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableQuery.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableRefetchQuery.graphql.ts
Labels: size:M

#5372 feat(playground): pre-emptively show dataset example template application errors in playground dataset table
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
  app/src/pages/playground/playgroundUtils.ts
Labels: size:L

#5401 feat(playground): support unknown tool / tool call format
  app/src/components/code/JSONEditor.tsx
  app/src/pages/playground/ChatMessageToolCallsEditor.tsx
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/PlaygroundTool.tsx
  app/src/pages/playground/PlaygroundToolCall.tsx
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/playground/schemas.ts
  app/src/schemas/__tests__/toolCallSchemas.test.ts
  app/src/schemas/__tests__/toolSchemas.test.ts
  app/src/schemas/jsonLiteralSchema.ts
  app/src/schemas/toolCallSchemas.ts
  app/src/schemas/toolSchemas.ts
Labels: size:XL

#5415 fix: copy output contents on run example slideover
  app/src/pages/experiment/ExperimentCompareTable.tsx
Labels: size:XS

#5421 fix: Prevent over-fetching when typing azure deployment name
  app/src/pages/playground/InvocationParametersForm.tsx
  app/src/pages/playground/ModelConfigButton.tsx
Labels: size:M

#5423 fix(playground): for Azure, handle initial chunk with no choices
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:XS

#5375 fix: replace pyarrow with json for dataframe transfer
  requirements/integration-tests.txt
  src/phoenix/server/api/routers/v1/spans.py
  src/phoenix/session/client.py
  src/phoenix/utilities/json.py
  tests/integration/server/test_launch_app.py
  tests/unit/utilities/test_json.py
  tests/utilities/__init__.py
Labels: size:L

#5361 feat(playground): example run slideover
  app/schema.graphql
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
  app/src/pages/playground/PlaygroundExperimentRunDetailsDialog.tsx
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableSubscription.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundExperimentRunDetailsDialogQuery.graphql.ts
  src/phoenix/server/api/types/ExperimentRun.py
Labels: size:XL

#5426 fix(playgroun): use saved model config for default model when switching providers
  app/src/pages/playground/ModelConfigButton.tsx
  app/src/store/playground/playgroundStore.tsx
Labels: size:S

#5425 fix: Hide Output Schema (response format) button on unsupported provider instances
  app/src/pages/playground/InvocationParametersForm.tsx
  app/src/pages/playground/ModelConfigButton.tsx
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/PlaygroundChatTemplateFooter.tsx
  app/src/pages/playground/PlaygroundTemplate.tsx
  app/src/pages/playground/__generated__/PlaygroundChatTemplateFooterResponseFormatQuery.graphql.ts
Labels: size:XL

#5374 fix(auth): ensure auth works behind a proxy
  app/src/authFetch.ts
  app/src/pages/Layout.tsx
  app/src/pages/auth/ForgotPasswordForm.tsx
  app/src/pages/auth/LoginForm.tsx
  app/src/pages/auth/OAuth2Login.tsx
  app/src/pages/auth/ResetPasswordWithTokenForm.tsx
  app/src/utils/__tests__/routingUtils.test.ts
  app/src/utils/routingUtils.ts
  app/vitest.setup.ts
  src/phoenix/config.py
  src/phoenix/server/api/routers/oauth2.py
Labels: size:L

#5432 chore(main): release arize-phoenix 5.9.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#5429 fix(playground): add llm provider and llm system attributes to playground spans
  src/phoenix/server/api/helpers/playground_clients.py
  src/phoenix/server/api/subscriptions.py
  tests/unit/server/api/test_subscriptions.py
Labels: size:M

#5334 feat: Implement "tool" message support for Anthropic
  app/package.json
  app/pnpm-lock.yaml
  app/src/pages/playground/MessageContentRadioGroup.tsx
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/playground/schemas.ts
  app/src/schemas/toolResultSchemas.ts
  src/phoenix/server/api/helpers/playground_clients.py
  src/phoenix/server/api/helpers/playground_spans.py
  tests/unit/server/api/test_subscriptions.py
Labels: size:L

#5438 chore(main): release arize-phoenix-evals 0.17.5
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#5428 fix(playground): compare invocationName and canonical name in all places where we try to find invocation params
  app/src/pages/playground/InvocationParametersForm.tsx
  app/src/pages/playground/PlaygroundResponseFormat.tsx
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/playgroundUtils.ts
  app/src/store/playground/playgroundStore.tsx
  src/phoenix/server/api/types/GenerativeProvider.py
  src/phoenix/server/api/types/Span.py
  tests/unit/server/api/types/test_GenerativeProvider.py
Labels: size:L

#5439 feat: Display playground chat completion errors within output card
  app/src/pages/playground/PlaygroundOutput.tsx
Labels: size:S

#5418 fix(auth): enable non-https OpenID Connect config URLs for development with local IDPs
  src/phoenix/config.py
Labels: size:XS

#5437 chore(main): release arize-phoenix 5.10.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#5445 fix(playground): allow serverside api keys
  app/src/pages/playground/playgroundUtils.ts
  src/phoenix/server/api/mutations/chat_mutations.py
  src/phoenix/server/api/subscriptions.py
Labels: size:M

#5440 fix(playground): add limit on the number of concurrent streams for streaming chat completions over a dataset
  src/phoenix/server/api/subscriptions.py
Labels: size:M

#5450 fix: Allow shrinking of playground dataset table cells that have long text
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
Labels: size:XS

#5447 fix(playground): return error messages for timeouts and unexpected errors during chat completion over dataset subscription
  src/phoenix/server/api/subscriptions.py
Labels: size:L

#5442 fix(playground): update error handling to show unhandled errors in playground
  app/src/pages/playground/InvocationParametersForm.tsx
  app/src/pages/playground/ModelPicker.tsx
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/PlaygroundCredentialsDropdown.tsx
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
  app/src/pages/playground/PlaygroundErrorWrap.tsx
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/utils/__tests__/errorUtils.test.ts
  app/src/utils/errorUtils.ts
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:L

#5453 fix: deselect dataset when selecting active dataset from dropdown
  app/src/pages/playground/PlaygroundDatasetPicker.tsx
Labels: size:XS

#5400 fix(playground): add tool call id to input and output messages
  src/phoenix/server/api/helpers/playground_spans.py
  src/phoenix/server/api/mutations/chat_mutations.py
Labels: size:S

#5467 fix(playground): fix tool call ui
  app/src/pages/playground/schemas.ts
Labels: size:XS

#5468 fix: Allow arbitrary column resizing without tail cell
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
Labels: size:XS

#5471 fix: Parse instrumented tool result messages as tool role messages
  app/src/pages/playground/playgroundUtils.ts
  app/src/schemas/toolResultSchemas.ts
Labels: size:M

#5476 feat(playground): block navigation when runs are in progress
  app/package.json
  app/pnpm-lock.yaml
  app/src/components/ConfirmNavigation.tsx
  app/src/pages/playground/InvocationParametersFormFields.tsx
  app/src/pages/playground/ModelConfigButton.tsx
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundDatasetSection.tsx
  app/src/pages/playground/PlaygroundStreamToggle.tsx
  app/src/pages/playground/__generated__/InvocationParametersFormFieldsQuery.graphql.ts
  app/src/pages/playground/constants.tsx
  app/src/pages/playground/playgroundUtils.ts
  app/src/store/playground/types.ts
  app/src/store/preferencesStore.tsx
Labels: size:L

#5477 fix(playground): batch chat completion requests for mutation
  src/phoenix/server/api/mutations/chat_mutations.py
Labels: size:M

#5488 fix: tighten up playground throttling
  src/phoenix/server/api/helpers/playground_clients.py
  src/phoenix/server/api/subscriptions.py
Labels: size:S

#5487 feat: add environment variable for default admin initial password
  src/phoenix/config.py
  src/phoenix/db/facilitator.py
Labels: size:S

#5497 fix(playground): improve error handling when instantiating playground llm clients
  pyproject.toml
  src/phoenix/server/api/helpers/playground_clients.py
  src/phoenix/server/api/mutations/chat_mutations.py
  src/phoenix/server/api/subscriptions.py
Labels: size:M

#5495 fix: in eval dataframe allow column to be all-null if type doesn't match
  src/phoenix/trace/span_evaluations.py
  tests/unit/trace/test_span_evaluations.py
Labels: size:S

#5496 fix: add backup import for ujson_dumps from pandas.io.json
  src/phoenix/utilities/json.py
Labels: size:XS

#5446 chore(main): release arize-phoenix 5.11.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:M

#5493 fix: Prevent layout shift when scrollbars are introduced
  app/src/pages/playground/Playground.tsx
Labels: size:S

#5506 ci: remove macos due to strange error for python CI
  .github/workflows/python-CI.yml
Labels: size:XS

#5494 fix: Add numeric playground defaults
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:M

#5508 fix: Use more generic `isawaitable` check
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:XS

#5500 feat(playground): add `None` as template formatter option
  app/schema.graphql
  app/src/components/templateEditor/TemplateEditor.tsx
  app/src/components/templateEditor/constants.ts
  app/src/components/templateEditor/templateEditorUtils.ts
  app/src/pages/playground/PlaygroundInput.tsx
  app/src/pages/playground/TemplateLanguageRadioGroup.tsx
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableMutation.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableSubscription.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundOutputMutation.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  app/src/pages/playground/playgroundUtils.ts
  src/phoenix/server/api/mutations/chat_mutations.py
  src/phoenix/server/api/subscriptions.py
  src/phoenix/server/api/types/TemplateLanguage.py
  src/phoenix/utilities/template_formatters.py
Labels: size:M

#5518 fix(playground): capture gemini token count for playground spans
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:XS

#5520 fix(playground): additional model names for anthropic claude
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:XS

#5486 fix(playground): ensure playground timeout errors are displayed
  src/phoenix/server/api/helpers/playground_clients.py
  src/phoenix/server/api/subscriptions.py
Labels: size:M

#5509 feat: Implement "Move Output" button on Playground Output
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/PlaygroundOutputMoveButton.tsx
Labels: size:L

#5538 fix(playground): block playground runs when app is readonly
  app/src/utils/errorUtils.ts
  src/phoenix/server/api/mutations/chat_mutations.py
  src/phoenix/server/api/subscriptions.py
Labels: size:S

#5470 fix: Hide tool button on non-supported providers, Display errors for missing invocation params
  app/src/components/Loading.tsx
  app/src/pages/playground/InvocationParametersFormFields.tsx
  app/src/pages/playground/ModelConfigButton.tsx
  app/src/pages/playground/ModelSupportedParamsFetcher.tsx
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/PlaygroundChatTemplateFooter.tsx
  app/src/pages/playground/PlaygroundTemplate.tsx
  app/src/pages/playground/__generated__/ModelSupportedParamsFetcherQuery.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundChatTemplateFooterResponseFormatQuery.graphql.ts
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/playgroundUtils.ts
  app/src/store/playground/__tests__/playgroundStore.test.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
Labels: size:XL

#5481 feat(sessions): add last start time to UI table for sessions
  app/schema.graphql
  app/src/pages/project/SessionsTable.tsx
  app/src/pages/project/__generated__/ProjectPageSessionsQuery.graphql.ts
  app/src/pages/project/__generated__/SessionsTableQuery.graphql.ts
  app/src/pages/project/__generated__/SessionsTable_sessions.graphql.ts
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/session_last_start_times.py
  src/phoenix/server/api/types/ProjectSession.py
  src/phoenix/server/app.py
Labels: size:L

#5544 fix(playground): update saved model config to overwrite all model config if present
  app/src/pages/playground/ModelConfigButton.tsx
  app/src/pages/playground/ModelSupportedParamsFetcher.tsx
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/PlaygroundOutputMoveButton.tsx
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/playgroundUtils.ts
  app/src/store/playground/__tests__/playgroundStore.test.ts
  app/src/store/playground/__tests__/playgroundStoreUtils.test.ts
  app/src/store/playground/index.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/playgroundStoreUtils.ts
  app/src/store/playground/types.ts
  app/src/store/preferencesStore.tsx
Labels: size:XXL

#5545 fix(playground): improve playground default invocation parameters
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:S

#5527 fix(playground): prepend system message from anthropic span
  app/src/pages/playground/playgroundUtils.ts
Labels: size:S

#5547 fix: Remove seed parameter (no longer accepted by server)
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:XS

#5548 chore(dx): add uv to tox allowlist
  tox.ini
Labels: size:XS

#5549 fix(playground): fix wording on missing input variable in playground over a dataset
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
Labels: size:XS

#5523 fix: ensure retrieval documents are unnested when converting from span to dataset example
  src/phoenix/server/api/helpers/dataset_helpers.py
  src/phoenix/server/api/mutations/dataset_mutations.py
  src/phoenix/server/api/types/Span.py
  tests/unit/server/api/helpers/test_dataset_helpers.py
  tests/unit/server/api/mutations/test_dataset_mutations.py
Labels: size:XL

#5524 fix(playground): use consistent playground experiment run format
  src/phoenix/server/api/helpers/playground_spans.py
  src/phoenix/server/api/mutations/chat_mutations.py
  tests/unit/server/api/test_subscriptions.py
Labels: size:S

#5552 chore(dx): revert add uv to tox allowlist
  tox.ini
Labels: size:XS

#5505 feat: Add evaluations to openapi schema
  schemas/openapi.json
  src/phoenix/server/api/routers/v1/evaluations.py
Labels: size:L

#5550 fix: Properly constrain/rename invocation params before submitting
  app/src/pages/playground/playgroundUtils.ts
Labels: size:XS

#5556 fix(playground): remove cascade of padding on prompts
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundResponseFormat.tsx
Labels: size:M

#5557 chore: align text vertically in experiments
  app/src/pages/playground/PlaygroundDatasetSection.tsx
Labels: size:XS

#5560 chore: remove unused feature flag
  app/src/contexts/FeatureFlagsContext.tsx
Labels: size:XS

#5535 fix: Detect provider from span attribute, fallback to model name heuristic
  app/package.json
  app/pnpm-lock.yaml
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/playground/schemas.ts
Labels: size:M

#5563 chore: Update CI for phoenix-evals and phoenix-otel
  .github/workflows/python-CI.yml
Labels: size:XS

#5551 chore: Add tox command for running phoenix UTs against local evals
  tox.ini
Labels: size:S
