Repository Arize-ai/phoenix, pull requests merged in 2024-06, with the labels that each got.

#3360 chore: remove pytest-lazy-fixture
  pyproject.toml
Labels: size:XS

#3362 feat(datasets): csv upload to create a dataset
  app/src/pages/datasets/DatasetActionMenu.tsx
  app/src/pages/datasets/DatasetFromCSVForm.tsx
  app/src/pages/datasets/DatasetsPage.tsx
Labels: size:L

#3364 fix(datasets): json return payload for upload csv endpoint
  app/src/pages/datasets/DatasetFromCSVForm.tsx
  src/phoenix/server/api/routers/v1/datasets.py
  tests/server/api/routers/v1/test_datasets.py
Labels: size:S

#3370 feat(datasets): sort on version
  app/schema.graphql
  src/phoenix/server/api/input_types/DatasetVersionSort.py
  src/phoenix/server/api/types/Dataset.py
Labels: size:M

#3343 feat: add patchDatasetExamples mutation
  app/schema.graphql
  src/phoenix/server/api/input_types/PatchDatasetExamplesInput.py
  src/phoenix/server/api/mutations/dataset_mutations.py
  tests/server/api/mutations/test_dataset_mutations.py
Labels: size:XL

#3377 feat: Adds timing info to llm_classify
  packages/phoenix-evals/src/phoenix/evals/classify.py
  packages/phoenix-evals/src/phoenix/evals/executors.py
  packages/phoenix-evals/tests/phoenix/evals/functions/test_classify.py
  packages/phoenix-evals/tests/phoenix/evals/functions/test_executor.py
  tutorials/evals/evaluations_with_error_handling.ipynb
Labels: size:XXL

#3379 fix: ensure patches are sorted in numeric patch order
  src/phoenix/server/api/mutations/dataset_mutations.py
Labels: size:S

#3373 feat(datasets): Display latest version
  app/src/components/CopyToClipboardButton.tsx
  app/src/components/LinkButton.tsx
  app/src/contexts/DatasetContext.tsx
  app/src/pages/Layout.tsx
  app/src/pages/dataset/DatasetCodeDropdown.tsx
  app/src/pages/dataset/DatasetExamplePage.tsx
  app/src/pages/dataset/DatasetPage.tsx
  app/src/pages/dataset/ExampleSelectionToolbar.tsx
  app/src/pages/dataset/__generated__/datasetLoaderQuery.graphql.ts
  app/src/pages/dataset/datasetLoader.ts
  app/src/pages/datasets/DatasetsTable.tsx
  app/src/pages/project/ProjectPage.tsx
  app/src/store/__generated__/datasetStore_latestVersionQuery.graphql.ts
  app/src/store/datasetStore.tsx
Labels: size:XL

#3361 refactor(datasets): implement revision resolver on DatasetExample gql type
  app/schema.graphql
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/dataset_example_revisions.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/Dataset.py
  src/phoenix/server/api/types/DatasetExample.py
  src/phoenix/server/api/types/DatasetExampleRevision.py
  src/phoenix/server/app.py
  tests/server/api/mutations/test_dataset_mutations.py
  tests/server/api/types/test_Dataset.py
  tests/server/api/types/test_Project.py
Labels: size:XL

#3382 feat: tweaks to get versioned dataset examples
  src/phoenix/server/api/routers/v1/dataset_examples.py
  tests/server/api/routers/v1/test_dataset_examples.py
Labels: size:M

#3381 feat: add experiment-related tables and migrations
  src/phoenix/db/migrations/versions/10460e46d750_datasets.py
  src/phoenix/db/models.py
Labels: size:L

#3393 fix: add separate package installations to notebooks
  tutorials/tracing/langchain_agent_tracing_tutorial.ipynb
  tutorials/tracing/langchain_google_palm_tracing_tutorial.ipynb
  tutorials/tracing/langchain_tracing_tutorial.ipynb
  tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb
Labels: size:S

#3396 feat(ui): display input and output for tool spans
  app/src/pages/trace/TracePage.tsx
Labels: size:L

#3380 feat: add span-level templates for evaluation hallucinations and qa correctness
  packages/phoenix-evals/src/phoenix/evals/__init__.py
  packages/phoenix-evals/src/phoenix/evals/default_templates.py
  packages/phoenix-evals/src/phoenix/evals/span_templates.py
Labels: size:L

#3378 chore(main): release arize-phoenix-evals 0.12.0
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#3403 fix: percentage sign for alembic configparser
  src/phoenix/db/migrate.py
Labels: size:XS

#3351 chore(main): release arize-phoenix 4.3.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3404 feat(experiments): gql resolver for experiments
  app/schema.graphql
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/Dataset.py
  src/phoenix/server/api/types/Experiment.py
Labels: size:M

#3406 feat: add project resolver on span
  app/schema.graphql
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/span_projects.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/api/types/Span.py
  src/phoenix/server/app.py
  tests/server/api/types/test_Span.py
Labels: size:L

#3394 feat: add span resolver on DatasetExample gql type
  app/schema.graphql
  src/phoenix/db/migrations/versions/10460e46d750_datasets.py
  src/phoenix/db/models.py
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/dataset_example_spans.py
  src/phoenix/server/api/dataloaders/span_descendants.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/DatasetExample.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/api/types/Trace.py
  src/phoenix/server/app.py
  tests/server/api/types/test_DatasetExample.py
Labels: size:L

#3413 feat(datasets): link to view source span
  app/package.json
  app/src/pages/dataset/DatasetExamplePage.tsx
  app/src/pages/dataset/__generated__/DatasetExamplePageQuery.graphql.ts
Labels: size:L

#3411 feat: Implement experiments REST API
  src/phoenix/db/migrations/versions/10460e46d750_datasets.py
  src/phoenix/db/models.py
  src/phoenix/server/api/routers/v1/__init__.py
  src/phoenix/server/api/routers/v1/experiment_evaluations.py
  src/phoenix/server/api/routers/v1/experiment_runs.py
  src/phoenix/server/api/routers/v1/experiments.py
  tests/server/api/routers/v1/test_experiments.py
Labels: size:L

#3419 chore: export openapi schema
  .github/workflows/python-CI.yml
  pyproject.toml
  schemas/openapi.yaml
  src/phoenix/server/api/openapi/main.py
  src/phoenix/server/api/openapi/schema.py
  src/phoenix/server/app.py
Labels: size:L

#3385 chore: remove `set_global_handler` for llama-index instrumentor in notebooks
  examples/using_llamaindex_with_huggingface_models.ipynb
  pyproject.toml
  scripts/rag/llama_index_w_evals_and_qa.py
  scripts/rag/llamaindex_retrieval_chunk_eval.ipynb
  tutorials/evals/evals_sql_correctness_eval_with_custom_agent.ipynb
  tutorials/evals/evaluate_rag.ipynb
  tutorials/integrations/arize_anyscale_traces_and_embeddings.ipynb
  tutorials/llm_application_tracing_evaluating_and_analysis.ipynb
  tutorials/llm_ops_overview.ipynb
  tutorials/mistral/evaluate_rag--mistral.ipynb
  tutorials/ragas_retrieval_evals_tutorial.ipynb
  tutorials/tracing/llama_index_openai_agent_tracing_tutorial.ipynb
  tutorials/tracing/llama_index_sql_retriever_tutorial.ipynb
  tutorials/tracing/llama_index_tracing_tutorial.ipynb
  tutorials/tracing/tracing_with_projects_tutorial.ipynb
Labels: size:XL

#3424 feat(datasets): add example modal
  app/src/pages/dataset/AddDatasetExampleButton.tsx
  app/src/pages/dataset/AddDatasetExampleDialog.tsx
  app/src/pages/dataset/DatasetExamplesTable.tsx
  app/src/pages/dataset/DatasetPage.tsx
  app/src/pages/dataset/__generated__/AddDatasetExampleDialogMutation.graphql.ts
  app/src/pages/dataset/__generated__/DatasetExamplesTableFragment.graphql.ts
  app/src/pages/dataset/__generated__/DatasetExamplesTableQuery.graphql.ts
  app/src/pages/dataset/__generated__/datasetLoaderQuery.graphql.ts
Labels: size:L

#3422 chore: add support for querying by datetime
  src/phoenix/trace/dsl/filter.py
Labels: size:XS

#3437 feat: gql resolver for dataset example count
  app/schema.graphql
  src/phoenix/server/api/types/Dataset.py
  tests/server/api/types/test_Dataset.py
Labels: size:M

#3441 fix: add support for querying datetimes
  src/phoenix/db/README.md
Labels: size:XS

#3442 chore(main): release arize-phoenix 4.3.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3445 chore: update llama-index pinned version
  pyproject.toml
Labels: size:XS

#3443 feat(datasets): gql resolver for experiment count
  app/schema.graphql
  src/phoenix/server/api/types/Dataset.py
  tests/server/api/types/test_Dataset.py
Labels: size:M

#3444 feat(datasets): version history modal
  app/src/pages/dataset/DatasetHistoryButton.tsx
  app/src/pages/dataset/DatasetHistoryDialog.tsx
  app/src/pages/dataset/DatasetHistoryTable.tsx
  app/src/pages/dataset/DatasetPage.tsx
  app/src/pages/dataset/__generated__/DatasetHistoryDialogQuery.graphql.ts
  app/src/pages/dataset/__generated__/DatasetHistoryTableVersionsQuery.graphql.ts
  app/src/pages/dataset/__generated__/DatasetHistoryTable_versions.graphql.ts
Labels: size:XL

#3430 test: Add experiment fixtures, some tests and fix associated bugs
  src/phoenix/db/migrations/versions/10460e46d750_datasets.py
  src/phoenix/db/models.py
  src/phoenix/server/api/routers/v1/experiment_evaluations.py
  src/phoenix/server/api/routers/v1/experiment_runs.py
  src/phoenix/server/api/routers/v1/experiments.py
  tests/server/api/conftest.py
  tests/server/api/routers/v1/test_experiments.py
Labels: size:L

#3447 feat(datasets): example and experiment count on datasets table
  app/src/pages/dataset/ExampleSelectionToolbar.tsx
  app/src/pages/datasets/DatasetsTable.tsx
  app/src/pages/datasets/__generated__/DatasetsPageQuery.graphql.ts
  app/src/pages/datasets/__generated__/DatasetsTableDatasetsQuery.graphql.ts
  app/src/pages/datasets/__generated__/DatasetsTable_datasets.graphql.ts
  app/src/pages/project/SpanSelectionToolbar.tsx
Labels: size:M

#3448 feat(datasets): gql resolver returns examples in descending order
  src/phoenix/server/api/types/Dataset.py
  tests/server/api/mutations/test_dataset_mutations.py
  tests/server/api/types/test_Dataset.py
Labels: size:L

#3449 chore: update tables for human annotations on experiment runs
  src/phoenix/db/migrations/versions/10460e46d750_datasets.py
  src/phoenix/db/models.py
  src/phoenix/server/api/routers/v1/experiment_evaluations.py
  tests/server/api/conftest.py
Labels: size:M

#3446 feat: add experiments resolver to DatasetExample gql type
  app/schema.graphql
  src/phoenix/server/api/types/DatasetExample.py
  src/phoenix/server/api/types/Experiment.py
  tests/server/api/types/test_DatasetExample.py
Labels: size:L

#3451 feat(ui): add filter snippets for metadata and substring search
  app/src/pages/project/SpanFilterConditionField.tsx
Labels: size:S

#3453 chore(main): release arize-phoenix 4.4.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3454 feat(experiments): experiments table
  app/src/pages/dataset/DatasetExperimentsTable.tsx
  app/src/pages/dataset/DatasetPage.tsx
  app/src/pages/dataset/__generated__/DatasetExperimentsTableFragment.graphql.ts
  app/src/pages/dataset/__generated__/DatasetExperimentsTableQuery.graphql.ts
  app/src/pages/dataset/__generated__/datasetLoaderQuery.graphql.ts
  app/src/pages/dataset/datasetLoader.ts
Labels: size:XL

#3458 fix: ensure welcome message urls are valid
  src/phoenix/server/main.py
Labels: size:S

#3463 chore(main): release arize-phoenix 4.4.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3465 feat: add runs resolver on Experiment type
  app/schema.graphql
  src/phoenix/db/models.py
  src/phoenix/server/api/types/Experiment.py
  src/phoenix/server/api/types/ExperimentRun.py
  tests/server/api/types/test_Experiment.py
Labels: size:L

#3470 feat(datasets): routing for examples and experiment pages
  app/package.json
  app/pnpm-lock.yaml
  app/src/Routes.tsx
  app/src/pages/dataset/DatasetPage.tsx
  app/src/pages/dataset/__generated__/datasetLoaderQuery.graphql.ts
  app/src/pages/dataset/datasetLoader.ts
  app/src/pages/dataset/index.tsx
  app/src/pages/example/EditExampleButton.tsx
  app/src/pages/example/EditExampleDialog.tsx
  app/src/pages/example/ExamplePage.tsx
  app/src/pages/example/__generated__/EditExampleDialogMutation.graphql.ts
  app/src/pages/example/__generated__/ExamplePageQuery.graphql.ts
  app/src/pages/example/index.tsx
  app/src/pages/examples/ExampleSelectionToolbar.tsx
  app/src/pages/examples/ExamplesPage.tsx
  app/src/pages/examples/ExamplesTable.tsx
  app/src/pages/examples/__generated__/ExampleSelectionToolbarDeleteExamplesMutation.graphql.ts
  app/src/pages/examples/__generated__/ExamplesTableFragment.graphql.ts
  app/src/pages/examples/__generated__/ExamplesTableQuery.graphql.ts
  app/src/pages/examples/__generated__/examplesLoaderQuery.graphql.ts
  app/src/pages/examples/examplesLoader.tsx
  app/src/pages/examples/index.tsx
  app/src/pages/experiments/ExperimentsPage.tsx
  app/src/pages/experiments/ExperimentsTable.tsx
  app/src/pages/experiments/__generated__/ExperimentsTableFragment.graphql.ts
  app/src/pages/experiments/__generated__/ExperimentsTableQuery.graphql.ts
  app/src/pages/experiments/__generated__/experimentsLoaderQuery.graphql.ts
  app/src/pages/experiments/experimentsLoader.tsx
  app/src/pages/experiments/index.tsx
  app/src/pages/index.tsx
  app/src/pages/project/SpanSelectionToolbar.tsx
Labels: size:XXL

#3473 feat: add annotations resolver on DatasetRun type
  app/schema.graphql
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/AnnotatorKind.py
  src/phoenix/server/api/types/ExperimentRun.py
  src/phoenix/server/api/types/ExperimentRunAnnotation.py
  tests/server/api/types/test_ExperimentRun.py
Labels: size:L

#3479 chore: change experiments resolver to experiment runs resolver on DatasetExample type
  app/schema.graphql
  src/phoenix/server/api/types/DatasetExample.py
  tests/server/api/types/test_DatasetExample.py
Labels: size:M

#3486 feat(datasets): add sequence number for experiments
  app/schema.graphql
  app/src/pages/experiments/ExperimentsTable.tsx
  app/src/pages/experiments/__generated__/ExperimentsTableFragment.graphql.ts
  app/src/pages/experiments/__generated__/ExperimentsTableQuery.graphql.ts
  app/src/pages/experiments/__generated__/experimentsLoaderQuery.graphql.ts
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/experiment_sequence_number.py
  src/phoenix/server/api/types/Dataset.py
  src/phoenix/server/api/types/Experiment.py
  src/phoenix/server/app.py
  tests/server/api/types/conftest.py
  tests/server/api/types/test_Dataset.py
  tests/server/api/types/test_Experiment.py
Labels: size:L

#3488 fix: add tiebreak to versions resolver
  src/phoenix/server/api/types/Dataset.py
  tests/server/api/types/test_Dataset.py
Labels: size:L

#3480 fix: order runs in descending order in runs resolver on Experiment type
  src/phoenix/server/api/types/Experiment.py
  tests/server/api/types/test_Experiment.py
Labels: size:XS

#3489 fix(datasets): select nested rows on traces
  app/package.json
  app/pnpm-lock.yaml
  app/src/pages/project/TracesTable.tsx
Labels: size:S

#3471 feat(experiments): Implement `run_experiment`
  pyproject.toml
  src/phoenix/__init__.py
  src/phoenix/datasets/__init__.py
  src/phoenix/datasets/experiments.py
  tests/conftest.py
  tests/datasets/conftest.py
  tests/datasets/test_experiments.py
  tests/server/api/conftest.py
Labels: size:L

#3493 feat(datasets): download jsonl for openai
  schemas/openapi.yaml
  src/phoenix/server/api/routers/v1/__init__.py
  src/phoenix/server/api/routers/v1/datasets.py
  tests/server/api/conftest.py
  tests/server/api/routers/v1/test_datasets.py
Labels: size:L

#3495 feat(datasets): add jsonl to download menu
  app/src/pages/dataset/DatasetPage.tsx
Labels: size:S

#3501 feat(datasets): deny v1 routes and gql mutations if readonly
  schemas/openapi.yaml
  src/phoenix/server/api/mutations/auth.py
  src/phoenix/server/api/mutations/dataset_mutations.py
  src/phoenix/server/api/mutations/export_events_mutations.py
  src/phoenix/server/api/mutations/project_mutations.py
  src/phoenix/server/api/routers/v1/__init__.py
  src/phoenix/server/api/routers/v1/dataset_examples.py
  src/phoenix/server/api/routers/v1/datasets.py
  src/phoenix/server/api/routers/v1/evaluations.py
  src/phoenix/server/api/routers/v1/spans.py
  src/phoenix/server/api/routers/v1/traces.py
Labels: size:L

#3500 refactor: update GET /v1/datasets/{datasetId}/examples to return dataset and version IDs as part of payload
  schemas/openapi.yaml
  src/phoenix/server/api/routers/v1/dataset_examples.py
  tests/server/api/routers/v1/test_dataset_examples.py
  tests/server/api/routers/v1/test_experiments.py
Labels: size:L

#3490 feat: implement get_dataset method on phoenix.Client
  src/phoenix/session/client.py
  src/phoenix/session/datasets.py
  tests/session/test_client.py
Labels: size:L

#3508 fix(datasets): reconcile Dataset methods
  src/phoenix/datasets/experiments.py
  tests/datasets/test_experiments.py
Labels: size:XS

#3510 fix(ui): light mode for messages
  app/src/pages/trace/TracePage.tsx
Labels: size:XS

#3511 chore(main): release arize-phoenix 4.4.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3509 feat(experiments): navigation to experiments view
  app/src/Routes.tsx
  app/src/pages/datasets/DatasetsTable.tsx
  app/src/pages/experiment/ExperimentComparePage.tsx
  app/src/pages/experiment/ExperimentMultiSelector.tsx
  app/src/pages/experiment/__generated__/ExperimentMultiSelector__experiments.graphql.ts
  app/src/pages/experiment/__generated__/experimentCompareLoaderQuery.graphql.ts
  app/src/pages/experiment/experimentCompareLoader.ts
  app/src/pages/experiment/index.tsx
  app/src/pages/experiments/ExperimentSelectionToolbar.tsx
  app/src/pages/experiments/ExperimentsTable.tsx
Labels: size:XL

#3512 feat(experiments): add experiment name
  app/schema.graphql
  src/phoenix/datasets/experiments.py
  src/phoenix/db/migrations/versions/10460e46d750_datasets.py
  src/phoenix/db/models.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/routers/v1/experiments.py
  src/phoenix/server/api/types/Experiment.py
  tests/datasets/test_experiments.py
  tests/server/api/conftest.py
  tests/server/api/types/conftest.py
  tests/server/api/types/test_Dataset.py
  tests/server/api/types/test_DatasetExample.py
  tests/server/api/types/test_Experiment.py
  tests/server/api/types/test_ExperimentRun.py
Labels: size:M

#3522 fix: resolve warning for remote
  src/phoenix/db/models.py
Labels: size:XS

#3523 feat(experments): Switch UI to use experiment name
  app/package.json
  app/pnpm-lock.yaml
  app/src/pages/experiment/ExperimentMultiSelector.tsx
  app/src/pages/experiment/__generated__/ExperimentMultiSelector__experiments.graphql.ts
  app/src/pages/experiment/__generated__/experimentCompareLoaderQuery.graphql.ts
  app/src/pages/experiments/ExperimentSelectionToolbar.tsx
  app/src/pages/experiments/ExperimentsTable.tsx
  app/src/pages/experiments/__generated__/ExperimentsTableFragment.graphql.ts
  app/src/pages/experiments/__generated__/ExperimentsTableQuery.graphql.ts
  app/src/pages/experiments/__generated__/experimentsLoaderQuery.graphql.ts
Labels: size:L

#3525 chore: docs to main
  docs/README.md
  docs/SUMMARY.md
  docs/api/client.md
  docs/api/evaluation-models.md
  docs/api/inference-and-schema.md
  docs/api/session.md
  docs/deployment/README.md
  docs/deployment/docker.md
  docs/deployment/faqs-deployment.md
  docs/deployment/persistence.md
  docs/environments.md
  docs/evaluation/concepts-evals/building-your-own-evals.md
  docs/evaluation/concepts-evals/evaluation.md
  docs/evaluation/concepts-evals/llm-as-a-judge.md
  docs/evaluation/evaluation-models.md
  docs/evaluation/how-to-evals/running-pre-tested-evals/README.md
  docs/how-to/define-your-schema/README.md
  docs/how-to/manage-the-app.md
  docs/inferences/how-to-inferences-1/use-example-inferences.md
  docs/integrations/bring-production-data-to-notebook-for-eda-or-retraining.md
  docs/notebooks.md
  docs/quickstart/llm-traces.md
  docs/quickstart/phoenix-inferences/README.md
  docs/reference/frequently-asked-questions.md
  docs/setup/README.md
  docs/setup/configuration.md
  docs/tracing/concepts-tracing/what-are-traces.md
  docs/tracing/faqs-tracing.md
  docs/tracing/how-to-tracing/README.md
  docs/tracing/how-to-tracing/customize-spans.md
  docs/tracing/how-to-tracing/extract-data-from-spans.md
  docs/tracing/how-to-tracing/instrumentation/auto-instrument-python/llamaindex.md
  docs/tracing/how-to-tracing/llm-evaluations.md
  docs/tracing/how-to-tracing/save-and-load-traces.md
  docs/use-cases/rag-evaluation.md
  docs/user-guide.md
Labels: size:XL

#3527 feat(datasets): sort by name and created at
  app/schema.graphql
  app/src/pages/datasets/DatasetsTable.tsx
  app/src/pages/datasets/__generated__/DatasetsPageQuery.graphql.ts
  app/src/pages/datasets/__generated__/DatasetsTableDatasetsQuery.graphql.ts
  app/src/pages/datasets/__generated__/DatasetsTable_datasets.graphql.ts
  src/phoenix/server/api/input_types/DatasetSort.py
  src/phoenix/server/api/queries.py
Labels: size:L

#3533 fix: hdbscan incompatibility with numpy 2.0
  .pre-commit-config.yaml
  pyproject.toml
  src/phoenix/core/model_schema.py
  src/phoenix/metrics/binning.py
  src/phoenix/server/api/types/Segments.py
  tests/metrics/test_binning.py
  tests/metrics/test_scalar_drift.py
Labels: size:M

#3540 fix: style and type errors
  app/schema.graphql
  src/phoenix/core/model_schema.py
Labels: size:XS

#3542 chore: fix pandas linting for python 3.9+
  pyproject.toml
Labels: size:XS

#3481 feat: compareExperiments resolver
  app/schema.graphql
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/ExperimentComparison.py
  src/phoenix/server/api/types/ExperimentRun.py
  tests/server/api/test_queries.py
  tests/server/api/types/test_Experiment.py
Labels: size:XL

#3541 fix: add requests back for type checking
  pyproject.toml
Labels: size:XS

#3528 feat(experiments): experiments compare table
  app/src/components/code/JSONText.tsx
  app/src/components/experiment/AnnotationLabel.tsx
  app/src/components/experiment/SequenceNumberLabel.tsx
  app/src/components/nav/Navbar.tsx
  app/src/components/table/CompactJSONCell.tsx
  app/src/components/table/index.tsx
  app/src/components/table/styles.ts
  app/src/pages/ErrorElement.tsx
  app/src/pages/example/ExampleExperimentRunsTable.tsx
  app/src/pages/experiment/ExperimentComparePage.tsx
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/experiment/ExperimentMultiSelector.tsx
  app/src/pages/experiment/__generated__/ExperimentCompareTableQuery.graphql.ts
  app/src/pages/experiments/ExperimentsTable.tsx
  app/src/typeUtils.ts
Labels: size:XL

#3532 feat: Support repetitions for experiment runs
  src/phoenix/datasets/experiments.py
  src/phoenix/db/migrations/versions/10460e46d750_datasets.py
  src/phoenix/db/models.py
  src/phoenix/server/api/routers/v1/experiment_runs.py
  src/phoenix/server/api/routers/v1/experiments.py
  tests/datasets/test_experiments.py
  tests/server/api/conftest.py
  tests/server/api/mutations/test_experiment_mutations.py
  tests/server/api/routers/v1/test_experiments.py
  tests/server/api/test_queries.py
  tests/server/api/types/conftest.py
  tests/server/api/types/test_Dataset.py
  tests/server/api/types/test_DatasetExample.py
  tests/server/api/types/test_Experiment.py
  tests/server/api/types/test_ExperimentRun.py
Labels: size:L

#3548 refactor: make deleteExperiments resolver support multiple deletions at once
  app/schema.graphql
  src/phoenix/server/api/input_types/DeleteExperimentInput.py
  src/phoenix/server/api/input_types/DeleteExperimentsInput.py
  src/phoenix/server/api/mutations/experiment_mutations.py
  tests/server/api/mutations/test_experiment_mutations.py
Labels: size:L

#3552 feat(experiments): delete experiments ui
  app/src/components/table/styles.ts
  app/src/pages/examples/ExampleSelectionToolbar.tsx
  app/src/pages/experiments/ExperimentSelectionToolbar.tsx
  app/src/pages/experiments/ExperimentsTable.tsx
  app/src/pages/experiments/__generated__/ExperimentSelectionToolbarDeleteExperimentsMutation.graphql.ts
Labels: size:L

#3546 feat(datasets): get_dataset by name
  schemas/openapi.yaml
  src/phoenix/server/api/routers/v1/datasets.py
  src/phoenix/session/client.py
  tests/session/test_client.py
  tutorials/experiments/internal/run_experiments.ipynb
Labels: size:L

#3555 fix(dataset): get metadata as `{}` when its value is `None` in JSON
  src/phoenix/server/api/routers/v1/experiment_evaluations.py
  src/phoenix/server/api/routers/v1/experiments.py
Labels: size:XS

#3551 feat(experiments): full-text toggle for experiments table
  app/src/components/code/JSONText.tsx
  app/src/components/nav/Navbar.tsx
  app/src/components/table/styles.ts
  app/src/pages/experiment/ExperimentComparePage.tsx
  app/src/pages/experiment/ExperimentCompareTable.tsx
Labels: size:L

#3556 fix(datasets): json cell for metadata in experiment table UI
  app/src/pages/experiments/ExperimentsTable.tsx
Labels: size:XS

#3534 feat: Add basic evaluators for string experiment outputs
  src/phoenix/datasets/experiments.py
Labels: size:M

#3557 feat(experiments): select example / slideover on compare view
  app/src/components/ViewSummaryAside.tsx
  app/src/components/code/JSONBlock.tsx
  app/src/components/code/index.tsx
  app/src/pages/example/ExamplePage.tsx
  app/src/pages/experiment/ExperimentCompareTable.tsx
Labels: size:L

#3566 feat(datasets): navigate to examples if no experiments exist
  app/src/pages/dataset/DatasetPage.tsx
  app/src/pages/dataset/__generated__/datasetLoaderQuery.graphql.ts
  app/src/pages/dataset/datasetLoader.ts
  app/src/pages/datasets/DatasetsTable.tsx
Labels: size:M

#3565 feat(auth): universal set of headers to be used by the client
  cspell.json
  src/phoenix/config.py
  src/phoenix/datasets/experiments.py
  src/phoenix/session/client.py
  src/phoenix/trace/exporter.py
  src/phoenix/utilities/re.py
  tests/session/test_client.py
  tests/utilities/test_re.py
Labels: size:L

#3549 feat: resolvers for experiment annotation aggregations
  app/schema.graphql
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/experiment_annotation_summaries.py
  src/phoenix/server/api/types/Dataset.py
  src/phoenix/server/api/types/Experiment.py
  src/phoenix/server/api/types/ExperimentAnnotationSummary.py
  src/phoenix/server/app.py
  tests/server/api/types/test_Experiment.py
Labels: size:XL

#3572 chore: hide openapi routes that are not usable in the playground
  schemas/openapi.yaml
  src/phoenix/server/api/routers/v1/evaluations.py
  src/phoenix/server/api/routers/v1/spans.py
  src/phoenix/server/api/routers/v1/traces.py
  src/phoenix/server/openapi/docs.py
Labels: size:S

#3568 refactor: define object types for experiments
  src/phoenix/datasets/evaluators.py
  src/phoenix/datasets/experiments.py
  src/phoenix/datasets/types.py
  src/phoenix/server/api/routers/v1/__init__.py
  src/phoenix/server/api/routers/v1/experiment_evaluations.py
  src/phoenix/server/api/routers/v1/experiment_runs.py
  src/phoenix/server/api/routers/v1/experiments.py
  src/phoenix/session/client.py
  src/phoenix/session/datasets.py
  src/phoenix/utilities/json_utils.py
  tests/datasets/test_experiments.py
  tests/server/api/routers/v1/test_experiments.py
  tutorials/experiments/run_experiments_with_llama_index.ipynb
Labels: size:XXL

#3554 fix(datasets): disallow `None` for `JSONB` in database
  src/phoenix/db/insertion/dataset.py
  src/phoenix/db/models.py
  src/phoenix/server/api/mutations/dataset_mutations.py
  tests/server/api/mutations/test_dataset_mutations.py
Labels: size:M

#3570 chore: dataset-level annotation summary resolver
  app/schema.graphql
  src/phoenix/server/api/dataloaders/experiment_annotation_summaries.py
  src/phoenix/server/api/types/Dataset.py
  tests/server/api/types/test_Experiment.py
Labels: size:L

#3575 feat(experiments): experiment evaluation summaries in the table
  app/package.json
  app/pnpm-lock.yaml
  app/src/components/code/JSONText.tsx
  app/src/components/experiment/AnnotationColorSwatch.tsx
  app/src/components/experiment/AnnotationLabel.tsx
  app/src/components/experiment/index.tsx
  app/src/hooks/useEmbeddingDimensionId.ts
  app/src/hooks/useWordColor.ts
  app/src/pages/embedding/EmbeddingPage.tsx
  app/src/pages/examples/ExamplesTable.tsx
  app/src/pages/experiments/ExperimentSelectionToolbar.tsx
  app/src/pages/experiments/ExperimentsTable.tsx
  app/src/pages/experiments/__generated__/ExperimentsTableFragment.graphql.ts
  app/src/pages/experiments/__generated__/ExperimentsTableQuery.graphql.ts
  app/src/pages/experiments/__generated__/experimentsLoaderQuery.graphql.ts
Labels: size:L

#3583 docs(datasets): print useful URLs, disable repetitions
  src/phoenix/datasets/experiments.py
  tests/datasets/test_experiments.py
  tutorials/experiments/internal/run_experiments.ipynb
Labels: size:M

#3587 fix: right align numeric colums
  app/src/@types/emotion.d.ts
  app/src/@types/table.d.ts
  app/src/pages/datasets/DatasetsTable.tsx
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/experiments/ExperimentsTable.tsx
Labels: size:M

#3588 feat: error rate resolver on Experiment type
  app/schema.graphql
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/experiment_error_rates.py
  src/phoenix/server/api/types/Experiment.py
  src/phoenix/server/app.py
  tests/server/api/types/test_Experiment.py
Labels: size:L

#3590 refactor: rename experiment_annotations table to experiment_run_annotations
  src/phoenix/db/migrations/versions/10460e46d750_datasets.py
  src/phoenix/db/models.py
  src/phoenix/server/api/dataloaders/experiment_annotation_summaries.py
  src/phoenix/server/api/routers/v1/experiment_evaluations.py
  src/phoenix/server/api/types/Dataset.py
  src/phoenix/server/api/types/ExperimentRun.py
  src/phoenix/server/api/types/ExperimentRunAnnotation.py
  tests/datasets/test_experiments.py
  tests/server/api/conftest.py
  tests/server/api/types/test_Experiment.py
  tests/server/api/types/test_ExperimentRun.py
Labels: size:M

#3585 feat: Unify `run_experiment` and `evaluate_experiment`
  src/phoenix/datasets/experiments.py
  tests/datasets/test_experiments.py
  tutorials/experiments/run_experiments_with_llama_index.ipynb
Labels: size:L

#3589 chore: unique constraint on experiment_run_annotations table
  src/phoenix/datasets/evaluators.py
  src/phoenix/db/migrations/versions/10460e46d750_datasets.py
  src/phoenix/db/models.py
  tests/server/api/types/test_Experiment.py
Labels: size:L

#3571 feat: Add LLM evaluators
  src/phoenix/datasets/evaluators.py
  src/phoenix/datasets/types.py
  tests/datasets/test_experiments.py
  tutorials/experiments/run_experiments_with_llama_index.ipynb
Labels: size:L

#3594 chore: add unique constraint on experiment runs table
  src/phoenix/db/migrations/versions/10460e46d750_datasets.py
  src/phoenix/db/models.py
Labels: size:S

#3598 chore: display the platform version in the UI
  app/src/components/nav/Navbar.tsx
  app/src/window.d.ts
  src/phoenix/server/app.py
  src/phoenix/server/templates/index.html
Labels: size:XS

#3579 feat(datasets): capture traces from experiments
  app/schema.graphql
  src/phoenix/datasets/experiments.py
  src/phoenix/datasets/tracing.py
  src/phoenix/datasets/types.py
  src/phoenix/db/migrations/versions/10460e46d750_datasets.py
  src/phoenix/db/models.py
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/trace_row_ids.py
  src/phoenix/server/api/mutations/experiment_mutations.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/routers/v1/experiment_evaluations.py
  src/phoenix/server/api/routers/v1/experiment_runs.py
  src/phoenix/server/api/routers/v1/experiments.py
  src/phoenix/server/api/types/ExperimentRun.py
  src/phoenix/server/api/types/ExperimentRunAnnotation.py
  src/phoenix/server/app.py
  src/phoenix/utilities/json.py
  tests/datasets/test_experiments.py
  tests/server/api/routers/v1/test_experiments.py
  tutorials/experiments/run_experiments_with_llama_index.ipynb
Labels: size:XL

#3606 feat(datasets): add graphql field from trace to project
  app/schema.graphql
  src/phoenix/server/api/dataloaders/trace_row_ids.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/ExperimentRun.py
  src/phoenix/server/api/types/ExperimentRunAnnotation.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/api/types/Trace.py
Labels: size:M

#3607 chore: rename upload_dataset_examples to upload_dataset and add return type
  src/phoenix/session/client.py
  src/phoenix/trace/fixtures.py
  tutorials/experiments/internal/run_experiments.ipynb
  tutorials/experiments/run_experiments_with_llama_index.ipynb
Labels: size:M

#3604 feat: Add relevance evaluator
  src/phoenix/datasets/evaluators.py
Labels: size:M

#3609 fix: Address relevance eval feedback
  src/phoenix/datasets/evaluators.py
Labels: size:S

#3610 fix: resolve phoenix-eval type errors
  packages/phoenix-evals/src/phoenix/evals/models/litellm.py
  packages/phoenix-evals/src/phoenix/evals/models/vertexai.py
Labels: size:XS

#3577 feat: added SQLEvaluator
  docs/api/evals.md
  packages/phoenix-evals/src/phoenix/evals/__init__.py
  packages/phoenix-evals/src/phoenix/evals/evaluators.py
Labels: size:S

#3608 chore: rename "retrieval_documents" to "documents" in examples
  src/phoenix/server/api/helpers/dataset_helpers.py
  tests/server/api/helpers/test_dataset_helpers.py
  tests/server/api/mutations/test_dataset_mutations.py
Labels: size:XS

#3612 chore(main): release arize-phoenix 4.5.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3603 feat(experiments): add the ability to view an experiment's traces
  app/package.json
  app/pnpm-lock.yaml
  app/schema.graphql
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/experiment/__generated__/ExperimentCompareTableQuery.graphql.ts
  app/src/pages/experiments/ExperimentsTable.tsx
  app/src/pages/experiments/__generated__/ExperimentsTableFragment.graphql.ts
  app/src/pages/experiments/__generated__/ExperimentsTableQuery.graphql.ts
  app/src/pages/experiments/__generated__/experimentsLoaderQuery.graphql.ts
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/project_by_name.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/Experiment.py
  src/phoenix/server/api/types/ExperimentRun.py
  src/phoenix/server/api/types/ExperimentRunAnnotation.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/api/types/Trace.py
  src/phoenix/server/app.py
  tutorials/experiments/run_experiments_with_llama_index.ipynb
Labels: size:L

#3619 fix: openapi import error
  src/phoenix/server/api/openapi/__init__.py
Labels: size:XS

#3635 fix: Update Dockerfile to work with ARM64 chips.
  Dockerfile
Labels: size:XS

#3637 fix(experments): fix colab links
  src/phoenix/datasets/experiments.py
  src/phoenix/server/api/openapi/schema.py
Labels: size:S

#3638 feat: Experiments improvements
  src/phoenix/datasets/evaluators/__init__.py
  src/phoenix/datasets/evaluators/_utils.py
  src/phoenix/datasets/evaluators/code_evaluators.py
  src/phoenix/datasets/evaluators/llm_evaluators.py
  src/phoenix/datasets/experiments.py
  tests/datasets/test_experiments.py
Labels: size:L

#3639 feat(experiments): evaluator icon and ingestion
  app/schema.graphql
  app/src/components/trace/SpanKindIcon.tsx
  app/src/components/trace/SpanKindLabel.tsx
  app/src/components/trace/TraceTree.tsx
  app/src/pages/project/__generated__/SpansTable_spans.graphql.ts
  app/src/pages/project/__generated__/TracesTable_spans.graphql.ts
  app/src/pages/trace/TracePage.tsx
  app/src/pages/trace/__generated__/TracePageQuery.graphql.ts
  src/phoenix/server/api/types/Span.py
  src/phoenix/trace/schemas.py
Labels: size:L

#3640 feat(experiments): show trace slide-over on experiment page
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/trace/TraceDetails.tsx
  app/src/pages/trace/TracePage.tsx
  app/src/pages/trace/__generated__/TraceDetailsQuery.graphql.ts
  app/src/pages/trace/index.tsx
Labels: size:XXL

#3642 feat: `create_evaluator` decorators
  src/phoenix/datasets/evaluators/_utils.py
  src/phoenix/datasets/evaluators/code_evaluators.py
  src/phoenix/datasets/evaluators/llm_evaluators.py
  src/phoenix/datasets/evaluators/utils.py
  src/phoenix/datasets/experiments.py
  src/phoenix/datasets/types.py
  tests/datasets/test_experiments.py
Labels: size:L

#3647 feat(datasets): print the URL to the dataset when uploaded
  src/phoenix/session/client.py
Labels: size:S

#3648 chore: add pyment config
  cspell.json
  pyment.conf
  pyproject.toml
  src/phoenix/datasets/tracing.py
Labels: size:S

#3626 docs(experiments): txt2sql
  tutorials/experiments/experiments_txt2sql.ipynb
Labels: size:L

#3651 fix: json input and output values are properly parsed when adding examples
  src/phoenix/server/api/helpers/dataset_helpers.py
  tests/server/api/helpers/test_dataset_helpers.py
Labels: size:M

#3646 refactor: user experience improvements
  src/phoenix/datasets/evaluators/code_evaluators.py
  src/phoenix/datasets/evaluators/llm_evaluators.py
  src/phoenix/datasets/evaluators/utils.py
  src/phoenix/datasets/experiments.py
  src/phoenix/datasets/types.py
  src/phoenix/server/api/routers/v1/datasets.py
  src/phoenix/server/api/routers/v1/experiment_runs.py
  src/phoenix/session/client.py
  tests/datasets/test_experiments.py
  tutorials/experiments/langchain_email_extraction.ipynb
  tutorials/experiments/run_experiments_with_llama_index.ipynb
Labels: size:XL

#3658 feat(datasets): upload JSON for dataset examples
  schemas/openapi.yaml
  src/phoenix/db/insertion/dataset.py
  src/phoenix/server/api/routers/v1/datasets.py
  src/phoenix/session/client.py
  tests/db/insertion/test_dataset.py
  tests/server/api/routers/v1/test_datasets.py
  tutorials/experiments/langchain_email_extraction.ipynb
Labels: size:L

#3657 feat(experiments): experiment error rate column
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/experiments/ErrorRateCell.tsx
  app/src/pages/experiments/ExperimentsTable.tsx
  app/src/pages/experiments/__generated__/ExperimentsTableFragment.graphql.ts
  app/src/pages/experiments/__generated__/ExperimentsTableQuery.graphql.ts
  app/src/pages/experiments/__generated__/experimentsLoaderQuery.graphql.ts
Labels: size:L

#3663 fix(dataset): bug with json upload
  src/phoenix/server/api/routers/v1/datasets.py
  tests/server/api/routers/v1/test_datasets.py
Labels: size:XS

#3664 fix(dataset): missing annotation trace id
  src/phoenix/server/api/routers/v1/experiment_evaluations.py
  src/phoenix/server/api/types/ExperimentRunAnnotation.py
Labels: size:XS

#3661 fix: support functools.partial for experiment tasks
  src/phoenix/datasets/experiments.py
Labels: size:S

#3666 feat(datasets): post the result of each experiment/evaluation run immediately when it finishes
  src/phoenix/datasets/experiments.py
  tests/conftest.py
  tests/datasets/test_experiments.py
Labels: size:M

#3667 fix(datasets): update span kind for evaluator with semantic conventions v0.1.9
  pyproject.toml
  src/phoenix/datasets/experiments.py
Labels: size:XS

#3672 fix(datasets): squash experiment run output by "result" key for graphql query
  src/phoenix/db/migrations/versions/10460e46d750_datasets.py
  src/phoenix/db/models.py
  src/phoenix/server/api/types/ExperimentRun.py
  tests/server/api/test_queries.py
  tests/server/api/types/test_DatasetExample.py
  tests/server/api/types/test_Experiment.py
Labels: size:M

#3673 docs: resolve import issues in notebooks
  tutorials/evals/evaluate_human_vs_ai_classifications.ipynb
  tutorials/evals/evaluate_summarization_classifications.ipynb
Labels: size:XS

#3662 fix: resolves the authentication issue for GeminiModel in evals model
  packages/phoenix-evals/src/phoenix/evals/models/vertex.py
Labels: size:S

#3669 docs(experiments): prompt template iteration for summarization task
  tutorials/experiments/summarization.ipynb
Labels: size:XL

#3440 chore(main): release arize-phoenix-evals 0.13.0
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#3674 feat(datasets): allow unrecognized parameters in the evaluator function with default values
  src/phoenix/datasets/evaluators/utils.py
Labels: size:S

#3679 feat(experiments): run count resolver on experiments
  app/schema.graphql
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/experiment_run_counts.py
  src/phoenix/server/api/types/Experiment.py
  src/phoenix/server/app.py
  tests/server/api/types/test_Experiment.py
Labels: size:L

#3680 feat(experiments): evaluator trace slide-over
  app/src/components/experiment/AnnotationLabel.tsx
  app/src/pages/experiment/ExperimentCompareTable.tsx
  tutorials/experiments/experiments_txt2sql.ipynb
Labels: size:L

#3684 fix(datasets): typo on dict type for typed dict
  src/phoenix/db/models.py
Labels: size:XS

#3683 test: tests for insert on conflict
  src/phoenix/db/insertion/evaluation.py
  src/phoenix/db/insertion/helpers.py
  src/phoenix/db/insertion/span.py
  src/phoenix/server/api/routers/v1/experiments.py
  tests/db/insertion/test_helpers.py
Labels: size:L

#3685 chore: add support for upserts for experiment evals
  src/phoenix/server/api/routers/v1/__init__.py
  src/phoenix/server/api/routers/v1/experiment_evaluations.py
Labels: size:S

#3686 feat(experments): add the ability to view experiment metadata in full
  app/src/components/code/JSONText.tsx
  app/src/pages/RemoveProjectDataForm.tsx
  app/src/pages/example/ExampleExperimentRunsTable.tsx
  app/src/pages/example/__generated__/ExampleExperimentRunsTableFragment.graphql.ts
  app/src/pages/example/__generated__/ExampleExperimentRunsTableQuery.graphql.ts
  app/src/pages/example/__generated__/ExamplePageQuery.graphql.ts
  app/src/pages/experiments/ExperimentsTable.tsx
  app/src/pages/projects/ProjectsPage.tsx
Labels: size:L

#3689 Update README.md
  README.md
Labels: size:XS

#3690 feat(experiments): Show run count
  app/src/pages/experiments/ExperimentsTable.tsx
  app/src/pages/experiments/__generated__/ExperimentsTableFragment.graphql.ts
  app/src/pages/experiments/__generated__/ExperimentsTableQuery.graphql.ts
  app/src/pages/experiments/__generated__/experimentsLoaderQuery.graphql.ts
Labels: size:M

#3687 refactor: organize experiments sub-module for convenient imports
  src/phoenix/datasets/evaluators/__init__.py
  src/phoenix/datasets/evaluators/base.py
  src/phoenix/datasets/evaluators/code_evaluators.py
  src/phoenix/datasets/evaluators/llm_evaluators.py
  src/phoenix/datasets/evaluators/utils.py
  src/phoenix/datasets/experiments.py
  src/phoenix/datasets/types.py
  tests/datasets/test_experiments.py
Labels: size:L

#3699 docs: readthedocs config
  .readthedocs.yaml
  api_docs.sh
  docs/api_sphinx/Makefile
  docs/api_sphinx/make.bat
  docs/api_sphinx/requirements.txt
  docs/api_sphinx/source/conf.py
  docs/api_sphinx/source/evals.models.rst
  docs/api_sphinx/source/evals.rst
  docs/api_sphinx/source/index.rst
  docs/api_sphinx/source/inferences.rst
  docs/api_sphinx/source/modules.rst
  docs/api_sphinx/source/session.rst
Labels: size:L

#3704 feat(experments): minimum viable dialog showing how to run an experiment
  app/src/pages/dataset/DatasetPage.tsx
  app/src/pages/dataset/RunExperimentButton.tsx
  app/src/pages/experiments/ExperimentsTable.tsx
  app/src/store/datasetStore.tsx
Labels: size:L

#3703 docs(notebook): datasets and experiments quickstart
  src/phoenix/datasets/evaluators/__init__.py
  tutorials/experiments/datasets_and_experiments_quickstart.ipynb
Labels: size:L

#3712 feat(datasets): add the ability to create a dataset dynamically
  app/src/components/dataset/CreateDatasetForm.tsx
  app/src/contexts/NotificationContext.tsx
  app/src/pages/trace/DatasetPicker.tsx
  app/src/pages/trace/SpanToDatasetExampleDialog.tsx
  app/src/pages/trace/TraceDetails.tsx
  app/src/pages/trace/__generated__/DatasetPickerRefetchQuery.graphql.ts
  app/src/pages/trace/__generated__/DatasetPicker__datasets.graphql.ts
  app/src/pages/trace/__generated__/SpanToDatasetExampleDialogQuery.graphql.ts
Labels: size:XL

#3706 docs(api-ref): fix readthedocs build issues
  .readthedocs.yaml
  docs/api_sphinx/requirements.txt
  docs/api_sphinx/source/conf.py
Labels: size:S

#3715 chore: refactor docs
  .readthedocs.yaml
  api_docs.sh
  docs/api_reference/Makefile
  docs/api_reference/make.bat
  docs/api_reference/requirements.txt
  docs/api_reference/source/conf.py
  docs/api_reference/source/evals.models.rst
  docs/api_reference/source/evals.rst
  docs/api_reference/source/index.rst
  docs/api_reference/source/inferences.rst
  docs/api_reference/source/modules.rst
  docs/api_reference/source/session.rst
Labels: size:M

#3716 chore: move api_reference
  .readthedocs.yaml
  api_reference/Makefile
  api_reference/make.bat
  api_reference/requirements.txt
  api_reference/source/conf.py
  api_reference/source/evals.models.rst
  api_reference/source/evals.rst
  api_reference/source/index.rst
  api_reference/source/inferences.rst
  api_reference/source/modules.rst
  api_reference/source/session.rst
Labels: size:S

#3717 chore: fix api_reference conf
  api_reference/source/conf.py
Labels: size:XS

#3718 chore: fix sphinx theming
  .readthedocs.yaml
  api_reference/.gitignore
  api_reference/requirements.txt
  api_reference/source/conf.py
  api_reference/source/index.rst
Labels: size:S
