Repository Arize-ai/phoenix, pull requests merged in 2024-02, with the labels that each got.

#2176 feat!: Remove model-level tenacity retries
  src/phoenix/experimental/evals/models/anthropic.py
  src/phoenix/experimental/evals/models/base.py
  src/phoenix/experimental/evals/models/bedrock.py
  src/phoenix/experimental/evals/models/litellm.py
  src/phoenix/experimental/evals/models/openai.py
  src/phoenix/experimental/evals/models/vertex.py
  src/phoenix/experimental/evals/models/vertexai.py
  tests/experimental/evals/functions/test_classify.py
Labels: size:L, lgtm

#2180 feat(evals): add support and move to gpt-4-turbo-preview
  .prettierignore
  docs/api/evals.md
  docs/llm-evals/quickstart-retrieval-evals/README.md
  docs/quickstart/evals.md
  docs/use-cases/rag-evaluation.md
  src/phoenix/experimental/evals/models/openai.py
  tests/experimental/evals/models/test_openai.py
  tutorials/evals/evals_quickstart.ipynb
  tutorials/evals/evaluate_QA_classifications.ipynb
  tutorials/evals/evaluate_code_readability_classifications.ipynb
  tutorials/evals/evaluate_hallucination_classifications.ipynb
  tutorials/evals/evaluate_human_vs_ai_classifications.ipynb
  tutorials/evals/evaluate_rag.ipynb
  tutorials/evals/evaluate_reference_link_correctness_classifications.ipynb
  tutorials/evals/evaluate_relevance_classifications.ipynb
  tutorials/evals/evaluate_summarization_classifications.ipynb
  tutorials/evals/evaluate_toxicity_classifications.ipynb
  tutorials/tracing/langchain_tracing_tutorial.ipynb
  tutorials/tracing/llama_index_tracing_tutorial.ipynb
Labels: size:XL, lgtm

#2151 feat: phoenix client `get_spans_dataframe()` and `query_spans()`
  pyproject.toml
  src/phoenix/__init__.py
  src/phoenix/core/traces.py
  src/phoenix/server/api/input_types/SpanSort.py
  src/phoenix/server/api/routers/__init__.py
  src/phoenix/server/api/routers/evaluation_handler.py
  src/phoenix/server/api/routers/span_handler.py
  src/phoenix/server/api/routers/trace_handler.py
  src/phoenix/server/api/types/Span.py
  src/phoenix/server/app.py
  src/phoenix/server/span_handler.py
  src/phoenix/session/client.py
  src/phoenix/session/data_extractor.py
  src/phoenix/session/session.py
  src/phoenix/trace/dsl/filter.py
  src/phoenix/trace/dsl/query.py
  src/phoenix/trace/schemas.py
  src/phoenix/utilities/__init__.py
  tests/session/test_client.py
  tests/trace/dsl/test_query.py
Labels: size:XL, lgtm

#2154 feat: phoenix client `get_evaluations()` and `get_trace_dataset()`
  src/phoenix/server/api/routers/evaluation_handler.py
  src/phoenix/server/api/routers/span_handler.py
  src/phoenix/server/api/routers/utils.py
  src/phoenix/server/app.py
  src/phoenix/session/client.py
  src/phoenix/session/data_extractor.py
  src/phoenix/session/session.py
  src/phoenix/trace/dsl/helpers.py
  src/phoenix/trace/dsl/query.py
  src/phoenix/trace/span_evaluations.py
  tests/session/test_client.py
  tutorials/evals/data/paul_graham/paul_graham_essay.txt
Labels: size:XL, lgtm

#2187 chore: remove accidentally committed file
  tutorials/evals/data/paul_graham/paul_graham_essay.txt
Labels: size:L, lgtm

#2191 refactor: only allow named arguments for Client
  src/phoenix/session/client.py
Labels: size:XS, lgtm

#2199 fix: absolute path for urljoin in px.Client
  src/phoenix/session/client.py
Labels: size:S, lgtm

#2200 fix: localhost address for px.Client
  src/phoenix/session/client.py
Labels: size:XS, lgtm

#2202 fix: absolute path for eval exporter
  src/phoenix/trace/exporter.py
Labels: size:XS, lgtm

#2206 fix: disregard active_session if endpoint is provided to px.Client
  src/phoenix/session/client.py
Labels: size:XS, lgtm

#2192 feat!: Integrate instrumentation migrations (OpenAI, LlamaIndex)
  pyproject.toml
  src/phoenix/trace/exporter.py
  src/phoenix/trace/llama_index/callback.py
  src/phoenix/trace/llama_index/streaming.py
  src/phoenix/trace/openai/instrumentor.py
  src/phoenix/trace/tracer.py
  tests/trace/openai/test_instrumentor.py
Labels: size:XXL, lgtm

#2209 fix(traces): warn if collector endpoint is set but launch app is called
  src/phoenix/session/session.py
Labels: size:S, lgtm

#2189 chore: remove duplicated dependency
  pyproject.toml
Labels: size:XS, lgtm

#2214 refactor: Move token counting functionality off of `BaseEvalModel`
  src/phoenix/experimental/evals/functions/processing.py
  src/phoenix/experimental/evals/models/anthropic.py
  src/phoenix/experimental/evals/models/base.py
  src/phoenix/experimental/evals/models/bedrock.py
  src/phoenix/experimental/evals/models/litellm.py
  src/phoenix/experimental/evals/models/openai.py
  src/phoenix/experimental/evals/models/vertex.py
  src/phoenix/experimental/evals/models/vertexai.py
  tests/experimental/evals/functions/test_classify.py
  tests/experimental/evals/functions/test_generate.py
  tests/experimental/evals/models/test_openai.py
Labels: size:XL, lgtm

#2215 refactor: rename BaseEvalModel to BaseModel
  scripts/rag/llama_index_w_evals_and_qa.py
  src/phoenix/experimental/evals/evaluators.py
  src/phoenix/experimental/evals/functions/classify.py
  src/phoenix/experimental/evals/functions/generate.py
  src/phoenix/experimental/evals/functions/processing.py
  src/phoenix/experimental/evals/models/__init__.py
  src/phoenix/experimental/evals/models/anthropic.py
  src/phoenix/experimental/evals/models/base.py
  src/phoenix/experimental/evals/models/bedrock.py
  src/phoenix/experimental/evals/models/litellm.py
  src/phoenix/experimental/evals/models/openai.py
  src/phoenix/experimental/evals/models/vertex.py
  src/phoenix/experimental/evals/models/vertexai.py
Labels: size:M, lgtm

#2222 fix(trace): return to /tracing url when dismissing trace slide over
  app/package.json
  app/src/pages/trace/TracePage.tsx
Labels: size:XS, lgtm

#2227 docs: custom spans
  cspell.json
  docs/telemetry/custom-spans.md
Labels: size:L

#2211 fix: endpoint for client inside ProcessSession
  src/phoenix/session/session.py
Labels: size:XS, lgtm

#2188 chore: download file as temporary file
  tutorials/evals/evaluate_rag.ipynb
Labels: size:M, lgtm

#2219 feat(embeddings): add search by text and ID on selection
  app/src/components/pointcloud/EventItem.tsx
  app/src/components/pointcloud/PointCloudPointHoverHalo.tsx
  app/src/components/pointcloud/SelectionDisplayRadioGroup.tsx
  app/src/components/pointcloud/SelectionGridSizeRadioGroup.tsx
  app/src/pages/embedding/PointSelectionGrid.tsx
  app/src/pages/embedding/PointSelectionPanelContent.tsx
  app/src/store/pointCloudStore.ts
Labels: size:L, lgtm

#2166 feat!: OpenInference instrumentor for LangChain
  src/phoenix/trace/langchain/__init__.py
  src/phoenix/trace/langchain/instrumentor.py
  src/phoenix/trace/langchain/tracer.py
Labels: size:XL

#2235 fix(evals): properly use kw args for models in notebooks
  tutorials/llm_ops_overview.ipynb
Labels: size:XS, lgtm

#2240 chore: update pin on llama-index
  pyproject.toml
Labels: size:XS, lgtm

#2244 feat(ui): add hour time range
  app/src/contexts/TimeRangeContext.tsx
Labels: size:S, lgtm

#2247 fix(ui): add last_hour, fix end of hour rounding
  app/package.json
  app/src/components/filter/PrimaryDatasetTimeRange.tsx
  app/src/contexts/TimeRangeContext.tsx
Labels: size:S

#2190 feat!: replace Phoenix tracers with OpenInference instrumentors
  MIGRATION.md
  README.md
  integration-tests/trace/langchain/test_tracer.py
  integration-tests/trace/llama_index/test_callback.py
  pyproject.toml
  src/phoenix/trace/exporter.py
  src/phoenix/trace/langchain/__init__.py
  src/phoenix/trace/langchain/instrumentor.py
  src/phoenix/trace/langchain/tracer.py
  src/phoenix/trace/llama_index/callback.py
  src/phoenix/trace/llama_index/streaming.py
  src/phoenix/trace/openai/instrumentor.py
  src/phoenix/trace/tracer.py
  tests/trace/langchain/test_tracer.py
  tests/trace/llama_index/conftest.py
  tests/trace/llama_index/test_callback.py
  tests/trace/llama_index/test_debug_callback.py
  tests/trace/openai/test_instrumentor.py
  tests/trace/test_tracer.py
Labels: size:XXL, feature branch

#2245 chore: update notebooks for otel instrumentor migration
  README.md
  tutorials/evals/evaluate_human_vs_ai_classifications.ipynb
  tutorials/evals/evaluate_reference_link_correctness_classifications.ipynb
  tutorials/internal/langchain_retrieval_qa_with_sources_chain_tracing_tutorial.ipynb
  tutorials/internal/llama_index_tracing_example.ipynb
  tutorials/internal/openai_request_types.ipynb
  tutorials/llm_application_tracing_evaluating_and_analysis.ipynb
  tutorials/tracing/autogen_tutorial.ipynb
  tutorials/tracing/langchain_agent_tracing_tutorial.ipynb
  tutorials/tracing/langchain_google_palm_tracing_tutorial.ipynb
  tutorials/tracing/langchain_tracing_tutorial.ipynb
  tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb
  tutorials/tracing/llama_index_openai_agent_tracing_tutorial.ipynb
  tutorials/tracing/openai_tracing_tutorial.ipynb
Labels: size:L, lgtm

#2257 fix: working_dir info to be fstring
  src/phoenix/config.py
Labels: size:XS

#2259 chore: pin pytest version to 7.4.4
  pyproject.toml
Labels: size:XS

#2260 chore: fix typo
  pyproject.toml
Labels: size:XS

#2262 fix: handle ndarray during ingestion
  src/phoenix/trace/otel.py
Labels: size:XS

#2269 chore: fix ci by restricting llama-index version
  pyproject.toml
Labels: size:XS

#2270 refactor: replace semconv with those from openinference
  pyproject.toml
  src/phoenix/core/traces.py
  src/phoenix/experimental/evals/functions/classify.py
  src/phoenix/server/api/input_types/SpanSort.py
  src/phoenix/server/api/types/Span.py
  src/phoenix/trace/dsl/filter.py
  src/phoenix/trace/dsl/helpers.py
  src/phoenix/trace/dsl/query.py
  src/phoenix/trace/otel.py
  src/phoenix/trace/schemas.py
  src/phoenix/trace/semantic_conventions.py
  src/phoenix/trace/span_json_decoder.py
  src/phoenix/trace/span_json_encoder.py
  src/phoenix/trace/trace_dataset.py
  tests/server/api/types/test_span.py
  tests/trace/dsl/test_filter.py
  tests/trace/dsl/test_query.py
  tests/trace/test_otel.py
Labels: size:XL

#2274 chore: migrate cloud storage assets to new bucket
  examples/using_llamaindex_with_huggingface_models.ipynb
  scripts/rag/llamaindex_retrieval_chunk_eval.ipynb
  src/phoenix/experimental/evals/utils/__init__.py
  tutorials/credit_card_fraud_tutorial.ipynb
  tutorials/evals/evals_quickstart.ipynb
  tutorials/evals/evaluate_QA_classifications.ipynb
  tutorials/evals/evaluate_code_readability_classifications.ipynb
  tutorials/evals/evaluate_hallucination_classifications.ipynb
  tutorials/evals/evaluate_human_vs_ai_classifications.ipynb
  tutorials/evals/evaluate_rag.ipynb
  tutorials/evals/evaluate_reference_link_correctness_classifications.ipynb
  tutorials/evals/evaluate_relevance_classifications.ipynb
  tutorials/evals/evaluate_summarization_classifications.ipynb
  tutorials/evals/evaluate_toxicity_classifications.ipynb
  tutorials/example_datasets.ipynb
  tutorials/image_classification_tutorial.ipynb
  tutorials/integrations/arize_anyscale_traces_and_embeddings.ipynb
  tutorials/internal/llama_index_tracing_example.ipynb
  tutorials/internal/llama_index_tracing_stream_example.ipynb
  tutorials/langchain_pinecone_search_and_retrieval_tutorial.ipynb
  tutorials/llama_index_search_and_retrieval_tutorial.ipynb
  tutorials/llm_application_tracing_evaluating_and_analysis.ipynb
  tutorials/llm_ops_overview.ipynb
  tutorials/llm_summarization_tutorial.ipynb
  tutorials/milvus_llamaindex_search_and_retrieval_tutorial.ipynb
  tutorials/ragas_retrieval_evals_tutorial.ipynb
  tutorials/sentiment_classification_tutorial.ipynb
  tutorials/tracing/autogen_tutorial.ipynb
  tutorials/tracing/langchain_agent_tracing_tutorial.ipynb
  tutorials/tracing/langchain_google_palm_tracing_tutorial.ipynb
  tutorials/tracing/langchain_tracing_tutorial.ipynb
  tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb
  tutorials/tracing/llama_index_openai_agent_tracing_tutorial.ipynb
  tutorials/tracing/llama_index_tracing_tutorial.ipynb
  tutorials/tracing/openai_tracing_tutorial.ipynb
Labels: size:L

#2272 fix(trace): perform library version compatibility on llama_index
  pyproject.toml
  src/phoenix/trace/errors.py
  src/phoenix/trace/llama_index/__init__.py
  src/phoenix/trace/llama_index/callback.py
  src/phoenix/trace/llama_index/debug_callback.py
Labels: size:L

#2264 chore(evals): soft deprecate model_name param
  src/phoenix/experimental/evals/models/litellm.py
  src/phoenix/experimental/evals/models/openai.py
  src/phoenix/experimental/evals/models/vertexai.py
  tests/experimental/evals/functions/test_generate.py
  tests/experimental/evals/models/test_openai.py
Labels: size:L

#2277 docs(trace): refactor llama-index tutorials to use 0.10.0
  tutorials/internal/llama_index_tracing_example.ipynb
  tutorials/internal/llama_index_tracing_stream_example.ipynb
  tutorials/tracing/llama_index_openai_agent_tracing_tutorial.ipynb
  tutorials/tracing/llama_index_tracing_tutorial.ipynb
Labels: size:XL

#2268 feat: filter by metadata values
  src/phoenix/trace/dsl/filter.py
  tests/trace/dsl/test_filter.py
Labels: size:M

#2286 fix: set global session to None if it fails to start
  src/phoenix/session/session.py
Labels: size:XS

#2284 chore: Moves the extras to use llama-index 0.10
  pyproject.toml
Labels: size:XS

#2287 chore: pin llama-index on scripts/ directory
  scripts/rag/llamaindex_retrieval_chunk_eval.ipynb
Labels: size:XS

#2254 fix(trace): Make dataset IDs unique by instance for TraceDataset
  src/phoenix/trace/fixtures.py
  src/phoenix/trace/trace_dataset.py
  tutorials/example_datasets.ipynb
Labels: size:M

#2292 chore: add llama-index-callbacks-arize-phoenix to extras
  pyproject.toml
Labels: size:XS

#2285 docs: Add bedrock instrumentation notebook
  tutorials/integrations/bedrock_tracing_tutorial.ipynb
Labels: size:L

#2297 fix: cast message to string in vertexai model
  src/phoenix/experimental/evals/models/vertex.py
Labels: size:XS

#2288 docs: dspy tutorial notebook
  tutorials/tracing/dspy_tracing_tutorial.ipynb
Labels: size:L

#2293 fix(ui): safely parse JSON and fallback to string for span attributes
  app/src/pages/trace/TracePage.tsx
Labels: size:M

#2301 fix: allow json string for metadata
  src/phoenix/trace/otel.py
Labels: size:XS

#2303 refactor: remove unnecessary variables
  src/phoenix/trace/otel.py
Labels: size:M

#2304 feat(trace): display metadata in the trace page UI
  app/package.json
  app/src/pages/trace/TracePage.tsx
  tutorials/tracing/langchain_tracing_tutorial.ipynb
Labels: size:S

#2306 fix: make dspy notebook work on colab
  tutorials/tracing/dspy_tracing_tutorial.ipynb
Labels: size:S

#2308 feat: px.Client `log_evaluations`
  src/phoenix/server/api/routers/evaluation_handler.py
  src/phoenix/session/client.py
  src/phoenix/session/evaluation.py
  src/phoenix/trace/span_evaluations.py
Labels: size:M

#2311 docs: update notebooks for log_evaluations
  tutorials/evals/evals_quickstart.ipynb
  tutorials/evals/evaluate_rag.ipynb
  tutorials/llm_application_tracing_evaluating_and_analysis.ipynb
  tutorials/llm_ops_overview.ipynb
  tutorials/tracing/langchain_tracing_tutorial.ipynb
  tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb
  tutorials/tracing/llama_index_tracing_tutorial.ipynb
Labels: size:M

#2313 docs: update markdowns for `px.Client().log_evaluations()`
  docs/how-to/define-your-schema/llm-evaluations.md
  docs/llm-evals/quickstart-retrieval-evals/README.md
  docs/quickstart/evals.md
  docs/use-cases/rag-evaluation.md
Labels: size:S

#2315 fix: llama_index_search_and_retrieval_notebook
  tutorials/llama_index_search_and_retrieval_tutorial.ipynb
Labels: size:XS

#2317 chore: Enable starting a demo server with multiple fixtures
  src/phoenix/server/main.py
Labels: size:S

#2320 chore: skip test for lite llm on python 3.8
  tests/experimental/evals/functions/test_generate.py
Labels: size:XS

#2314 chore: set up Python monorepo with packages
  .github/workflows/python-CI.yml
  .github/workflows/release.yml
  .release-please-manifest.json
  dev-requirements.txt
  packages/phoenix-evals/IP_NOTICE
  packages/phoenix-evals/LICENSE
  packages/phoenix-evals/README.md
  packages/phoenix-evals/SECURITY
  packages/phoenix-evals/pyproject.toml
  packages/phoenix-evals/src/phoenix/evals/__init__.py
  packages/phoenix-evals/src/phoenix/evals/py.typed
  packages/phoenix-evals/src/phoenix/evals/version.py
  packages/phoenix-evals/tests/phoenix/evals/test_dummy.py
  pyproject.toml
  release-please-config.json
  tox.ini
Labels: size:L

#2324 chore: revert release-please manifest
  .release-please-manifest.json
  release-please-config.json
Labels: size:S

#2325 chore: fix release please manifest for Phoenix
  .release-please-manifest.json
  release-please-config.json
Labels: size:S

#2327 chore: revert release please manifest mode
  .github/workflows/release.yml
  .release-please-manifest.json
  release-please-config.json
Labels: size:M

#2328 chore: release-please (move to multi-repo)
  .github/workflows/release.yml
  .release-please-manifest.json
  release-please-config.json
Labels: size:M

#2329 docs: update cspell
  cspell.json
Labels: size:XS

#2331 chore: update release-please for evals
  packages/phoenix-evals/src/phoenix/evals/version.py
  release-please-config.json
Labels: size:XS

#2338 docs: Fix .rst links with markdown links
  docs/telemetry/instrumentation.md
Labels: size:XL

#2345 ci: Update cla.yml to 2.3.1
  .github/workflows/cla.yml
Labels: size:XS

#2346 fix: use static version in pyproject.toml for packages
  .release-please-manifest.json
  packages/phoenix-evals/pyproject.toml
  packages/phoenix-evals/src/phoenix/evals/version.py
  packages/phoenix-evals/tests/phoenix/evals/test_dummy.py
  release-please-config.json
Labels: size:S

#2353 feat: show span as soon as they arrive
  app/src/components/trace/utils.ts
  app/src/pages/trace/TracePage.tsx
  src/phoenix/core/traces.py
  src/phoenix/server/api/types/Span.py
  tests/core/test_traces.py
Labels: size:L

#2360 chore: change package name for release please
  release-please-config.json
Labels: size:XS

#2362 refactor: remove unused dictionary for orphan spans
  src/phoenix/core/traces.py
Labels: size:XS

#2363 docs(evals): add README
  README.md
  packages/phoenix-evals/README.md
Labels: size:M

#2355 chore: clean unnecessary line in langchain tutorial
  tutorials/tracing/langchain_tracing_tutorial.ipynb
Labels: size:XS

#2384 chore: exclude `packages` folder from source distribution
  pyproject.toml
Labels: size:XS

#2375 fix: remove run_relevance_evals and fix import issues
  packages/phoenix-evals/pyproject.toml
  packages/phoenix-evals/src/phoenix/evals/__init__.py
  packages/phoenix-evals/src/phoenix/evals/classify.py
  packages/phoenix-evals/tests/phoenix/evals/functions/test_classify.py
  scripts/rag/llama_index_w_evals_and_qa.py
  tests/experimental/evals/functions/test_classify.py
Labels: size:XL

#2390 fix: export reference link templates
  packages/phoenix-evals/src/phoenix/evals/__init__.py
Labels: size:XS

#2394 chore: exclude evals from wheel and source distribution
  pyproject.toml
Labels: size:XS

#2393 fix(evals): reference link template export
  packages/phoenix-evals/src/phoenix/evals/__init__.py
Labels: size:XS

#2396 chore: add missing sdist config
  packages/phoenix-evals/pyproject.toml
Labels: size:XS

#2389 feat: Add `phoenix.evals` bridge to `phoenix` and add `evals` extra install
  pyproject.toml
  src/phoenix/__init__.py
Labels: size:M

#2388 docs(evals): migrate evaluation notebooks
  tutorials/evals/evals_quickstart.ipynb
  tutorials/evals/evaluate_QA_classifications.ipynb
  tutorials/evals/evaluate_code_readability_classifications.ipynb
  tutorials/evals/evaluate_hallucination_classifications.ipynb
  tutorials/evals/evaluate_human_vs_ai_classifications.ipynb
  tutorials/evals/evaluate_rag.ipynb
  tutorials/evals/evaluate_reference_link_correctness_classifications.ipynb
  tutorials/evals/evaluate_relevance_classifications.ipynb
  tutorials/evals/evaluate_summarization_classifications.ipynb
  tutorials/evals/evaluate_toxicity_classifications.ipynb
Labels: size:S

#2391 chore: add symlink
  packages/phoenix-evals/src/phoenix/evals/models/anthropic.py
  src/phoenix/evals
Labels: size:XS

#2399 fix(traces): add y scroll on trace tree
  app/src/pages/trace/TracePage.tsx
Labels: size:M

#2400 docs: update ragas integration
  tutorials/ragas_retrieval_evals_tutorial.ipynb
Labels: size:XL

#2408 fix: remove symbolic links for docker build
  Dockerfile
Labels: size:XS

#2407 fix: source distribution build
  packages/phoenix-evals/pyproject.toml
  pyproject.toml
Labels: size:XS
