Repository Arize-ai/phoenix, pull requests merged in 2024-12, with the labels that each got.

#5572 ci: remove version pin on typing extensions
  requirements/unit-tests.txt
Labels: size:XS

#5570 fix(playground): add AZURE_OPENAI_API_KEY
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:XS

#5576 feat(playground)!: release playground feature
  app/src/contexts/FeatureFlagsContext.tsx
  app/src/pages/Layout.tsx
  app/src/pages/trace/SpanDetails.tsx
Labels: size:M

#5571 fix: spelling errors in prompt templates
  packages/phoenix-evals/src/phoenix/evals/default_templates.py
  src/phoenix/experiments/evaluators/llm_evaluators.py
Labels: size:S

#5522 feat: Enable `phoenix.evals` to handle multimodal message templates
  packages/phoenix-evals/src/phoenix/evals/classify.py
  packages/phoenix-evals/src/phoenix/evals/generate.py
  packages/phoenix-evals/src/phoenix/evals/models/anthropic.py
  packages/phoenix-evals/src/phoenix/evals/models/base.py
  packages/phoenix-evals/src/phoenix/evals/models/bedrock.py
  packages/phoenix-evals/src/phoenix/evals/models/litellm.py
  packages/phoenix-evals/src/phoenix/evals/models/mistralai.py
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
  packages/phoenix-evals/src/phoenix/evals/models/vertex.py
  packages/phoenix-evals/src/phoenix/evals/models/vertexai.py
  packages/phoenix-evals/src/phoenix/evals/templates.py
  packages/phoenix-evals/tests/phoenix/evals/templates/test_template.py
Labels: size:L

#5579 docs: update feature table on README to include prompt playground
  README.md
Labels: size:XS

#5581 ci: update uv and ruff
  .github/workflows/playwright.yaml
  .github/workflows/python-CI.yml
  .github/workflows/python-cron.yml
  tox.ini
Labels: size:M

#5578 chore: remove langchain claude tracing tutorial
  tutorials/tracing/bedrock_claude_tracing_tutorial.ipynb
Labels: size:L

#5566 feat: Add cancel button to playground runs
  app/src/RelayEnvironment.ts
  app/src/authFetch.ts
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/PlaygroundRunButton.tsx
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
  tox.ini
Labels: size:L

#5559 feat: Show invocation param errors within form
  app/src/pages/playground/InvocationParameterJsonEditor.tsx
  app/src/pages/playground/InvocationParametersFormFields.tsx
  app/src/pages/playground/ModelConfigButton.tsx
  app/src/pages/playground/ModelSupportedParamsFetcher.tsx
  app/src/pages/playground/__generated__/InvocationParametersFormFieldsQuery.graphql.ts
  app/src/pages/playground/__generated__/ModelSupportedParamsFetcherQuery.graphql.ts
  app/src/pages/playground/constants.tsx
  app/src/store/playground/playgroundStore.tsx
Labels: size:XL

#5592 feat(sessions): getting started guide
  app/src/pages/project/PythonSessionsGuide.tsx
  app/src/pages/project/SessionsTableEmpty.tsx
  app/src/pages/project/TypeScriptSessionsGuide.tsx
  cspell.json
  js/examples/notebooks/tracing_openai_sessions_tutorial.ipynb
  tutorials/tracing/openai_sessions_tutorial.ipynb
Labels: size:XL

#5596 fix: add copy to clipboard icon for experiment ids on experiment compare page
  app/src/components/experiment/ExperimentActionMenu.tsx
  app/src/components/table/styles.ts
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/experiment/__generated__/ExperimentCompareTableQuery.graphql.ts
  app/src/pages/experiments/ExperimentsTable.tsx
Labels: size:L

#5598 chore: change + prompt to compare
  app/src/pages/playground/Playground.tsx
Labels: size:XS

#5601 fix(playground): handle experiment id's for non streaming
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
Labels: size:S

#5363 fix: Remove deadzone when hovering example table cells
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
Labels: size:M

#5580 chore(main): release arize-phoenix 6.1.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#5606 fix(sessions): sortable last trace start time
  app/schema.graphql
  app/src/pages/project/SessionsTable.tsx
  app/src/pages/project/__generated__/SessionsTableQuery.graphql.ts
  app/src/pages/project/__generated__/SessionsTable_sessions.graphql.ts
  src/phoenix/db/insertion/span.py
  src/phoenix/db/migrations/versions/4ded9e43755f_create_project_sessions_table.py
  src/phoenix/db/models.py
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/session_last_start_times.py
  src/phoenix/server/api/input_types/ProjectSessionSort.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/api/types/ProjectSession.py
  src/phoenix/server/app.py
  tests/integration/db_migrations/test_data_migration_4ded9e43755f_create_project_sessions_table.py
  tests/integration/db_migrations/test_up_and_down_migrations.py
  tests/unit/_helpers.py
  tests/unit/server/api/dataloaders/conftest.py
Labels: size:L

#5610 refactor: print elapsed time for db migration
  src/phoenix/db/migrate.py
Labels: size:XS

#5613 chore(sessions): minor styling changes to session deetails
  app/src/pages/trace/SessionDetailsTraceList.tsx
Labels: size:S

#5612 fix(sessions): separate migration script for populating the project sessions table
  MIGRATION.md
  src/phoenix/db/migrations/data_migration_scripts/__init__.py
  src/phoenix/db/migrations/data_migration_scripts/populate_project_sessions.py
  src/phoenix/db/migrations/versions/4ded9e43755f_create_project_sessions_table.py
  tests/integration/db_migrations/test_data_migration_4ded9e43755f_create_project_sessions_table.py
Labels: size:L

#5620 docs(sessions): add note about pg extra
  MIGRATION.md
Labels: size:XS

#5622 fix: styling of experiment sequence numbers
  app/src/pages/experiments/ExperimentsTable.tsx
Labels: size:XS

#5630 fix(sessions): remove requirement that session_id has to be on root span
  src/phoenix/db/insertion/span.py
  tests/integration/_helpers.py
  tests/integration/project_sessions/test_project_sessions.py
Labels: size:L

#5638 fix(sessions): remove session_user from database table
  app/schema.graphql
  src/phoenix/db/insertion/span.py
  src/phoenix/db/migrations/data_migration_scripts/populate_project_sessions.py
  src/phoenix/db/migrations/versions/4ded9e43755f_create_project_sessions_table.py
  src/phoenix/db/models.py
  src/phoenix/server/api/types/ProjectSession.py
  tests/integration/db_migrations/test_data_migration_4ded9e43755f_create_project_sessions_table.py
  tests/integration/db_migrations/test_up_and_down_migrations.py
  tests/unit/_helpers.py
  tests/unit/server/api/types/test_ProjectSession.py
Labels: size:M

#5609 feat(components): add story book and ComboBox
  app/.env.example
  app/.eslintrc.js
  app/.gitignore
  app/.storybook/main.ts
  app/.storybook/preview-body.html
  app/.storybook/preview-head.html
  app/chromatic.config.json
  app/package.json
  app/pnpm-lock.yaml
  app/src/GlobalStyles.tsx
  app/src/__mocks__/config.ts
  app/src/components/Loading.tsx
  app/src/components/chart/ChartTooltip.tsx
  app/src/components/combobox/ComboBox.tsx
  app/src/components/combobox/index.tsx
  app/src/components/combobox/styles.tsx
  app/src/components/filter/Toolbar.tsx
  app/src/components/form/DimensionPicker.tsx
  app/src/components/index.tsx
  app/src/components/nav/Navbar.tsx
  app/src/components/pointcloud/CanvasModeRadioGroup.tsx
  app/src/components/pointcloud/ClusteringSettings.tsx
  app/src/components/pointcloud/EventItem.tsx
  app/src/components/pointcloud/InferencesVisibilitySettings.tsx
  app/src/components/pointcloud/PointCloud.tsx
  app/src/components/pointcloud/PointCloudDisplaySettings.tsx
  app/src/components/pointcloud/PointCloudParameterSettings.tsx
  app/src/components/pointcloud/PointGroupVisibilitySettings.tsx
  app/src/components/pointcloud/VisibilityCheckboxField.tsx
  app/src/components/types/index.ts
  app/src/components/types/sizing.tsx
  app/src/pages/ErrorElement.tsx
  app/src/pages/dimension/DimensionDriftTimeSeries.tsx
  app/src/pages/dimension/DimensionPage.tsx
  app/src/pages/dimension/DimensionQuantilesStats.tsx
  app/src/pages/embedding/ClusterSortPicker.tsx
  app/src/pages/embedding/EventDetails.tsx
  app/src/pages/embedding/MetricTimeSeries.tsx
  app/src/pages/embedding/PointSelectionGrid.tsx
  app/src/pages/embedding/PointSelectionPanelContent.tsx
  app/src/pages/model/ModelPage.tsx
  app/src/utils/__tests__/spanUtils.test.ts
  app/stories/ComboBox.stories.tsx
  app/stories/Gallery.stories.tsx
  app/stories/components/ThemeSplitView.tsx
  app/stories/components/ThemeToggleWrap.tsx
  app/stories/components/ThemeWrapper.tsx
  app/vite.config.mts
Labels: size:L

#5641 chore: add httpx<0.28 to tutorials
  tutorials/demos/demo_llama_index_rag.ipynb
  tutorials/evals/evals_sql_correctness_eval_with_custom_agent.ipynb
  tutorials/evals/evaluate_QA_classifications.ipynb
  tutorials/evals/evaluate_code_functionality_classifications.ipynb
  tutorials/evals/evaluate_code_readability_classifications.ipynb
  tutorials/evals/evaluate_hallucination_classifications.ipynb
  tutorials/evals/evaluate_human_vs_ai_classifications.ipynb
  tutorials/evals/evaluate_rag.ipynb
  tutorials/evals/evaluate_rag_haystack.ipynb
  tutorials/evals/evaluate_reference_link_correctness_classifications.ipynb
  tutorials/evals/evaluate_relevance_classifications.ipynb
  tutorials/evals/evaluate_summarization_classifications.ipynb
  tutorials/evals/evaluate_tool_calling.ipynb
  tutorials/evals/evaluate_toxicity_classifications.ipynb
  tutorials/evals/evaluate_user_frustration_classifications.ipynb
  tutorials/evals/evaluations_with_error_handling.ipynb
  tutorials/experiments/datasets_and_experiments_quickstart.ipynb
  tutorials/experiments/langchain_email_extraction.ipynb
  tutorials/experiments/run_experiments_with_llama_index.ipynb
  tutorials/experiments/summarization.ipynb
  tutorials/experiments/txt2sql.ipynb
  tutorials/find_cluster_export_and_explore_with_gpt.ipynb
  tutorials/hosted_phoenix/hosted_phoenix_llamaindex_tutorial.ipynb
  tutorials/hosted_phoenix/hosted_phoenix_openai_tutorial.ipynb
  tutorials/integrations/arize_anyscale_traces_and_embeddings.ipynb
  tutorials/integrations/tracing_and_evals_with_mongodb_and_llama_index.ipynb
  tutorials/llama_index_search_and_retrieval_tutorial.ipynb
  tutorials/llm_application_tracing_evaluating_and_analysis.ipynb
  tutorials/llm_generative_gpt_4.ipynb
  tutorials/llm_ops_overview.ipynb
  tutorials/milvus_llamaindex_search_and_retrieval_tutorial.ipynb
  tutorials/mistral/evaluate_rag--mistral.ipynb
  tutorials/multi_modal/image_classification_tutorial.ipynb
  tutorials/multi_modal/tracing_with_images_tutorial.ipynb
  tutorials/qdrant_langchain_instrumentation_search_and_retrieval_tutorial.ipynb
  tutorials/quickstarts/evals_quickstart.ipynb
  tutorials/quickstarts/evaluating_traces_quickstart.ipynb
  tutorials/quickstarts/tracing_quickstart_openai.ipynb
  tutorials/ragas_retrieval_evals_tutorial.ipynb
  tutorials/tracing/autogen_tutorial.ipynb
  tutorials/tracing/dspy_tracing_tutorial.ipynb
  tutorials/tracing/langchain_agent_tracing_tutorial.ipynb
  tutorials/tracing/langchain_tracing_tutorial.ipynb
  tutorials/tracing/llama_index_openai_agent_tracing_tutorial.ipynb
  tutorials/tracing/llama_index_sql_retriever_tutorial.ipynb
  tutorials/tracing/llama_index_tracing_tutorial.ipynb
  tutorials/tracing/manual_instrumentation_tutorial.ipynb
  tutorials/tracing/openai_tracing_tutorial.ipynb
  tutorials/tracing/span_filtering_tutorial.ipynb
  tutorials/tracing/tracing_with_projects_tutorial.ipynb
Labels: size:L

#5643 fix: fixing other slack link in readme
  README.md
Labels: size:XS

#5644 fix: Update README.md
  README.md
Labels: size:XS

#5642 feat(playground): pull prompt template variables from span and capture on playground spans
  app/src/pages/playground/SpanPlaygroundPage.tsx
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/constants.tsx
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/playground/schemas.ts
  app/src/store/playground/types.ts
  src/phoenix/server/api/mutations/chat_mutations.py
  src/phoenix/server/api/subscriptions.py
  tests/unit/server/api/test_subscriptions.py
Labels: size:L

#5659 fix: postgresql url query param
  src/phoenix/db/engines.py
  tests/unit/db/test_engines.py
Labels: size:XS

#5646 feat(client): add timeout parameters to log_evaluations, get_evaluations
  src/phoenix/session/client.py
Labels: size:S

#5665 ci: fix scikit-learn 1.6 compatibility for unit tests
  src/phoenix/config.py
  src/phoenix/metrics/wrappers.py
  src/phoenix/server/api/types/EmbeddingDimension.py
  tests/unit/graphql.py
  tests/unit/metrics/test_retrieval_metrics.py
  tests/unit/metrics/test_wrappers.py
Labels: size:S

#5657 fix: Intel x86_64 macOS issue with wrapt 1.17
  .github/workflows/python-CI.yml
  pyproject.toml
Labels: size:S

#5674 feat!: relaese sessions feature as arize-phoenix v7.0
  src/phoenix/db/migrations/versions/4ded9e43755f_create_project_sessions_table.py
Labels: size:S

#5672 chore(main): release arize-phoenix 7.0.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:M

#5675 fix: evaluate_tool_calling { character formatting
  tutorials/evals/evaluate_tool_calling.ipynb
Labels: documentation, size:L

#5679 fix: sslmode query parameter in postgresql database url for asyncpg
  src/phoenix/db/engines.py
Labels: size:S

#5680 chore(main): release arize-phoenix 7.0.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#5683 chore: add sessions to github readme
  README.md
Labels: size:XS

#5692 fix: prevent useless tooltips from appearing in projects
  app/src/pages/project/ProjectPage.tsx
Labels: size:XS

#5693 fix(ui): support light mode for tool coice picker
  app/src/components/generative/ToolChoiceSelector.tsx
Labels: size:XS

#5648 feat(sessions): Prettify rendered json mimeType inputs/outputs in session details pane
  app/src/pages/trace/SessionDetails.tsx
  app/src/pages/trace/SessionDetailsTraceList.tsx
  app/src/pages/trace/__generated__/SessionDetailsQuery.graphql.ts
Labels: size:M

#5696 docs: playground demo notebook
  scripts/demos/playground_demo.ipynb
Labels: size:L

#5615 fix: compute trace latency rather than relying on root span latency
  app/schema.graphql
  app/src/pages/trace/TraceDetails.tsx
  app/src/pages/trace/__generated__/TraceDetailsQuery.graphql.ts
  src/phoenix/server/api/types/Trace.py
Labels: size:M

#5634 chore: update mistral eval model to mistrailai>=1.0.0
  packages/phoenix-evals/pyproject.toml
  packages/phoenix-evals/src/phoenix/evals/models/mistralai.py
  packages/phoenix-evals/tests/phoenix/evals/models/test_mistralai.py
Labels: size:M

#5645 feat(playground): support arbitrary string model names
  app/src/components/combobox/ComboBox.tsx
  app/src/components/combobox/styles.tsx
  app/src/pages/playground/ModelComboBox.tsx
  app/src/pages/playground/ModelConfigButton.tsx
  app/src/pages/playground/ModelPicker.tsx
  app/src/pages/playground/__generated__/ModelComboBoxQuery.graphql.ts
  app/src/pages/playground/__generated__/ModelConfigButtonDialogQuery.graphql.ts
  app/src/pages/playground/__generated__/ModelPickerFragment.graphql.ts
  app/stories/ComboBox.stories.tsx
  app/stories/Gallery.stories.tsx
Labels: size:XL

#5702 fix(ts): remove explicit prebuild command
  .github/workflows/typescript-packages-CI.yml
  js/package.json
Labels: size:XS

#5703 chore(js): add rudamentary types for experiments
  js/packages/phoenix-client/src/types/annotations.ts
  js/packages/phoenix-client/src/types/core.ts
  js/packages/phoenix-client/src/types/datasets.ts
  js/packages/phoenix-client/src/types/experiments.ts
Labels: size:L

#5636 fix: add locked mode
  src/phoenix/server/api/auth.py
  src/phoenix/server/api/context.py
  src/phoenix/server/api/mutations/api_key_mutations.py
  src/phoenix/server/api/mutations/chat_mutations.py
  src/phoenix/server/api/mutations/dataset_mutations.py
  src/phoenix/server/api/mutations/span_annotations_mutations.py
  src/phoenix/server/api/mutations/trace_annotations_mutations.py
  src/phoenix/server/api/mutations/user_mutations.py
  src/phoenix/server/api/subscriptions.py
Labels: size:M

#5705 feat(js): Produce ESM build artifacts
  js/package.json
  js/packages/phoenix-client/package.json
  js/packages/phoenix-client/src/__generated__/api/v1.d.ts
  js/packages/phoenix-client/src/index.ts
  js/packages/phoenix-client/test/config.test.ts
  js/packages/phoenix-client/tsconfig.esnext.json
  js/packages/phoenix-client/tsconfig.json
  js/packages/phoenix-evals/README.md
  js/packages/phoenix-evals/package.json
  js/packages/phoenix-evals/tsconfig.esm.json
  js/packages/phoenix-evals/tsconfig.esnext.json
  js/packages/phoenix-evals/tsconfig.json
  js/packages/phoenix-types/README.md
  js/packages/phoenix-types/package.json
  js/packages/phoenix-types/tsconfig.esm.json
  js/packages/phoenix-types/tsconfig.esnext.json
  js/packages/phoenix-types/tsconfig.json
  js/pnpm-lock.yaml
  js/tsconfig.base.es5.json
  js/tsconfig.base.esm.json
  js/tsconfig.base.esnext.json
Labels: size:XXL

#5708 feat(playground): Support gemini-2.0-flash-exp model
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:XS

#5694 chore(main): release arize-phoenix 7.1.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#5706 fix: increase python upper bound to include python 3.13
  .github/workflows/playwright.yaml
  .github/workflows/python-CI.yml
  .github/workflows/python-cron.yml
  pyproject.toml
  requirements/build-graphql-schema.txt
  requirements/type-check.txt
  src/phoenix/server/api/input_types/DataQualityMetricInput.py
  src/phoenix/server/api/input_types/PerformanceMetricInput.py
  src/phoenix/server/api/types/DataQualityMetric.py
  src/phoenix/server/api/types/PerformanceMetric.py
  src/phoenix/server/api/types/TimeSeries.py
  src/phoenix/server/types.py
Labels: size:L

#5709 chore(main): release arize-phoenix 7.1.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#5714 chore: Update readme links
  README.md
Labels: size:S

#5715 feat(playground): Enhance template editor ergonomics
  app/src/components/templateEditor/TemplateEditor.tsx
  app/src/pages/playground/PlaygroundChatTemplate.tsx
Labels: size:S

#5671 feat(js): initial directories
  .github/workflows/typescript-packages-CI.yml
  js/.changeset/README.md
  js/.changeset/config.json
  js/.eslintrc.js
  js/.prettierignore
  js/README.MD
  js/examples/notebooks/langchain/deno.json
  js/examples/notebooks/langchain/package.json
  js/package.json
  js/packages/phoenix-client/README.md
  js/packages/phoenix-client/examples/list_datasets.ts
  js/packages/phoenix-client/package.json
  js/packages/phoenix-client/src/__generated__/api/v1.d.ts
  js/packages/phoenix-client/src/index.ts
  js/packages/phoenix-client/src/types/annotations.ts
  js/packages/phoenix-client/src/types/core.ts
  js/packages/phoenix-client/src/types/datasets.ts
  js/packages/phoenix-client/src/types/experiments.ts
  js/packages/phoenix-client/test/config.test.ts
  js/packages/phoenix-client/tsconfig.esnext.json
  js/packages/phoenix-client/tsconfig.json
  js/pnpm-lock.yaml
  js/tsconfig.base.es5.json
  js/tsconfig.base.esm.json
  js/tsconfig.base.esnext.json
Labels: size:XL

#5722 ci: always use python 3.9 for building schemas
  .github/workflows/python-CI.yml
  tox.ini
Labels: size:S

#5739 docs: add support for hiding LLM invocation parameters in masking span attributes
  docs/tracing/how-to-tracing/customize-spans/masking-span-attributes.md
Labels: size:XS

#5726 feat(promts): skeleton UI for promts
  app/schema.graphql
  app/src/Routes.tsx
  app/src/pages/Layout.tsx
  app/src/pages/index.tsx
  app/src/pages/prompt/PromptPage.tsx
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  app/src/pages/prompt/index.tsx
  app/src/pages/prompt/promptLoader.tsx
  app/src/pages/prompts/PromptsPage.tsx
  app/src/pages/prompts/PromptsTable.tsx
  app/src/pages/prompts/__generated__/PromptsTablePromptsQuery.graphql.ts
  app/src/pages/prompts/__generated__/PromptsTable_datasets.graphql.ts
  app/src/pages/prompts/__generated__/PromptsTable_prompts.graphql.ts
  app/src/pages/prompts/__generated__/promptsLoaderQuery.graphql.ts
  app/src/pages/prompts/index.tsx
  app/src/pages/prompts/promptsLoader.ts
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/Prompt.py
Labels: size:XXL

#5747 ci: remove windows for playwright tests
  .github/workflows/playwright.yaml
Labels: size:XS

#5748 feat(prompts): Add prompt combobox to playground page + deeplink to prompt specific playground
  app/src/Routes.tsx
  app/src/components/combobox/ComboBox.tsx
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/PlaygroundTemplate.tsx
  app/src/pages/playground/PromptComboBox.tsx
  app/src/pages/playground/__generated__/PromptComboBoxQuery.graphql.ts
  app/src/pages/prompt/PromptPage.tsx
  app/src/pages/prompt/PromptPlaygroundPage.tsx
  app/src/pages/prompt/promptLoader.tsx
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
Labels: size:L

#5749 Doc Fix: Column Name in *Evaluating Phoenix Traces*
  docs/evaluation/how-to-evals/evaluating-phoenix-traces.md
Labels: size:XS

#5751 feat(prompts): Implement SavePromptForm for creating new prompts
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundTemplate.tsx
  app/src/pages/playground/SavePromptForm.tsx
  app/src/pages/prompts/PromptsPage.tsx
Labels: size:L

#5745 feat: Add prompthub models migration
  src/phoenix/db/migrations/versions/bc8fea3c2bc8_add_prompt_tables.py
  src/phoenix/db/models.py
  tests/integration/db_migrations/test_up_and_down_migrations.py
Labels: size:L

#5752 feat(prompts): rudimentary prompt details page #5741
  app/src/pages/prompt/ChatTemplateMessage.tsx
  app/src/pages/prompt/PromptPage.tsx
  app/src/pages/prompt/PromptTabContent.tsx
  app/src/pages/prompt/__generated__/PromptTabContentAside.graphql.ts
  app/src/pages/prompt/__generated__/PromptTabContent__aside.graphql.ts
  app/src/pages/prompt/__generated__/PromptTabContent__main.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  app/src/pages/prompt/promptLoader.tsx
Labels: size:L

#5768 docs(zh): initial readme
  docs/locales/zh/README.md
Labels: size:M

#5769 docs(jp): initial readme in japanese
  docs/locales/jp/README.md
Labels: size:M

#5767 feat: Spike out dummy PromptVersion connection
  app/schema.graphql
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/Prompt.py
  src/phoenix/server/api/types/PromptVersion.py
Labels: size:L

#5766 feat(prompts): Scaffold prompt versions tab / list
  app/src/Routes.tsx
  app/src/components/utility/Truncate.tsx
  app/src/pages/playground/ModelConfigButton.tsx
  app/src/pages/prompt/PromptIndexPage.tsx
  app/src/pages/prompt/PromptLayout.tsx
  app/src/pages/prompt/PromptPlaygroundPage.tsx
  app/src/pages/prompt/PromptVersionDetailsPage.tsx
  app/src/pages/prompt/PromptVersionsList.tsx
  app/src/pages/prompt/PromptVersionsPage.tsx
  app/src/pages/prompt/__generated__/PromptIndexPage__aside.graphql.ts
  app/src/pages/prompt/__generated__/PromptIndexPage__main.graphql.ts
  app/src/pages/prompt/__generated__/PromptLayout__main.graphql.ts
  app/src/pages/prompt/__generated__/PromptTabContent__main.graphql.ts
  app/src/pages/prompt/__generated__/PromptVersionsList__main.graphql.ts
  app/src/pages/prompt/__generated__/PromptVersionsPageContent__main.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts
  app/src/pages/prompt/index.tsx
  app/src/pages/prompt/promptLoader.tsx
  app/src/pages/prompt/promptVersionLoader.tsx
  app/src/pages/prompt/usePromptIdLoader.tsx
  src/phoenix/server/api/queries.py
Labels: size:XXL

#5781 fix(sessions): exclude null i/o values in dataloader query for sessions table
  src/phoenix/server/api/dataloaders/session_io.py
Labels: size:S

#5783 fix: update index.html
  src/phoenix/server/templates/index.html
Labels: size:XS

#5718 chore(main): release arize-phoenix 7.2.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#5780 feat(prompts): Render model invocation params in prompt details view
  app/src/pages/prompt/PromptIndexPage.tsx
  app/src/pages/prompt/PromptInvocationParameters.tsx
  app/src/pages/prompt/PromptVersionDetailsPage.tsx
  app/src/pages/prompt/PromptVersionsList.tsx
  app/src/pages/prompt/__generated__/PromptIndexPage__main.graphql.ts
  app/src/pages/prompt/__generated__/PromptInvocationParameters__main.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts
  app/src/pages/prompt/promptVersionLoader.tsx
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/Prompt.py
  src/phoenix/server/api/types/PromptVersion.py
Labels: size:XL

#5786 feat(prompts): Render prompt messages on prompt detail view
  app/src/Routes.tsx
  app/src/components/CopyToClipboardButton.tsx
  app/src/components/templateEditor/TemplateEditor.tsx
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/prompt/ChatTemplateMessage.tsx
  app/src/pages/prompt/PromptChatMessages.tsx
  app/src/pages/prompt/PromptIndexPage.tsx
  app/src/pages/prompt/PromptInvocationParameters.tsx
  app/src/pages/prompt/PromptVersionDetailsPage.tsx
  app/src/pages/prompt/PromptVersionsList.tsx
  app/src/pages/prompt/PromptVersionsPage.tsx
  app/src/pages/prompt/__generated__/PromptChatMessages__main.graphql.ts
  app/src/pages/prompt/__generated__/PromptIndexPage__main.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts
  app/src/pages/prompt/__generated__/promptVersionsLoaderQuery.graphql.ts
  app/src/pages/prompt/promptVersionLoader.tsx
  app/src/pages/prompt/promptVersionsLoader.tsx
  app/src/pages/prompt/schemas.ts
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/Prompt.py
Labels: size:XL

#5789 fix: fix light mode filters and colors
  app/src/pages/project/AnnotationTooltipFilterActions.tsx
  app/src/pages/trace/SpanDetails.tsx
Labels: size:XS

#5577 chore(main): release arize-phoenix-evals 0.18.0
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#5803 feat(components): styled button
  app/src/components/button/Button.tsx
  app/src/components/button/styles.tsx
  app/src/components/types/index.ts
  app/src/components/types/sizing.ts
  app/src/components/types/variance.ts
  app/stories/Button.stories.tsx
  app/stories/Gallery.stories.tsx
Labels: size:L

#5773 feat(playground): Update o1 model listing and params
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:S

#5805 fix(prompts): rename tables
  src/phoenix/db/migrations/versions/bc8fea3c2bc8_add_prompt_tables.py
  src/phoenix/db/models.py
Labels: size:M

#5787 feat: Add PromptTemplate type
  app/schema.graphql
  app/src/hooks/useChatMessageStyles.ts
  app/src/pages/prompt/PromptChatMessages.tsx
  app/src/pages/prompt/__generated__/PromptChatMessages__main.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts
  app/src/pages/prompt/promptVersionLoader.tsx
  app/src/pages/prompt/schemas.ts
  src/phoenix/server/api/helpers/prompts/__init__.py
  src/phoenix/server/api/helpers/prompts/models.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/Prompt.py
  src/phoenix/server/api/types/PromptVersion.py
  src/phoenix/server/api/types/PromptVersionTemplate.py
Labels: size:XL

#5810 fix(prompts): add sqlite_autoincrement for primary key on prompt_versions table
  src/phoenix/db/migrations/versions/bc8fea3c2bc8_add_prompt_tables.py
  tests/integration/db_migrations/test_autoincrement_primary_keys.py
Labels: size:M

#5811 feat(tracing): pretty print JSON strings for structured data outputs
  app/src/components/code/styles.tsx
  app/src/components/markdown/MarkdownBlock.tsx
  app/src/components/utility/PrettyText.tsx
  app/src/components/utility/index.tsx
  app/src/hooks/usePrettyText.ts
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/trace/SpanDetails.tsx
Labels: size:M

#5790 chore(main): release arize-phoenix 7.3.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#5755 feat(js): run experiment
  js/.prettierrc.json
  js/README.MD
  js/examples/apps/phoenix-experiment-runner/.env.example
  js/examples/apps/phoenix-experiment-runner/README.md
  js/examples/apps/phoenix-experiment-runner/docker-compose.yml
  js/examples/apps/phoenix-experiment-runner/index.ts
  js/examples/apps/phoenix-experiment-runner/package.json
  js/examples/apps/phoenix-experiment-runner/qa-dataset.csv
  js/examples/apps/phoenix-experiment-runner/tsconfig.json
  js/packages/phoenix-client/package.json
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  js/packages/phoenix-client/src/client.ts
  js/packages/phoenix-client/src/config.ts
  js/packages/phoenix-client/src/experiments/index.ts
  js/packages/phoenix-client/src/experiments/runExperiment.ts
  js/packages/phoenix-client/src/index.ts
  js/packages/phoenix-client/src/types/datasets.ts
  js/packages/phoenix-client/src/types/experiments.ts
  js/packages/phoenix-client/src/utils/pluralize.ts
  js/packages/phoenix-client/src/utils/promisifyResult.ts
  js/packages/phoenix-client/tsconfig.esm.json
  js/packages/phoenix-client/tsconfig.json
  js/pnpm-lock.yaml
  js/pnpm-workspace.yaml
Labels: size:XXL

#5818 fix: increase wait time allowance for uvicorn server process start
  src/phoenix/server/main.py
Labels: size:XS

#5819 chore(main): release arize-phoenix 7.3.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#5820 chore: enable running embeddings, passthrough smtp config
  app/package.json
  requirements/dev.txt
  tox.ini
Labels: size:S

#5823 fix(playground): add common base class for OpenAI and AzureOpenAI streaming clients
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:M

#5824 chore(main): release arize-phoenix 7.3.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#5829 feat(docs): add support links
  app/src/Routes.tsx
  app/src/components/icon/Icons.tsx
  app/src/components/nav/Navbar.tsx
  app/src/pages/Layout.tsx
  app/src/pages/index.tsx
  app/src/pages/support/SupportPage.tsx
  app/src/pages/support/index.tsx
Labels: size:L

#5847 chore(prompts): add prompt version tags graphql schema with mocks
  app/schema.graphql
  src/phoenix/server/api/types/PromptVersion.py
  src/phoenix/server/api/types/PromptVersionTag.py
Labels: size:M

#5849 feat(prompts): graphql types for tools, output_schema
  app/schema.graphql
  app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts
  app/src/pages/prompt/promptVersionLoader.tsx
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/JSONSchema.py
  src/phoenix/server/api/types/Prompt.py
  src/phoenix/server/api/types/PromptVersion.py
  src/phoenix/server/api/types/ToolDefinition.py
Labels: size:L

#5843 feat(prompts): Implement prompts as code examples beneath prompt
  app/src/components/code/PythonBlock.tsx
  app/src/pages/prompt/PromptCodeExportCard.tsx
  app/src/pages/prompt/PromptIndexPage.tsx
  app/src/pages/prompt/PromptVersionDetailsPage.tsx
  app/src/pages/prompt/__generated__/PromptCodeExportCard__main.graphql.ts
  app/src/pages/prompt/__generated__/PromptIndexPage__main.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts
  app/src/pages/prompt/promptCodeSnippets.tsx
  app/src/pages/prompt/promptVersionLoader.tsx
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/Prompt.py
Labels: size:XL

#5850 feat(components): TextField
  app/src/GlobalStyles.tsx
  app/src/components/auth/CreateAPIKeyDialog.tsx
  app/src/components/code/CodeEditorFieldWrapper.tsx
  app/src/components/combobox/ComboBox.tsx
  app/src/components/combobox/styles.tsx
  app/src/components/content/Text.tsx
  app/src/components/dataset/DatasetForm.tsx
  app/src/components/field/styles.ts
  app/src/components/index.tsx
  app/src/components/textfield/TextField.tsx
  app/src/components/textfield/index.tsx
  app/stories/Button.stories.tsx
  app/stories/Gallery.stories.tsx
  app/stories/TextField.stories.tsx
Labels: size:L
