Repository Arize-ai/phoenix, pull requests merged in 2024-03, with the labels that each got.

#2386 docs(evals): update tracing tutorials with arize-phoenix-evals
  tutorials/tracing/autogen_tutorial.ipynb
  tutorials/tracing/langchain_google_palm_tracing_tutorial.ipynb
  tutorials/tracing/langchain_tracing_tutorial.ipynb
  tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb
  tutorials/tracing/llama_index_tracing_tutorial.ipynb
Labels: size:M

#2366 fix: remove __computed__ attributes from exported dataframe
  src/phoenix/trace/span_json_encoder.py
Labels: size:S

#2422 docs: Remove references to deprecated `processing` module in docs
  docs/llm-evals/running-pre-tested-evals/q-and-a-on-retrieved-data.md
  docs/llm-evals/running-pre-tested-evals/retrieval-rag-relevance.md
Labels: size:M

#2421 feat: Removes token processing module from `phoenix.evals`
  packages/phoenix-evals/pyproject.toml
  packages/phoenix-evals/src/phoenix/evals/processing.py
  src/phoenix/experimental/evals/functions/processing.py
Labels: size:L

#2359 feat(ui): new side nav with projects
  app/package-lock.json
  app/package.json
  app/src/Routes.tsx
  app/src/components/Link.tsx
  app/src/components/nav/Navbar.tsx
  app/src/components/trace/SpanKindIcon.tsx
  app/src/pages/Layout.tsx
  app/src/pages/home/homeLoader.ts
  app/src/pages/projects/ProjectsPage.tsx
  app/src/pages/trace/TracePage.tsx
  app/src/pages/tracing/SpansTable.tsx
  app/src/pages/tracing/TracesTable.tsx
  app/src/window.d.ts
  cspell.json
  src/phoenix/server/app.py
  src/phoenix/server/templates/index.html
Labels: size:L

#2429 chore: downsize hatch dependencies
  pyproject.toml
  tests/experimental/evals/functions/test_generate.py
Labels: size:S

#2430 chore: Update llama-index rag optimization script
  scripts/rag/llama_index_w_evals_and_qa.py
  scripts/rag/llamaindex_retrieval_chunk_eval.ipynb
Labels: size:L

#2432 chore: remove tests from source distribution
  packages/phoenix-evals/pyproject.toml
Labels: size:XS

#2426 chore: upgrade ruff to 0.3.0
  .pre-commit-config.yaml
  dev-requirements.txt
  packages/phoenix-evals/pyproject.toml
  packages/phoenix-evals/src/phoenix/evals/executors.py
  packages/phoenix-evals/src/phoenix/evals/models/rate_limiters.py
  packages/phoenix-evals/tests/phoenix/evals/test_dummy.py
  pyproject.toml
  scripts/rag/llama_index_w_evals_and_qa.py
  src/phoenix/core/evals.py
  src/phoenix/core/model.py
  src/phoenix/core/model_schema.py
  src/phoenix/experimental/evals/functions/executor.py
  src/phoenix/experimental/evals/models/base.py
  src/phoenix/experimental/evals/models/rate_limiters.py
  src/phoenix/metrics/__init__.py
  src/phoenix/metrics/binning.py
  src/phoenix/metrics/mixins.py
  src/phoenix/metrics/wrappers.py
  src/phoenix/pointcloud/pointcloud.py
  src/phoenix/server/api/input_types/SpanSort.py
  src/phoenix/server/api/interceptor.py
  src/phoenix/server/api/routers/trace_handler.py
  src/phoenix/server/api/schema.py
  src/phoenix/server/api/types/Segments.py
  src/phoenix/server/main.py
  src/phoenix/session/data_extractor.py
  src/phoenix/session/evaluation.py
  src/phoenix/trace/dsl/filter.py
  src/phoenix/trace/dsl/helpers.py
  src/phoenix/trace/langchain/tracer.py
  src/phoenix/trace/span_evaluations.py
  src/phoenix/trace/tracer.py
  tests/datasets/test_dataset.py
Labels: size:L

#2431 chore: add deprecation warning to phoenix.experimental.evals
  src/phoenix/experimental/evals/__init__.py
Labels: size:S

#2435 docs: update readme for phoenix.evals, fix llama-index example
  README.md
Labels: size:M

#2425 fix: Properly define `BedrockModel`
  packages/phoenix-evals/src/phoenix/evals/models/bedrock.py
  packages/phoenix-evals/src/phoenix/evals/models/litellm.py
  packages/phoenix-evals/tests/phoenix/evals/models/test_bedrock.py
  src/phoenix/experimental/evals/models/litellm.py
  tests/experimental/evals/functions/test_generate.py
Labels: size:M

#2438 fix: turn span_kind enums into string because it's not serializable by pyarrow
  src/phoenix/trace/dsl/query.py
  tests/trace/dsl/test_query.py
Labels: size:S

#2441 fix: `llm_generate` now preserves input index when constructing the output
  packages/phoenix-evals/src/phoenix/evals/generate.py
  packages/phoenix-evals/tests/phoenix/evals/functions/test_generate.py
Labels: size:M

#2442 fix: update rag and llm ops notebooks
  tutorials/evals/evaluate_rag.ipynb
  tutorials/llm_ops_overview.ipynb
Labels: size:S

#2445 docs: log information about the server at startup
  pyproject.toml
  src/phoenix/server/main.py
Labels: size:M

#2339 feat: add metadata to spans and traces table
  app/schema.graphql
  app/src/pages/tracing/SpansTable.tsx
  app/src/pages/tracing/TracesTable.tsx
  app/src/pages/tracing/__generated__/SpansTableSpansQuery.graphql.ts
  app/src/pages/tracing/__generated__/SpansTable_spans.graphql.ts
  app/src/pages/tracing/__generated__/TracesTableQuery.graphql.ts
  app/src/pages/tracing/__generated__/TracesTable_spans.graphql.ts
  app/src/pages/tracing/__generated__/TracingHomePageQuery.graphql.ts
  app/src/store/tracingStore.tsx
  src/phoenix/server/api/types/Span.py
Labels: size:L

#2444 chore: add graphql scaffolding for projects
  app/schema.graphql
  src/phoenix/server/api/schema.py
  src/phoenix/server/api/types/Project.py
Labels: size:L

#2460 fix(ui): link to span in spans table
  app/src/pages/project/SpansTable.tsx
Labels: size:XS

#2458 feat(ui): auto-expand side nav on hover
  app/src/GlobalStyles.tsx
  app/src/components/nav/Navbar.tsx
  app/src/pages/Layout.tsx
Labels: size:L

#2433 feat(traces): store and query spans by project name
  src/phoenix/core/project.py
  src/phoenix/core/traces.py
  src/phoenix/server/api/input_types/SpanSort.py
  src/phoenix/server/api/routers/trace_handler.py
  src/phoenix/server/api/schema.py
  src/phoenix/server/api/types/Project.py
  tests/core/test_project.py
Labels: size:XL

#2465 chore: pin instrumentation versions
  pyproject.toml
Labels: size:XS

#2466 feat(projects): project node interace
  src/phoenix/server/api/schema.py
Labels: size:XS

#2459 feat(projects): project listing
  app/package.json
  app/src/Routes.tsx
  app/src/pages/Layout.tsx
  app/src/pages/home/__generated__/homeLoaderQuery.graphql.ts
  app/src/pages/home/homeLoader.ts
  app/src/pages/project/__generated__/projectLoaderQuery.graphql.ts
  app/src/pages/project/index.tsx
  app/src/pages/project/projectLoader.ts
  app/src/pages/projects/ProjectsPage.tsx
  app/src/pages/projects/__generated__/ProjectsPageQuery.graphql.ts
Labels: size:XL

#2471 refactor: use semantic convention resource attribute for project name
  pyproject.toml
  src/phoenix/server/api/routers/trace_handler.py
Labels: size:XS

#2470 refactor: ProjectPageHeader uses projects type for query
  app/src/pages/project/ProjectPage.tsx
  app/src/pages/project/ProjectPageHeader.tsx
  app/src/pages/project/__generated__/ProjectPageHeaderQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectPageHeader_stats.graphql.ts
  app/src/pages/project/__generated__/ProjectPageQuery.graphql.ts
Labels: size:L

#2475 refactor: relocate gql eval queries under project
  app/schema.graphql
  src/phoenix/server/api/types/Project.py
Labels: size:L

#2477 refactor: add project_name parameter to downloads
  src/phoenix/server/api/routers/evaluation_handler.py
  src/phoenix/server/api/routers/span_handler.py
  src/phoenix/session/client.py
  src/phoenix/session/data_extractor.py
  src/phoenix/session/session.py
  src/phoenix/utilities/__init__.py
Labels: size:M

#2436 refactor: remove computed attributes from span attributes
  src/phoenix/core/project.py
  src/phoenix/core/traces.py
  src/phoenix/server/api/input_types/SpanSort.py
  src/phoenix/server/api/types/Span.py
  src/phoenix/trace/dsl/filter.py
  src/phoenix/trace/schemas.py
  src/phoenix/trace/span_json_encoder.py
  tests/core/test_project.py
  tests/server/api/input_types/test_SpanSort.py
Labels: size:L

#2485 refactor: revert dict to list
  src/phoenix/server/api/schema.py
Labels: size:XS

#2482 refactor: remove post method on span handler
  src/phoenix/core/traces.py
  src/phoenix/server/api/routers/span_handler.py
  src/phoenix/server/api/routers/trace_handler.py
  src/phoenix/server/main.py
  src/phoenix/session/session.py
Labels: size:M

#2468 docs: Add SQL retriever tracing tutorial
  tutorials/tracing/llama_index_sql_retriever_tutorial.ipynb
Labels: size:L

#2489 feat: Update `AnthropicModel` to use `messages` API
  packages/phoenix-evals/pyproject.toml
  packages/phoenix-evals/src/phoenix/evals/__init__.py
  packages/phoenix-evals/src/phoenix/evals/models/__init__.py
  packages/phoenix-evals/src/phoenix/evals/models/anthropic.py
Labels: size:M

#2480 refactor(ui): fetch document evaluation summary from project
  app/schema.graphql
  app/src/pages/project/DocumentEvaluationSummary.tsx
  app/src/pages/project/__generated__/DocumentEvaluationSummaryQuery.graphql.ts
  app/src/pages/project/__generated__/DocumentEvaluationSummaryValueFragment.graphql.ts
  app/src/pages/project/__generated__/DocumentEvaluationSummaryValueQuery.graphql.ts
  src/phoenix/server/api/schema.py
Labels: size:L

#2423 chore: demonstrate using self hosted Ollama & OpenAI as BaseModel
  packages/phoenix-evals/src/phoenix/evals/models/litellm.py
  packages/phoenix-evals/tests/phoenix/evals/models/test_litellm.py
  packages/phoenix-evals/tests/phoenix/evals/models/test_openai.py
Labels: size:M

#2478 refactor: add spans field to gql project type
  app/schema.graphql
  src/phoenix/server/api/types/Project.py
Labels: size:M

#2491 chore: Bump LiteLLM minimum version
  packages/phoenix-evals/pyproject.toml
  packages/phoenix-evals/tests/phoenix/evals/models/test_litellm.py
  packages/phoenix-evals/tests/phoenix/evals/models/test_openai.py
Labels: size:M

#2420 feat: Integrate `phoenix.evals` into `phoenix`
  MIGRATION.md
  src/phoenix/experimental/evals/__init__.py
Labels: size:M

#2484 feat(gql): add trace count to gql project
  app/schema.graphql
  app/src/pages/projects/ProjectsPage.tsx
  app/src/pages/projects/__generated__/ProjectsPageQuery.graphql.ts
  src/phoenix/core/project.py
  src/phoenix/core/traces.py
  src/phoenix/server/api/types/Project.py
  tests/core/test_project.py
Labels: size:M

#2494 refactor: Add `streaming_last_updated_at` to Project model
  app/schema.graphql
  src/phoenix/server/api/types/Project.py
Labels: size:XS

#2492 refactor: traces and spans table pull data from project query
  app/src/pages/project/ProjectPage.tsx
  app/src/pages/project/ProjectPageHeader.tsx
  app/src/pages/project/SpanColumnSelector.tsx
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/StreamToggle.tsx
  app/src/pages/project/TracesTable.tsx
  app/src/pages/project/__generated__/LiveStreamButtonRefetchQuery.graphql.ts
  app/src/pages/project/__generated__/LiveStreamButton_data.graphql.ts
  app/src/pages/project/__generated__/ProjectPageHeaderQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectPageHeader_stats.graphql.ts
  app/src/pages/project/__generated__/ProjectPageQuery.graphql.ts
  app/src/pages/project/__generated__/SpanColumnSelector_evaluations.graphql.ts
  app/src/pages/project/__generated__/SpansTableSpansQuery.graphql.ts
  app/src/pages/project/__generated__/SpansTable_spans.graphql.ts
  app/src/pages/project/__generated__/StreamToggleRefetchQuery.graphql.ts
  app/src/pages/project/__generated__/StreamToggle_data.graphql.ts
  app/src/pages/project/__generated__/TracesTableQuery.graphql.ts
  app/src/pages/project/__generated__/TracesTable_spans.graphql.ts
Labels: size:XXL

#2496 feat(ui): copy to clipboard for prompt template etc.
  app/package-lock.json
  app/package.json
  app/src/components/CopyToClipboardButton.tsx
  app/src/components/index.tsx
  app/src/pages/trace/TracePage.tsx
Labels: size:L

#2343 docs: sync Feb 21, 2024
  cspell.json
  docs/.gitbook/assets/evals.png
  docs/README.md
  docs/SUMMARY.md
  docs/api/client.md
  docs/api/dataset-and-schema.md
  docs/api/evals.md
  docs/api/evaluation-models.md
  docs/concepts/embeddings-analysis.md
  docs/concepts/embeddings.md
  docs/concepts/evaluation.md
  docs/concepts/generating-embeddings.md
  docs/concepts/llm-observability.md
  docs/concepts/llm-traces.md
  docs/concepts/open-inference.md
  docs/environments.md
  docs/how-to/define-your-schema/README.md
  docs/how-to/define-your-schema/llm-evaluations.md
  docs/how-to/export-your-data.md
  docs/how-to/manage-the-app.md
  docs/how-to/use-example-datasets.md
  docs/install-and-import-phoenix.md
  docs/integrations/autogen-support.md
  docs/integrations/dspy.md
  docs/integrations/langchain.md
  docs/integrations/llamaindex.md
  docs/integrations/openai.md
  docs/llm-evals/building-your-own-evals.md
  docs/llm-evals/evaluation-types.md
  docs/llm-evals/llm-evals.md
  docs/llm-evals/quickstart-retrieval-evals/README.md
  docs/llm-evals/running-pre-tested-evals/README.md
  docs/llm-evals/running-pre-tested-evals/q-and-a-on-retrieved-data.md
  docs/llm-evals/running-pre-tested-evals/retrieval-rag-relevance.md
  docs/notebooks.md
  docs/quickstart/evals.md
  docs/quickstart/llm-traces.md
  docs/quickstart/phoenix-inferences/README.md
  docs/reference/frequently-asked-questions.md
  docs/telemetry/custom-spans.md
  docs/telemetry/deploying-phoenix.md
  docs/telemetry/instrumentation.md
  docs/use-cases/rag-evaluation.md
  docs/use-cases/troubleshooting-llm-retrieval-with-vector-stores.md
Labels: size:XL

#2501 Revert "docs: sync Feb 21, 2024"
  cspell.json
  docs/.gitbook/assets/evals.png
  docs/README.md
  docs/SUMMARY.md
  docs/api/client.md
  docs/api/dataset-and-schema.md
  docs/api/evals.md
  docs/api/evaluation-models.md
  docs/concepts/embeddings-analysis.md
  docs/concepts/embeddings.md
  docs/concepts/evaluation.md
  docs/concepts/generating-embeddings.md
  docs/concepts/llm-observability.md
  docs/concepts/llm-traces.md
  docs/concepts/open-inference.md
  docs/environments.md
  docs/how-to/define-your-schema/README.md
  docs/how-to/define-your-schema/llm-evaluations.md
  docs/how-to/export-your-data.md
  docs/how-to/manage-the-app.md
  docs/how-to/use-example-datasets.md
  docs/install-and-import-phoenix.md
  docs/integrations/autogen-support.md
  docs/integrations/dspy.md
  docs/integrations/langchain.md
  docs/integrations/llamaindex.md
  docs/integrations/openai.md
  docs/llm-evals/building-your-own-evals.md
  docs/llm-evals/evaluation-types.md
  docs/llm-evals/llm-evals.md
  docs/llm-evals/quickstart-retrieval-evals/README.md
  docs/llm-evals/running-pre-tested-evals/README.md
  docs/llm-evals/running-pre-tested-evals/q-and-a-on-retrieved-data.md
  docs/llm-evals/running-pre-tested-evals/retrieval-rag-relevance.md
  docs/notebooks.md
  docs/quickstart/evals.md
  docs/quickstart/llm-traces.md
  docs/quickstart/phoenix-inferences/README.md
  docs/reference/frequently-asked-questions.md
  docs/telemetry/custom-spans.md
  docs/telemetry/deploying-phoenix.md
  docs/telemetry/instrumentation.md
  docs/use-cases/rag-evaluation.md
  docs/use-cases/troubleshooting-llm-retrieval-with-vector-stores.md
Labels: size:XL

#2502 docs: sync
  cspell.json
  docs/.gitbook/assets/evals.png
  docs/README.md
  docs/SUMMARY.md
  docs/api/client.md
  docs/api/dataset-and-schema.md
  docs/api/evals.md
  docs/api/evaluation-models.md
  docs/concepts/embeddings-analysis.md
  docs/concepts/embeddings.md
  docs/concepts/evaluation.md
  docs/concepts/generating-embeddings.md
  docs/concepts/llm-observability.md
  docs/concepts/llm-traces.md
  docs/concepts/open-inference.md
  docs/environments.md
  docs/how-to/define-your-schema/README.md
  docs/how-to/define-your-schema/llm-evaluations.md
  docs/how-to/export-your-data.md
  docs/how-to/manage-the-app.md
  docs/how-to/use-example-datasets.md
  docs/install-and-import-phoenix.md
  docs/integrations/autogen-support.md
  docs/integrations/dspy.md
  docs/integrations/langchain.md
  docs/integrations/llamaindex.md
  docs/integrations/openai.md
  docs/llm-evals/building-your-own-evals.md
  docs/llm-evals/evaluation-types.md
  docs/llm-evals/llm-evals.md
  docs/llm-evals/quickstart-retrieval-evals/README.md
  docs/llm-evals/running-pre-tested-evals/README.md
  docs/llm-evals/running-pre-tested-evals/q-and-a-on-retrieved-data.md
  docs/llm-evals/running-pre-tested-evals/retrieval-rag-relevance.md
  docs/notebooks.md
  docs/quickstart/evals.md
  docs/quickstart/llm-traces.md
  docs/quickstart/phoenix-inferences/README.md
  docs/reference/frequently-asked-questions.md
  docs/telemetry/custom-spans.md
  docs/telemetry/deploying-phoenix.md
  docs/telemetry/instrumentation.md
  docs/use-cases/rag-evaluation.md
  docs/use-cases/troubleshooting-llm-retrieval-with-vector-stores.md
Labels: size:XL

#2504 refactor: add validate_span_filter_condition to project type
  app/schema.graphql
  src/phoenix/server/api/types/Project.py
Labels: size:S

#2508 feat(ui): show first non-empty project
  app/src/pages/home/__generated__/homeLoaderQuery.graphql.ts
  app/src/pages/home/homeLoader.ts
Labels: size:S

#2503 refactor: remove old query fields
  app/schema.graphql
  app/src/pages/project/EvaluationSummary.tsx
  app/src/pages/project/SpanFilterConditionField.tsx
  app/src/pages/project/__generated__/EvaluationSummaryQuery.graphql.ts
  app/src/pages/project/__generated__/EvaluationSummaryValueFragment.graphql.ts
  app/src/pages/project/__generated__/EvaluationSummaryValueQuery.graphql.ts
  app/src/pages/project/__generated__/SpanFilterConditionFieldValidationQuery.graphql.ts
  app/src/pages/trace/TracePage.tsx
  app/src/pages/trace/__generated__/TracePageQuery.graphql.ts
  src/phoenix/server/api/schema.py
  src/phoenix/server/api/types/Dataset.py
  src/phoenix/server/api/types/DatasetInfo.py
Labels: size:XXL

#2514 chore: add deprecation message for launch_app port and host parameters
  src/phoenix/session/session.py
Labels: size:S

#2515 feat(projects): add support for the PHOENIX_PROJECT_NAME param
  src/phoenix/config.py
  src/phoenix/session/client.py
  src/phoenix/session/session.py
  src/phoenix/trace/langchain/instrumentor.py
  src/phoenix/trace/llama_index/callback.py
  src/phoenix/trace/openai/instrumentor.py
Labels: size:M

#2516 fix: support minimal llama-index installations
  src/phoenix/trace/llama_index/callback.py
Labels: size:M

#2522 feat(graphql): embed project inside graphql span as private attribute
  src/phoenix/core/traces.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/api/types/Span.py
  tests/server/api/input_types/test_SpanSort.py
Labels: size:L

#2524 refactor: purge deprecated dummy tracer
  src/phoenix/trace/langchain/__init__.py
  src/phoenix/trace/langchain/instrumentor.py
  src/phoenix/trace/langchain/tracer.py
  src/phoenix/trace/llama_index/callback.py
  src/phoenix/trace/openai/instrumentor.py
  src/phoenix/trace/tracer.py
Labels: size:L

#2523 refactor: remove span from http exporter
  src/phoenix/trace/exporter.py
Labels: size:S

#2520 feat(trace): context manager to pause tracing
  src/phoenix/trace/__init__.py
  tests/trace/test_suppress_tracing.py
Labels: size:M

#2527 fix: parse files to detect sagemaker
  src/phoenix/session/session.py
Labels: size:XS

#2531 fix: display newlines in explanations
  app/package.json
  app/src/components/table/TextCell.tsx
  app/src/pages/trace/SpanEvaluationsTable.tsx
Labels: size:S

#2537 feat: Enable dynamic project switching
  src/phoenix/trace/__init__.py
  src/phoenix/trace/projects.py
  tests/trace/test_projects.py
Labels: size:M

#2549 fix: prevent browser caching of static assets
  src/phoenix/server/app.py
Labels: size:XS

#2554 feat: add phoenix-evals support for python 3.12
  .github/workflows/python-CI.yml
  packages/phoenix-evals/pyproject.toml
  packages/phoenix-evals/src/phoenix/evals/models/vertex.py
  packages/phoenix-evals/src/phoenix/evals/models/vertexai.py
Labels: size:XS

#2555 feat: add arize-phoenix support for python 3.12
  .github/workflows/python-CI.yml
  pyproject.toml
Labels: size:S

#2552 fix(ui): scroll column selector when long
  app/src/pages/project/SpanColumnSelector.tsx
Labels: size:M

#2553 feat: experimental span storage with append-only text files
  pyproject.toml
  src/phoenix/config.py
  src/phoenix/core/project.py
  src/phoenix/core/traces.py
  src/phoenix/server/api/routers/evaluation_handler.py
  src/phoenix/server/api/routers/span_handler.py
  src/phoenix/server/api/routers/trace_handler.py
  src/phoenix/server/api/types/Span.py
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  src/phoenix/storage/__init__.py
  src/phoenix/storage/spanstore/__init__.py
  src/phoenix/storage/spanstore/text_file.py
  src/phoenix/utilities/project.py
  tests/storage/spanstore/test_text_file_impl.py
Labels: size:L

#2562 chore: run hatch tests on python 3.12
  .github/workflows/python-CI.yml
  pyproject.toml
Labels: size:S

#2573 fix: sanitize base path
  app/src/RelayEnvironment.ts
Labels: size:XS

#2575 fix: increase span attributes limit to 10000
  src/phoenix/trace/langchain/instrumentor.py
  src/phoenix/trace/llama_index/callback.py
  src/phoenix/trace/openai/instrumentor.py
Labels: size:XS

#2583 fix: support numpy arrays in span to json encoder
  src/phoenix/trace/span_json_encoder.py
  tests/trace/test_span_json_encoder.py
Labels: size:M

#2576 feat: Add project name to `client.log_evaluations`
  src/phoenix/server/api/routers/evaluation_handler.py
  src/phoenix/session/client.py
Labels: size:S

#2585 feat: project archiving and deletion
  app/schema.graphql
  src/phoenix/core/project.py
  src/phoenix/core/traces.py
  src/phoenix/server/api/schema.py
Labels: size:M

#2586 fix(projects): the home page should direct you to the projects page if there are multiple projects with data
  app/src/pages/home/homeLoader.ts
Labels: size:S

#2588 feat: Add project name to client helper functions
  src/phoenix/trace/dsl/helpers.py
Labels: size:S

#2590 fix: use environment variable for project name
  src/phoenix/session/client.py
  src/phoenix/trace/dsl/helpers.py
Labels: size:XS

#2589 docs: Improve projects-related API docstrings
  src/phoenix/session/client.py
  src/phoenix/trace/__init__.py
  src/phoenix/trace/projects.py
Labels: size:M

#2591 chore: fix style of labels and add a tooltip
  app/src/pages/project/EvaluationLabel.tsx
  app/src/pages/project/RetrievalEvaluationLabel.tsx
Labels: size:L

#2602 chore: protect default project from deletion
  src/phoenix/core/traces.py
Labels: size:S

#2597 fix: pass verbose to evaluators
  packages/phoenix-evals/src/phoenix/evals/classify.py
Labels: size:XS

#2604 chore: raise exception for unexpected node types for deleteProject and archiveProject mutations
  src/phoenix/server/api/schema.py
  src/phoenix/server/api/types/node.py
Labels: size:M

#2611 docs: Add projects tutorial
  tutorials/tracing/tracing_with_projects_tutorial.ipynb
Labels: size:L

#2626 fix(trace): numpy array truth ambiguity
  src/phoenix/core/project.py
  src/phoenix/server/api/types/Span.py
Labels: size:S

#2630 chore: update typescript and related dependencies
  app/package-lock.json
  app/package.json
Labels: size:XS

#2634 docs: Add Qdrant + Langchain tracing example
  tutorials/qdrant_langchain_instrumentation_search_and_retrieval_tutorial.ipynb
Labels: size:L

#2632 fix(trace): redefine root span
  app/src/pages/trace/TracePage.tsx
  pyproject.toml
  src/phoenix/core/project.py
  tests/core/test_project.py
Labels: size:M

#2637 chore: add prometheus metrics
  Dockerfile
  pyproject.toml
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  src/phoenix/server/prometheus.py
Labels: size:L

#2642 fix(ui): increase pagination size to 1000 for TracePage
  app/src/pages/trace/TracePage.tsx
  app/src/pages/trace/__generated__/TracePageQuery.graphql.ts
Labels: size:S

#2645 feat: add time range arguments to span query helper functions
  src/phoenix/trace/dsl/helpers.py
Labels: size:S

#2648 fix: project name for evaluation ingestion
  src/phoenix/server/api/routers/evaluation_handler.py
  src/phoenix/server/api/types/Span.py
Labels: size:M

#2652 fix(trace): query dsl for numpy arrays
  src/phoenix/trace/dsl/query.py
  tests/trace/dsl/test_query.py
Labels: size:S

#2660 feat: Add `response_format` argument to `MistralAIModel`
  packages/phoenix-evals/src/phoenix/evals/models/mistralai.py
  pyproject.toml
Labels: size:XS

#2643 docs: example using cron for online phoenix evals
  examples/cron-evals/.gitignore
  examples/cron-evals/README.md
  examples/cron-evals/build_vector_store.py
  examples/cron-evals/requirements.txt
  examples/cron-evals/run_chain.py
  examples/cron-evals/run_evals.py
Labels: size:L

#2627 docs: mistral tutorial
  tutorials/mistral/evaluate_rag--mistral.ipynb
Labels: size:XXL

#2636 feat: update bedrock.py to use messages API for claude
  packages/phoenix-evals/src/phoenix/evals/models/bedrock.py
Labels: size:S

#2665 docs: Remove pinecone notebook
  tutorials/langchain_pinecone_search_and_retrieval_tutorial.ipynb
  tutorials/qdrant_langchain_instrumentation_search_and_retrieval_tutorial.ipynb
  tutorials/tracing/langchain_google_palm_tracing_tutorial.ipynb
  tutorials/tracing/langchain_tracing_tutorial.ipynb
  tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb
Labels: size:XL

#2672 fix: Update broken imports on tracing and analysis example
  tutorials/llm_application_tracing_evaluating_and_analysis.ipynb
Labels: size:M

#2681 docs: add mistral instrumentation to notebook
  cspell.json
  tutorials/mistral/evaluate_rag--mistral.ipynb
Labels: size:XS

#2682 docs: add mistral instrumentor to mistral tutorial
  tutorials/llm_application_tracing_evaluating_and_analysis.ipynb
  tutorials/mistral/evaluate_rag--mistral.ipynb
Labels: size:M

#2686 fix: long project names do not overflow and squash project icon
  app/src/pages/projects/ProjectsPage.tsx
Labels: size:S

#2698 chore: update relay-compiler to v16
  .pre-commit-config.yaml
  app/package-lock.json
  app/package.json
  app/relay.config.js
  app/src/components/form/__generated__/DimensionPickerQuery.graphql.ts
  app/src/pages/__generated__/ModelRootQuery.graphql.ts
  app/src/pages/embedding/__generated__/EmbeddingPageModelQuery.graphql.ts
  app/src/pages/embedding/__generated__/ExportSelectionButtonExportsQuery.graphql.ts
  app/src/pages/home/__generated__/homeLoaderQuery.graphql.ts
  app/src/pages/project/__generated__/DocumentEvaluationSummaryValueFragment.graphql.ts
  app/src/pages/project/__generated__/EvaluationSummaryValueFragment.graphql.ts
  app/src/pages/project/__generated__/ProjectPageHeader_stats.graphql.ts
  app/src/pages/project/__generated__/SpansTable_spans.graphql.ts
  app/src/pages/project/__generated__/StreamToggle_data.graphql.ts
  app/src/pages/project/__generated__/TracesTable_spans.graphql.ts
  app/src/pages/projects/__generated__/ProjectsPageProjectsQuery.graphql.ts
  app/src/pages/projects/__generated__/ProjectsPageQuery.graphql.ts
Labels: size:M

#2702 chore: migrate arize-phoenix to pnpm
  .github/workflows/typescript-CI.yml
  .gitignore
  app/README.md
  app/jest.config.js
  app/package-lock.json
  app/package.json
  app/pnpm-lock.yaml
Labels: size:M

#2707 chore: update release pipeline
  .github/workflows/publish-to-pypi.yml
  .github/workflows/release.yml
Labels: size:M

#2708 feat: change docker base image to distroless
  .dockerignore
  Dockerfile
Labels: size:L

#2714 fix: ignore docs/ directory when formatting
  pyproject.toml
Labels: size:XS

#2716 fix: repair frontend build step in release pipeline
  .github/workflows/release.yml
Labels: size:XS

#2700 refactor: use suppress_tracing from openinference-instrumentation
  pyproject.toml
  src/phoenix/trace/__init__.py
  tests/trace/test_suppress_tracing.py
Labels: size:M

#2662 feat(gql): add trace node and trace evaluations
  app/schema.graphql
  app/src/pages/trace/TracePage.tsx
  app/src/pages/trace/__generated__/TracePageQuery.graphql.ts
  src/phoenix/core/project.py
  src/phoenix/server/api/types/Evaluation.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/api/types/Trace.py
Labels: size:XL

#2703 feat(ui): markdown highlighting
  app/package.json
  app/pnpm-lock.yaml
  app/src/markdown/MarkdownBlock.tsx
  app/src/markdown/MarkdownDisplayContext.tsx
  app/src/markdown/MarkdownModeRadioGroup.tsx
  app/src/markdown/index.tsx
  app/src/markdown/types.ts
  app/src/pages/trace/TracePage.tsx
Labels: size:XL

#2723 fix(UI): color rotation for markdown
  app/src/markdown/MarkdownBlock.tsx
Labels: size:S

#2725 fix(ui): broken context for markdown
  app/src/markdown/MarkdownDisplayContext.tsx
  app/src/pages/trace/TracePage.tsx
Labels: size:M

#2727 fix(ui): show formatted JSON for attributes
  app/src/pages/trace/TracePage.tsx
Labels: size:XS

#2729 chore: remove unused websockets
  src/phoenix/server/app.py
Labels: size:XS
