Repository Arize-ai/phoenix, pull requests merged in 2024-07, with the labels that each got.

#3758 test: experiment projects are omitted
  tests/server/api/test_queries.py
  tests/server/api/types/test_Project.py
Labels: size:L

#3765 refactor: rename append_dataset client method to append_to_dataset
  src/phoenix/session/client.py
Labels: size:XS

#3772 feat: rate limit on experiment evals
  src/phoenix/experiments/functions.py
Labels: size:M

#3774 chore: Nest experiment payloads under `data` key
  src/phoenix/experiments/functions.py
  src/phoenix/server/api/routers/v1/datasets.py
  src/phoenix/server/api/routers/v1/experiment_runs.py
  src/phoenix/server/api/routers/v1/experiments.py
  tests/server/api/routers/v1/test_datasets.py
  tests/server/api/routers/v1/test_experiments.py
Labels: size:S

#3773 feat(datasets): usability enhancements
  pyproject.toml
  src/phoenix/experiments/evaluators/utils.py
  src/phoenix/experiments/functions.py
  src/phoenix/experiments/types.py
  src/phoenix/session/client.py
  src/phoenix/utilities/json.py
  tests/datasets/test_experiments.py
  tests/session/test_client.py
  tutorials/experiments/llama-index/answer_and_context_relevancy.ipynb
  tutorials/experiments/llama-index/guideline_eval.ipynb
  tutorials/experiments/llama-index/pairwise_eval.ipynb
Labels: size:XXL

#3781 fix: dataset.examples list
  tutorials/experiments/summarization.ipynb
Labels: size:XS

#3782 chore: pin llama-index dependencies
  pyproject.toml
Labels: size:XS

#3783 fix: upload examples in txt2sql
  tutorials/experiments/txt2sql.ipynb
Labels: size:XS

#3785 chore: Remove ddent from notebook
  tutorials/experiments/txt2sql.ipynb
Labels: size:M

#3778 chore: Add OpenAPI specs to experiment routes
  schemas/openapi.yaml
  src/phoenix/server/api/routers/v1/experiment_evaluations.py
  src/phoenix/server/api/routers/v1/experiment_runs.py
  src/phoenix/server/api/routers/v1/experiments.py
Labels: size:XL

#3779 feat: improve async error message
  src/phoenix/experiments/functions.py
Labels: size:XS

#3788 fix: openapi yaml parsing for containers
  pyproject.toml
Labels: size:XS

#3790 feat(datasets): add `reference` as alias of `expected` for evaluator argument bindings
  src/phoenix/experiments/evaluators/utils.py
  src/phoenix/experiments/functions.py
  src/phoenix/experiments/types.py
  src/phoenix/experiments/utils.py
  src/phoenix/session/client.py
  tests/datasets/test_experiments.py
  tutorials/experiments/llama-index/answer_and_context_relevancy.ipynb
  tutorials/experiments/llama-index/guideline_eval.ipynb
  tutorials/experiments/llama-index/pairwise_eval.ipynb
Labels: size:L

#3791 chore: print experiment errors to console
  src/phoenix/experiments/functions.py
Labels: size:M

#3789 feat: Improve task argument binding and document `run_experiment`
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
  src/phoenix/datasets/evaluators/utils.py
  src/phoenix/experiments/evaluators/base.py
  src/phoenix/experiments/evaluators/utils.py
  src/phoenix/experiments/functions.py
  tests/datasets/test_experiments.py
  tutorials/experiments/datasets_and_experiments_quickstart.ipynb
  tutorials/experiments/internal/run_experiments.ipynb
  tutorials/experiments/langchain_email_extraction.ipynb
  tutorials/experiments/llama-index/answer_and_context_relevancy.ipynb
  tutorials/experiments/llama-index/guideline_eval.ipynb
  tutorials/experiments/llama-index/pairwise_eval.ipynb
  tutorials/experiments/run_experiments_with_llama_index.ipynb
  tutorials/experiments/summarization.ipynb
  tutorials/experiments/txt2sql.ipynb
Labels: size:L

#3796 chore: sync docs
  docs/datasets-and-experiments/how-to-datasets/README.md
  docs/datasets-and-experiments/how-to-datasets/creating-datasets.md
  docs/datasets-and-experiments/how-to-datasets/run-experiments.md
  docs/datasets-and-experiments/how-to-datasets/using-evaluators.md
  docs/datasets-and-experiments/quickstart-datasets.md
  docs/datasets-and-experiments/use-cases-datasets/summarization.md
  docs/datasets-and-experiments/use-cases-datasets/text2sql.md
Labels: size:M

#3797 feat: Set private experiment routes
  schemas/openapi.yaml
  src/phoenix/server/api/routers/v1/experiment_evaluations.py
  src/phoenix/server/api/routers/v1/experiment_runs.py
  src/phoenix/server/api/routers/v1/experiments.py
Labels: size:S

#3700 chore(main): release arize-phoenix 4.6.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:L

#3786 docs: big overhaul and fixes for api reference
  api_reference/Makefile
  api_reference/requirements.txt
  api_reference/source/_static/custom.css
  api_reference/source/_static/logo.png
  api_reference/source/_static/logo_dark.png
  api_reference/source/api/evals.classify.rst
  api_reference/source/api/evals.default_templates.rst
  api_reference/source/api/evals.evaluators.rst
  api_reference/source/api/evals.exceptions.rst
  api_reference/source/api/evals.executors.rst
  api_reference/source/api/evals.generate.rst
  api_reference/source/api/evals.models.anthropic.rst
  api_reference/source/api/evals.models.base.rst
  api_reference/source/api/evals.models.bedrock.rst
  api_reference/source/api/evals.models.litellm.rst
  api_reference/source/api/evals.models.mistralai.rst
  api_reference/source/api/evals.models.openai.rst
  api_reference/source/api/evals.models.rate_limiters.rst
  api_reference/source/api/evals.models.rst
  api_reference/source/api/evals.models.vertex.rst
  api_reference/source/api/evals.models.vertexai.rst
  api_reference/source/api/evals.retrievals.rst
  api_reference/source/api/evals.rst
  api_reference/source/api/evals.span_templates.rst
  api_reference/source/api/evals.templates.rst
  api_reference/source/api/evals.utils.rst
  api_reference/source/api/inferences.errors.rst
  api_reference/source/api/inferences.fixtures.rst
  api_reference/source/api/inferences.inferences.rst
  api_reference/source/api/inferences.rst
  api_reference/source/api/inferences.schema.rst
  api_reference/source/api/inferences.validation.rst
  api_reference/source/api/modules.rst
  api_reference/source/api/ref.rst
  api_reference/source/api/session.client.rst
  api_reference/source/api/session.data_extractor.rst
  api_reference/source/api/session.evaluation.rst
  api_reference/source/api/session.rst
  api_reference/source/api/session.session.rst
  api_reference/source/conf.py
  api_reference/source/evals.models.rst
  api_reference/source/evals.rst
  api_reference/source/index.md
  api_reference/source/index.rst
  api_reference/source/inferences.rst
  api_reference/source/modules.rst
  api_reference/source/session.rst
Labels: size:L

#3798 chore: update notebooks
  api_reference/source/conf.py
  docs/datasets-and-experiments/quickstart-datasets.md
  docs/datasets-and-experiments/use-cases-datasets/answer_and_context_relevancy.md
  docs/datasets-and-experiments/use-cases-datasets/guideline_eval.md
  docs/datasets-and-experiments/use-cases-datasets/langchain_email_extraction.md
  docs/datasets-and-experiments/use-cases-datasets/pairwise_eval.md
  docs/datasets-and-experiments/use-cases-datasets/run_experiments_with_llama_index.md
  docs/datasets-and-experiments/use-cases-datasets/summarization.md
  docs/datasets-and-experiments/use-cases-datasets/text2sql.md
  tutorials/experiments/langchain_email_extraction.ipynb
  tutorials/experiments/llama-index/answer_and_context_relevancy.ipynb
  tutorials/experiments/llama-index/guideline_eval.ipynb
  tutorials/experiments/llama-index/pairwise_eval.ipynb
  tutorials/experiments/run_experiments_with_llama_index.ipynb
  tutorials/experiments/summarization.ipynb
  tutorials/experiments/txt2sql.ipynb
Labels: size:XXL

#3800 chore(main): release arize-phoenix 4.6.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3806 fix(experiments): order annotations by name to make output deterministic
  app/src/pages/experiments/ExperimentsTable.tsx
  src/phoenix/server/api/types/ExperimentRun.py
Labels: size:XS

#3807 chore(main): release arize-phoenix 4.6.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3818 fix(UI): explanation overflow
  app/src/components/experiment/AnnotationLabel.tsx
Labels: size:XS

#3819 chore(main): release arize-phoenix 4.6.3
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3820 fix: allow invocations of OpenAIModel without api key
  .gitignore
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
  packages/phoenix-evals/tests/phoenix/evals/functions/test_generate.py
  packages/phoenix-evals/tests/phoenix/evals/models/test_openai.py
Labels: size:M

#3823 chore(main): release arize-phoenix-evals 0.13.2
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#3834 docs: Update model wrapper docstrings
  packages/phoenix-evals/src/phoenix/evals/models/anthropic.py
  packages/phoenix-evals/src/phoenix/evals/models/bedrock.py
  packages/phoenix-evals/src/phoenix/evals/models/mistralai.py
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
  packages/phoenix-evals/src/phoenix/evals/models/vertex.py
  packages/phoenix-evals/src/phoenix/evals/models/vertexai.py
Labels: size:L

#3832 feat(image): add image rendering on messages
  app/package.json
  app/pnpm-lock.yaml
  app/src/openInference/tracing/types.ts
  app/src/pages/trace/TraceDetails.tsx
Labels: size:M

#3805 docs: Update email extraction tutorial notebook
  tutorials/experiments/langchain_email_extraction.ipynb
Labels: size:XXL

#3836 chore: fix ci
  api_reference/source/conf.py
  api_reference/source/utils.py
Labels: size:M

#3822 chore(main): release arize-phoenix 4.7.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3839 fix: ensure experiment errors messages work on python 3.8 and 3.9
  src/phoenix/experiments/functions.py
Labels: size:XS

#3841 fix: ensure experiment errors messages work on python 3.8 and 3.9
  src/phoenix/__init__.py
Labels: size:XS

#3842 chore(main): release arize-phoenix 4.7.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3756 fix: make projects page scrollable
  app/src/pages/projects/ProjectsPage.tsx
  app/src/pages/projects/__generated__/ProjectsPageProjectsFragment.graphql.ts
  app/src/pages/projects/__generated__/ProjectsPageProjectsQuery.graphql.ts
  app/src/pages/projects/__generated__/ProjectsPageQuery.graphql.ts
Labels: size:L

#3803 refactor: flatten experiment run payload
  schemas/openapi.yaml
  src/phoenix/experiments/functions.py
  src/phoenix/experiments/types.py
  src/phoenix/server/api/routers/v1/experiment_runs.py
  tests/datasets/test_experiments.py
  tests/server/api/routers/v1/test_experiments.py
Labels: size:M

#3845 chore: change task function to be async in notebook
  tutorials/experiments/llama-index/guideline_eval.ipynb
Labels: size:XS

#3846 fix: do client.post in thread
  src/phoenix/experiments/functions.py
  src/phoenix/experiments/types.py
  tests/datasets/test_experiments.py
  tutorials/experiments/llama-index/guideline_eval.ipynb
Labels: size:M

#3843 chore(main): release arize-phoenix 4.7.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3838 docs: api ref style update, evals api documentation
  api_reference/source/_static/custom.css
  api_reference/source/_static/switcher.json
  api_reference/source/api/client.rst
  api_reference/source/api/client_package.rst
  api_reference/source/api/db.rst
  api_reference/source/api/evals.classify.rst
  api_reference/source/api/evals.default_templates.rst
  api_reference/source/api/evals.evaluators.rst
  api_reference/source/api/evals.exceptions.rst
  api_reference/source/api/evals.executors.rst
  api_reference/source/api/evals.generate.rst
  api_reference/source/api/evals.models.anthropic.rst
  api_reference/source/api/evals.models.base.rst
  api_reference/source/api/evals.models.mistralai.rst
  api_reference/source/api/evals.models.openai.rst
  api_reference/source/api/evals.models.rate_limiters.rst
  api_reference/source/api/evals.models.rst
  api_reference/source/api/evals.models.vertexai.rst
  api_reference/source/api/evals.retrievals.rst
  api_reference/source/api/evals.rst
  api_reference/source/api/evals.templates.rst
  api_reference/source/api/evals.utils.rst
  api_reference/source/api/inferences.errors.rst
  api_reference/source/api/inferences.fixtures.rst
  api_reference/source/api/inferences.inferences.rst
  api_reference/source/api/inferences.rst
  api_reference/source/api/inferences.schema.rst
  api_reference/source/api/inferences.validation.rst
  api_reference/source/api/modules.rst
  api_reference/source/api/ref.rst
  api_reference/source/api/session.client.rst
  api_reference/source/api/session.data_extractor.rst
  api_reference/source/api/session.evaluation.rst
  api_reference/source/api/session.rst
  api_reference/source/api/session.session.rst
  api_reference/source/conf.py
  api_reference/source/index.md
  api_reference/source/utils.py
  packages/phoenix-evals/src/phoenix/evals/classify.py
  packages/phoenix-evals/src/phoenix/evals/evaluators.py
  packages/phoenix-evals/src/phoenix/evals/executors.py
  packages/phoenix-evals/src/phoenix/evals/generate.py
  packages/phoenix-evals/src/phoenix/evals/retrievals.py
  packages/phoenix-evals/src/phoenix/evals/utils.py
Labels: size:L

#3853 feat: REST endpoint to delete dataset
  app/src/pages/datasets/DatasetActionMenu.tsx
  app/src/pages/experiments/ExperimentSelectionToolbar.tsx
  schemas/openapi.yaml
  src/phoenix/db/helpers.py
  src/phoenix/server/api/dataloaders/project_by_name.py
  src/phoenix/server/api/mutations/dataset_mutations.py
  src/phoenix/server/api/mutations/experiment_mutations.py
  src/phoenix/server/api/routers/v1/__init__.py
  src/phoenix/server/api/routers/v1/datasets.py
  src/phoenix/server/api/utils.py
  tests/server/api/routers/v1/test_datasets.py
  tests/server/api/routers/v1/test_experiments.py
Labels: size:L

#3858 docs: eval api ref update
  api_reference/source/_static/custom.css
  api_reference/source/api/evals.classify.rst
  api_reference/source/api/evals.default_templates.rst
  api_reference/source/api/evals.evaluators.rst
  api_reference/source/api/evals.generate.rst
  api_reference/source/api/evals.models.anthropic.rst
  api_reference/source/api/evals.models.bedrock.rst
  api_reference/source/api/evals.models.litellm.rst
  api_reference/source/api/evals.models.mistralai.rst
  api_reference/source/api/evals.models.openai.rst
  api_reference/source/api/evals.models.rst
  api_reference/source/api/evals.models.vertex.rst
  api_reference/source/api/evals.models.vertexai.rst
  api_reference/source/api/evals.retrievals.rst
  api_reference/source/api/evals.span_templates.rst
  api_reference/source/api/evals.templates.rst
  api_reference/source/api/evals.utils.rst
  api_reference/source/conf.py
  api_reference/source/utils.py
  packages/phoenix-evals/src/phoenix/evals/default_templates.py
  packages/phoenix-evals/src/phoenix/evals/span_templates.py
Labels: size:L

#3861 ci: fix styles
  api_reference/source/conf.py
  api_reference/source/utils.py
Labels: size:S

#3862 chore: ignore api_reference styles
  pyproject.toml
Labels: size:XS

#3860 docs: updated index for api reference
  api_reference/requirements.txt
  api_reference/source/_static/custom.css
  api_reference/source/conf.py
  api_reference/source/index.md
  api_reference/source/utils.py
Labels: size:L

#3867 fix: span json decoder for event lists
  src/phoenix/trace/span_json_decoder.py
  src/phoenix/trace/trace_dataset.py
Labels: size:XS

#3859 chore(main): release arize-phoenix 4.8.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3874 chore: docs to main
  docs/SUMMARY.md
  docs/api/client.md
  docs/api/evaluation-models.md
  docs/datasets-and-experiments/concepts-datasets.md
  docs/datasets-and-experiments/how-to-datasets/README.md
  docs/datasets-and-experiments/how-to-datasets/exporting-datasets.md
  docs/datasets-and-experiments/how-to-experiments/README.md
  docs/datasets-and-experiments/how-to-experiments/run-experiments.md
  docs/datasets-and-experiments/how-to-experiments/using-evaluators.md
  docs/datasets-and-experiments/overview-datasets.md
  docs/datasets-and-experiments/quickstart-datasets.md
  docs/datasets-and-experiments/use-cases-datasets/README.md
  docs/datasets-and-experiments/use-cases-datasets/email-extraction.md
  docs/datasets-and-experiments/use-cases-datasets/summarization.md
  docs/datasets-and-experiments/use-cases-datasets/text2sql.md
  docs/evaluation/how-to-evals/running-pre-tested-evals/summarization-eval.md
  docs/notebooks.md
  docs/tracing/how-to-tracing/extract-data-from-spans.md
  docs/tracing/how-to-tracing/manual-instrumentation/javascript.md
Labels: size:L

#3870 feat: retry eval insertions
  src/phoenix/db/bulk_inserter.py
Labels: size:M

#3872 docs: api reference overhaul modules
  api_reference/source/_static/custom.css
  api_reference/source/_static/github-large-banner-phoenix.jpg
  api_reference/source/_static/switcher.json
  api_reference/source/api/client.rst
  api_reference/source/api/client_package.rst
  api_reference/source/api/db.bulk_inserter.rst
  api_reference/source/api/db.engines.rst
  api_reference/source/api/db.helpers.rst
  api_reference/source/api/db.insertion.dataset.rst
  api_reference/source/api/db.insertion.evaluation.rst
  api_reference/source/api/db.insertion.helpers.rst
  api_reference/source/api/db.insertion.rst
  api_reference/source/api/db.insertion.span.rst
  api_reference/source/api/db.migrate.rst
  api_reference/source/api/db.migrations.env.rst
  api_reference/source/api/db.migrations.rst
  api_reference/source/api/db.migrations.types.rst
  api_reference/source/api/db.models.rst
  api_reference/source/api/db.rst
  api_reference/source/api/evals.classify.rst
  api_reference/source/api/evals.evaluators.rst
  api_reference/source/api/evals.generate.rst
  api_reference/source/api/evals.models.anthropic.rst
  api_reference/source/api/evals.models.bedrock.rst
  api_reference/source/api/evals.models.litellm.rst
  api_reference/source/api/evals.models.mistralai.rst
  api_reference/source/api/evals.models.openai.rst
  api_reference/source/api/evals.models.vertex.rst
  api_reference/source/api/evals.models.vertexai.rst
  api_reference/source/api/evals.retrievals.rst
  api_reference/source/api/evals.rst
  api_reference/source/api/evals.templates.rst
  api_reference/source/api/evals.utils.rst
  api_reference/source/api/experiments.evaluators.base.rst
  api_reference/source/api/experiments.evaluators.code_evaluators.rst
  api_reference/source/api/experiments.evaluators.llm_evaluators.rst
  api_reference/source/api/experiments.evaluators.rst
  api_reference/source/api/experiments.evaluators.utils.rst
  api_reference/source/api/experiments.functions.rst
  api_reference/source/api/experiments.rst
  api_reference/source/api/experiments.tracing.rst
  api_reference/source/api/experiments.types.rst
  api_reference/source/api/experiments.utils.rst
  api_reference/source/api/inferences.errors.rst
  api_reference/source/api/inferences.inferences.rst
  api_reference/source/api/inferences.rst
  api_reference/source/api/inferences.schema.rst
  api_reference/source/api/inferences_schema.rst
  api_reference/source/api/session.rst
  api_reference/source/conf.py
  api_reference/source/index.md
  src/phoenix/inferences/inferences.py
  src/phoenix/session/client.py
  src/phoenix/trace/trace_dataset.py
Labels: size:L

#3877 revert: "feat: retry eval insertions"
  src/phoenix/db/bulk_inserter.py
Labels: size:M

#3875 fix: remove phoenix.daasets imports
  app/src/pages/dataset/RunExperimentButton.tsx
Labels: size:XS

#3879 fix(graphql): clear project when `end_time` is `UNSET`
  src/phoenix/server/api/mutations/project_mutations.py
Labels: size:XS

#3876 chore(main): release arize-phoenix 4.9.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3869 feat: Add REST routes for span and trace annotations
  schemas/openapi.yaml
  src/phoenix/server/api/routers/v1/__init__.py
  src/phoenix/server/api/routers/v1/spans.py
  src/phoenix/server/api/routers/v1/traces.py
Labels: size:L

#3881 feat: Add function call evaluator template to span_templates.py & tutorial notebook
  packages/phoenix-evals/src/phoenix/evals/__init__.py
  packages/phoenix-evals/src/phoenix/evals/default_templates.py
  packages/phoenix-evals/src/phoenix/evals/span_templates.py
  tutorials/evals/evaluate_tool_calling.ipynb
Labels: size:XXL

#3889 refactor: simplify `insert_on_conflict`
  src/phoenix/db/insertion/evaluation.py
  src/phoenix/db/insertion/helpers.py
  src/phoenix/db/insertion/span.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/routers/v1/experiment_evaluations.py
  src/phoenix/server/api/routers/v1/experiments.py
  src/phoenix/server/api/routers/v1/spans.py
  src/phoenix/server/api/routers/v1/traces.py
  tests/db/insertion/test_helpers.py
Labels: size:L

#3835 chore(main): release arize-phoenix-evals 0.14.0
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#3895 feat(annotations): ability to copy span and trace IDs
  app/src/pages/trace/SpanCodeDropdown.tsx
  app/src/pages/trace/TraceDetails.tsx
  app/src/pages/trace/__generated__/TraceDetailsQuery.graphql.ts
Labels: size:M

#3891 feat: Add GQL mutations for Span + Trace Annotations
  app/schema.graphql
  app/src/pages/example/__generated__/ExampleExperimentRunsTableFragment.graphql.ts
  app/src/pages/experiment/__generated__/ExperimentCompareTableQuery.graphql.ts
  src/phoenix/server/api/input_types/CreateSpanAnnotationsInput.py
  src/phoenix/server/api/input_types/CreateTraceAnnotationsInput.py
  src/phoenix/server/api/input_types/DeleteAnnotationsInput.py
  src/phoenix/server/api/input_types/PatchAnnotationsInput.py
  src/phoenix/server/api/mutations/__init__.py
  src/phoenix/server/api/mutations/span_annotations_mutations.py
  src/phoenix/server/api/mutations/trace_annotations_mutations.py
  src/phoenix/server/api/routers/v1/spans.py
  src/phoenix/server/api/routers/v1/traces.py
  src/phoenix/server/api/types/AnnotatorKind.py
  src/phoenix/server/api/types/ExperimentRunAnnotation.py
  src/phoenix/server/api/types/SpanAnnotation.py
  src/phoenix/server/api/types/TraceAnnotation.py
  tests/server/api/types/test_SpanAnnotation.py
  tests/server/api/types/test_TraceAnnotation.py
Labels: size:XL

#3888 chore(main): release arize-phoenix 4.10.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3884 fix: Run Bedrock calls in executor for async
  packages/phoenix-evals/src/phoenix/evals/models/bedrock.py
  packages/phoenix-evals/tests/phoenix/evals/models/test_bedrock.py
Labels: size:M

#3906 chore(main): release arize-phoenix-evals 0.14.1
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#3898 feat(UI): user preferences context with markdown preferences
  app/package.json
  app/pnpm-lock.yaml
  app/src/App.tsx
  app/src/components/markdown/MarkdownDisplayContext.tsx
  app/src/components/markdown/MarkdownModeRadioGroup.tsx
  app/src/contexts/PreferencesContext.tsx
  app/src/pages/trace/TraceDetails.tsx
  app/src/store/preferencesStore.tsx
Labels: size:L

#3909 fix: debug flag should be `store_true`
  src/phoenix/server/main.py
Labels: size:XS

#3911 chore(main): release arize-phoenix 4.10.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3915 feat(annotations): gql resolver for annotations on a span
  app/schema.graphql
  cspell.json
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/span_annotations.py
  src/phoenix/server/api/types/Annotation.py
  src/phoenix/server/api/types/Evaluation.py
  src/phoenix/server/api/types/Span.py
  src/phoenix/server/api/types/SpanAnnotation.py
  src/phoenix/server/app.py
Labels: size:L

#3910 docs: Update LiteLLM and OpenAI docstrings
  packages/phoenix-evals/src/phoenix/evals/models/litellm.py
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
Labels: size:M

#3921 fix: initialize tracer provider for internal server instrumentation
  src/phoenix/server/app.py
Labels: size:XS

#3919 feat: Add Guardrail span kind type
  app/schema.graphql
  app/src/components/trace/SpanKindIcon.tsx
  app/src/components/trace/SpanKindLabel.tsx
  app/src/pages/project/__generated__/SpansTable_spans.graphql.ts
  app/src/pages/project/__generated__/TracesTable_spans.graphql.ts
  app/src/pages/trace/__generated__/TraceDetailsQuery.graphql.ts
  src/phoenix/server/api/types/Span.py
  src/phoenix/trace/schemas.py
Labels: size:M

#3924 fix: security fix for braces
  app/package.json
  app/pnpm-lock.yaml
Labels: size:M

#3926 fix: flattening sequence attribute when value is `ndarray` (which is not `Sequence`)
  pyproject.toml
  src/phoenix/trace/attributes.py
  src/phoenix/trace/span_json_decoder.py
  tests/server/api/conftest.py
  tests/server/api/routers/v1/test_spans.py
Labels: size:M

#3916 chore(main): release arize-phoenix 4.11.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3928 chore: correct migration guide
  MIGRATION.md
Labels: size:S

#3929 feat: add timeout arguments to client methods
  src/phoenix/session/client.py
  src/phoenix/session/data_extractor.py
  src/phoenix/session/session.py
Labels: size:M

#3930 chore(main): release arize-phoenix 4.12.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3931 feat(annotations): graphql resolver for all annotation names on a project
  app/schema.graphql
  src/phoenix/server/api/types/Project.py
Labels: size:M

#3934 docs: add getpass and missing install to datasets and experiments quickstart notebook
  tutorials/experiments/datasets_and_experiments_quickstart.ipynb
Labels: size:S

#3901 build: migrate web build to Vite
  DEVELOPMENT.md
  app/.gitignore
  app/esbuild.config.mjs
  app/esbuild.relay.mjs
  app/package.json
  app/pnpm-lock.yaml
  app/relay.config.js
  app/src/components/model/__generated__/ModelEmbeddingsTable_embeddingDimensions.graphql.ts
  app/src/components/model/__generated__/ModelSchemaTable_dimensions.graphql.ts
  app/src/index.tsx
  app/src/pages/dataset/__generated__/DatasetHistoryTable_versions.graphql.ts
  app/src/pages/datasets/__generated__/DatasetsTable_datasets.graphql.ts
  app/src/pages/example/__generated__/ExampleExperimentRunsTableFragment.graphql.ts
  app/src/pages/examples/__generated__/ExamplesTableFragment.graphql.ts
  app/src/pages/experiments/__generated__/ExperimentsTableFragment.graphql.ts
  app/src/pages/project/__generated__/DatasetSelectorPopoverContent_datasets.graphql.ts
  app/src/pages/project/__generated__/DocumentEvaluationSummaryValueFragment.graphql.ts
  app/src/pages/project/__generated__/EvaluationSummaryValueFragment.graphql.ts
  app/src/pages/project/__generated__/ProjectPageHeader_stats.graphql.ts
  app/src/pages/project/__generated__/SpansTable_spans.graphql.ts
  app/src/pages/project/__generated__/StreamToggle_data.graphql.ts
  app/src/pages/project/__generated__/TracesTable_spans.graphql.ts
  app/src/pages/projects/__generated__/ProjectsPageProjectsFragment.graphql.ts
  app/src/pages/trace/__generated__/DatasetPicker__datasets.graphql.ts
  app/vite.config.mts
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  src/phoenix/server/templates/index.html
Labels: size:L

#3940 chore: api ref updates and docstring fixes
  api_reference/README.md
  api_reference/source/_static/custom.css
  api_reference/source/_static/logo_dark.png
  api_reference/source/_static/switcher.json
  api_reference/source/_templates/custom_sidebar.html
  api_reference/source/api/client.rst
  api_reference/source/api/evals.span_templates.rst
  api_reference/source/api/inferences_schema.rst
  api_reference/source/api/session.rst
  api_reference/source/conf.py
  packages/phoenix-evals/src/phoenix/evals/generate.py
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
  src/phoenix/experiments/functions.py
Labels: size:L

#3942 fix(experiments): ensure experiments table appears even when an experiment has no runs
  app/schema.graphql
  app/src/pages/experiments/ErrorRateCell.tsx
  app/src/pages/experiments/__generated__/ExperimentsTableFragment.graphql.ts
  src/phoenix/server/api/dataloaders/average_experiment_run_latency.py
  src/phoenix/server/api/dataloaders/experiment_error_rates.py
  src/phoenix/server/api/dataloaders/experiment_run_counts.py
  src/phoenix/server/api/types/Experiment.py
  tests/server/api/types/test_Experiment.py
Labels: size:L

#3947 fix: re-enable server side caching
  src/phoenix/server/app.py
Labels: size:XS

#3948 chore(main): release arize-phoenix 4.13.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3950 docs: make txt2sql notebook compatible with lower versions of python
  tutorials/experiments/txt2sql.ipynb
Labels: size:S

#3951 chore: fix notebook typo for experiment task
  tutorials/experiments/langchain_email_extraction.ipynb
Labels: size:XS

#3952 chore: fix Starlette lifespan for tests
  pyproject.toml
  src/phoenix/db/bulk_inserter.py
  tests/conftest.py
  tests/db/insertion/test_helpers.py
  tests/server/api/conftest.py
  tests/server/api/routers/v1/test_spans.py
Labels: size:L

#3954 chore: increase wait time to reduce test flakiness
  tests/server/api/routers/v1/test_spans.py
Labels: size:XS

#3955 chore: allow kwargs for get_dataset_version first argument
  src/phoenix/session/client.py
Labels: size:XS

#3958 chore: deprecate and remove dataset_description parameter in append_to_dataset client method
  src/phoenix/session/client.py
Labels: size:XS

#3953 refactor: annotator graphql types
  app/schema.graphql
  src/phoenix/server/api/input_types/CreateSpanAnnotationInput.py
  src/phoenix/server/api/input_types/CreateTraceAnnotationInput.py
  src/phoenix/server/api/input_types/PatchAnnotationInput.py
  src/phoenix/server/api/mutations/span_annotations_mutations.py
  src/phoenix/server/api/mutations/trace_annotations_mutations.py
  tests/server/api/types/test_SpanAnnotation.py
  tests/server/api/types/test_TraceAnnotation.py
Labels: size:M

#3939 feat: Extend evals DSL to accept 'annotations' symbol
  src/phoenix/trace/dsl/filter.py
  tests/trace/dsl/test_filter.py
Labels: size:M

#3969 docs: Fix docstring
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
Labels: size:XS

#3967 chore: specify indent_size in .editorconfig
  .editorconfig
Labels: size:XS

#3971 chore: sync docs with main
  docs/.gitbook/assets/Benchmark Performance.png
  docs/.gitbook/assets/Choose LLM.png
  docs/.gitbook/assets/CleanShot 2024-07-01 at 17.18.38@2x.png
  docs/.gitbook/assets/Create Template.png
  docs/.gitbook/assets/Golden Dataset.png
  docs/.gitbook/assets/image (1) (1) (1) (1).png
  docs/.gitbook/assets/image (1) (1) (1).png
  docs/.gitbook/assets/image (1) (1).png
  docs/.gitbook/assets/image (1).png
  docs/.gitbook/assets/image (2) (1) (1).png
  docs/.gitbook/assets/image (2) (1).png
  docs/.gitbook/assets/image (2).png
  docs/.gitbook/assets/image.png
  docs/SUMMARY.md
  docs/datasets-and-experiments/quickstart-datasets.md
  docs/evaluation/concepts-evals/building-your-own-evals.md
  docs/evaluation/evaluation-models.md
  docs/evaluation/how-to-evals/running-pre-tested-evals/tool-calling-eval.md
  docs/evaluation/how-to-evals/running-pre-tested-evals/user-frustration.md
  docs/hosted-phoenix.md
  docs/inferences/how-to-inferences-1/README.md
  docs/inferences/how-to-inferences/use-example-inferences.md
  docs/quickstart/llm-traces.md
  docs/reference/open-inference.md
  docs/retrieval/concepts-retrieval/troubleshooting-llm-retrieval-with-vector-stores.md
  docs/setup/README.md
  docs/tracing/how-to-tracing/README.md
  docs/tracing/how-to-tracing/customize-spans/README.md
  docs/tracing/how-to-tracing/customize-spans/instrumenting-prompt-templates-and-prompt-variables.md
  docs/tracing/how-to-tracing/importing-existing-traces.md
  docs/tracing/how-to-tracing/instrumentation/auto-instrument-python/README.md
  docs/tracing/how-to-tracing/instrumentation/auto-instrument-python/vertexai.md
  docs/tracing/how-to-tracing/manual-instrumentation/README.md
  docs/tracing/how-to-tracing/manual-instrumentation/custom-spans/README.md
  docs/tracing/how-to-tracing/manual-instrumentation/custom-spans/instrumenting-span-types.md
  docs/tracing/how-to-tracing/tracing-core-concepts.md
Labels: size:XL

#3914 feat(annotations): annotations UI
  app/src/components/dataset/CreateDatasetForm.tsx
  app/src/contexts/FeatureFlagsContext.tsx
  app/src/pages/trace/AnnotationActionMenu.tsx
  app/src/pages/trace/EditSpanAnnotationsButton.tsx
  app/src/pages/trace/EditSpanAnnotationsDialog.tsx
  app/src/pages/trace/NewSpanAnnotationForm.tsx
  app/src/pages/trace/SpanAnnotationActionMenu.tsx
  app/src/pages/trace/SpanAnnotationForm.tsx
  app/src/pages/trace/TraceDetails.tsx
  app/src/pages/trace/__generated__/EditSpanAnnotationsDialogNewAnnotationQuery.graphql.ts
  app/src/pages/trace/__generated__/EditSpanAnnotationsDialogQuery.graphql.ts
  app/src/pages/trace/__generated__/NewSpanAnnotationFormMutation.graphql.ts
  app/src/pages/trace/__generated__/SpanAnnotationActionMenuDeleteMutation.graphql.ts
  app/src/store/preferencesStore.tsx
Labels: size:XXL

#3973 fix: get_dataset_versions client method does not break on mixed timestamp formats
  src/phoenix/session/client.py
  tests/session/test_client.py
Labels: size:M

#3968 chore(main): release arize-phoenix 4.14.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3975 fix: remove clean step from release pipeline and remove rimraf dev dep
  .github/workflows/release.yml
  app/package.json
  app/pnpm-lock.yaml
Labels: size:XS

#3976 chore(main): release arize-phoenix 4.14.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3977 docs: add reverse proxy example
  examples/proxy/.gitignore
  examples/proxy/README.md
  examples/proxy/routes.toml
  examples/proxy/traefik.toml
Labels: size:M

#3885 refactor: migrate to fastapi
  pyproject.toml
  schemas/openapi.json
  schemas/openapi.yaml
  src/phoenix/server/api/context.py
  src/phoenix/server/api/openapi/main.py
  src/phoenix/server/api/openapi/schema.py
  src/phoenix/server/api/routers/v1/__init__.py
  src/phoenix/server/api/routers/v1/dataset_examples.py
  src/phoenix/server/api/routers/v1/datasets.py
  src/phoenix/server/api/routers/v1/evaluations.py
  src/phoenix/server/api/routers/v1/experiment_evaluations.py
  src/phoenix/server/api/routers/v1/experiment_runs.py
  src/phoenix/server/api/routers/v1/experiments.py
  src/phoenix/server/api/routers/v1/pydantic_compat.py
  src/phoenix/server/api/routers/v1/spans.py
  src/phoenix/server/api/routers/v1/traces.py
  src/phoenix/server/api/routers/v1/utils.py
  src/phoenix/server/app.py
  src/phoenix/server/openapi/docs.py
  src/phoenix/server/thread_server.py
  src/phoenix/session/client.py
  tests/conftest.py
  tests/server/api/openapi/test_schema.py
  tests/server/api/routers/v1/test_datasets.py
  tests/server/api/routers/v1/test_pydantic_compat.py
  tests/server/api/routers/v1/test_spans.py
  tests/server/api/routers/v1/test_traces.py
  tests/server/api/types/conftest.py
Labels: size:XXL, feature branch

#3982 fix: remove invalid command from dev:ui script
  app/package.json
  app/vite.config.mts
Labels: size:XS

#3979 refactor: remove dataset_examples submodule
  schemas/openapi.json
  src/phoenix/server/api/routers/v1/dataset_examples.py
  src/phoenix/server/api/routers/v1/datasets.py
  tests/server/api/routers/v1/test_dataset_examples.py
  tests/server/api/routers/v1/test_datasets.py
Labels: size:XL

#3983 fix: replace is_() with == in dataset name filter
  src/phoenix/server/api/routers/v1/datasets.py
Labels: size:XS

#3991 chore: update phoenix version in kubernetes manifests
  kustomize/base/phoenix.yaml
Labels: size:XS

#3987 refactor: use production db setup for all tests
  tests/conftest.py
  tests/core/test_model.py
  tests/core/test_model_schema.py
  tests/datasets/conftest.py
  tests/datasets/test_experiments.py
  tests/db/insertion/test_helpers.py
  tests/db/test_engines.py
  tests/db/test_models.py
  tests/inferences/test_inferences.py
  tests/inferences/test_schema.py
  tests/inferences/test_validation.py
  tests/metrics/test_retrieval_metrics.py
  tests/metrics/test_scalar_drift.py
  tests/server/api/conftest.py
  tests/server/api/input_types/test_DimensionFilter.py
  tests/server/api/input_types/test_TimeRange.py
  tests/server/api/mutations/test_dataset_mutations.py
  tests/server/api/mutations/test_experiment_mutations.py
  tests/server/api/routers/v1/test_datasets.py
  tests/server/api/routers/v1/test_experiments.py
  tests/server/api/routers/v1/test_spans.py
  tests/server/api/routers/v1/test_traces.py
  tests/server/api/test_interceptor.py
  tests/server/api/test_queries.py
  tests/server/api/types/conftest.py
  tests/server/api/types/test_Dataset.py
  tests/server/api/types/test_DatasetExample.py
  tests/server/api/types/test_Experiment.py
  tests/server/api/types/test_ExperimentRun.py
  tests/server/api/types/test_Project.py
  tests/server/api/types/test_Span.py
  tests/server/api/types/test_SpanAnnotation.py
  tests/server/api/types/test_TraceAnnotation.py
  tests/server/api/types/test_node.py
  tests/server/api/types/test_pagination.py
  tests/server/test_telemetry.py
  tests/session/test_client.py
  tests/trace/dsl/conftest.py
  tests/trace/dsl/test_filter.py
  tests/trace/dsl/test_helpers.py
  tests/trace/dsl/test_query.py
  tests/trace/test_attributes.py
  tests/trace/test_exporter.py
  tests/trace/test_otel.py
  tests/trace/test_projects.py
  tests/trace/test_schemas.py
  tests/trace/test_span_evaluations.py
  tests/trace/test_span_json_decoder.py
  tests/trace/test_trace_dataset.py
  tests/utilities/test_error_handling.py
  tests/utilities/test_re.py
Labels: size:XXL

#3981 fix: add mutex for sqlite
  src/phoenix/db/engines.py
  src/phoenix/server/app.py
Labels: size:S

#3989 feat: Version mismatch checks
  src/phoenix/experiments/functions.py
  src/phoenix/server/app.py
  src/phoenix/session/client.py
  src/phoenix/utilities/client.py
Labels: size:L

#4010 refactor: rename reverse proxy folder
  examples/reverse-proxy/.gitignore
  examples/reverse-proxy/README.md
  examples/reverse-proxy/routes.toml
  examples/reverse-proxy/traefik.toml
Labels: size:XS

#3943 fix: move all fixtures from jsonl to parquet
  src/phoenix/server/grpc_server.py
  src/phoenix/server/main.py
  src/phoenix/trace/fixtures.py
  src/phoenix/trace/utils.py
  src/phoenix/utilities/project.py
Labels: size:M

#4015 feat: Add containedInDataset boolean field to gql Spans
  app/schema.graphql
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/span_dataset_examples.py
  src/phoenix/server/api/types/Span.py
  src/phoenix/server/app.py
  tests/server/api/types/test_Span.py
Labels: size:L

#4024 feat(annotations): add annot ation macro and filter condition snippet to project page
  app/src/pages/project/SpanFilterConditionField.tsx
Labels: size:M

#4032 docs: notebook contribution commands
  DEVELOPMENT.md
Labels: size:XS

#4033 docs: clarify evaluators quickstart
  docs/quickstart/evals.md
Labels: size:S

#4014 feat(trace): UI lazy loading of spans
  app/jest.config.js
  app/src/components/trace/TraceTree.tsx
  app/src/components/trace/__tests__/utils.test.ts
  app/src/components/trace/index.tsx
  app/src/components/trace/types.ts
  app/src/openInference/tracing/types.ts
  app/src/pages/example/ExampleDetailsDialog.tsx
  app/src/pages/example/__generated__/ExampleDetailsDialogQuery.graphql.ts
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
  app/src/pages/trace/SpanDetails.tsx
  app/src/pages/trace/TraceDetails.tsx
  app/src/pages/trace/__generated__/SpanDetailsQuery.graphql.ts
  app/src/pages/trace/__generated__/TraceDetailsQuery.graphql.ts
  app/tsconfig.json
Labels: size:XXL

#3978 chore(main): release arize-phoenix 4.15.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4035 feat: add trace stream toggle into preferences context
  app/src/components/markdown/MarkdownDisplayContext.tsx
  app/src/contexts/StreamStateContext.tsx
  app/src/pages/project/StreamToggle.tsx
  app/src/store/preferencesStore.tsx
Labels: size:M

#4069 feat(annotations): add feedback tab to span details
  app/src/pages/trace/SpanDetails.tsx
  app/src/pages/trace/SpanFeedback.tsx
  app/src/pages/trace/__generated__/SpanDetailsQuery.graphql.ts
  app/src/pages/trace/__generated__/SpanFeedback_annotations.graphql.ts
  app/src/typeUtils.ts
Labels: size:L

#4080 fix: add raise keyword before exceptions in experiments.types
  src/phoenix/experiments/types.py
Labels: size:XS

#4071 feat(trace): add a span aside with timing info and feedback
  app/src/components/trace/SpanItem.tsx
  app/src/components/trace/TokenCount.tsx
  app/src/components/trace/TraceTree.tsx
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
  app/src/pages/trace/SpanAside.tsx
  app/src/pages/trace/SpanDetails.tsx
  app/src/pages/trace/TraceDetails.tsx
  app/src/pages/trace/__generated__/SpanAsideSpanQuery.graphql.ts
  app/src/pages/trace/__generated__/SpanAside_span.graphql.ts
  app/src/pages/trace/__generated__/SpanDetailsQuery.graphql.ts
  app/src/store/preferencesStore.tsx
Labels: size:XL

#4079 feat: Add sort order argument to Span- and Trace- Annotation fields
  app/schema.graphql
  src/phoenix/server/api/input_types/SpanAnnotationSort.py
  src/phoenix/server/api/input_types/TraceAnnotationSort.py
  src/phoenix/server/api/types/Span.py
  src/phoenix/server/api/types/Trace.py
Labels: size:L

#4081 feat(annotations): default collapse annotation explanations
  app/src/pages/trace/SpanAnnotationForm.tsx
Labels: size:M

#4026 feat: allow retries for insertions
  pyproject.toml
  src/phoenix/db/bulk_inserter.py
  src/phoenix/db/helpers.py
  src/phoenix/db/insertion/constants.py
  src/phoenix/db/insertion/document_annotation.py
  src/phoenix/db/insertion/helpers.py
  src/phoenix/db/insertion/span_annotation.py
  src/phoenix/db/insertion/trace_annotation.py
  src/phoenix/db/insertion/types.py
  src/phoenix/server/api/routers/v1/evaluations.py
  src/phoenix/server/api/routers/v1/spans.py
  src/phoenix/server/api/routers/v1/traces.py
  src/phoenix/server/app.py
  tests/conftest.py
  tests/server/api/routers/v1/test_annotations.py
  tests/server/api/routers/v1/test_spans.py
  tests/server/api/routers/v1/test_traces.py
Labels: size:XXL

#4066 fix: use outerjoin for evals filter
  src/phoenix/trace/dsl/filter.py
  tests/conftest.py
  tests/trace/dsl/conftest.py
  tests/trace/dsl/test_query.py
Labels: size:L

#4082 feat(annotations): make color for evaluation summaries consistent wit…
  app/src/pages/project/EvaluationSummary.tsx
Labels: size:XS

#4036 chore(main): release arize-phoenix 4.16.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4084 fix: process annotation insertions after spans
  src/phoenix/db/bulk_inserter.py
  src/phoenix/db/insertion/constants.py
Labels: size:S

#4085 chore(main): release arize-phoenix 4.16.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4093 fix: color for span aside
  app/src/pages/trace/SpanAside.tsx
Labels: size:XS
