Repository Arize-ai/phoenix, pull requests merged in 2024-08, with the labels that each got.

#4095 chore: add filled icons for spans
  app/src/components/trace/SpanKindIcon.tsx
Labels: size:L

#4101 feat(annotations): update RetrievalEvaluationLabel styles to match AnnotationLabel
  app/src/components/ColorSwatch.tsx
  app/src/components/annotation/AnnotationColorSwatch.tsx
  app/src/components/annotation/AnnotationLabel.tsx
  app/src/pages/project/RetrievalEvaluationLabel.tsx
Labels: size:M

#4087 feat: Expose configuration for initial rate limit
  packages/phoenix-evals/src/phoenix/evals/models/anthropic.py
  packages/phoenix-evals/src/phoenix/evals/models/bedrock.py
  packages/phoenix-evals/src/phoenix/evals/models/mistralai.py
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
  packages/phoenix-evals/src/phoenix/evals/models/rate_limiters.py
  packages/phoenix-evals/src/phoenix/evals/models/vertex.py
  packages/phoenix-evals/src/phoenix/evals/models/vertexai.py
Labels: size:M

#4107 chore: add `.view()` to `px.launch_app()` in notebooks
  tutorials/credit_card_fraud_tutorial.ipynb
  tutorials/evals/evals_quickstart.ipynb
  tutorials/evals/evals_sql_correctness_eval_with_custom_agent.ipynb
  tutorials/evals/evaluate_human_vs_ai_classifications.ipynb
  tutorials/evals/evaluate_rag.ipynb
  tutorials/evals/evaluate_reference_link_correctness_classifications.ipynb
  tutorials/evals/evaluate_tool_calling.ipynb
  tutorials/evals/evaluate_user_frustration_classifications.ipynb
  tutorials/example_datasets.ipynb
  tutorials/experiments/datasets_and_experiments_quickstart.ipynb
  tutorials/experiments/langchain_email_extraction.ipynb
  tutorials/experiments/llama-index/answer_and_context_relevancy.ipynb
  tutorials/experiments/llama-index/guideline_eval.ipynb
  tutorials/experiments/llama-index/pairwise_eval.ipynb
  tutorials/experiments/run_experiments_with_llama_index.ipynb
  tutorials/experiments/summarization.ipynb
  tutorials/experiments/txt2sql.ipynb
  tutorials/find_cluster_export_and_explore_with_gpt.ipynb
  tutorials/image_classification_tutorial.ipynb
  tutorials/integrations/arize_anyscale_traces_and_embeddings.ipynb
  tutorials/integrations/bedrock_tracing_tutorial.ipynb
  tutorials/internal/langchain_retrieval_qa_with_sources_chain_tracing_tutorial.ipynb
  tutorials/internal/openai_request_types.ipynb
  tutorials/internal/span_query_language.ipynb
  tutorials/internal/trace_eval_ingestion_testing.ipynb
  tutorials/llama_index_search_and_retrieval_tutorial.ipynb
  tutorials/llm_application_tracing_evaluating_and_analysis.ipynb
  tutorials/llm_generative_gpt_4.ipynb
  tutorials/llm_ops_overview.ipynb
  tutorials/llm_summarization_tutorial.ipynb
  tutorials/log_traces_to_phoenix.ipynb
  tutorials/milvus_llamaindex_search_and_retrieval_tutorial.ipynb
  tutorials/mistral/evaluate_rag--mistral.ipynb
  tutorials/qdrant_langchain_instrumentation_search_and_retrieval_tutorial.ipynb
  tutorials/ragas_retrieval_evals_tutorial.ipynb
  tutorials/sentiment_classification_tutorial.ipynb
  tutorials/tracing/autogen_tutorial.ipynb
  tutorials/tracing/bedrock_claude_tracing_tutorial.ipynb
  tutorials/tracing/langchain_agent_tracing_tutorial.ipynb
  tutorials/tracing/langchain_google_palm_tracing_tutorial.ipynb
  tutorials/tracing/langchain_tracing_tutorial.ipynb
  tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb
  tutorials/tracing/llama_index_openai_agent_tracing_tutorial.ipynb
  tutorials/tracing/llama_index_sql_retriever_tutorial.ipynb
  tutorials/tracing/llama_index_tracing_tutorial.ipynb
  tutorials/tracing/manual_instrumentation_tutorial.ipynb
  tutorials/tracing/openai_tracing_tutorial.ipynb
  tutorials/tracing/tracing_with_projects_tutorial.ipynb
Labels: size:XXL

#4099 feat(ui): condensed trace tree
  app/src/components/trace/LatencyText.tsx
  app/src/components/trace/SpanItem.tsx
  app/src/components/trace/SpanKindIcon.tsx
  app/src/components/trace/TraceTree.tsx
  app/src/pages/trace/SpanAside.tsx
  app/src/pages/trace/SpanDetails.tsx
  app/src/pages/trace/TraceDetails.tsx
  app/src/utils/timeFormatUtils.ts
Labels: size:L

#4094 chore(main): release arize-phoenix 4.17.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4114 feat(session): support a slug to the seesion.view
  src/phoenix/session/session.py
Labels: size:S

#4116 docs(annotations): add a feedback tooltip
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
Labels: size:M

#4111 feat(annotations): add ability to edit human span annotations
  app/package.json
  app/src/contexts/FeatureFlagsContext.tsx
  app/src/pages/trace/AnnotationActionMenu.tsx
  app/src/pages/trace/EditSpanAnnotationsDialog.tsx
  app/src/pages/trace/NewSpanAnnotationForm.tsx
  app/src/pages/trace/SpanAnnotationActionMenu.tsx
  app/src/pages/trace/SpanAnnotationForm.tsx
  app/src/pages/trace/SpanDetails.tsx
  app/src/pages/trace/__generated__/EditSpanAnnotationsDialogEditAnnotationMutation.graphql.ts
  app/src/pages/trace/__generated__/EditSpanAnnotationsDialogNewAnnotationQuery.graphql.ts
  src/phoenix/server/api/mutations/span_annotations_mutations.py
Labels: size:XL

#4117 fix: higher lower bound for OpenInference packages
  pyproject.toml
Labels: size:XS

#4115 chore(main): release arize-phoenix 4.18.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4119 feat(annotations): show all annotations in annotation summary in project page header
  app/schema.graphql
  app/src/pages/project/AnnotationSummary.tsx
  app/src/pages/project/ProjectPageHeader.tsx
  app/src/pages/project/__generated__/AnnotationSummaryQuery.graphql.ts
  app/src/pages/project/__generated__/AnnotationSummaryValueFragment.graphql.ts
  app/src/pages/project/__generated__/AnnotationSummaryValueQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectPageHeaderQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectPageHeader_stats.graphql.ts
  app/src/pages/project/__generated__/ProjectPageQuery.graphql.ts
  app/src/pages/trace/EditSpanAnnotationsDialog.tsx
  app/src/pages/trace/__generated__/EditSpanAnnotationsDialogEditAnnotationMutation.graphql.ts
  src/phoenix/server/api/dataloaders/annotation_summaries.py
  src/phoenix/server/api/types/Project.py
Labels: size:L

#4122 chore(main): release arize-phoenix 4.19.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4123 feat: Add span annotations to dataset example metadata
  src/phoenix/server/api/mutations/dataset_mutations.py
  tests/server/api/mutations/test_dataset_mutations.py
Labels: size:M

#4125 chore: docs sync
  docs/.gitbook/assets/Chat flow example 1.png
  docs/.gitbook/assets/Chat flow example 2.png
  docs/.gitbook/assets/DALL·E 2024-08-01 16.45.13 - An icon of a phoenix on a path. The phoenix should be stylized with fiery, vibrant feathers, and wings partially spread. The path should be simple, wi.webp
  docs/.gitbook/assets/DALL·E 2024-08-01 16.45.34 - An icon of a phoenix on a graph. The phoenix should be stylized with fiery, vibrant feathers, and wings partially spread. The graph should be simple, .webp
  docs/.gitbook/assets/DALL·E 2024-08-01 16.46.05 - An icon of a phoenix and a cloud. The phoenix should be stylized with fiery, vibrant feathers, and wings partially spread. The cloud should be soft an.webp
  docs/.gitbook/assets/Experiments-small.jpg
  docs/.gitbook/assets/Experiments.png
  docs/.gitbook/assets/Promptflow Example Screenshot.png
  docs/.gitbook/assets/Promptflow Example Span.png
  docs/.gitbook/assets/experiments.png
  docs/README.md
  docs/SUMMARY.md
  docs/api/client.md
  docs/concepts/llm-traces.md
  docs/datasets-and-experiments/how-to-experiments/run-experiments.md
  docs/datasets-and-experiments/quickstart-datasets.md
  docs/datasets-and-experiments/use-cases-datasets/text2sql.md
  docs/deployment/persistence.md
  docs/evaluation/concepts-evals/README.md
  docs/evaluation/how-to-evals/bring-your-own-evaluator.md
  docs/evaluation/how-to-evals/running-pre-tested-evals/tool-calling-eval.md
  docs/hosted-phoenix.md
  docs/quickstart.md
  docs/quickstart/evals.md
  docs/setup/configuration.md
  docs/tracing/how-to-tracing/README.md
  docs/tracing/how-to-tracing/customize-spans/instrumenting-prompt-templates-and-prompt-variables.md
  docs/tracing/how-to-tracing/instrumentation/README.md
  docs/tracing/how-to-tracing/instrumentation/auto-instrument-python.md
  docs/tracing/how-to-tracing/instrumentation/auto-instrument-python/README.md
  docs/tracing/how-to-tracing/instrumentation/auto-instrument-python/bedrock.md
  docs/tracing/how-to-tracing/instrumentation/auto-instrument-python/dspy.md
  docs/tracing/how-to-tracing/instrumentation/auto-instrument-python/langchain.md
  docs/tracing/how-to-tracing/instrumentation/auto-instrument-python/mistralai.md
  docs/tracing/how-to-tracing/instrumentation/auto-instrument-python/openai.md
  docs/tracing/how-to-tracing/instrumentation/auto-instrument-python/vertexai.md
  docs/tracing/how-to-tracing/instrumentation/auto-instrument-ts.md
  docs/tracing/how-to-tracing/manual-instrumentation/custom-spans/instrumenting-span-types.md
  docs/tracing/integrations-tracing/README.md
  docs/tracing/integrations-tracing/autogen-support.md
  docs/tracing/integrations-tracing/bedrock.md
  docs/tracing/integrations-tracing/dspy.md
  docs/tracing/integrations-tracing/haystack-1.md
  docs/tracing/integrations-tracing/haystack.md
  docs/tracing/integrations-tracing/langchain.js.md
  docs/tracing/integrations-tracing/langchain.md
  docs/tracing/integrations-tracing/llamaindex.md
  docs/tracing/integrations-tracing/mistralai-1.md
  docs/tracing/integrations-tracing/mistralai-2.md
  docs/tracing/integrations-tracing/mistralai.md
  docs/tracing/integrations-tracing/openai-node-sdk.md
  docs/tracing/integrations-tracing/openai.md
  docs/tracing/integrations-tracing/vertexai.md
  docs/tracing/quckstart-tracing.md
  docs/user-guide.md
Labels: size:L

#4128 chore: delete case sensistive images
  docs/.gitbook/assets/Experiments.png
  docs/.gitbook/assets/experiments.png
Labels: size:XS

#4002 docs: Include annotation routes in OpenAPI schema
  cspell.json
  schemas/openapi.json
  src/phoenix/server/api/routers/v1/spans.py
  src/phoenix/server/api/routers/v1/traces.py
Labels: size:L

#4137 fix: ensure rest api urls include custom root path
  src/phoenix/session/client.py
Labels: size:XS

#4136 fix: use dataloader for span annotations
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/span_annotations.py
  src/phoenix/server/api/types/Span.py
Labels: size:M

#4124 chore(main): release arize-phoenix 4.20.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4144 fix: ensure span annotations appear in sorted order by name
  src/phoenix/server/api/types/Span.py
Labels: size:XS

#4138 fix: cache invalidation
  app/schema.graphql
  pyproject.toml
  src/phoenix/db/bulk_inserter.py
  src/phoenix/db/insertion/document_annotation.py
  src/phoenix/db/insertion/span_annotation.py
  src/phoenix/db/insertion/trace_annotation.py
  src/phoenix/db/insertion/types.py
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/mutations/dataset_mutations.py
  src/phoenix/server/api/mutations/experiment_mutations.py
  src/phoenix/server/api/mutations/project_mutations.py
  src/phoenix/server/api/mutations/span_annotations_mutations.py
  src/phoenix/server/api/mutations/trace_annotations_mutations.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/routers/v1/datasets.py
  src/phoenix/server/api/routers/v1/experiment_evaluations.py
  src/phoenix/server/api/routers/v1/experiment_runs.py
  src/phoenix/server/api/routers/v1/experiments.py
  src/phoenix/server/api/routers/v1/spans.py
  src/phoenix/server/api/routers/v1/traces.py
  src/phoenix/server/api/types/Dataset.py
  src/phoenix/server/api/types/Experiment.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/app.py
  src/phoenix/server/dml_event.py
  src/phoenix/server/dml_event_handler.py
  src/phoenix/server/types.py
  tests/conftest.py
  tests/server/api/routers/v1/test_annotations.py
Labels: size:XXL

#4146 chore(main): release arize-phoenix 4.20.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4148 fix(ui): lazy load the spans table on a project
  app/src/pages/project/ProjectPage.tsx
  app/src/pages/project/__generated__/ProjectPageQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectPageSpansQuery.graphql.ts
Labels: size:XL

#4150 feat(ui): add trace tree controls
  app/package.json
  app/pnpm-lock.yaml
  app/src/components/trace/TraceTree.tsx
  app/src/components/trace/TraceTreeContext.tsx
  app/src/store/preferencesStore.tsx
Labels: size:L

#4151 docs: fix integration badges
  docs/tracing/integrations-tracing/README.md
Labels: size:XS

#4152 chore: sleep longer for flaky test
  tests/server/api/routers/v1/test_annotations.py
Labels: size:XS

#4153 refactor: use `uvloop` for async tests
  tests/conftest.py
  tests/server/api/routers/v1/test_annotations.py
Labels: size:S

#4154 chore: add `skip_dep_check=True` to notebooks
  tutorials/evals/evals_sql_correctness_eval_with_custom_agent.ipynb
  tutorials/evals/evaluate_human_vs_ai_classifications.ipynb
  tutorials/evals/evaluate_rag.ipynb
  tutorials/evals/evaluate_reference_link_correctness_classifications.ipynb
  tutorials/evals/evaluate_tool_calling.ipynb
  tutorials/evals/evaluate_user_frustration_classifications.ipynb
  tutorials/experiments/langchain_email_extraction.ipynb
  tutorials/experiments/llama-index/answer_and_context_relevancy.ipynb
  tutorials/experiments/llama-index/guideline_eval.ipynb
  tutorials/experiments/llama-index/pairwise_eval.ipynb
  tutorials/experiments/run_experiments_with_llama_index.ipynb
  tutorials/experiments/summarization.ipynb
  tutorials/experiments/txt2sql.ipynb
  tutorials/integrations/arize_anyscale_traces_and_embeddings.ipynb
  tutorials/integrations/bedrock_tracing_tutorial.ipynb
  tutorials/internal/langchain_retrieval_qa_with_sources_chain_tracing_tutorial.ipynb
  tutorials/internal/openai_request_types.ipynb
  tutorials/llm_application_tracing_evaluating_and_analysis.ipynb
  tutorials/llm_ops_overview.ipynb
  tutorials/mistral/evaluate_rag--mistral.ipynb
  tutorials/qdrant_langchain_instrumentation_search_and_retrieval_tutorial.ipynb
  tutorials/ragas_retrieval_evals_tutorial.ipynb
  tutorials/tracing/autogen_tutorial.ipynb
  tutorials/tracing/bedrock_claude_tracing_tutorial.ipynb
  tutorials/tracing/dspy_tracing_tutorial.ipynb
  tutorials/tracing/langchain_agent_tracing_tutorial.ipynb
  tutorials/tracing/langchain_google_palm_tracing_tutorial.ipynb
  tutorials/tracing/langchain_tracing_tutorial.ipynb
  tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb
  tutorials/tracing/llama_index_openai_agent_tracing_tutorial.ipynb
  tutorials/tracing/llama_index_sql_retriever_tutorial.ipynb
  tutorials/tracing/llama_index_tracing_tutorial.ipynb
  tutorials/tracing/manual_instrumentation_tutorial.ipynb
  tutorials/tracing/openai_tracing_tutorial.ipynb
  tutorials/tracing/tracing_with_projects_tutorial.ipynb
Labels: size:M

#4159 fix: reduce page size of project page queries
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
  app/src/pages/project/__generated__/ProjectPageQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectPageSpansQuery.graphql.ts
  app/src/pages/project/__generated__/SpansTableSpansQuery.graphql.ts
  app/src/pages/project/__generated__/SpansTable_spans.graphql.ts
  app/src/pages/project/__generated__/TracesTableQuery.graphql.ts
  app/src/pages/project/__generated__/TracesTable_spans.graphql.ts
Labels: size:M

#4135 fix: add token count columns to spans table to improve projects page query performance
  src/phoenix/db/insertion/span.py
  src/phoenix/db/migrations/types.py
  src/phoenix/db/migrations/versions/10460e46d750_datasets.py
  src/phoenix/db/migrations/versions/3be8647b87d8_add_token_columns_to_spans_table.py
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
  src/phoenix/db/models.py
  src/phoenix/server/api/dataloaders/token_counts.py
  src/phoenix/server/api/input_types/SpanSort.py
  src/phoenix/server/api/types/Span.py
  tests/server/api/dataloaders/conftest.py
Labels: size:L, feature branch

#4149 chore(main): release arize-phoenix 4.20.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4161 chore: update phoenix version in kubernetes
  kustomize/base/phoenix.yaml
Labels: size:XS

#4160 feat(annotations): add cta for span annotations
  app/src/pages/trace/SpanAnnotationsEmpty.tsx
  app/src/pages/trace/SpanFeedback.tsx
Labels: size:M

#4165 chore(ui): add an error boundary arround span info to catch malformed attributes
  app/src/components/ErrorBoundary.tsx
  app/src/pages/trace/SpanAside.tsx
  app/src/pages/trace/SpanDetails.tsx
Labels: size:M

#4168 fix: Correct import path in UI
  app/src/pages/dataset/RunExperimentButton.tsx
Labels: size:XS

#4163 chore(main): release arize-phoenix 4.21.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4166 chore: make feeback annotations more clear in the UI
  examples/manually-instrumented-chatbot/chat-service/chat/app.py
Labels: size:XS

#4176 chore(auth): add auth-related environment variables
  src/phoenix/config.py
Labels: size:M

#4113 chore(auth): add auth-related tables and migration
  pyproject.toml
  src/phoenix/db/migrations/future_versions/README.md
  src/phoenix/db/migrations/future_versions/cd164e83824f_users_and_tokens.py
  src/phoenix/db/migrations/versions/.gitignore
  src/phoenix/db/models.py
Labels: size:L

#4194 feat(UI): annotation filter actions on span/trace tables
  app/src/components/annotation/AnnotationTooltip.tsx
  app/src/components/trace/TraceTreeContext.tsx
  app/src/pages/project/AnnotationTooltipFilterActions.tsx
  app/src/pages/project/ProjectPage.tsx
  app/src/pages/project/SpanFilterConditionContext.tsx
  app/src/pages/project/SpanFilterConditionField.tsx
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
Labels: size:L

#4201 chore(main): release arize-phoenix 4.22.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4203 chore(annotations): remove span_evaluations resolvers
  app/schema.graphql
  app/src/pages/project/TracesTable.tsx
  app/src/pages/trace/TraceDetails.tsx
  app/src/pages/trace/__generated__/TraceDetailsQuery.graphql.ts
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/evaluation_summaries.py
  src/phoenix/server/api/dataloaders/span_evaluations.py
  src/phoenix/server/api/dataloaders/trace_evaluations.py
  src/phoenix/server/api/types/Evaluation.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/api/types/Span.py
  src/phoenix/server/app.py
  src/phoenix/server/dml_event_handler.py
  tests/server/api/dataloaders/test_evaluation_summaries.py
  tests/server/api/routers/v1/test_annotations.py
Labels: size:XL

#4205 fix: remove skep_deps_check param on phoenix.instrumentors
  tutorials/evals/evaluate_human_vs_ai_classifications.ipynb
  tutorials/evals/evaluate_reference_link_correctness_classifications.ipynb
  tutorials/evals/evaluate_user_frustration_classifications.ipynb
  tutorials/experiments/txt2sql.ipynb
  tutorials/internal/openai_request_types.ipynb
  tutorials/tracing/autogen_tutorial.ipynb
  tutorials/tracing/openai_tracing_tutorial.ipynb
Labels: size:S

#4204 fix: evaluate existing experiment runs
  src/phoenix/experiments/functions.py
  src/phoenix/experiments/types.py
  src/phoenix/server/api/routers/v1/experiment_runs.py
  tests/datasets/conftest.py
  tests/datasets/test_experiments.py
Labels: size:M

#4211 ci: update `googleapis/release-please-action@v4`
  .github/workflows/release.yml
Labels: size:XS

#4206 chore(main): release arize-phoenix 4.22.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4213 feat(auth): plumb auth_enabled flag, add a settings page
  app/src/App.tsx
  app/src/Routes.tsx
  app/src/config.ts
  app/src/contexts/FunctionalityContext.tsx
  app/src/pages/Layout.tsx
  app/src/pages/index.tsx
  app/src/pages/settings/SettingsPage.tsx
  app/src/pages/settings/index.tsx
  app/src/window.d.ts
  cspell.json
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  src/phoenix/server/templates/index.html
  src/phoenix/session/session.py
  tests/conftest.py
Labels: size:L

#4218 fix(UI): show IO if embedding span is missing embeddings
  app/src/pages/trace/SpanDetails.tsx
Labels: size:XS

#4219 feat(auth): user gql query
  app/schema.graphql
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/User.py
Labels: size:M

#4217 docs: create answer_and_context_relevancy_llamatrace.ipynb
  tutorials/experiments/llama-index/answer_and_context_relevancy_llamatrace.ipynb
Labels: size:XS

#4221 feat(auth): users table in settings
  app/src/pages/settings/SettingsPage.tsx
  app/src/pages/settings/UsersTable.tsx
  app/src/pages/settings/__generated__/UsersTableQuery.graphql.ts
Labels: size:L

#4195 fix: Propagate span annotation metadata to examples on all mutations
  src/phoenix/server/api/mutations/dataset_mutations.py
  src/phoenix/server/api/types/Span.py
Labels: size:M

#4216 chore(main): release arize-phoenix 4.23.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4210 docs: Add multimodal image reasoning tutorial with llama index
  tutorials/llama_index_multimodal_image_reasoning.ipynb
Labels: size:L

#4229 feat(auth): add user role, exclude system in user lists
  app/schema.graphql
  app/src/pages/settings/UsersTable.tsx
  app/src/pages/settings/__generated__/UsersTableQuery.graphql.ts
  pyproject.toml
  src/phoenix/db/migrations/future_versions/cd164e83824f_users_and_tokens.py
  src/phoenix/db/models.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/User.py
  src/phoenix/server/api/types/UserRole.py
Labels: size:M

#4232 feat(auth): user / system api key resolvers
  app/schema.graphql
  src/phoenix/db/models.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/ApiKey.py
  src/phoenix/server/api/types/SystemApiKey.py
  src/phoenix/server/api/types/UserApiKey.py
Labels: size:L

#4241 ci(evals): limit `mistralai` below version 1.0
  packages/phoenix-evals/pyproject.toml
Labels: size:XS

#4189 feat(experiments): ability to specify concurrency in run_experiment and evaluate_experiment
  src/phoenix/experiments/functions.py
Labels: size:XS

#3920 chore(main): release arize-phoenix-evals 0.15.0
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#4225 chore(main): release arize-phoenix 4.24.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4249 docs: fix variable name typo in run experiments doc
  docs/datasets-and-experiments/how-to-experiments/run-experiments.md
Labels: size:XS

#4235 feat(auth): create system key
  app/schema.graphql
  pyproject.toml
  src/phoenix/server/api/context.py
  src/phoenix/server/api/mutations/__init__.py
  src/phoenix/server/api/mutations/api_key_mutations.py
  src/phoenix/server/api/mutations/auth.py
  src/phoenix/server/app.py
  src/phoenix/server/main.py
Labels: size:L

#4255 refactor: daemon task abstraction
  src/phoenix/server/types.py
Labels: size:S

#4257 docs: Add human feedback notebook tutorial
  tutorials/human_feedback/chatbot_with_human_feedback.ipynb
Labels: size:L

#4259 fix: Default to adding span annotations to queue
  src/phoenix/server/api/routers/v1/spans.py
Labels: size:XS

#4260 fix: Update OpenAPI spec
  schemas/openapi.json
Labels: size:XS

#4263 fix: conditionally display re-ranker queries in span details
  app/src/pages/trace/SpanDetails.tsx
Labels: size:S

#4230 feat: Create `phoenix.otel` package
  packages/phoenix-otel/IP_NOTICE
  packages/phoenix-otel/LICENSE
  packages/phoenix-otel/README.md
  packages/phoenix-otel/SECURITY
  packages/phoenix-otel/pyproject.toml
  packages/phoenix-otel/src/phoenix/otel/__init__.py
  packages/phoenix-otel/src/phoenix/otel/otel.py
  packages/phoenix-otel/src/phoenix/otel/settings.py
  release-please-config.json
Labels: size:XL

#4264 chore(main): release arize-phoenix-otel 0.1.0
  .release-please-manifest.json
  packages/phoenix-otel/CHANGELOG.md
  packages/phoenix-otel/pyproject.toml
Labels: autorelease: pending, size:S

#4202 docs: Add Phoenix Llamaindex RAG Demo notebook + chunks + questions
  .gitignore
  src/phoenix/trace/fixtures.py
  tutorials/internal/.gitignore
  tutorials/internal/demo_llama_index/.gitignore
  tutorials/internal/demo_llama_index/demo_llama_index_rag.ipynb
Labels: size:XXL

#4265 refactor(auth): name it role.name
  app/schema.graphql
  app/src/pages/settings/UsersTable.tsx
  app/src/pages/settings/__generated__/UsersTableQuery.graphql.ts
  src/phoenix/db/migrations/future_versions/cd164e83824f_users_and_tokens.py
  src/phoenix/db/models.py
  src/phoenix/server/api/mutations/api_key_mutations.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/UserRole.py
Labels: size:M

#4279 feat: OTEL patch
  packages/phoenix-otel/README.md
  release-please-config.json
Labels: size:XS

#4280 feat: Clarify `register` API documentation
  packages/phoenix-otel/src/phoenix/otel/otel.py
  release-please-config.json
Labels: size:S

#4281 chore(main): release arize-phoenix-otel 0.2.0
  .release-please-manifest.json
  packages/phoenix-otel/CHANGELOG.md
  packages/phoenix-otel/pyproject.toml
Labels: autorelease: pending, size:S

#4287 chore: add utility function for password salting and hashing
  src/phoenix/auth/__init__.py
  src/phoenix/auth/utils.py
Labels: size:S

#4270 feat(auth): system api keys ui
  app/src/pages/dataset/DatasetCodeDropdown.tsx
  app/src/pages/settings/APIKeysCard.tsx
  app/src/pages/settings/CreateSystemAPIKeyDialog.tsx
  app/src/pages/settings/SettingsPage.tsx
  app/src/pages/settings/SystemAPIKeysTable.tsx
  app/src/pages/settings/__generated__/APIKeysCardQuery.graphql.ts
  app/src/pages/settings/__generated__/CreateSystemAPIKeyDialogMutation.graphql.ts
  app/src/pages/settings/__generated__/SystemAPIKeysTableFragment.graphql.ts
  app/src/pages/settings/__generated__/SystemAPIKeysTableRefetchQuery.graphql.ts
Labels: size:XL

#4286 docs: add LLM fixtures for demo dataset (fine-tuning dataset), fix demo notebook
  src/phoenix/trace/fixtures.py
  tutorials/internal/demo_llama_index/demo_llama_index_rag.ipynb
Labels: size:L

#4290 ci: standardize testpaths and fail fast
  .github/workflows/python-CI.yml
  packages/phoenix-evals/pyproject.toml
  packages/phoenix-otel/pyproject.toml
  pyproject.toml
  tox.ini
Labels: size:M

#4296 feat(auth): add expiry support for system keys
  app/src/components/table/TableEmpty.tsx
  app/src/pages/settings/APIKeysCard.tsx
  app/src/pages/settings/CreateSystemAPIKeyDialog.tsx
  app/src/pages/settings/SystemAPIKeysTable.tsx
  app/src/pages/settings/__generated__/APIKeysCardQuery.graphql.ts
  app/src/pages/settings/__generated__/CreateSystemAPIKeyDialogMutation.graphql.ts
  app/src/pages/settings/__generated__/SystemAPIKeysTableFragment.graphql.ts
  app/src/pages/settings/__generated__/SystemAPIKeysTableRefetchQuery.graphql.ts
Labels: size:L

#4295 feat: Improve OTel wrapper ergonomics
  packages/phoenix-otel/README.md
  packages/phoenix-otel/src/phoenix/otel/__init__.py
  packages/phoenix-otel/src/phoenix/otel/otel.py
Labels: size:L

#4297 chore(main): release arize-phoenix-otel 0.3.0
  .release-please-manifest.json
  packages/phoenix-otel/CHANGELOG.md
  packages/phoenix-otel/pyproject.toml
Labels: autorelease: pending, size:S

#4298 ci: exclude buggy scipy version
  pyproject.toml
Labels: size:XS

#4251 chore(main): release arize-phoenix 4.25.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:M

#4293 feat(auth): add login/ logout routes and createUser mutation
  app/schema.graphql
  src/phoenix/auth.py
  src/phoenix/auth/__init__.py
  src/phoenix/auth/utils.py
  src/phoenix/server/api/input_types/UserRoleInput.py
  src/phoenix/server/api/mutations/__init__.py
  src/phoenix/server/api/mutations/user_mutations.py
  src/phoenix/server/api/routers/auth.py
  src/phoenix/server/app.py
  tests/test_auth.py
Labels: size:L

#4304 fix(db): postgresql migrations
  pyproject.toml
  src/phoenix/db/engines.py
Labels: size:XS

#4299 chore(main): release arize-phoenix 4.26.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4306 ci(python): increase timeout for integration test
  .github/workflows/python-CI.yml
Labels: size:XS

#4262 feat: onboarding demo projects
  src/phoenix/inferences/fixtures.py
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  src/phoenix/trace/fixtures.py
  tests/server/test_scaffolding.py
Labels: size:L

#4309 fix: handle None values in the context
  src/phoenix/trace/dsl/helpers.py
Labels: size:XS

#4317 feat(experiments): add the ability to copy experiment IDs to the clipboard
  app/src/pages/experiments/ExperimentsTable.tsx
Labels: size:S

#4318 chore: loosen scipy version
  pyproject.toml
Labels: size:XS

#4308 refactor: eliminate consecutive blank lines in log for integration test
  .github/workflows/python-CI.yml
  integration_tests/server/test_launch_app.py
Labels: size:XS

#4322 fix: support `pydantic` in the range `2.4.1<=pydantic<=2.7.1`
  src/phoenix/server/api/routers/v1/utils.py
Labels: size:XS

#4320 feat(auth): minimal login page
  app/src/Routes.tsx
  app/src/components/nav/Logo.tsx
  app/src/pages/index.tsx
  app/src/pages/login/LoginPage.tsx
  app/src/pages/login/index.tsx
Labels: size:L

#4315 feat: Add fixtures only for new DBs, add flag to force fixture ingestion
  src/phoenix/server/app.py
  src/phoenix/server/main.py
Labels: size:L

#4313 chore(main): release arize-phoenix 4.27.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4329 docs: Refine otel readme
  packages/phoenix-otel/README.md
Labels: size:XS

#4319 feat(auth): add create user modal to ui
  app/src/components/dataset/CreateDatasetForm.tsx
  app/src/components/dataset/DatasetForm.tsx
  app/src/components/dataset/EditDatasetForm.tsx
  app/src/components/settings/RolePicker.tsx
  app/src/components/settings/UserForm.tsx
  app/src/constants/index.ts
  app/src/constants/userConstants.ts
  app/src/pages/settings/NewUserDialog.tsx
  app/src/pages/settings/SettingsPage.tsx
  app/src/pages/settings/UsersCard.tsx
  app/src/pages/settings/UsersTable.tsx
  app/src/pages/settings/__generated__/NewUserDialogMutation.graphql.ts
  app/src/pages/settings/__generated__/UsersCardQuery.graphql.ts
  app/src/pages/settings/__generated__/UsersTableQuery.graphql.ts
  app/src/pages/settings/__generated__/UsersTable_users.graphql.ts
  src/phoenix/auth.py
Labels: size:XL

#4316 docs: update api reference
  api_reference/README.md
  api_reference/source/_static/switcher.json
  api_reference/source/api/session.rst
  api_reference/source/conf.py
Labels: size:L

#4333 chore: update pnpm version and pin in package.json
  .github/workflows/typescript-CI.yml
  app/.npmrc
  app/package.json
  app/pnpm-lock.yaml
Labels: size:XS

#4332 feat(auth): prettier login screen
  app/src/pages/login/LoginPage.tsx
  app/src/pages/login/PhoenixLogo.tsx
Labels: size:L

#4327 refactor: convert login and logout routes to mutations
  app/package.json
  app/schema.graphql
  app/src/pages/login/LoginForm.tsx
  app/src/pages/login/LoginPage.tsx
  app/src/pages/login/__generated__/LoginFormMutation.graphql.ts
  src/phoenix/server/api/context.py
  src/phoenix/server/api/mutations/__init__.py
  src/phoenix/server/api/mutations/auth_mutations.py
  src/phoenix/server/api/routers/auth.py
  src/phoenix/server/app.py
Labels: size:L

#4336 ci: add docker sbom and attestation flags
  .github/workflows/docker-build-nightly.yml
  .github/workflows/docker-build-release.yml
Labels: size:S

#4340 ci: fix docker build to use attestations
  .github/workflows/docker-build-nightly.yml
  .github/workflows/docker-build-release.yml
Labels: size:XS

#4341 ci: use buildx
  .github/workflows/docker-build-nightly.yml
  .github/workflows/docker-build-release.yml
Labels: size:XS

#4330 chore(main): release arize-phoenix 4.28.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4342 ci: fix pnpm build on release please
  .github/workflows/release.yml
Labels: size:XS

#4018 docs: new hosted_phoenix tutorials
  tutorials/hosted_phoenix/hosted_phoenix_llamaindex_tutorial.ipynb
  tutorials/hosted_phoenix/hosted_phoenix_openai_tutorial.ipynb
Labels: size:XL

#4343 fix: format code
  tutorials/hosted_phoenix/hosted_phoenix_llamaindex_tutorial.ipynb
  tutorials/hosted_phoenix/hosted_phoenix_openai_tutorial.ipynb
  tutorials/tracing/haystack_tracing_tutorial.ipynb
Labels: size:L

#4345 chore(main): release arize-phoenix 4.28.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4339 chore: mask unexpected error messages in graphql api
  src/phoenix/server/api/dataloaders/dataset_example_revisions.py
  src/phoenix/server/api/exceptions.py
  src/phoenix/server/api/mutations/auth_mutations.py
  src/phoenix/server/api/mutations/dataset_mutations.py
  src/phoenix/server/api/mutations/experiment_mutations.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/schema.py
  tutorials/hosted_phoenix/hosted_phoenix_llamaindex_tutorial.ipynb
  tutorials/hosted_phoenix/hosted_phoenix_openai_tutorial.ipynb
Labels: size:L

#4338 feat: Improve urlencoding logic + bug fixes
  packages/phoenix-otel/src/phoenix/otel/otel.py
  packages/phoenix-otel/src/phoenix/otel/settings.py
Labels: size:S

#4325 chore(main): release arize-phoenix-otel 0.4.0
  .release-please-manifest.json
  packages/phoenix-otel/CHANGELOG.md
  packages/phoenix-otel/pyproject.toml
Labels: autorelease: pending, size:S

#4373 docs(examples): add crew ai example
  tutorials/integrations/CrewAi_Arize_Phoenix.ipynb
Labels: size:XL

#4375 chore: re-name crewai tutorial
  tutorials/experiments/txt2sql.ipynb
  tutorials/integrations/CrewAi_Arize_Phoenix.ipynb
  tutorials/tracing/crewai_tracing_tutorial.ipynb
  tutorials/tracing/haystack_tracing_tutorial.ipynb
Labels: size:XXL

#4376 chore: cleanup notebooks
  tutorials/tracing/crewai_tracing_tutorial.ipynb
  tutorials/tracing/haystack_tracing_tutorial.ipynb
Labels: size:M

#4380 fix(otel): add semantic conventions dependency
  packages/phoenix-otel/pyproject.toml
Labels: size:XS

#4381 chore(main): release arize-phoenix-otel 0.4.1
  .release-please-manifest.json
  packages/phoenix-otel/CHANGELOG.md
  packages/phoenix-otel/pyproject.toml
Labels: autorelease: pending, size:S

#4382 feat: Add arize-phoenix-otel as a dependency
  pyproject.toml
  src/phoenix/otel
Labels: size:XS

#4356 feat: Add Experiments API to OpenAPI Schema
  schemas/openapi.json
  src/phoenix/server/api/routers/v1/experiments.py
Labels: size:L

#4384 chore: support multi-architecture docker builds for nightly release
  .github/workflows/docker-build-nightly.yml
Labels: size:XS

#4385 chore: Remove support for passing Azure env var via OpenAI env var
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
Labels: size:S

#4386 fix(docker): support arm64 architecture in docker images
  .github/workflows/docker-build-release.yml
Labels: size:XS

#4374 chore(main): release arize-phoenix 4.29.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4387 chore: Make keyword argument more explicit
  packages/phoenix-otel/src/phoenix/otel/otel.py
Labels: size:XS

#4390 chore(main): release arize-phoenix 4.30.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4388 chore: remove dataset_description parameter in append_to_dataset client method
  src/phoenix/session/client.py
Labels: size:XS

#4391 fix: improve timeout error message for `query_spans` client method
  src/phoenix/session/client.py
  tests/session/test_client.py
Labels: size:M

#4394 chore(main): release arize-phoenix 4.30.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4397 fix: use dataloader for experiment run annotations
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/experiment_run_annotations.py
  src/phoenix/server/api/types/ExperimentRun.py
  src/phoenix/server/app.py
Labels: size:M

#4402 fix(experiments): ensure compare experiments page does not break for experiments that contain a large number of examples
  src/phoenix/server/api/dataloaders/dataset_example_revisions.py
Labels: size:M

#4403 chore(main): release arize-phoenix 4.30.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4404 chore: pin multi-modal llama-index notebook dependancies
  tutorials/llama_index_multimodal_image_reasoning.ipynb
Labels: size:S

#4393 docs: demo dataset ingestion
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  src/phoenix/trace/fixtures.py
  src/phoenix/trace/utils.py
Labels: size:L

#4408 docs: Add OTEL module to API documentation
  api_reference/source/api/otel.rst
  api_reference/source/conf.py
  api_reference/source/index.md
Labels: size:S

#4405 fix: fix typos in prompt templates
  docs/evaluation/how-to-evals/running-pre-tested-evals/ai-vs-human-groundtruth.md
  packages/phoenix-evals/src/phoenix/evals/default_templates.py
  tutorials/evals/evaluate_human_vs_ai_classifications.ipynb
Labels: size:S

#4407 feat(vision): show images in a gallery, expandable images
  app/src/pages/trace/SpanDetails.tsx
  app/src/pages/trace/SpanImage.tsx
Labels: size:L

#4412 fix: annotation events should refresh trace project
  src/phoenix/server/dml_event_handler.py
Labels: size:XS

#4406 chore(main): release arize-phoenix 4.31.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4324 chore(main): release arize-phoenix-evals 0.15.1
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#4414 feat(ui): add the ability to turn off auto-refresh of projects
  app/src/hooks/useInterval.ts
  app/src/pages/projects/ProjectsAutoRefreshToggle.tsx
  app/src/pages/projects/ProjectsPage.tsx
  app/src/pages/projects/__generated__/ProjectsPageProjectsFragment.graphql.ts
  app/src/pages/projects/__generated__/ProjectsPageProjectsQuery.graphql.ts
  app/src/pages/projects/__generated__/ProjectsPageQuery.graphql.ts
  app/src/store/preferencesStore.tsx
Labels: size:L

#4413 chore(main): release arize-phoenix 4.31.0
  .release-please-manifest.json
  CHANGELOG.md
Labels: autorelease: pending, size:S

#4415 fix: scaffolder should incorporate `port` specified via command line
  src/phoenix/server/app.py
  src/phoenix/server/main.py
Labels: size:L

#4411 chore(docs): update api reference readme
  api_reference/README.md
  api_reference/source/api/inferences_schema.rst
Labels: size:M

#4305 chore: update development tooling dependencies
  pyproject.toml
Labels: size:XS

#4419 feat(auth): wire up login/logout
  app/package.json
  app/pnpm-lock.yaml
  app/src/Routes.tsx
  app/src/pages/Layout.tsx
  app/src/pages/index.tsx
  app/src/pages/login/LoginForm.tsx
  app/src/pages/profile/LogoutButton.tsx
  app/src/pages/profile/ProfilePage.tsx
  app/src/pages/profile/__generated__/LogoutButtonMutation.graphql.ts
  app/src/pages/profile/index.tsx
  app/src/pages/projects/ProjectActionMenu.tsx
  app/src/pages/projects/RemoveProjectDataForm.tsx
  app/src/pages/projects/__generated__/RemoveProjectDataFormMutation.graphql.ts
Labels: size:L

#4424 chore: make image thumbnail square to account for different image dimensions
  app/src/pages/trace/SpanImage.tsx
Labels: size:XS

#4422 fix: error message for PHOENIX_PORT env vars auto-generated by kubernetes
  src/phoenix/config.py
Labels: size:S

#4426 feat(auth): delete system keys
  app/src/pages/settings/APIKeysCard.tsx
  app/src/pages/settings/DeleteSystemAPIKeyButton.tsx
  app/src/pages/settings/SettingsPage.tsx
  app/src/pages/settings/SystemAPIKeysTable.tsx
  app/src/pages/settings/UsersCard.tsx
  app/src/pages/settings/__generated__/DeleteSystemAPIKeyButtonMutation.graphql.ts
  app/src/pages/settings/__generated__/SystemAPIKeysTableFragment.graphql.ts
  app/src/pages/settings/__generated__/SystemAPIKeysTableQuery.graphql.ts
Labels: size:L
