Repository Arize-ai/phoenix, pull requests merged in 2024-09, with the labels that each got.

#4465 feat(onboarding): add bedrock
  app/src/components/project/IntegrationIcons.tsx
  app/src/components/project/Integrations.tsx
Labels: size:M

#4461 fix: improve error message for phoenix secret
  src/phoenix/auth.py
  src/phoenix/config.py
Labels: size:M

#4466 fix: allow secret when auth is disabled
  src/phoenix/config.py
Labels: size:XS

#4468 fix: sqlite should autoincrement integer primary keys
  .github/workflows/python-CI.yml
  .pre-commit-config.yaml
  dev-requirements.txt
  integration_tests/auth/conftest.py
  integration_tests/auth/test_auth.py
  pyproject.toml
  src/phoenix/db/migrations/versions/cd164e83824f_users_and_tokens.py
  src/phoenix/db/models.py
Labels: size:M

#4469 docs: vercel ai sdk
  docs/tracing/integrations-tracing/README.md
  docs/tracing/integrations-tracing/vercel-ai-sdk.md
Labels: size:M

#4456 docs: create nbconvert makefile
  docs/Makefile
  docs/quickstart/evals.md
  docs/tracing/llm-traces-1.md
  tutorials/quickstarts/evals_quickstart.ipynb
  tutorials/quickstarts/tracing_quickstart_openai.ipynb
Labels: size:L

#4474 feat: incorporate schema for postgresql and add integration test
  .github/workflows/python-CI.yml
  .pre-commit-config.yaml
  dev-requirements.txt
  integration_tests/conftest.py
  integration_tests/mypy.ini
  integration_tests/pytest.ini
  integration_tests/requirements.txt
  integration_tests/ruff.toml
  integration_tests/server/conftest.py
  integration_tests/server/test_launch_app.py
  pyproject.toml
  src/phoenix/config.py
  src/phoenix/db/engines.py
  src/phoenix/db/migrate.py
  src/phoenix/db/models.py
  src/phoenix/server/app.py
  tox.ini
Labels: size:XL

#4477 fix(auth): prevent first admin salt from being reset on every start
  src/phoenix/db/facilitator.py
Labels: size:XS

#4476 feat: Add CreateUserApiKey mutation
  app/schema.graphql
  src/phoenix/server/api/mutations/api_key_mutations.py
Labels: size:M

#4429 chore(auth): implement viewer on query
  app/schema.graphql
  src/phoenix/server/api/context.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/UserApiKey.py
Labels: size:M

#4482 feat(auth): auth rbac components
  app/.eslintrc.js
  app/package.json
  app/src/components/auth/index.tsx
  app/src/pages/profile/ProfilePage.tsx
  app/src/pages/settings/DeleteSystemAPIKeyButton.tsx
  app/src/pages/settings/SettingsPage.tsx
Labels: size:M

#4479 feat: render db schema in welcome message when applicable
  src/phoenix/server/main.py
Labels: size:S

#4436 chore(main): release arize-phoenix 4.33.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:M

#4486 feat: api keys on viewer node
  app/schema.graphql
  src/phoenix/server/api/types/ApiKey.py
  src/phoenix/server/api/types/User.py
Labels: size:S

#4485 chore(docs): update API reference readme
  api_reference/README.md
Labels: size:S

#4495 chore: update graphiql param in strawberry
  src/phoenix/server/app.py
Labels: size:XS

#4489 feat(auth): add delete user api keys mutation
  app/schema.graphql
  app/src/pages/settings/__generated__/SystemAPIKeysTableDeleteAPIKeyMutation.graphql.ts
  src/phoenix/server/api/mutations/api_key_mutations.py
Labels: size:M

#4496 fix(auth): fix graphql_ide param type
  src/phoenix/server/app.py
Labels: size:XS

#4458 feat(auth): refresh route and auth router refactor
  app/package.json
  app/schema.graphql
  app/src/__generated__/Routes_datasetMetadata.graphql.ts
  app/src/pages/__generated__/RemoveProjectTracesFormMutation.graphql.ts
  app/src/pages/datasets/__generated__/CreateDatasetFormMutation.graphql.ts
  app/src/pages/datasets/__generated__/datasetsLoaderQuery.graphql.ts
  app/src/pages/example/__generated__/ExampleDetailsDialogDialogQuery.graphql.ts
  app/src/pages/example/__generated__/ExamplePageQuery.graphql.ts
  app/src/pages/login/LoginForm.tsx
  app/src/pages/login/__generated__/LoginFormMutation.graphql.ts
  app/src/pages/profile/LogoutButton.tsx
  app/src/pages/profile/__generated__/LogoutButtonMutation.graphql.ts
  integration_tests/auth/conftest.py
  integration_tests/auth/test_auth.py
  src/phoenix/auth.py
  src/phoenix/db/migrations/versions/cd164e83824f_users_and_tokens.py
  src/phoenix/server/api/mutations/__init__.py
  src/phoenix/server/api/mutations/auth_mutations.py
  src/phoenix/server/api/routers/__init__.py
  src/phoenix/server/api/routers/auth.py
  src/phoenix/server/app.py
  src/phoenix/server/rate_limiters.py
Labels: size:XXL

#4501 style: remove extra api key reference in slideover
  app/src/components/project/PythonProjectGuide.tsx
Labels: size:XS

#4500 chore: Modify conftest to allow a threshold of flaky postgres tests
  tests/conftest.py
Labels: size:S

#4503 feat(auth): add delete user api keys to ui
  app/src/pages/settings/UserAPIKeysTable.tsx
  app/src/pages/settings/__generated__/APIKeysCardQuery.graphql.ts
  app/src/pages/settings/__generated__/UserAPIKeysTableDeleteAPIKeyMutation.graphql.ts
  app/src/pages/settings/__generated__/UserAPIKeysTableFragment.graphql.ts
  app/src/pages/settings/__generated__/UserAPIKeysTableQuery.graphql.ts
Labels: size:L

#4506 chore: Enable flaky test allowance in CI only
  .github/workflows/python-CI.yml
  tests/conftest.py
Labels: size:S

#4504 feat: graphql resolvers to patch users
  app/schema.graphql
  integration_tests/auth/conftest.py
  integration_tests/auth/test_auth.py
  integration_tests/conftest.py
  src/phoenix/server/api/context.py
  src/phoenix/server/api/mutations/user_mutations.py
  src/phoenix/server/api/routers/auth.py
  src/phoenix/server/jwt_store.py
  src/phoenix/server/types.py
Labels: size:XL

#4514 feat(gql): indicate whether user password needs reset
  app/schema.graphql
  src/phoenix/server/api/mutations/user_mutations.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/User.py
Labels: size:M

#4508 feat(auth): secure graphql api when auth is enabled
  integration_tests/auth/test_auth.py
  src/phoenix/server/api/routers/v1/__init__.py
  src/phoenix/server/app.py
  src/phoenix/server/bearer_auth.py
Labels: size:M

#4518 fix: Ensure dataloader output ordering by input keys
  src/phoenix/server/api/dataloaders/average_experiment_run_latency.py
  src/phoenix/server/api/dataloaders/dataset_example_spans.py
  src/phoenix/server/api/dataloaders/experiment_annotation_summaries.py
  src/phoenix/server/api/dataloaders/experiment_error_rates.py
  src/phoenix/server/api/dataloaders/experiment_run_annotations.py
  src/phoenix/server/api/dataloaders/experiment_run_counts.py
  src/phoenix/server/api/dataloaders/experiment_sequence_number.py
  src/phoenix/server/api/dataloaders/span_dataset_examples.py
  src/phoenix/server/api/dataloaders/span_projects.py
Labels: size:S

#4523 ci: reinstantiate httpx client so cookies are not retained
  integration_tests/auth/conftest.py
  integration_tests/auth/test_auth.py
  integration_tests/conftest.py
Labels: size:M

#4527 fix: Fix typo and update ensure dataloader results ordering
  src/phoenix/experiments/functions.py
Labels: size:XS

#4528 chore(main): release arize-phoenix 4.33.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4499 feat(auth): auth refresh tokens
  app/__tests__/authFetch.test.ts
  app/jest.config.js
  app/package.json
  app/pnpm-lock.yaml
  app/src/RelayEnvironment.ts
  app/src/__mocks__/config.ts
  app/src/authFetch.ts
  app/src/components/nav/Navbar.tsx
  app/src/pages/Layout.tsx
  app/src/pages/profile/LogoutButton.tsx
  app/src/pages/profile/ProfilePage.tsx
Labels: size:L

#4520 feat: environment variable for `Secure` attribute on cookies
  src/phoenix/auth.py
  src/phoenix/config.py
Labels: size:S

#4535 fix(auth): don't show error on successful logout
  app/src/pages/Layout.tsx
Labels: size:XS

#4545 feat(auth): Reset password
  app/src/Routes.tsx
  app/src/pages/AuthenticatedRoot.tsx
  app/src/pages/__generated__/authenticatedRootLoaderQuery.graphql.ts
  app/src/pages/auth/AuthLayout.tsx
  app/src/pages/auth/LoginForm.tsx
  app/src/pages/auth/LoginPage.tsx
  app/src/pages/auth/PhoenixLogo.tsx
  app/src/pages/auth/ResetPasswordForm.tsx
  app/src/pages/auth/ResetPasswordPage.tsx
  app/src/pages/auth/__generated__/ResetPasswordFormMutation.graphql.ts
  app/src/pages/auth/__generated__/resetPasswordLoaderQuery.graphql.ts
  app/src/pages/auth/index.tsx
  app/src/pages/auth/resetPasswordLoader.ts
  app/src/pages/authenticatedRootLoader.ts
  app/src/pages/index.tsx
  app/src/pages/login/index.tsx
  app/src/pages/profile/ProfilePage.tsx
  integration_tests/auth/conftest.py
  integration_tests/auth/test_auth.py
  src/phoenix/auth.py
  src/phoenix/db/facilitator.py
Labels: size:XL

#4547 fix: don't redirect if there is no viewer in case auth is disabled
  app/src/pages/authenticatedRootLoader.ts
Labels: size:XS

#4537 feat(auth): add deleteUsers mutation
  app/schema.graphql
  integration_tests/auth/conftest.py
  integration_tests/auth/test_auth.py
  src/phoenix/auth.py
  src/phoenix/db/facilitator.py
  src/phoenix/server/api/exceptions.py
  src/phoenix/server/api/mutations/user_mutations.py
Labels: size:L

#4544 ci: remove unnecessary fixtures from integration tests
  integration_tests/__init__.py
  integration_tests/_helpers.py
  integration_tests/auth/__init__.py
  integration_tests/auth/conftest.py
  integration_tests/auth/test_auth.py
  integration_tests/conftest.py
  integration_tests/mypy.ini
  integration_tests/pytest.ini
  integration_tests/requirements.txt
  integration_tests/server/__init__.py
  integration_tests/server/test_launch_app.py
Labels: size:XXL

#4555 chore(auth): rename env vars
  app/package.json
  src/phoenix/config.py
Labels: size:S

#4554 feat: role based access control for gql queries
  integration_tests/_helpers.py
  integration_tests/auth/test_auth.py
  src/phoenix/server/api/README.md
  src/phoenix/server/api/auth.py
  src/phoenix/server/api/context.py
  src/phoenix/server/api/mutations/api_key_mutations.py
  src/phoenix/server/api/mutations/dataset_mutations.py
  src/phoenix/server/api/mutations/experiment_mutations.py
  src/phoenix/server/api/mutations/export_events_mutations.py
  src/phoenix/server/api/mutations/project_mutations.py
  src/phoenix/server/api/mutations/span_annotations_mutations.py
  src/phoenix/server/api/mutations/trace_annotations_mutations.py
  src/phoenix/server/api/mutations/user_mutations.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/app.py
  src/phoenix/server/bearer_auth.py
Labels: size:L

#4559 feat(auth): edit profile UI
  app/src/contexts/ViewerContext.tsx
  app/src/pages/auth/ResetPasswordForm.tsx
  app/src/pages/profile/ProfilePage.tsx
  app/src/pages/profile/ProfilePicture.tsx
  app/src/pages/profile/ViewerProfileCard.tsx
  app/src/pages/profile/__generated__/ViewerProfileCardMutation.graphql.ts
Labels: size:L

#4556 chore(auth): clean up unused auth-related commands, checks, and folders
  pyproject.toml
  src/phoenix/db/migrations/future_versions/README.md
Labels: size:XS

#4560 ci: run integration tests on python 3.12
  .github/workflows/python-CI.yml
  dev-requirements.txt
  integration_tests/pytest.ini
  pyproject.toml
Labels: size:S

#4558 ci: forbid default admin from logging out when running tests concurrently
  integration_tests/_helpers.py
  integration_tests/auth/test_auth.py
Labels: size:L

#4566 feat(auth): Add API key guidance
  app/src/components/auth/OneTimeAPIKeyDialog.tsx
Labels: size:M

#4562 fix(auth): soft-delete users
  integration_tests/auth/test_auth.py
  src/phoenix/server/api/dataloaders/users.py
  src/phoenix/server/api/mutations/api_key_mutations.py
  src/phoenix/server/api/mutations/user_mutations.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/routers/auth.py
Labels: size:L

#4557 ci(auth): add workflow to publish experimental auth docker image
  .github/workflows/docker-build-experimental.yml
Labels: size:M

#4572 docs: add docs link to readme
  README.md
Labels: size:XS

#4578 feat(auth): UI guidance on how to set api keys for tracing and experi…
  app/src/components/project/PythonProjectGuide.tsx
  app/src/components/project/TypeScriptProjectGuide.tsx
  app/src/components/project/hosting.ts
  app/src/pages/dataset/RunExperimentButton.tsx
Labels: size:L

#4585 feat(auth): add environment variables for token expiries
  src/phoenix/auth.py
  src/phoenix/config.py
  src/phoenix/server/api/routers/auth.py
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  tests/test_config.py
Labels: size:L

#4587 refactor(auth): ensure auth environment variables are read once
  src/phoenix/config.py
  src/phoenix/db/facilitator.py
  src/phoenix/server/api/openapi/schema.py
  src/phoenix/server/api/routers/__init__.py
  src/phoenix/server/api/routers/v1/__init__.py
  src/phoenix/server/app.py
  src/phoenix/server/main.py
Labels: size:M

#4595 fix: username should be optional for user creation
  integration_tests/auth/test_auth.py
  src/phoenix/server/api/mutations/user_mutations.py
Labels: size:S

#4596 refactor: remove redundant db facilitator
  src/phoenix/db/facilitator.py
  src/phoenix/server/app.py
Labels: size:M

#4591 feat(auth): force password repeat on new user addition
  app/src/components/settings/UserForm.tsx
  app/src/pages/settings/NewUserDialog.tsx
Labels: size:M

#4592 docs(quickstart): update inferences documentation to correct example syntax
  docs/quickstart/phoenix-inferences/README.md
Labels: size:XS

#4597 ci: integration tests for span exporters using environment variables
  app/src/components/auth/OneTimeAPIKeyDialog.tsx
  app/src/components/project/TypeScriptProjectGuide.tsx
  integration_tests/auth/test_auth.py
Labels: size:M

#4599 fix: get_retrieved_documents should handle missing values
  src/phoenix/trace/dsl/query.py
  tests/trace/dsl/conftest.py
  tests/trace/dsl/test_helpers.py
Labels: size:L

#4573 chore(main): release arize-phoenix 4.33.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4590 feat: Pick up authorization headers from environment variable
  packages/phoenix-otel/README.md
  packages/phoenix-otel/src/phoenix/otel/otel.py
  packages/phoenix-otel/src/phoenix/otel/settings.py
Labels: size:L

#4575 chore(main): release arize-phoenix-otel 0.5.0
  .release-please-manifest.json
  packages/phoenix-otel/CHANGELOG.md
  packages/phoenix-otel/pyproject.toml
Labels: autorelease: pending, size:S

#4589 feat(auth): secure `/exports` when auth is enabled
  integration_tests/_helpers.py
  integration_tests/auth/test_auth.py
  src/phoenix/server/api/routers/__init__.py
  src/phoenix/server/api/routers/embeddings.py
  src/phoenix/server/app.py
Labels: size:M

#4608 fix(auth): add unique constraint on refresh_token_id in access_tokens table
  src/phoenix/db/migrations/versions/cd164e83824f_users_and_tokens.py
  src/phoenix/db/models.py
Labels: size:XS

#4604 feat!: Remove legacy instrumentation modules
  pyproject.toml
  src/phoenix/__init__.py
  src/phoenix/trace/langchain/__init__.py
  src/phoenix/trace/langchain/instrumentor.py
  src/phoenix/trace/llama_index/__init__.py
  src/phoenix/trace/llama_index/callback.py
  src/phoenix/trace/openai/__init__.py
  src/phoenix/trace/openai/instrumentor.py
Labels: size:L

#4619 docs (quickstart): fix incorrect object reference in Inferences example
  docs/quickstart/phoenix-inferences/README.md
Labels: size:XS

#4593 docs(quickstart): convert Phoenix inferences instructions to notebook
  tutorials/quickstarts/inferences_quickstart.ipynb
Labels: size:XL

#4615 docs: create groq_tracing_tutorial.ipynb
  tutorials/tracing/groq_tracing_tutorial.ipynb
Labels: size:L

#4627 chore: move configuration to be in .env files
  app/.env.example
  app/README.md
  app/package.json
  src/phoenix/server/main.py
Labels: size:S

#4626 fix: Clarify type annotation
  packages/phoenix-otel/src/phoenix/otel/otel.py
Labels: size:XS

#4611 ci: cron for python integration test
  .github/workflows/python-cron.yml
Labels: size:M

#4633 feat: OpenAI support for o1 preview
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
  packages/phoenix-evals/tests/phoenix/evals/functions/test_classify.py
Labels: size:M

#4629 chore(main): release arize-phoenix-otel 0.5.1
  .release-please-manifest.json
  packages/phoenix-otel/CHANGELOG.md
  packages/phoenix-otel/pyproject.toml
Labels: autorelease: pending, size:S

#4574 chore(main): release arize-phoenix-evals 0.16.0
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#4632 feat: finer grain last N time range
  app/src/components/datetime/LastNTimeRangeContext.tsx
  app/src/components/datetime/LastNTimeRangePicker.tsx
  app/src/components/datetime/constants.ts
  app/src/components/datetime/types.ts
  app/src/components/datetime/utils.ts
  app/src/store/preferencesStore.tsx
Labels: size:M

#4624 chore(main): release arize-phoenix 4.34.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4636 feat: adds o1 testing demo project
  src/phoenix/trace/fixtures.py
  tutorials/tracing/groq_tracing_tutorial.ipynb
Labels: size:M

#4639 fix: update file name to dodge gcs caching
  src/phoenix/trace/fixtures.py
Labels: size:XS

#4638 chore(main): release arize-phoenix 4.35.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4637 fix: inadvertent cookie deletion when changing user password via PatchUser
  integration_tests/_helpers.py
  src/phoenix/server/api/context.py
  src/phoenix/server/api/mutations/user_mutations.py
Labels: size:M

#4641 ci: tox posargs for pytest only
  tox.ini
Labels: size:XS

#4642 ci: retry postgres clean-up when connection is not available
  integration_tests/_helpers.py
Labels: size:S

#4643 fix: submodule packaging for bazel
  src/phoenix/__init__.py
Labels: size:XS

#4644 chore(main): release arize-phoenix 4.35.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4645 ci: print name of test alongside httpx payload in the log
  integration_tests/_helpers.py
  integration_tests/conftest.py
Labels: size:S

#4617 feat: Wire up API keys via env var for Phoenix clients and experiments
  src/phoenix/experiments/functions.py
  src/phoenix/session/client.py
  src/phoenix/utilities/client.py
Labels: size:S

#4647 fix: forbid role change on default admin
  integration_tests/auth/test_auth.py
  src/phoenix/server/api/mutations/user_mutations.py
Labels: size:S

#4646 ci: print decoded token ids in the log
  integration_tests/_helpers.py
Labels: size:M

#4631 feat(auth): add admin user management ui
  app/schema.graphql
  app/src/components/settings/RolePicker.tsx
  app/src/constants/userConstants.ts
  app/src/pages/settings/DeleteUserButton.tsx
  app/src/pages/settings/DeleteUserDialog.tsx
  app/src/pages/settings/ResetPasswordDialog.tsx
  app/src/pages/settings/UserActionMenu.tsx
  app/src/pages/settings/UserRoleChangeDialog.tsx
  app/src/pages/settings/UsersTable.tsx
  app/src/pages/settings/__generated__/DeleteUserDialogMutation.graphql.ts
  app/src/pages/settings/__generated__/ResetPasswordDialogMutation.graphql.ts
  app/src/pages/settings/__generated__/UserRoleChangeDialogMutation.graphql.ts
  app/src/pages/settings/__generated__/UsersCardQuery.graphql.ts
  app/src/pages/settings/__generated__/UsersTableQuery.graphql.ts
  app/src/pages/settings/__generated__/UsersTable_users.graphql.ts
  src/phoenix/server/api/types/AuthMethod.py
  src/phoenix/server/api/types/User.py
Labels: size:XL

#4667 fix: Update phoenix otel dependency
  pyproject.toml
Labels: size:XS

#4671 feat(auth): cleaned up reset password UI
  app/.env.example
  app/src/pages/auth/ForgotPasswordForm.tsx
  app/src/pages/auth/ForgotPasswordPage.tsx
  app/src/pages/auth/LoginForm.tsx
  cspell.json
  src/phoenix/config.py
  src/phoenix/server/email/sender.py
  src/phoenix/server/email/templates/password_reset.html
Labels: size:L

#4668 chore: add analytics script
  scripts/analytics/.env.example
  scripts/analytics/.gitignore
  scripts/analytics/README.md
  scripts/analytics/analytics.py
  scripts/analytics/requirements.txt
Labels: size:L

#4672 fix: users should not be asked to reset password again right after they reset their password
  integration_tests/_helpers.py
  integration_tests/auth/test_auth.py
  src/phoenix/server/api/routers/auth.py
Labels: size:M

#4674 fix: user should be able to initiate password reset again before existing token is used or expires
  integration_tests/auth/test_auth.py
  src/phoenix/db/models.py
  src/phoenix/server/api/routers/auth.py
Labels: size:M

#4681 docs: Change column name 'value' to 'score' in example SpanEvaluations dataframe
  docs/tracing/how-to-tracing/llm-evaluations.md
Labels: size:XS

#4521 docs: add evaluating traces notebook
  docs/Makefile
  docs/evaluation/how-to-evals/evaluating-phoenix-traces.md
  tutorials/quickstarts/evaluating_traces_quickstart.ipynb
Labels: size:XL

#4618 feat(auth): add support for oauth2 with openid connect discovery
  app/schema.graphql
  app/src/pages/auth/LoginForm.tsx
  app/src/pages/auth/LoginPage.tsx
  app/src/pages/auth/OAuth2Login.tsx
  app/src/pages/settings/__generated__/UsersTable_users.graphql.ts
  app/src/window.d.ts
  cspell.json
  pyproject.toml
  src/phoenix/auth.py
  src/phoenix/config.py
  src/phoenix/db/enums.py
  src/phoenix/db/facilitator.py
  src/phoenix/db/migrations/versions/cd164e83824f_users_and_tokens.py
  src/phoenix/db/models.py
  src/phoenix/experiments/evaluators/code_evaluators.py
  src/phoenix/server/api/mutations/user_mutations.py
  src/phoenix/server/api/routers/__init__.py
  src/phoenix/server/api/routers/auth.py
  src/phoenix/server/api/routers/oauth2.py
  src/phoenix/server/api/types/AuthMethod.py
  src/phoenix/server/api/types/User.py
  src/phoenix/server/app.py
  src/phoenix/server/bearer_auth.py
  src/phoenix/server/main.py
  src/phoenix/server/oauth2.py
  src/phoenix/server/rate_limiters.py
  src/phoenix/server/templates/index.html
Labels: size:XXL

#4693 fix(auth): set oauth2 state and nonce cookies with lax samesite policy
  src/phoenix/auth.py
Labels: size:S

#4695 fix(auth): ensure return urls are relative
  src/phoenix/server/api/routers/oauth2.py
Labels: size:S

#4694 fix: `TraceDataset.to_span()` should unflatten dot separators at all levels
  pyproject.toml
  src/phoenix/trace/trace_dataset.py
  tests/trace/test_trace_dataset.py
Labels: size:M

#4548 fix: Fix DB unittest reliability
  .github/workflows/python-CI.yml
  pyproject.toml
  src/phoenix/server/app.py
  tests/conftest.py
  tests/datasets/test_experiments.py
  tests/server/api/routers/v1/test_annotations.py
  tests/server/api/routers/v1/test_spans.py
  tests/trace/dsl/test_helpers.py
Labels: size:L

#4635 feat: Add environment variable setting for structured logging
  packages/phoenix-otel/src/phoenix/otel/settings.py
  pyproject.toml
  src/phoenix/config.py
  src/phoenix/db/alembic.ini
  src/phoenix/db/engines.py
  src/phoenix/db/insertion/dataset.py
  src/phoenix/db/insertion/types.py
  src/phoenix/db/migrate.py
  src/phoenix/db/migrations/env.py
  src/phoenix/inferences/fixtures.py
  src/phoenix/inferences/inferences.py
  src/phoenix/logging/__init__.py
  src/phoenix/logging/_config.py
  src/phoenix/logging/_filter.py
  src/phoenix/logging/_formatter.py
  src/phoenix/metrics/__init__.py
  src/phoenix/server/api/routers/v1/datasets.py
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  src/phoenix/server/telemetry.py
  src/phoenix/services.py
  src/phoenix/session/client.py
  src/phoenix/session/evaluation.py
  src/phoenix/session/session.py
  src/phoenix/settings.py
  src/phoenix/trace/exporter.py
  src/phoenix/trace/fixtures.py
  src/phoenix/trace/langchain/instrumentor.py
  src/phoenix/trace/llama_index/callback.py
  src/phoenix/trace/openai/instrumentor.py
  src/phoenix/utilities/logging.py
  src/phoenix/utilities/re.py
Labels: size:L

#4702 fix: close db connection after migration
  src/phoenix/db/migrate.py
Labels: size:XS

#4697 fix: playwright scaffolding and user action menu rendering
  app/global-setup.ts
  app/jest.config.js
  app/playwright.config.ts
  app/src/pages/settings/UserActionMenu.tsx
  app/src/pages/settings/UsersCard.tsx
  app/tests/getting-started.spec.ts
  app/tests/user-management.spec.ts
Labels: size:L

#4700 chore(main): release arize-phoenix 4.36.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4698 fix: Correct auth login rate limit routes
  app/playwright.config.ts
  app/src/pages/auth/LoginForm.tsx
  app/tests/login.rate-limit.spec.ts
  integration_tests/auth/conftest.py
  src/phoenix/config.py
  src/phoenix/server/api/routers/auth.py
  src/phoenix/server/api/routers/oauth2.py
Labels: size:M

#4705 feat(auth): add user friendly messages to the login page
  app/src/pages/auth/LoginPage.tsx
  app/src/pages/auth/ResetPasswordForm.tsx
  app/src/pages/auth/ResetPasswordWithTokenForm.tsx
  app/src/pages/auth/ResetPasswordWithTokenPage.tsx
  app/src/pages/authenticatedRootLoader.ts
  app/src/utils/__tests__/routingUtils.test.ts
  app/src/utils/routingUtils.ts
Labels: size:L

#4703 docs: add agent framework example
  .gitignore
  examples/agent_framework_comparison/.gitignore
  examples/agent_framework_comparison/README.md
  examples/agent_framework_comparison/code_based_agent/main.py
  examples/agent_framework_comparison/code_based_agent/router.py
  examples/agent_framework_comparison/db/database.py
  examples/agent_framework_comparison/db/download_traces_from_px.py
  examples/agent_framework_comparison/langgraph/analyze_data.py
  examples/agent_framework_comparison/langgraph/generate_sql_query.py
  examples/agent_framework_comparison/langgraph/main.py
  examples/agent_framework_comparison/langgraph/router.py
  examples/agent_framework_comparison/li_workflow/main.py
  examples/agent_framework_comparison/li_workflow/router.py
  examples/agent_framework_comparison/prompt_templates/data_analysis_template.py
  examples/agent_framework_comparison/prompt_templates/router_template.py
  examples/agent_framework_comparison/prompt_templates/sql_generator_template.py
  examples/agent_framework_comparison/requirements.txt
  examples/agent_framework_comparison/skills/analyze_data.py
  examples/agent_framework_comparison/skills/generate_sql_query.py
  examples/agent_framework_comparison/skills/skill.py
  examples/agent_framework_comparison/skills/skill_map.py
  examples/agent_framework_comparison/utils/instrument.py
  examples/agent_framework_comparison/utils/save_agent_traces.py
Labels: size:XL

#4696 refactor(auth): add computed attribute for `auth_method` on `users` table
  src/phoenix/auth.py
  src/phoenix/db/enums.py
  src/phoenix/db/models.py
  src/phoenix/server/api/mutations/user_mutations.py
  src/phoenix/server/api/routers/auth.py
  src/phoenix/server/api/types/User.py
Labels: size:M

#4708 docs: update hosted_phoenix_openai_tutorial.ipynb
  examples/agent_framework_comparison/langgraph/analyze_data.py
  examples/agent_framework_comparison/utils/instrument.py
  pyproject.toml
  tutorials/hosted_phoenix/hosted_phoenix_openai_tutorial.ipynb
Labels: size:M

#4713 refactor(auth): simplify config
  src/phoenix/config.py
  src/phoenix/server/oauth2.py
Labels: size:S

#4714 fix(auth): automatically resolve username collisions when creating oauth2 users
  src/phoenix/server/api/routers/oauth2.py
Labels: size:M

#4715 fix(auth): hard-delete users
  src/phoenix/db/migrations/versions/cd164e83824f_users_and_tokens.py
  src/phoenix/db/models.py
  src/phoenix/server/api/dataloaders/users.py
  src/phoenix/server/api/mutations/api_key_mutations.py
  src/phoenix/server/api/mutations/user_mutations.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/routers/auth.py
Labels: size:M

#4706 fix: allow logging out with just the refresh token
  integration_tests/_helpers.py
  integration_tests/auth/test_auth.py
  src/phoenix/server/api/routers/auth.py
Labels: size:M

#4719 docs: Playwright in READE
  .tours/app.tour
  app/README.md
Labels: size:M

#4721 docs(auth): migration guide for auth
  MIGRATION.md
Labels: size:M

#4724 feat(auth): Profile picture
  app/schema.graphql
  app/src/components/user/UserPicture.tsx
  app/src/contexts/ViewerContext.tsx
  app/src/contexts/__generated__/ViewerContextRefetchQuery.graphql.ts
  app/src/contexts/__generated__/ViewerContext_viewer.graphql.ts
  app/src/pages/__generated__/authenticatedRootLoaderQuery.graphql.ts
  app/src/pages/profile/ViewerProfileCard.tsx
  app/src/pages/settings/UsersTable.tsx
  app/src/pages/settings/__generated__/UsersCardQuery.graphql.ts
  app/src/pages/settings/__generated__/UsersTableQuery.graphql.ts
  app/src/pages/settings/__generated__/UsersTable_users.graphql.ts
  src/phoenix/server/api/types/User.py
Labels: size:L

#4723 feat: fetch from db on token cache miss
  src/phoenix/server/jwt_store.py
Labels: size:S

#4722 chore: Remove pyjwt dependency
  integration_tests/requirements.txt
  pyproject.toml
  src/phoenix/server/jwt_store.py
Labels: size:S

#4726 fix: db lookup on token cache miss
  src/phoenix/server/jwt_store.py
Labels: size:XS

#4725 feat: Auth prometheus metrics
  src/phoenix/server/jwt_store.py
  src/phoenix/server/prometheus.py
  src/phoenix/server/rate_limiters.py
Labels: size:M

#4732 docs(auth): instrumentation migration
  MIGRATION.md
Labels: size:S

#4735 feat(auth): add cancel for reset password page
  app/src/pages/auth/ResetPasswordForm.tsx
Labels: size:M

#4738 fix(playwright): make rate-limiting test run last
  app/playwright.config.ts
Labels: size:XS

#4737 fix(auth): infer origin url
  src/phoenix/config.py
  src/phoenix/server/api/routers/oauth2.py
  src/phoenix/server/app.py
  src/phoenix/server/main.py
Labels: size:M

#4734 fix(auth): make username a required field
  app/global-setup.ts
  app/schema.graphql
  app/src/components/settings/UserForm.tsx
  app/src/pages/settings/__generated__/NewUserDialogMutation.graphql.ts
  app/tests/user-management.spec.ts
  integration_tests/_helpers.py
  integration_tests/auth/test_auth.py
  src/phoenix/auth.py
  src/phoenix/db/facilitator.py
  src/phoenix/db/migrations/versions/cd164e83824f_users_and_tokens.py
  src/phoenix/db/models.py
  src/phoenix/server/api/mutations/user_mutations.py
Labels: size:M

#4739 ci: deprecate 3.8 support
  .github/workflows/python-CI.yml
Labels: size:S

#4742 test: Add load testing script
  scripts/testing/send_spans.py
Labels: size:L

#4729 fix: remove `exp` from `jwt`
  integration_tests/_helpers.py
  integration_tests/auth/conftest.py
  integration_tests/conftest.py
  src/phoenix/server/jwt_store.py
Labels: size:M

#4746 fix: use referer from headers for base url in password reset url
  src/phoenix/server/api/routers/auth.py
  src/phoenix/server/email/sender.py
  src/phoenix/server/email/templates/password_reset.html
  src/phoenix/server/email/templates/types.py
  src/phoenix/server/email/types.py
Labels: size:M

#4751 fix: remove python 3.8 version dep
  pyproject.toml
Labels: size:XS

#4745 ci: Update hatch to only run on 3.9 + 3.12
  pyproject.toml
  scripts/testing/send_spans.py
Labels: size:M

#4753 fix: padding on users table
  app/src/pages/settings/UsersCard.tsx
Labels: size:XS

#4754 chore(auth): update it python version to 3.9
  .github/workflows/python-CI.yml
  .github/workflows/python-cron.yml
Labels: size:XS

#4752 fix: Catch decode error
  src/phoenix/server/api/routers/oauth2.py
  src/phoenix/server/jwt_store.py
Labels: size:XS

#4755 fix(auth): handle forgot password form submission
  app/global-setup.ts
  app/playwright.config.ts
  app/src/pages/auth/ForgotPasswordForm.tsx
  app/tests/getting-started.spec.ts
  app/tests/login.rate-limit.spec.ts
  app/tests/user-management.spec.ts
  src/phoenix/server/api/routers/auth.py
Labels: size:M

#4757 docs: deprecate phoenix.trace.openai
  docs/datasets-and-experiments/how-to-experiments/run-experiments.md
  docs/datasets-and-experiments/use-cases-datasets/text2sql.md
  docs/tracing/integrations-tracing/autogen-support.md
  tutorials/experiments/txt2sql.ipynb
Labels: size:M

#4756 chore: add integration test for broken jwt
  integration_tests/_helpers.py
  integration_tests/auth/test_auth.py
  integration_tests/conftest.py
Labels: size:S

#4758 fix(playwright): revert back to localhost for playwright
  app/playwright.config.ts
  app/tests/user-management.spec.ts
Labels: size:S

#4748 fix(auth): ensure consistent origin url
  src/phoenix/server/api/routers/oauth2.py
Labels: size:M

#4759 fix: overflow of UI issues
  app/src/GlobalStyles.tsx
  app/src/pages/settings/UsersCard.tsx
Labels: size:XS

#4749 ci: Avoid second db entry in tests
  pyproject.toml
  tests/datasets/test_experiments.py
Labels: size:L

#4760 chore(ci): add pnpm cache and frozen-lockfile install for playwright
  .github/workflows/playwright.yaml
  .github/workflows/typescript-CI.yml
Labels: size:S

#4762 chore(ci): move pnpm action above node
  .github/workflows/typescript-CI.yml
  app/schema.graphql
  app/src/contexts/__generated__/ViewerContext_viewer.graphql.ts
  app/src/pages/settings/UsersTable.tsx
  app/src/pages/settings/__generated__/UsersTable_users.graphql.ts
  src/phoenix/server/api/types/User.py
  tests/datasets/test_experiments.py
Labels: size:M

#4740 fix(auth): minor db fix
  src/phoenix/db/models.py
Labels: size:XS

#4766 fix!: deprecate python 3.8
  pyproject.toml
Labels: size:XS

#4768 fix: only redirect if auth is enabled
  app/src/RelayEnvironment.ts
Labels: size:XS

#4769 ci: fix cron for python 3.9
  .github/workflows/python-cron.yml
Labels: size:XS

#4772 feat: update fixtures.py to include new demos
  src/phoenix/trace/fixtures.py
Labels: size:S

#4771 fix: fixes to the langgraph example agent
  .gitignore
  examples/agent_framework_comparison/code_based_agent/main.py
  examples/agent_framework_comparison/code_based_agent/router.py
  examples/agent_framework_comparison/db/database.py
  examples/agent_framework_comparison/langgraph/analyze_data.py
  examples/agent_framework_comparison/langgraph/generate_sql_query.py
  examples/agent_framework_comparison/langgraph/main.py
  examples/agent_framework_comparison/li_workflow/main.py
  examples/agent_framework_comparison/prompt_templates/router_template.py
  examples/agent_framework_comparison/utils/save_agent_traces.py
Labels: size:L

#4780 chore: fix lint
  examples/agent_framework_comparison/code_based_agent/main.py
  examples/agent_framework_comparison/langgraph/main.py
Labels: size:XS

#4777 docs: initial playground PRD
  cspell.json
  internal_docs/specs/playground.md
Labels: size:L

#4779 chore: move pytest flags from tox.ini to pytest.ini
  integration_tests/pytest.ini
  tox.ini
Labels: size:XS
