Repository Arize-ai/phoenix, pull requests merged in 2024-04, with the labels that each got.

#2734 docs: make dockerhub URL go to public
  README.md
Labels: size:XS

#2736 docs: fix qa with reference tutorial
  tutorials/evals/evaluate_QA_classifications.ipynb
Labels: size:XS

#2730 docs: manually instrumented chatbot
  examples/manually-instrumented-chatbot/.gitignore
  examples/manually-instrumented-chatbot/Makefile
  examples/manually-instrumented-chatbot/README.md
  examples/manually-instrumented-chatbot/app.py
  examples/manually-instrumented-chatbot/chat/__init__.py
  examples/manually-instrumented-chatbot/chat/app.py
  examples/manually-instrumented-chatbot/chat/types.py
  examples/manually-instrumented-chatbot/pyproject.toml
Labels: size:L

#2747 refactor: sqlite with SQLAlchemy
  pyproject.toml
  src/phoenix/db/database.py
  src/phoenix/db/models.py
Labels: size:L

#2748 feat(persistence): migrations support
  cspell.json
  pyproject.toml
  src/phoenix/db/__init__.py
  src/phoenix/db/alembic.ini
  src/phoenix/db/database.py
  src/phoenix/db/migrate.py
  src/phoenix/db/migrations/README
  src/phoenix/db/migrations/env.py
  src/phoenix/db/migrations/script.py.mako
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
  src/phoenix/db/models.py
  src/phoenix/server/main.py
Labels: size:L

#2762 fix: switch license format in toml
  packages/phoenix-evals/pyproject.toml
  pyproject.toml
Labels: size:XS

#2784 refactor: sqlite async session for graphql api
  app/schema.graphql
  pyproject.toml
  src/phoenix/core/traces.py
  src/phoenix/db/database.py
  src/phoenix/db/engines.py
  src/phoenix/db/migrate.py
  src/phoenix/db/migrations/env.py
  src/phoenix/db/models.py
  src/phoenix/server/api/context.py
  src/phoenix/server/api/routers/trace_handler.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/api/types/Span.py
  src/phoenix/server/api/types/Trace.py
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  src/phoenix/session/session.py
  tests/server/api/types/conftest.py
Labels: size:XXL

#2800 chore: add /healthz route for healthchecks
  pyproject.toml
  src/phoenix/server/app.py
Labels: size:XS

#2797 docs: dockerize manual instrumentation example
  examples/manually-instrumented-chatbot/Makefile
  examples/manually-instrumented-chatbot/README.md
  examples/manually-instrumented-chatbot/chat-service/Dockerfile
  examples/manually-instrumented-chatbot/chat-service/Makefile
  examples/manually-instrumented-chatbot/chat-service/chat/__init__.py
  examples/manually-instrumented-chatbot/chat-service/chat/app.py
  examples/manually-instrumented-chatbot/chat-service/chat/types.py
  examples/manually-instrumented-chatbot/chat-service/export_schema.py
  examples/manually-instrumented-chatbot/chat-service/pyproject.toml
  examples/manually-instrumented-chatbot/chat-service/requirements.txt
  examples/manually-instrumented-chatbot/compose.yml
  examples/manually-instrumented-chatbot/frontend/Dockerfile
  examples/manually-instrumented-chatbot/frontend/Makefile
  examples/manually-instrumented-chatbot/frontend/__init__.py
  examples/manually-instrumented-chatbot/frontend/frontend/app.py
  examples/manually-instrumented-chatbot/frontend/frontend/request_types.py
  examples/manually-instrumented-chatbot/frontend/pyproject.toml
  examples/manually-instrumented-chatbot/frontend/requirements.txt
  examples/manually-instrumented-chatbot/frontend/schema.json
Labels: size:XL

#2790 docs: remove experimental tags in code
  src/phoenix/datasets/schema.py
  src/phoenix/session/evaluation.py
  src/phoenix/session/session.py
Labels: size:XS

#2785 feat: Deprecate `datasets` module, rename to `inferences`
  src/phoenix/__init__.py
  src/phoenix/core/model.py
  src/phoenix/core/model_schema_adapter.py
  src/phoenix/datasets/dataset.py
  src/phoenix/datasets/fixtures.py
  src/phoenix/datasets/schema.py
  src/phoenix/inferences/__init__.py
  src/phoenix/inferences/errors.py
  src/phoenix/inferences/fixtures.py
  src/phoenix/inferences/inferences.py
  src/phoenix/inferences/schema.py
  src/phoenix/inferences/validation.py
  src/phoenix/server/main.py
  src/phoenix/session/session.py
  src/phoenix/utilities/deprecation.py
  tests/core/test_model.py
  tests/inferences/test_inference.py
  tests/inferences/test_schema.py
  tests/inferences/test_validation.py
  tests/server/api/types/conftest.py
  tests/server/api/types/test_EmbeddingDimension.py
  tests/server/api/types/test_inference.py
Labels: size:XXL

#2796 feat(persistece): configurable sql engine
  Dockerfile
  pyproject.toml
  src/phoenix/config.py
  src/phoenix/db/alembic.ini
  src/phoenix/db/engines.py
  src/phoenix/server/main.py
  src/phoenix/session/session.py
Labels: size:M

#2812 fix: fix docker build for sql
  Dockerfile
Labels: size:XS

#2808 feat(persistence): experimental bulk inserter for spans
  src/phoenix/db/alembic.ini
  src/phoenix/db/bulk_inserter.py
  src/phoenix/db/engines.py
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
  src/phoenix/db/models.py
  src/phoenix/server/api/routers/trace_handler.py
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  src/phoenix/session/session.py
Labels: size:L

#2816 chore: Remove unused litellm params
  packages/phoenix-evals/src/phoenix/evals/models/litellm.py
Labels: size:XS

#2788 feat(persistence): span annotation tables
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
  src/phoenix/db/models.py
Labels: size:M

#2828 chore: add trace annotations table
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
  src/phoenix/db/models.py
Labels: size:M

#2830 chore: add document annotations table
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
  src/phoenix/db/models.py
Labels: size:M

#2817 feat(persistence): launch app with persist
  cspell.json
  src/phoenix/__init__.py
  src/phoenix/db/migrations/env.py
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  src/phoenix/session/session.py
Labels: size:M

#2832 ci(persistence): add asyncio to add greenlet for mac
  cspell.json
  pyproject.toml
Labels: size:XS

#2834 chore: add down migrations for annotation tables
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
Labels: size:XXL

#2820 chore: make alembic runnable via command line
  src/phoenix/db/engines.py
  src/phoenix/db/migrations/README.md
  src/phoenix/db/migrations/env.py
Labels: size:M

#2835 fix: preserve loggers across migrations
  src/phoenix/db/alembic.ini
  src/phoenix/db/migrate.py
  src/phoenix/db/migrations/env.py
Labels: size:M

#2818 feat(persistence): fetch latency_ms percentiles using sql with dataloaders
  app/schema.graphql
  app/src/pages/project/ProjectPageHeader.tsx
  app/src/pages/project/__generated__/ProjectPageHeaderQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectPageHeader_stats.graphql.ts
  app/src/pages/project/__generated__/ProjectPageQuery.graphql.ts
  app/src/pages/projects/ProjectsPage.tsx
  app/src/pages/projects/__generated__/ProjectsPageProjectsFragment.graphql.ts
  app/src/pages/projects/__generated__/ProjectsPageProjectsQuery.graphql.ts
  app/src/pages/projects/__generated__/ProjectsPageQuery.graphql.ts
  pyproject.toml
  src/phoenix/db/bulk_inserter.py
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
  src/phoenix/db/models.py
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/latency_ms_quantile.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/app.py
  tests/server/api/types/conftest.py
Labels: size:L

#2836 feat: add manual instrumentation notebook
  tutorials/tracing/manual_instrumentation_tutorial.ipynb
Labels: size:XS

#2837 feat: ingest pyarrow span evals into sqlite
  src/phoenix/db/bulk_inserter.py
  src/phoenix/server/api/routers/evaluation_handler.py
  src/phoenix/server/app.py
Labels: size:M

#2844 fix(persistence): postgres timestamp insertion
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
  src/phoenix/db/models.py
Labels: size:S

#2849 feat(persistence): json binary for postgres
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
  src/phoenix/db/models.py
Labels: size:S

#2847 feat: ingest document evals
  src/phoenix/db/bulk_inserter.py
Labels: size:M

#2850 fix(persistence): importing assert_never from typing_extension
  src/phoenix/db/bulk_inserter.py
Labels: size:XS

#2852 feat: ingest trace evals
  src/phoenix/db/bulk_inserter.py
Labels: size:S

#2854 fix: improve error handling and logging for eval insertions
  src/phoenix/db/bulk_inserter.py
Labels: size:M

#2855 feat(persistence): ensure migrations run for TreadSession
  src/phoenix/config.py
  src/phoenix/db/engines.py
  src/phoenix/db/migrate.py
  src/phoenix/session/session.py
Labels: size:M

#2858 chore: Update Dataset references in notebooks
  examples/anthropic_evals_persona.ipynb
  examples/dolly-pythia-fine-tuned/create_data_with_dolly_and_pythia.ipynb
  examples/dolly-pythia-fine-tuned/dolly_vs_pythia.ipynb
  examples/taylor_swift_lyrics.ipynb
  tutorials/credit_card_fraud_tutorial.ipynb
  tutorials/find_cluster_export_and_explore_with_gpt.ipynb
  tutorials/image_classification_tutorial.ipynb
  tutorials/integrations/arize_anyscale_traces_and_embeddings.ipynb
  tutorials/llama_index_search_and_retrieval_tutorial.ipynb
  tutorials/llm_generative_gpt_4.ipynb
  tutorials/llm_ops_overview.ipynb
  tutorials/llm_summarization_tutorial.ipynb
  tutorials/milvus_llamaindex_search_and_retrieval_tutorial.ipynb
  tutorials/mistral/evaluate_rag--mistral.ipynb
  tutorials/ragas_retrieval_evals_tutorial.ipynb
  tutorials/sentiment_classification_tutorial.ipynb
Labels: size:M

#2859 chore: More `Inferences` cleanup
  README.md
  src/phoenix/inferences/inferences.py
  src/phoenix/server/main.py
  src/phoenix/session/session.py
Labels: size:M

#2862 chore: log level control over migrations
  src/phoenix/db/alembic.ini
  src/phoenix/db/migrate.py
  src/phoenix/db/migrations/env.py
  src/phoenix/server/main.py
  src/phoenix/settings.py
Labels: size:M

#2860 feat: make graphql api for span evaluations read from database
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/latency_ms_quantile.py
  src/phoenix/server/api/dataloaders/span_evaluations.py
  src/phoenix/server/api/types/Evaluation.py
  src/phoenix/server/api/types/Span.py
  src/phoenix/server/app.py
Labels: size:M

#2865 feat: graphql api for document evaluations
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/document_evaluations.py
  src/phoenix/server/api/types/Evaluation.py
  src/phoenix/server/api/types/Span.py
  src/phoenix/server/app.py
Labels: size:M

#2861 feat: Add SQL and Code Functionality Eval Templates
  packages/phoenix-evals/src/phoenix/evals/__init__.py
  packages/phoenix-evals/src/phoenix/evals/default_templates.py
  tutorials/evals/evals_sql_correctness_eval_with_custom_agent.ipynb
  tutorials/evals/evaluate_code_functionality_classifications.ipynb
Labels: size:L

#2876 ci: add dependabot to cla.yml
  .github/workflows/cla.yml
Labels: size:XS

#2873 fix: Restore `from_open_inference` method on `Inferences`
  src/phoenix/inferences/inferences.py
Labels: size:L

#2839 feat(persistence): get or delete projects using sql
  app/schema.graphql
  src/phoenix/core/traces.py
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
  src/phoenix/db/models.py
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/latency_ms_quantile.py
  src/phoenix/server/api/schema.py
  src/phoenix/server/api/types/Project.py
Labels: size:L

#2887 fix: include migration files
  pyproject.toml
  src/phoenix/db/migrations/__init__.py
  src/phoenix/db/migrations/env.py
Labels: size:XS

#2866 feat: Update API for OpenAPI compliance
  src/phoenix/server/api/routers/evaluation_handler.py
  src/phoenix/server/api/routers/span_handler.py
  src/phoenix/server/api/routers/trace_handler.py
  src/phoenix/server/api/routers/v1/__init__.py
  src/phoenix/server/api/routers/v1/evaluations.py
  src/phoenix/server/api/routers/v1/spans.py
  src/phoenix/server/api/routers/v1/traces.py
  src/phoenix/server/app.py
  src/phoenix/session/client.py
  tests/session/test_client.py
Labels: size:XL

#2888 feat: document evaluation aggregation
  src/phoenix/core/project.py
  src/phoenix/db/models.py
  src/phoenix/server/api/types/Project.py
Labels: size:M

#2867 feat: convert graphql api to pull trace evaluations from db
  app/schema.graphql
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/trace_evaluations.py
  src/phoenix/server/api/types/Evaluation.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/api/types/Trace.py
  src/phoenix/server/app.py
Labels: size:L

#2896 feat: project page metrics display last 7D
  app/src/components/nav/Navbar.tsx
  app/src/pages/projects/ProjectsPage.tsx
  app/src/pages/projects/__generated__/ProjectsPageProjectsFragment.graphql.ts
  app/src/pages/projects/__generated__/ProjectsPageProjectsQuery.graphql.ts
  app/src/pages/projects/__generated__/ProjectsPageQuery.graphql.ts
  cspell.json
Labels: size:XL

#2898 chore: remove filesystem based span_store
  pyproject.toml
  src/phoenix/server/api/routers/v1/traces.py
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  src/phoenix/session/session.py
  src/phoenix/storage/__init__.py
  src/phoenix/storage/span_store/__init__.py
  src/phoenix/storage/span_store/text_file.py
  src/phoenix/utilities/span_store.py
  tests/storage/spanstore/test_text_file_impl.py
Labels: size:L

#2897 feat: Add `log_traces` method that sends `TraceDataset` traces to Phoenix
  src/phoenix/session/client.py
  tests/session/test_client.py
Labels: size:L

#2903 fix(docs): add the remainder of the sentence to run_evals concurrency
  docs/api/evals.md
Labels: size:XS

#2900 feat: support for span evaluations to get evaluations endpoint
  src/phoenix/server/api/routers/v1/evaluations.py
  src/phoenix/server/app.py
Labels: size:M

#2905 fix(persistence): db race condition between spans and evals
  src/phoenix/db/bulk_inserter.py
Labels: size:S

#2902 docs: Add `log_traces` tutorial
  src/phoenix/server/api/routers/trace_handler.py
  src/phoenix/server/main.py
  src/phoenix/session/client.py
  src/phoenix/trace/otel.py
  src/phoenix/utilities/span_store.py
  tests/core/test_project.py
  tests/trace/test_otel.py
  tutorials/log_traces_to_phoenix.ipynb
Labels: size:L

#2907 feat: add a last N time range selector on project / projects pages
  app/src/Routes.tsx
  app/src/components/datetime/ConnectedLastNTimeRangePicker.tsx
  app/src/components/datetime/LastNTimeRangeContext.tsx
  app/src/components/datetime/LastNTimeRangePicker.tsx
  app/src/components/datetime/constants.ts
  app/src/components/datetime/index.tsx
  app/src/components/datetime/types.ts
  app/src/components/datetime/utils.ts
  app/src/components/markdown/MarkdownBlock.tsx
  app/src/components/markdown/MarkdownDisplayContext.tsx
  app/src/components/markdown/MarkdownModeRadioGroup.tsx
  app/src/components/markdown/index.tsx
  app/src/components/markdown/types.ts
  app/src/pages/ProjectsRoot.tsx
  app/src/pages/index.tsx
  app/src/pages/project/DocumentEvaluationSummary.tsx
  app/src/pages/project/EvaluationSummary.tsx
  app/src/pages/project/ProjectPage.tsx
  app/src/pages/project/ProjectPageHeader.tsx
  app/src/pages/project/RetrievalEvaluationLabel.tsx
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
  app/src/pages/project/__generated__/DocumentEvaluationSummaryQuery.graphql.ts
  app/src/pages/project/__generated__/DocumentEvaluationSummaryValueFragment.graphql.ts
  app/src/pages/project/__generated__/DocumentEvaluationSummaryValueQuery.graphql.ts
  app/src/pages/project/__generated__/EvaluationSummaryQuery.graphql.ts
  app/src/pages/project/__generated__/EvaluationSummaryValueFragment.graphql.ts
  app/src/pages/project/__generated__/EvaluationSummaryValueQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectPageHeaderQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectPageHeader_stats.graphql.ts
  app/src/pages/project/__generated__/ProjectPageQuery.graphql.ts
  app/src/pages/project/__generated__/SpansTableSpansQuery.graphql.ts
  app/src/pages/project/__generated__/SpansTable_spans.graphql.ts
  app/src/pages/project/__generated__/TracesTableQuery.graphql.ts
  app/src/pages/project/__generated__/TracesTable_spans.graphql.ts
  app/src/pages/projects/ProjectsPage.tsx
  app/src/pages/projects/index.tsx
  app/src/pages/trace/TracePage.tsx
Labels: size:XL

#2915 fix(persistence): postgres down migration and url support
  cspell.json
  src/phoenix/db/engines.py
  src/phoenix/db/migrations/env.py
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
  tests/db/test_engines.py
Labels: size:M

#2917 feat: Added support for default_headers for azure_openai.
  src/phoenix/experimental/evals/models/openai.py
  tests/experimental/evals/models/test_openai.py
Labels: size:M

#2924 chore: Standardize query params
  src/phoenix/server/api/routers/v1/evaluations.py
  src/phoenix/session/client.py
Labels: size:XS

#2920 feat: Update eval summaries to use persistence
  src/phoenix/server/api/types/EvaluationSummary.py
  src/phoenix/server/api/types/Project.py
Labels: size:L

#2928 feat: Add user frustration eval
  packages/phoenix-evals/src/phoenix/evals/__init__.py
  packages/phoenix-evals/src/phoenix/evals/default_templates.py
  tutorials/evals/evaluate_user_frustration_classifications.ipynb
Labels: size:M

#2851 feat(persistence): make launch_app runnable on tmp directory
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  src/phoenix/services.py
  src/phoenix/session/client.py
  src/phoenix/session/session.py
Labels: size:M

#2944 chore: promote PHOENIX_SQL_DATABASE_URL to a first-class env var
  src/phoenix/config.py
  src/phoenix/db/__init__.py
  src/phoenix/db/engines.py
  src/phoenix/server/main.py
Labels: size:M

#2945 feat!: Remove `experimental` module
  examples/using_llamaindex_with_huggingface_models.ipynb
  integration-tests/evals/test_multiple_classify_calls_anthropic.py
  integration-tests/evals/test_multiple_classify_calls_openai.py
  integration-tests/evals/test_multiple_classify_calls_vertex.py
  scripts/data/build_llama_index_rag_data.py
  scripts/rag/llama_index_w_evals_and_qa.py
  scripts/rag/llamaindex_retrieval_chunk_eval.ipynb
  src/phoenix/experimental/__init__.py
  src/phoenix/experimental/evals/__init__.py
  src/phoenix/experimental/evals/evaluators.py
  src/phoenix/experimental/evals/functions/__init__.py
  src/phoenix/experimental/evals/functions/classify.py
  src/phoenix/experimental/evals/functions/executor.py
  src/phoenix/experimental/evals/functions/generate.py
  src/phoenix/experimental/evals/functions/processing.py
  src/phoenix/experimental/evals/models/__init__.py
  src/phoenix/experimental/evals/models/anthropic.py
  src/phoenix/experimental/evals/models/base.py
  src/phoenix/experimental/evals/models/bedrock.py
  src/phoenix/experimental/evals/models/litellm.py
  src/phoenix/experimental/evals/models/openai.py
  src/phoenix/experimental/evals/models/rate_limiters.py
  src/phoenix/experimental/evals/models/vertex.py
  src/phoenix/experimental/evals/models/vertexai.py
  src/phoenix/experimental/evals/retrievals.py
  src/phoenix/experimental/evals/templates/__init__.py
  src/phoenix/experimental/evals/templates/default_templates.py
  src/phoenix/experimental/evals/templates/template.py
  src/phoenix/experimental/evals/utils/__init__.py
  src/phoenix/experimental/evals/utils/threads.py
  tests/experimental/evals/conftest.py
  tests/experimental/evals/functions/test_classify.py
  tests/experimental/evals/functions/test_executor.py
  tests/experimental/evals/functions/test_generate.py
  tests/experimental/evals/models/test_openai.py
  tests/experimental/evals/models/test_rate_limiters.py
  tests/experimental/evals/templates/test_template.py
  tests/experimental/evals/test_evaluators.py
  tests/experimental/evals/test_retrievals.py
  tests/experimental/evals/test_utils.py
  tutorials/integrations/arize_anyscale_traces_and_embeddings.ipynb
  tutorials/internal/evaluators.ipynb
  tutorials/internal/langchain_retrieval_qa_with_sources_chain_tracing_tutorial.ipynb
  tutorials/internal/logging.ipynb
  tutorials/internal/long_context_summary_evals.ipynb
  tutorials/internal/span_query_language.ipynb
  tutorials/internal/trace_eval_ingestion_testing.ipynb
  tutorials/llama_index_search_and_retrieval_tutorial.ipynb
  tutorials/llm_ops_overview.ipynb
  tutorials/milvus_llamaindex_search_and_retrieval_tutorial.ipynb
Labels: size:XXL

#2946 fix(persistence): typo in trace annotation table name
  src/phoenix/server/api/types/Project.py
Labels: size:XS

#2948 fix: ensure recent version of opentelemetry-proto is used
  pyproject.toml
Labels: size:XS

#2949 ci: change to macos-12 because macos-latest is arm64 which not compatible with python 3.8
  .github/workflows/python-CI.yml
Labels: size:XS

#2952 chore: merge main into sql branch
  .github/workflows/cla.yml
  .github/workflows/python-CI.yml
  .release-please-manifest.json
  CHANGELOG.md
  docs/api/evals.md
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
  packages/phoenix-evals/src/phoenix/evals/__init__.py
  packages/phoenix-evals/src/phoenix/evals/default_templates.py
  pyproject.toml
  src/phoenix/experimental/evals/models/openai.py
  src/phoenix/inferences/inferences.py
  src/phoenix/server/api/routers/trace_handler.py
  src/phoenix/server/api/routers/v1/traces.py
  src/phoenix/server/main.py
  src/phoenix/session/client.py
  src/phoenix/trace/otel.py
  src/phoenix/utilities/span_store.py
  src/phoenix/version.py
  tests/core/test_project.py
  tests/session/test_client.py
  tests/trace/test_otel.py
  tutorials/evals/evals_sql_correctness_eval_with_custom_agent.ipynb
  tutorials/evals/evaluate_code_functionality_classifications.ipynb
  tutorials/evals/evaluate_user_frustration_classifications.ipynb
  tutorials/integrations/arize_anyscale_traces_and_embeddings.ipynb
  tutorials/log_traces_to_phoenix.ipynb
Labels: size:XL

#2954 chore: update ruff and mypy
  .pre-commit-config.yaml
  dev-requirements.txt
  pyproject.toml
  src/phoenix/experimental/evals/functions/classify.py
Labels: size:S

#2955 chore: merge main into sql branch
  .pre-commit-config.yaml
  dev-requirements.txt
  pyproject.toml
Labels: size:S

#2947 feat(persistence): use sqlean v3.45.1 as sqlite engine
  pyproject.toml
  src/phoenix/db/engines.py
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
  src/phoenix/db/models.py
  src/phoenix/trace/dsl/filter.py
  tests/trace/dsl/conftest.py
  tests/trace/dsl/test_filter.py
  tests/trace/dsl/test_query.py
Labels: size:L

#2956 feat: add gradient start/end to projects table
  app/schema.graphql
  app/src/pages/projects/ProjectsPage.tsx
  app/src/pages/projects/__generated__/ProjectsPageProjectsFragment.graphql.ts
  app/src/pages/projects/__generated__/ProjectsPageProjectsQuery.graphql.ts
  app/src/pages/projects/__generated__/ProjectsPageQuery.graphql.ts
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
  src/phoenix/db/models.py
  src/phoenix/server/api/schema.py
  src/phoenix/server/api/types/Project.py
Labels: size:L

#2958 fix: disable client-side sorting on trace/span tables
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
Labels: size:XS

#2959 fix: cartesian product in sql join
  src/phoenix/server/api/types/Project.py
Labels: size:XS

#2960 feat: fetch document retrieval metrics using SQL
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/api/types/Span.py
  src/phoenix/server/api/types/Trace.py
Labels: size:M

#2962 fix: forbid blank or empty evaluation names
  src/phoenix/exceptions.py
  src/phoenix/server/api/routers/v1/evaluations.py
  src/phoenix/trace/span_evaluations.py
Labels: size:S

#2819 feat(persistence): fetch streaming_last_updated_at
  src/phoenix/db/bulk_inserter.py
  src/phoenix/server/api/context.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/app.py
Labels: size:M

#2964 feat(persistence): fetch evaluation names
  src/phoenix/server/api/types/Project.py
  src/phoenix/trace/dsl/filter.py
  src/phoenix/trace/dsl/query.py
Labels: size:M

#2923 feat: span filtering by span evaluations
  integration-tests/eval_query_testing.ipynb
  src/phoenix/trace/dsl/filter.py
  tests/trace/dsl/test_filter.py
  tests/trace/test_trace_dataset.py
Labels: size:XL

#2966 chore: delete empty file
  src/phoenix/server/api/routers/trace_handler.py
Labels: size:XS

#2965 chore: delete legacy `Traces` class
  src/phoenix/core/project.py
  src/phoenix/core/traces.py
  src/phoenix/server/api/context.py
  src/phoenix/server/api/input_types/SpanSort.py
  src/phoenix/server/api/routers/v1/evaluations.py
  src/phoenix/server/api/routers/v1/traces.py
  src/phoenix/server/api/schema.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  src/phoenix/session/session.py
  tests/core/test_project.py
  tests/server/api/input_types/test_SpanSort.py
Labels: size:XXL

#2967 fix: typo in SpanAnnotation
  src/phoenix/server/api/types/Project.py
Labels: size:XS

#2968 chore: remove comment
  src/phoenix/trace/dsl/filter.py
Labels: size:S

#2972 refactor: miscellaneous clean up
  src/phoenix/db/engines.py
Labels: size:S

#2971 refactor: rename document index to document position in document_annotations table
  src/phoenix/db/bulk_inserter.py
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
  src/phoenix/db/models.py
  src/phoenix/server/api/routers/v1/evaluations.py
  src/phoenix/server/api/types/Evaluation.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/api/types/Span.py
Labels: size:S

#2976 feat(persistence): clear project
  app/schema.graphql
  cspell.json
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
  src/phoenix/db/models.py
  src/phoenix/server/api/schema.py
Labels: size:S

#2977 feat(persistence): add support for sorting by eval scores and labels
  src/phoenix/server/api/input_types/SpanSort.py
  src/phoenix/server/api/types/Project.py
Labels: size:M

#2973 test: Add postgres testing
  .github/workflows/python-CI.yml
  DEVELOPMENT.md
  pyproject.toml
  tests/conftest.py
  tests/db/test_models.py
  tests/trace/dsl/conftest.py
  tests/trace/dsl/test_filter.py
  tests/trace/dsl/test_helpers.py
  tests/trace/dsl/test_query.py
Labels: size:XL

#2919 feat: add bedrock claude tracing tutorial
  tutorials/tracing/bedrock_claude_tracing_tutorial.ipynb
Labels: size:XXL

#2978 feat(persistence): dataloader for document retrieval metrics
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/document_retrieval_metrics.py
  src/phoenix/server/api/types/Span.py
  src/phoenix/server/app.py
Labels: size:L

#2986 test: Flip postgres testing flag
  .github/workflows/python-CI.yml
  DEVELOPMENT.md
  tests/conftest.py
Labels: size:S

#2980 feat(persistence): dataloader for span descendants
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/span_descendants.py
  src/phoenix/server/api/types/Span.py
  src/phoenix/server/app.py
Labels: size:M

#2987 chore: readme for ast
  src/phoenix/trace/dsl/README.md
Labels: size:L

#2990 feat: add opentelemetry trace instrumentation for Phoenix server
  pyproject.toml
  src/phoenix/config.py
  src/phoenix/server/api/schema.py
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  src/phoenix/server/telemetry.py
Labels: size:M

#2991 chore: delete duplicate readme
  src/phoenix/db/migrations/README
Labels: size:XS

#2992 refactor: move readme
  src/phoenix/db/README.md
Labels: size:XS

#2988 feat(persistence): clear traces UI
  app/src/pages/projects/ProjectActionMenu.tsx
  app/src/pages/projects/ProjectsPage.tsx
  app/src/pages/projects/__generated__/ProjectActionMenuClearMutation.graphql.ts
  app/src/pages/projects/__generated__/ProjectActionMenuDeleteMutation.graphql.ts
Labels: size:L

#2993 chore: reset fixture span ids and timestamps
  src/phoenix/server/main.py
  src/phoenix/trace/fixtures.py
Labels: size:L

#2994 fix: Propagate migration errors and show an informative message
  src/phoenix/db/migrate.py
  src/phoenix/exceptions.py
  src/phoenix/server/app.py
Labels: size:M

#2995 feat!: Remove Datasets
  src/phoenix/__init__.py
  src/phoenix/datasets/__init__.py
  src/phoenix/datasets/dataset.py
  src/phoenix/datasets/fixtures.py
  src/phoenix/datasets/schema.py
Labels: size:L

#2999 chore: Format notebooks
  tutorials/tracing/bedrock_claude_tracing_tutorial.ipynb
Labels: size:XXL

#2998 fix: eliminate interference on global tracer provider
  pyproject.toml
  src/phoenix/config.py
  src/phoenix/server/api/schema.py
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  src/phoenix/server/telemetry.py
Labels: size:M

#3000 docs: Add migration guide for `Dataset` -> `Inferences`
  MIGRATION.md
Labels: size:S

#3009 fix: span event to dict conversion
  src/phoenix/db/bulk_inserter.py
  src/phoenix/server/api/types/Span.py
  src/phoenix/trace/schemas.py
Labels: size:XS

#3001 fix: normalize telemetry url before setup
  src/phoenix/server/telemetry.py
  tests/server/test_telemetry.py
Labels: size:M

#3010 feat: allow Prometheus to be configured via an environment variable
  Dockerfile
  src/phoenix/config.py
  src/phoenix/server/main.py
Labels: size:M

#2989 chore(persistence): improve naming for indexes and constraints
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
  src/phoenix/db/models.py
Labels: size:S

#3012 chore: remove card padding
  app/src/pages/trace/TracePage.tsx
Labels: size:XS

#3013 fix: span and trace evaluation summaries
  src/phoenix/server/api/types/Project.py
Labels: size:M

#3015 chore: otel resource name
  pyproject.toml
  src/phoenix/server/telemetry.py
Labels: size:XS

#3014 chore: script to generate spans and evaluations
  scripts/data/generate_traces.py
  src/phoenix/server/api/routers/v1/evaluations.py
Labels: size:L

#3031 docs: remove experimental from docs
  docs/.gitbook/assets/online_evals_periodic_eval_chron (1).py
  docs/.gitbook/assets/online_evals_periodic_eval_chron.py
  docs/evaluation/concepts-evals/building-your-own-evals.md
  docs/evaluation/concepts-evals/evals-with-explanations.md
  docs/evaluation/evaluation-models.md
  docs/evaluation/how-to-evals/running-pre-tested-evals/ai-vs-human-groundtruth.md
  docs/evaluation/how-to-evals/running-pre-tested-evals/code-generation-eval.md
  docs/evaluation/how-to-evals/running-pre-tested-evals/hallucinations.md
  docs/evaluation/how-to-evals/running-pre-tested-evals/q-and-a-on-retrieved-data.md
  docs/evaluation/how-to-evals/running-pre-tested-evals/reference-link-evals.md
  docs/evaluation/how-to-evals/running-pre-tested-evals/retrieval-rag-relevance.md
  docs/evaluation/how-to-evals/running-pre-tested-evals/summarization-eval.md
  docs/evaluation/how-to-evals/running-pre-tested-evals/toxicity.md
  docs/quickstart/evals.md
  docs/retrieval/quickstart-retrieval.md
  docs/use-cases/rag-evaluation.md
Labels: size:L

#3026 feat: add default limit to `/v1/spans` and corresponding client methods
  src/phoenix/server/api/routers/v1/evaluations.py
  src/phoenix/server/api/routers/v1/spans.py
  src/phoenix/session/client.py
  src/phoenix/session/data_extractor.py
  src/phoenix/session/session.py
  src/phoenix/trace/dsl/query.py
  tests/trace/dsl/test_query.py
Labels: size:M

#3035 docs(development): make it explicit that you need to run pnpm build
  DEVELOPMENT.md
Labels: size:S

#3036 fix: Cannot start prometheus
  src/phoenix/server/main.py
Labels: size:XS

#3037 fix: Enable listening on IPv6
  src/phoenix/server/main.py
  src/phoenix/server/prometheus.py
Labels: size:XS

#3041 feat: openapi ui for api exploration
  src/phoenix/server/app.py
  src/phoenix/server/openapi/__init__.py
  src/phoenix/server/openapi/docs.py
Labels: size:L
