Repository Arize-ai/phoenix, pull requests merged in 2024-05, with the labels that each got.

#3047 fix: Dockerfile launches Phoenix that listens on IPv6
  Dockerfile
Labels: size:XS

#3048 refactor: hide embedding vector
  src/phoenix/server/api/types/Span.py
Labels: size:S

#3051 fix: Ensure uvicorn listens on all interfaces
  src/phoenix/server/main.py
Labels: size:XS

#3052 refactor: make bulk inserter wait longer
  src/phoenix/db/bulk_inserter.py
Labels: size:XS

#3054 refactor: miscellaneous clean up
  src/phoenix/server/api/types/Project.py
  src/phoenix/trace/dsl/filter.py
Labels: size:S

#3055 chore: Instrument GRPC
  src/phoenix/server/grpc_server.py
  src/phoenix/server/prometheus.py
Labels: size:S

#3053 chore: default spans limit
  src/phoenix/server/api/types/Project.py
Labels: size:XS

#3056 feat: grpc interceptor for prometheus
  pyproject.toml
  src/phoenix/server/app.py
  src/phoenix/server/grpc_server.py
  src/phoenix/server/prometheus.py
Labels: size:M

#3059 chore: Add prometheus metrics to bulk inserter
  pyproject.toml
  src/phoenix/db/bulk_inserter.py
  src/phoenix/server/main.py
  src/phoenix/server/prometheus.py
Labels: size:L

#3061 feat: Support basic auth
  app/src/RelayEnvironment.ts
  src/phoenix/server/main.py
Labels: size:S

#3064 chore: `num_docs` shouldn't be randomized again in `_gen_attributes`
  scripts/data/generate_traces.py
Labels: size:XS

#3065 fix: remove broken non-asyncio prometheus grpc server interceptor
  src/phoenix/server/grpc_server.py
Labels: size:S

#3066 fix: prometheus for bulkloader
  pyproject.toml
  src/phoenix/db/bulk_inserter.py
  src/phoenix/server/app.py
Labels: size:L

#3069 fix: close delete modal on delete
  app/src/pages/projects/ProjectActionMenu.tsx
Labels: size:XS

#3050 refactor: cache for summary dataloaders (sqlite only)
  pyproject.toml
  src/phoenix/db/bulk_inserter.py
  src/phoenix/db/helpers.py
  src/phoenix/db/insertion/__init__.py
  src/phoenix/db/insertion/evaluation.py
  src/phoenix/db/insertion/span.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/cache/__init__.py
  src/phoenix/server/api/dataloaders/cache/two_tier_cache.py
  src/phoenix/server/api/dataloaders/document_evaluation_summaries.py
  src/phoenix/server/api/dataloaders/evaluation_summaries.py
  src/phoenix/server/api/dataloaders/latency_ms_quantile.py
  src/phoenix/server/api/dataloaders/min_start_or_max_end_times.py
  src/phoenix/server/api/dataloaders/record_counts.py
  src/phoenix/server/api/dataloaders/token_counts.py
  src/phoenix/server/api/types/DocumentEvaluationSummary.py
  src/phoenix/server/app.py
  src/phoenix/server/prometheus.py
Labels: size:XL

#3079 fix: round down time points to facilitate caching
  app/src/components/datetime/utils.ts
Labels: size:S

#3080 refactor: async stream for spans under trace
  src/phoenix/server/api/types/Trace.py
Labels: size:S

#3082 feat: Add indexes on Annotation tables
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
  src/phoenix/db/models.py
Labels: size:S

#3081 fix: cartesian products in get_evaluations
  src/phoenix/server/api/routers/v1/evaluations.py
Labels: size:M

#3083 refactor: run in threadpool in traces endpoint
  src/phoenix/server/api/routers/v1/traces.py
Labels: size:XS

#3084 chore: remove unused code
  src/phoenix/config.py
Labels: size:S

#3085 fix(evals): incorrect wording in hallucinations
  packages/phoenix-evals/src/phoenix/evals/default_templates.py
  tutorials/evals/evaluate_hallucination_classifications.ipynb
Labels: size:S

#3089 refactor: add `uvloop` to container dependencies
  pyproject.toml
Labels: size:XS

#3088 fix: normalize datetime for phoenix client
  src/phoenix/datetime_utils.py
  src/phoenix/db/models.py
  src/phoenix/server/api/routers/v1/spans.py
  src/phoenix/session/client.py
Labels: size:M

#3096 chore: remove unused dependency `sortedcontainers`
  pyproject.toml
Labels: size:XS

#3097 refactor: transmit truncated strings for input and output values in table displays
  app/schema.graphql
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
  app/src/pages/project/__generated__/ProjectPageQuery.graphql.ts
  app/src/pages/project/__generated__/SpansTableSpansQuery.graphql.ts
  app/src/pages/project/__generated__/SpansTable_spans.graphql.ts
  app/src/pages/project/__generated__/TracesTableQuery.graphql.ts
  app/src/pages/project/__generated__/TracesTable_spans.graphql.ts
  src/phoenix/server/api/types/Span.py
Labels: size:L

#3095 refactor: graphql node interface for trace and spans
  app/schema.graphql
  src/phoenix/server/api/schema.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/api/types/Span.py
  src/phoenix/server/api/types/Trace.py
Labels: size:M

#3093 refactor: use TTL for project cache for dataloaders
  src/phoenix/server/api/dataloaders/document_evaluation_summaries.py
  src/phoenix/server/api/dataloaders/evaluation_summaries.py
  src/phoenix/server/api/dataloaders/latency_ms_quantile.py
  src/phoenix/server/api/dataloaders/record_counts.py
  src/phoenix/server/api/dataloaders/token_counts.py
Labels: size:M

#3098 feat: Add indexes on spans table
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
  src/phoenix/db/models.py
Labels: size:S

#3087 refactor: refresh page on a per-project basis
  src/phoenix/db/bulk_inserter.py
  src/phoenix/server/api/context.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/app.py
Labels: size:M

#3100 fix: run docker as nonroot user
  Dockerfile
Labels: size:XS

#3103 chore: merge main into sql
  .release-please-manifest.json
  CHANGELOG.md
  DEVELOPMENT.md
  Dockerfile
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
  packages/phoenix-evals/src/phoenix/evals/default_templates.py
  src/phoenix/version.py
  tutorials/evals/evaluate_hallucination_classifications.ipynb
  tutorials/tracing/bedrock_claude_tracing_tutorial.ipynb
Labels: size:L

#3099 chore: add docker-compose.yml with postgres
  Dockerfile
  docker-compose.yml
Labels: size:M

#3104 chore: adds kustomize deployment
  kustomize/README
  kustomize/backends/postgres/kustomization.yaml
  kustomize/backends/postgres/patches.yaml
  kustomize/backends/postgres/postgres.yaml
  kustomize/base/kustomization.yaml
  kustomize/base/phoenix.yaml
Labels: size:L

#3105 fix: disable grpc when readonly
  src/phoenix/server/app.py
  src/phoenix/server/grpc_server.py
Labels: size:XS

#3110 chore: clear todo tags
  src/phoenix/db/engines.py
  src/phoenix/db/insertion/span.py
  src/phoenix/db/models.py
  src/phoenix/server/api/types/Project.py
Labels: size:S

#3112 refactor: Explicitly configure transaction context and ensure rollbacks on failure
  src/phoenix/db/migrations/env.py
Labels: size:S

#3113 fix: Invalidate cache on project reset
  src/phoenix/db/insertion/span.py
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/schema.py
  src/phoenix/server/app.py
  tests/server/api/types/conftest.py
Labels: size:S

#3046 feat: support pagination on spans resolver
  app/schema.graphql
  integration-tests/pagination_queries.ipynb
  integration-tests/pagination_query_testing.ipynb
  src/phoenix/server/api/input_types/SpanSort.py
  src/phoenix/server/api/schema.py
  src/phoenix/server/api/types/Model.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/api/types/Trace.py
  src/phoenix/server/api/types/pagination.py
  tests/server/api/input_types/test_SpanSort.py
  tests/server/api/types/test_pagination.py
  tests/trace/dsl/test_filter.py
Labels: size:XXL

#3115 fix: commit insert into alembic_version at the end of migration
  src/phoenix/db/migrations/env.py
Labels: size:XS

#3121 refactor: simplify dataloader cache invalidation
  src/phoenix/db/bulk_inserter.py
  src/phoenix/db/insertion/evaluation.py
  src/phoenix/db/insertion/span.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/cache/two_tier_cache.py
  src/phoenix/server/api/dataloaders/document_evaluation_summaries.py
  src/phoenix/server/api/dataloaders/evaluation_summaries.py
  src/phoenix/server/api/dataloaders/latency_ms_quantile.py
  src/phoenix/server/api/dataloaders/min_start_or_max_end_times.py
  src/phoenix/server/api/dataloaders/record_counts.py
  src/phoenix/server/api/dataloaders/token_counts.py
  src/phoenix/server/api/schema.py
Labels: size:L

#3116 refactor: insertion on conflict do something (or nothing)
  src/phoenix/db/insertion/evaluation.py
  src/phoenix/db/insertion/helpers.py
  src/phoenix/db/insertion/span.py
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
  src/phoenix/db/models.py
Labels: size:L

#3123 chore: Use summaries not hisograms for Prometheus metrics
  src/phoenix/server/prometheus.py
Labels: size:XS

#3124 fix: backward compatible truthiness in from_dict parsing for SpanQuery
  src/phoenix/trace/dsl/query.py
Labels: size:XS

#3126 chore: Rename metrics
  src/phoenix/server/prometheus.py
Labels: size:XS

#3125 fix: check payload for legacy project_name
  src/phoenix/server/api/routers/v1/spans.py
Labels: size:XS

#3129 ci: bootstrap release please for release
  release-please-config.json
Labels: size:XS

#3133 ci: reset release please
  .github/workflows/python-CI.yml
  .release-please-manifest.json
  release-please-config.json
Labels: size:S

#3136 chore: Revert "ci: reset release please"
  .github/workflows/python-CI.yml
  .release-please-manifest.json
  release-please-config.json
Labels: size:S

#3141 chore: don't look back on releases
  release-please-config.json
Labels: size:XS

#3146 refactor: add parentheses
  src/phoenix/db/insertion/helpers.py
Labels: size:XS

#3148 docs: update kustomize k8s manifests
  kustomize/README
  kustomize/base/phoenix.yaml
Labels: size:L

#3147 fix: coerce `input.value` to string at ingestion
  src/phoenix/trace/otel.py
Labels: size:S

#3150 refactor: add `.md` file extension to README
  kustomize/README.md
Labels: size:XS

#3151 fix: Bulk inserter begins first insert immediately
  src/phoenix/db/bulk_inserter.py
Labels: size:S

#3170 fix: unflatten attributes when loading spans from `trace_dataset`
  src/phoenix/trace/trace_dataset.py
Labels: size:XS

#3169 feat: add dataset-related tables
  src/phoenix/db/migrations/types.py
  src/phoenix/db/migrations/versions/10460e46d750_datasets.py
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
  src/phoenix/db/models.py
Labels: size:L

#3183 feat(datasets): dataset upload endpoint (plus fixtures)
  pyproject.toml
  scripts/fixtures/datasets/ChatRAG-Bench.ipynb
  src/phoenix/db/bulk_inserter.py
  src/phoenix/db/insertion/dataset.py
  src/phoenix/db/insertion/evaluation.py
  src/phoenix/db/insertion/helpers.py
  src/phoenix/server/api/routers/v1/__init__.py
  src/phoenix/server/api/routers/v1/datasets.py
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  src/phoenix/session/client.py
  src/phoenix/trace/exporter.py
  src/phoenix/trace/fixtures.py
  tests/db/insertion/test_dataset.py
  tests/session/test_client.py
Labels: size:XXL

#3190 PHOENIX_WORKING_DIR default value documentation
  docs/deployment/persistence.md
  docs/setup/configuration.md
Labels: size:XS

#3193 docs: bump base image in kustomize
  kustomize/base/phoenix.yaml
Labels: size:XS

#3184 refactor: use strawberry relay types
  app/schema.graphql
  src/phoenix/server/api/schema.py
  src/phoenix/server/api/types/Dimension.py
  src/phoenix/server/api/types/EmbeddingDimension.py
  src/phoenix/server/api/types/Model.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/api/types/Span.py
  src/phoenix/server/api/types/Trace.py
  src/phoenix/server/api/types/UMAPPoints.py
  src/phoenix/server/api/types/node.py
  src/phoenix/server/api/types/pagination.py
  tests/server/api/types/test_node.py
Labels: size:L

#3192 feat(datasets): datasets gql node and connection
  app/schema.graphql
  app/src/store/pointCloudStore.ts
  src/phoenix/server/api/schema.py
  src/phoenix/server/api/types/Dataset.py
Labels: size:M

#3195 fix: evaluators no longer have incorrect type hints
  packages/phoenix-evals/src/phoenix/evals/evaluators.py
  packages/phoenix-evals/tests/phoenix/evals/test_evaluators.py
Labels: size:L

#3172 feat(datasets): datasets page
  app/package.json
  app/pnpm-lock.yaml
  app/src/Routes.tsx
  app/src/components/nav/Navbar.tsx
  app/src/pages/Layout.tsx
  app/src/pages/dataset/DatasetPage.tsx
  app/src/pages/dataset/__generated__/datasetLoaderQuery.graphql.ts
  app/src/pages/dataset/datasetLoader.ts
  app/src/pages/dataset/index.tsx
  app/src/pages/datasets/DatasetsPage.tsx
  app/src/pages/datasets/DatasetsTable.tsx
  app/src/pages/datasets/__generated__/DatasetsPageQuery.graphql.ts
  app/src/pages/datasets/__generated__/DatasetsTableDatasetsQuery.graphql.ts
  app/src/pages/datasets/__generated__/DatasetsTable_datasets.graphql.ts
  app/src/pages/datasets/__generated__/datasetsLoaderQuery.graphql.ts
  app/src/pages/datasets/index.tsx
  app/src/pages/index.tsx
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/projectLoader.ts
  cspell.json
  package.json
  pnpm-lock.yaml
Labels: size:XXL

#3203 feat(datasets): gql dataset create
  app/schema.graphql
  src/phoenix/server/api/schema.py
  src/phoenix/server/api/types/Dataset.py
Labels: size:M

#3204 feat(datasets): expose the API playgrounds
  app/src/Routes.tsx
  app/src/pages/Layout.tsx
  app/src/pages/apis/APIsPage.tsx
  app/src/pages/apis/index.tsx
  app/src/pages/index.tsx
Labels: size:M

#3213 fix(datasets): api spec for upload endpoint
  src/phoenix/server/api/routers/v1/datasets.py
Labels: size:XS

#3197 feat: Implement `GET /datasets/id` and `GET /datasets`
  .github/workflows/python-CI.yml
  src/phoenix/db/insertion/dataset.py
  src/phoenix/db/models.py
  src/phoenix/server/api/routers/v1/__init__.py
  src/phoenix/server/api/routers/v1/datasets.py
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  src/phoenix/session/session.py
  tests/conftest.py
  tests/db/insertion/test_dataset.py
  tests/db/test_models.py
  tests/server/api/conftest.py
  tests/server/api/routers/v1/test_datasets.py
Labels: size:XL

#3217 feat(datasets): create dataset UI
  app/src/pages/datasets/CreateDatasetForm.tsx
  app/src/pages/datasets/DatasetsPage.tsx
  app/src/pages/datasets/__generated__/CreateDatasetFormMutation.graphql.ts
Labels: size:L

#3222 feat(dataset): gql dataset versions connection
  app/schema.graphql
  src/phoenix/server/api/types/Dataset.py
  src/phoenix/server/api/types/DatasetVersion.py
Labels: size:M

#3211 feat: Added support for default_headers for azure_openai.
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
  packages/phoenix-evals/tests/phoenix/evals/models/test_openai.py
Labels: size:S

#3225 docs: Clean up dataset references from docs
  docs/SUMMARY.md
  docs/api/client.md
  docs/api/inference-and-schema.md
  docs/api/session.md
  docs/environments.md
  docs/evaluation/concepts-evals/building-your-own-evals.md
  docs/evaluation/concepts-evals/evaluation.md
  docs/evaluation/concepts-evals/llm-as-a-judge.md
  docs/evaluation/how-to-evals/running-pre-tested-evals/README.md
  docs/how-to/define-your-schema/README.md
  docs/how-to/manage-the-app.md
  docs/inferences/how-to-inferences-1/use-example-inferences.md
  docs/integrations/bring-production-data-to-notebook-for-eda-or-retraining.md
  docs/quickstart/llm-traces.md
  docs/quickstart/phoenix-inferences/README.md
  docs/setup/configuration.md
  docs/tracing/how-to-tracing/llm-evaluations.md
  docs/use-cases/rag-evaluation.md
  docs/user-guide.md
Labels: size:M

#3186 feat: Add ASGI root path parameter to Phoenix server
  src/phoenix/config.py
  src/phoenix/server/main.py
  src/phoenix/session/client.py
  src/phoenix/session/evaluation.py
  src/phoenix/trace/exporter.py
  tests/session/test_client.py
  tests/trace/test_exporter.py
Labels: size:M

#3232 fix: resolve rounding issue in postgres
  src/phoenix/db/models.py
Labels: size:XS

#3235 chore: update kustomize
  kustomize/base/phoenix.yaml
Labels: size:XS

#3231 docs: new updated readme
  README.md
Labels: size:L

#3205 feat: add graphql resolver for adding spans to datasets
  app/schema.graphql
  src/phoenix/server/api/datasets_helpers.py
  src/phoenix/server/api/schema.py
  tests/server/api/test_dataset_helpers.py
  tests/server/api/test_schema.py
Labels: size:XL

#3239 refactor(datasets): break contents of schema into query and mutation sub-modules
  app/schema.graphql
  src/phoenix/server/api/datasets_helpers.py
  src/phoenix/server/api/input_types/AddSpansToDatasetInput.py
  src/phoenix/server/api/mutations/__init__.py
  src/phoenix/server/api/mutations/dataset_mutations.py
  src/phoenix/server/api/mutations/export_events_mutations.py
  src/phoenix/server/api/mutations/project_mutations.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/schema.py
  src/phoenix/server/api/types/AddSpansToDatasetPayload.py
  tests/server/api/mutations/test_dataset_mutations.py
  tests/server/api/test_schema.py
Labels: size:XXL

#3244 test: fix timestamp issue causing tests to fail in uv
  tests/metrics/test_timeseries.py
Labels: size:L

#3242 refactor: use input and output types for create datasets mutation
  app/schema.graphql
  app/src/pages/datasets/CreateDatasetForm.tsx
  app/src/pages/datasets/DatasetsPage.tsx
  app/src/pages/datasets/__generated__/CreateDatasetFormMutation.graphql.ts
  src/phoenix/server/api/input_types/CreateDatasetInput.py
  src/phoenix/server/api/mutations/dataset_mutations.py
  src/phoenix/server/api/types/CreateDatasetPayload.py
Labels: size:L

#3238 feat: gql resolver for dataset examples
  app/schema.graphql
  src/phoenix/server/api/types/Dataset.py
  src/phoenix/server/api/types/DatasetExample.py
  tests/server/api/types/test_Dataset.py
Labels: size:L

#3243 test: improve test case for add span to dataset
  tests/server/api/mutations/test_dataset_mutations.py
Labels: size:L

#3248 fix: join on `trace_id` in `get_qa_with_reference`
  src/phoenix/trace/dsl/helpers.py
Labels: size:M

#3245 test: pagination
  tests/server/api/types/test_Project.py
Labels: size:XXL

#3256 fix: clarify error message for missing azure api-key
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
Labels: size:XS

#3250 feat(datasets): download dataset as CSV text file
  src/phoenix/server/api/routers/v1/__init__.py
  src/phoenix/server/api/routers/v1/datasets.py
  src/phoenix/session/client.py
  src/phoenix/trace/exporter.py
  src/phoenix/trace/fixtures.py
  tests/server/api/conftest.py
  tests/server/api/routers/v1/test_datasets.py
  tests/session/test_client.py
Labels: size:L

#3251 fix: Bypass signal handler if running in a thread
  packages/phoenix-evals/src/phoenix/evals/executors.py
  packages/phoenix-evals/tests/phoenix/evals/functions/test_executor.py
Labels: size:L

#3255 ci: docker image build in GH actions
  .github/workflows/docker-build-nightly.yml
  .github/workflows/docker-build-release.yml
  Dockerfile
Labels: size:L

#3260 fix: Correctly use format strings
  .github/workflows/docker-build-nightly.yml
  .github/workflows/docker-build-release.yml
Labels: size:S

#3261 ci: Use environment variables to set base image for clarity
  .github/workflows/docker-build-nightly.yml
  .github/workflows/docker-build-release.yml
Labels: size:M

#3262 ci: Put arg at top of Dockerfile
  Dockerfile
Labels: size:XS

#3263 ci: Remove attestation step
  .github/workflows/docker-build-nightly.yml
  .github/workflows/docker-build-release.yml
Labels: size:S

#3267 fix: need to check ".get()" because attribute may not be a dict
  src/phoenix/trace/attributes.py
  tests/trace/test_attributes.py
Labels: size:M

#3266 feat(datasets): gql for adding examples
  app/schema.graphql
  app/src/components/dataset/__generated__/CreateDatasetFormMutation.graphql.ts
  app/src/pages/project/__generated__/SpanSelectionToolbarAddSpansToDatasetMutation.graphql.ts
  src/phoenix/server/api/input_types/AddExamplesToDatasetInput.py
  src/phoenix/server/api/input_types/DatasetExampleInput.py
  src/phoenix/server/api/mutations/dataset_mutations.py
  src/phoenix/server/api/types/AddSpansToDatasetPayload.py
Labels: size:L

#3282 feat: docker image runs as root by default with tags for nonroot and debug images
  src/phoenix/db/README.md
Labels: size:XS

#3284 chore: update docker image version in kustomize to use new root image
  kustomize/base/phoenix.yaml
Labels: size:XS

#3279 feat(datasets): spans as examples
  app/schema.graphql
  src/phoenix/server/api/helpers/__init__.py
  src/phoenix/server/api/helpers/dataset_helpers.py
  src/phoenix/server/api/mutations/dataset_mutations.py
  src/phoenix/server/api/types/DatasetExample.py
  src/phoenix/server/api/types/ExampleInterface.py
  src/phoenix/server/api/types/Span.py
  tests/server/api/helpers/test_dataset_helpers.py
  tests/server/api/mutations/test_dataset_mutations.py
Labels: size:XL

#3271 feat: List Dataset Examples
  src/phoenix/server/api/routers/v1/__init__.py
  src/phoenix/server/api/routers/v1/dataset_examples.py
  tests/server/api/conftest.py
  tests/server/api/routers/v1/test_dataset_examples.py
Labels: size:L

#3288 ci: Try to trigger image builds more reliably on release
  .github/workflows/docker-build-release.yml
Labels: size:M

#3291 fix(gql): don't clear data if read_only
  src/phoenix/server/api/context.py
  src/phoenix/server/api/schema.py
  src/phoenix/server/app.py
Labels: size:XS

#3293 docs: Move image listing to top-level deployment page
  docs/deployment/README.md
  docs/deployment/docker.md
Labels: size:S

#3295 fix: Tweak release flow
  .github/workflows/docker-build-release.yml
  .github/workflows/release.yml
Labels: size:S

#3296 chore(main): release arize-phoenix 4.2.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3298 chore(main): release arize-phoenix 4.2.3
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3230 feat(datasets): add span to dataset from the trace page
  app/package.json
  app/pnpm-lock.yaml
  app/src/components/code/JSONEditor.tsx
  app/src/components/code/index.tsx
  app/src/pages/trace/SpanToDatasetExampleDialog.tsx
  app/src/pages/trace/TracePage.tsx
  app/src/pages/trace/__generated__/SpanToDatasetExampleDialogAddExampleToDatasetMutation.graphql.ts
  app/src/pages/trace/__generated__/SpanToDatasetExampleDialogQuery.graphql.ts
  app/src/pages/trace/__generated__/TracePageQuery.graphql.ts
  app/src/utils/__tests__/jsonUtils.test.ts
  app/src/utils/jsonUtils.ts
  src/phoenix/server/api/mutations/dataset_mutations.py
Labels: size:XL

#3316 docs: Update Langchain dependencies in notebook tutorials
  tutorials/tracing/langchain_agent_tracing_tutorial.ipynb
  tutorials/tracing/langchain_google_palm_tracing_tutorial.ipynb
  tutorials/tracing/langchain_tracing_tutorial.ipynb
  tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb
Labels: size:XS

#3312 feat(datasets): download csv button
  app/src/pages/dataset/DatasetPage.tsx
  app/src/pages/datasets/DatasetsPage.tsx
Labels: size:M

#3314 docs: rest api guidance
  DEVELOPMENT.md
Labels: size:M

#3299 feat(datasets): add pagination to dataset examples table
  app/src/pages/dataset/DatasetExamplesTable.tsx
  app/src/pages/dataset/DatasetPage.tsx
  app/src/pages/dataset/__generated__/DatasetExamplesTableFragment.graphql.ts
  app/src/pages/dataset/__generated__/DatasetExamplesTableQuery.graphql.ts
  app/src/pages/dataset/__generated__/datasetLoaderQuery.graphql.ts
Labels: size:L

#3320 refactor: make csv download more restful
  app/src/pages/dataset/DatasetPage.tsx
  src/phoenix/server/api/routers/v1/__init__.py
  src/phoenix/server/api/routers/v1/datasets.py
  src/phoenix/session/client.py
  tests/server/api/routers/v1/test_datasets.py
  tests/session/test_client.py
Labels: size:L

#3322 fix: update link to openinference spec
  app/src/pages/trace/TracePage.tsx
Labels: size:S

#3318 chore(main): release arize-phoenix 4.2.4
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#3324 feat(datasets): delete examples mutation
  app/schema.graphql
  src/phoenix/server/api/input_types/DeleteDatasetExamplesInput.py
  src/phoenix/server/api/mutations/dataset_mutations.py
Labels: size:L

#3270 feat: Support mistral
  packages/phoenix-evals/src/phoenix/evals/models/bedrock.py
Labels: size:S

#3323 feat(datasets): JSON endpoint to get dataset versions
  src/phoenix/server/api/routers/v1/__init__.py
  src/phoenix/server/api/routers/v1/datasets.py
  src/phoenix/session/client.py
  tests/server/api/conftest.py
  tests/server/api/routers/v1/test_datasets.py
  tests/session/test_client.py
Labels: size:L

#3321 feat(datasets): Delete dataset mutation
  app/schema.graphql
  src/phoenix/server/api/input_types/DeleteDatasetInput.py
  src/phoenix/server/api/mutations/dataset_mutations.py
  tests/server/api/mutations/test_dataset_mutations.py
Labels: size:L

#3325 feat: dataset example slideover
  app/src/Routes.tsx
  app/src/pages/dataset/DatasetExamplePage.tsx
  app/src/pages/dataset/DatasetExamplesTable.tsx
  app/src/pages/dataset/DatasetPage.tsx
  app/src/pages/dataset/__generated__/DatasetExamplePageQuery.graphql.ts
  app/src/pages/dataset/index.tsx
  app/src/pages/trace/TracePage.tsx
Labels: size:L

#3336 feat(datasets): Delete dataset UI
  app/src/pages/dataset/DatasetPage.tsx
  app/src/pages/datasets/DatasetActionMenu.tsx
  app/src/pages/datasets/DatasetsTable.tsx
  app/src/pages/datasets/__generated__/DatasetActionMenuDeleteMutation.graphql.ts
Labels: size:L

#3334 refactor(datasets): use revisions field on DatasetExample type
  app/package.json
  app/schema.graphql
  app/src/pages/dataset/DatasetExamplePage.tsx
  app/src/pages/dataset/DatasetExamplesTable.tsx
  app/src/pages/dataset/__generated__/DatasetExamplePageQuery.graphql.ts
  app/src/pages/dataset/__generated__/DatasetExamplesTableFragment.graphql.ts
  app/src/pages/dataset/__generated__/DatasetExamplesTableQuery.graphql.ts
  app/src/pages/dataset/__generated__/datasetLoaderQuery.graphql.ts
  app/src/pages/trace/SpanToDatasetExampleDialog.tsx
  app/src/pages/trace/__generated__/SpanToDatasetExampleDialogQuery.graphql.ts
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/Dataset.py
  src/phoenix/server/api/types/DatasetExample.py
  src/phoenix/server/api/types/DatasetExampleRevision.py
  src/phoenix/server/api/types/ExampleRevisionInterface.py
  src/phoenix/server/api/types/Span.py
  src/phoenix/server/api/types/pagination.py
  tests/server/api/mutations/test_dataset_mutations.py
  tests/server/api/types/test_Dataset.py
Labels: size:XL

#3347 feat(datasets): synchronously upload dataset examples returning `dataset_id` in JSON
  pyproject.toml
  src/phoenix/db/insertion/dataset.py
  src/phoenix/server/api/routers/v1/datasets.py
  tests/server/api/routers/v1/test_datasets.py
Labels: size:L

#3348 docs: minimum working example with a local llm
  tutorials/evals/local_llm.ipynb
Labels: size:L

#3350 feat: Allow skipping on template mapping errors, returning debug info
  packages/phoenix-evals/src/phoenix/evals/classify.py
  packages/phoenix-evals/src/phoenix/evals/exceptions.py
  packages/phoenix-evals/src/phoenix/evals/executors.py
  packages/phoenix-evals/src/phoenix/evals/generate.py
  packages/phoenix-evals/tests/phoenix/evals/functions/test_classify.py
  packages/phoenix-evals/tests/phoenix/evals/functions/test_executor.py
Labels: size:L

#3358 feat: Serializable execution details
  packages/phoenix-evals/src/phoenix/evals/classify.py
  packages/phoenix-evals/tests/phoenix/evals/functions/test_classify.py
  tutorials/evals/evaluations_with_error_handling.ipynb
Labels: size:XXL

#3354 chore(main): release arize-phoenix-evals 0.11.0
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S
