Repository Arize-ai/phoenix, pull requests merged in 2024-01, with the labels that each got.

#2104 chore: deprecate llama_index llm predictor
  cspell.json
  tutorials/internal/llama_index_tracing_example.ipynb
  tutorials/llama_index_search_and_retrieval_tutorial.ipynb
  tutorials/milvus_llamaindex_search_and_retrieval_tutorial.ipynb
Labels: size:S, lgtm

#2095 feat: launch phoenix with evaluations
  src/phoenix/session/evaluation.py
  src/phoenix/session/session.py
Labels: size:M, lgtm

#2100 docs(evals): update ragas integration notebook
  tutorials/ragas_retrieval_evals_tutorial.ipynb
Labels: size:S, lgtm

#2102 fix: Clean up vertex clients after event loop closure
  integration-tests/evals/test_multiple_classify_calls_anthropic.py
  integration-tests/evals/test_multiple_classify_calls_openai.py
  integration-tests/evals/test_multiple_classify_calls_vertex.py
  src/phoenix/experimental/evals/models/anthropic.py
  src/phoenix/experimental/evals/models/vertex.py
Labels: size:M, lgtm

#2106 add locks
  src/phoenix/core/evals.py
Labels: size:S

#2094 feat: support eval exports for session
  src/phoenix/core/evals.py
  src/phoenix/session/session.py
Labels: size:M, lgtm

#2107 feat: add get_trace_dataset method to session
  src/phoenix/session/session.py
Labels: size:XS, lgtm

#2110 chore(demos): add chatbot embedding fixture
  app/package.json
  src/phoenix/datasets/fixtures.py
Labels: size:M, lgtm

#2096 fix: Determine default async concurrency on a per-model basis
  src/phoenix/experimental/evals/evaluators.py
  src/phoenix/experimental/evals/functions/classify.py
  src/phoenix/experimental/evals/functions/generate.py
  src/phoenix/experimental/evals/models/base.py
  src/phoenix/experimental/evals/models/vertex.py
Labels: size:M, lgtm

#2108 chore: remove tokenizer warnings
  src/phoenix/experimental/evals/models/anthropic.py
  src/phoenix/experimental/evals/models/bedrock.py
Labels: size:XS, lgtm

#2112 feat(evals): Gpt 4 turbo context window size
  src/phoenix/experimental/evals/models/openai.py
Labels: size:XS, lgtm

#2114 fix: Resolves Bedrock model compatibility issues
  src/phoenix/experimental/evals/models/bedrock.py
Labels: size:XS, lgtm

#2115 chore(evals): Removes duplicate paragraph in hallucination prompt base template
  src/phoenix/experimental/evals/templates/default_templates.py
Labels: size:XS, lgtm

#2121 feat(persistence): add a PHOENIX_WORKING_DIR env var for setting up a…
  src/phoenix/config.py
Labels: size:M, lgtm

#2125 chore: bump frontend dependancies
  .pre-commit-config.yaml
  app/.prettierrc.json
  app/package-lock.json
  app/package.json
  app/src/contexts/FeatureFlagsContext.tsx
  app/src/pages/dimension/DimensionDriftTimeSeries.tsx
  app/src/pages/dimension/DimensionQuantilesTimeSeries.tsx
  app/src/pages/embedding/MetricTimeSeries.tsx
  app/src/pages/trace/TracePage.tsx
  app/src/pages/tracing/TracingHomePageHeader.tsx
  app/src/store/pointCloudStore.ts
Labels: size:L, lgtm

#2126 fix: Do not retry when context window has been exceeded
  src/phoenix/exceptions.py
  src/phoenix/experimental/evals/models/anthropic.py
  src/phoenix/experimental/evals/models/base.py
  src/phoenix/experimental/evals/models/bedrock.py
  src/phoenix/experimental/evals/models/openai.py
Labels: size:L, lgtm

#2144 fix: broken link and openinference links
  README.md
  src/phoenix/experimental/evals/functions/classify.py
  src/phoenix/trace/llama_index/callback.py
  tutorials/internal/llama_index_tracing_stream_example.ipynb
  tutorials/llama_index_search_and_retrieval_tutorial.ipynb
  tutorials/tracing/langchain_tracing_tutorial.ipynb
  tutorials/tracing/llama_index_tracing_tutorial.ipynb
Labels: size:S, lgtm

#2146 docs: sync main
  docs/.gitbook/assets/deploying_pheonix_v2.jpg
  docs/.gitbook/assets/deploying_phoenix_deployment_options.jpg
  docs/llm-evals/running-pre-tested-evals/hallucinations.md
  docs/llm-evals/running-pre-tested-evals/retrieval-rag-relevance.md
  docs/reference/deploying-phoenix.md
  docs/reference/environments.md
Labels: size:M

#2147 chore: pin pydantic version for mypy
  pyproject.toml
Labels: size:XS, lgtm

#2143 refactor: hexlify span and trace ids
  src/phoenix/server/api/schema.py
  src/phoenix/trace/llama_index/callback.py
  src/phoenix/trace/llama_index/streaming.py
  src/phoenix/trace/otel.py
  src/phoenix/trace/schemas.py
  src/phoenix/trace/span_json_decoder.py
  src/phoenix/trace/tracer.py
  tests/trace/test_otel.py
Labels: size:L, lgtm

#2148 refactor: support json string attributes in addition to flattened mappings
  src/phoenix/trace/otel.py
  tests/trace/test_otel.py
Labels: size:L, lgtm

#2152 fix: databricks check crashes in python console
  src/phoenix/session/session.py
Labels: size:XS, lgtm

#2153 fix: remove hyphens from span_id in evaluation fixtures
  src/phoenix/trace/fixtures.py
Labels: size:S, lgtm

#2159 refactor: use urljoin for urls
  src/phoenix/trace/exporter.py
  tests/trace/test_exporter.py
Labels: size:M, lgtm

#2161 fix: default collector endpoint breaks on windows
  src/phoenix/trace/exporter.py
  tests/trace/test_exporter.py
Labels: size:S, lgtm

#2164 refactor: catch all exceptions including TypeError when decoding json strings
  src/phoenix/trace/otel.py
Labels: size:XS, lgtm
