Repository Arize-ai/phoenix, pull requests merged in 2024-10, with the labels that each got.

#4821 chore: Fix broken links in app README, support .venv convention
  .gitignore
  app/README.md
Labels: size:XS

#4819 chore(main): release arize-phoenix 5.1.3
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4824 chore: add the new eslint rule
  app/.eslintrc.js
  app/package.json
  app/pnpm-lock.yaml
  app/src/contexts/DatasetContext.tsx
  app/src/contexts/PlaygroundContext.tsx
  app/src/contexts/PointCloudContext.tsx
  app/src/contexts/PreferencesContext.tsx
  app/src/contexts/TracingContext.tsx
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/experiments/ExperimentsTable.tsx
  app/src/pages/trace/TraceDetails.tsx
Labels: size:M

#4838 fix: handle `ndarray` for `json.dumps` in `encode_span_to_otlp`
  src/phoenix/trace/otel.py
Labels: size:XS

#4839 chore(main): release arize-phoenix 5.1.4
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4826 docs: add deno notebook examples and scaffold the js monorepo
  cspell.json
  js/.npmrc
  js/examples/notebooks/README.md
  js/examples/notebooks/deno.json
  js/examples/notebooks/tracing_openai_node_tutorial.ipynb
  js/package.json
  js/pnpm-lock.yaml
  js/pnpm-workspace.yaml
  pyproject.toml
Labels: size:L

#4842 fix(auth): show reset password button only for locally authenticated users
  app/src/contexts/ViewerContext.tsx
  app/src/contexts/__generated__/ViewerContextRefetchQuery.graphql.ts
  app/src/contexts/__generated__/ViewerContext_viewer.graphql.ts
  app/src/pages/__generated__/authenticatedRootLoaderQuery.graphql.ts
  app/src/pages/profile/ViewerProfileCard.tsx
Labels: size:M

#4845 fix: remove incorrect URL in python guide
  app/src/components/project/PythonProjectGuide.tsx
Labels: size:XS

#4851 fix: bump strawberry-graphql version
  dev-requirements.txt
  pyproject.toml
  src/phoenix/server/app.py
Labels: size:M

#4855 fix: pin postgres version at 16 for docker compose
  docker-compose.yml
Labels: size:XS

#4841 chore(main): release arize-phoenix 5.1.5
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4852 refactor: remove python 3.8 limitations from `dsl` module
  src/phoenix/trace/dsl/filter.py
  tests/trace/dsl/test_filter.py
Labels: size:M

#4861 chore: Ignore react compiler error
  app/src/pages/playground/PlaygroundOutput.tsx
Labels: size:XS

#4863 ci: cache playwright dependencies
  .github/workflows/playwright.yaml
Labels: size:M

#4866 fix: replace hdbscan with fast-hdbscan
  pyproject.toml
  src/phoenix/pointcloud/clustering.py
Labels: size:XS

#4820 docs: testing philosophy, coverage, types
  docs/internal_docs/TESTING.md
Labels: size:M

#4867 chore(main): release arize-phoenix 5.1.6
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4868 fix: create optional dependency group for umap-learn and fast-hdbscan
  pyproject.toml
  src/phoenix/server/app.py
Labels: size:S

#4872 ci: suppress warning from pytest-asyncio
  tests/integration/pytest.ini
Labels: size:XS

#4875 ci: add caching for integration tests
  .github/workflows/python-CI.yml
  .github/workflows/python-cron.yml
  requirements/integration-tests.txt
  tox.ini
Labels: size:M

#4870 feat: phoenix cli
  pyproject.toml
  src/phoenix/server/main.py
Labels: size:M

#4871 chore(main): release arize-phoenix 5.2.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4848 docs(js): add langchain deno notebook
  js/examples/notebooks/langchain/deno.json
  js/examples/notebooks/langchain/package.json
  js/examples/notebooks/langchain/tracing_langchain_node_tutorial.ipynb
  js/examples/notebooks/tracing_openai_node_tutorial.ipynb
Labels: size:L

#4907 feat(playground): rudimentary graphql support for messages input
  app/schema.graphql
  app/src/pages/playground/MessageRolePicker.tsx
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  app/src/store/playgroundStore.tsx
  src/phoenix/server/api/input_types/ChatCompletionMessageInput.py
  src/phoenix/server/api/subscriptions.py
  src/phoenix/server/api/types/ChatCompletionMessageRole.py
Labels: size:L

#4909 feat(playground): Implement message role picker callback
  app/src/pages/playground/MessageRolePicker.tsx
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/playgroundUtils.ts
  app/src/store/playgroundStore.tsx
Labels: size:M

#4915 fix: handle badly ingested llm spans gracefully
  app/src/openInference/tracing/__tests__/types.test.ts
  app/src/openInference/tracing/types.ts
  app/src/pages/trace/SpanDetails.tsx
Labels: size:M

#4905 chore(main): release arize-phoenix 5.2.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4919 test: add e2e for member creating user api key
  app/global-setup.ts
  app/tests/member-access.spec.ts
Labels: size:M

#4874 ci: clean up caches by a branch
  .github/workflows/clean_up_caches.yml
Labels: size:M

#4918 ci: add e2e test for admin can create system api key
  app/tests/api-key-management.spec.ts
Labels: size:S

#4906 feat(playground): parse span attribute `llm.input_messages` for playground span replay
  app/jest.config.js
  app/jest.setup.ts
  app/package.json
  app/pnpm-lock.yaml
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/SpanPlaygroundPage.tsx
  app/src/pages/playground/__tests__/fixtures.ts
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/constants.tsx
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/playground/schemas.ts
  app/src/pages/playground/spanPlaygroundPageLoader.ts
  app/src/pages/trace/SpanDetails.tsx
  app/src/store/playgroundStore.tsx
  app/src/utils/jsonUtils.ts
Labels: size:L

#4873 ci: fix `tox.ini` for integration tests
  .github/workflows/playwright.yaml
  .github/workflows/python-CI.yml
  .github/workflows/python-cron.yml
  packages/phoenix-evals/pyproject.toml
  packages/phoenix-otel/pyproject.toml
  pyproject.toml
  requirements/ci.txt
  requirements/integration-tests.txt
  tests/integration/_helpers.py
  tests/integration/conftest.py
  tests/integration/pytest.ini
  tests/integration/ruff.toml
  tox.ini
Labels: size:L

#4876 ci: use tox for unit tests
  .github/workflows/python-CI.yml
  requirements/ci.txt
  requirements/unit-tests.txt
  tox.ini
Labels: size:M

#4877 ci: one ruff to rule them all
  .github/workflows/python-CI.yml
  requirements/ci.txt
  tox.ini
Labels: size:M

#4881 ci: separate type check from integration tests
  .github/workflows/python-CI.yml
  tox.ini
Labels: size:M

#4927 chore: leave in concurrency config for playwright
  app/playwright.config.ts
Labels: size:XS

#4878 chore: use git town for making stacked changes
  .git-branches.toml
  .github/workflows/git-town.yml
Labels: size:L

#4933 chore: Revert "chore: use git town for making stacked changes"
  .git-branches.toml
  .github/workflows/git-town.yml
Labels: size:L

#4935 fix: playwright
  app/package.json
  app/pnpm-lock.yaml
  app/tests/admin-access.ts
Labels: size:XS

#4931 feat(playground): make chat messages match style in traces
  app/src/hooks/useChatMessageStyles.ts
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/SpanPlaygroundPage.tsx
  app/src/pages/trace/SpanDetails.tsx
  app/src/store/playgroundStore.tsx
Labels: size:L

#4916 fix: add middleware for checking Cross-Site Request Forgery (CSRF) when trusted origins are specified via environment variable
  pyproject.toml
  src/phoenix/config.py
  src/phoenix/server/app.py
  tests/integration/auth/conftest.py
  tests/integration/auth/test_auth.py
Labels: size:M

#4937 feat: Always prompt as system for OpenAI Models
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
Labels: size:XS

#4940 chore(main): release arize-phoenix-evals 0.17.0
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#4936 feat(playground): re-ordering of messages using dnd
  app/package.json
  app/pnpm-lock.yaml
  app/src/components/dnd/DragHandle.tsx
  app/src/components/dnd/helpers/move.ts
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/playgroundUtils.ts
  app/src/store/playgroundStore.tsx
Labels: size:XL

#4934 chore(main): release arize-phoenix 5.2.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#4944 chore: restore deleted tracing tutorial jupyter notebook for vertexai
  tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb
Labels: size:L

#4947 feat(playground): add / delete messages
  app/src/components/dnd/DragHandle.tsx
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/PlaygroundInstance.tsx
  app/src/pages/playground/PlaygroundTemplate.tsx
Labels: size:L

#4946 docs: update dspy notebook to reflect new instrumentation for v2.5 and above
  tutorials/tracing/dspy_tracing_tutorial.ipynb
Labels: size:L

#4957 ci: for integration tests postgresql schema should always exist
  tests/integration/_helpers.py
Labels: size:XS

#4955 refactor: Switch to Vitest from Jest
  .tours/app.tour
  app/README.md
  app/__tests__/authFetch.test.ts
  app/jest.config.js
  app/package.json
  app/pnpm-lock.yaml
  app/src/utils/__tests__/routingUtils.test.ts
  app/tsconfig.json
  app/vite.config.mts
  docs/internal_docs/TESTING.md
Labels: size:M

#4966 ci: fix vitest
  app/package.json
  app/pnpm-lock.yaml
  app/vite.config.mts
  app/vitest.setup.ts
Labels: size:XS

#4941 feat(playground): accumulate errors while parsing span attributes
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/SpanPlaygroundPage.tsx
  app/src/pages/playground/__tests__/fixtures.ts
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/constants.tsx
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/playground/schemas.ts
  app/src/store/playgroundStore.tsx
  app/src/typeUtils.ts
Labels: size:XL

#4956 ci: add test for db migrations
  tests/integration/_helpers.py
  tests/integration/conftest.py
  tests/integration/db_migrations/__init__.py
  tests/integration/db_migrations/conftest.py
  tests/integration/db_migrations/test_up_and_down_migrations.py
Labels: size:L

#4969 ci: remove redundant hatch checks
  .github/workflows/python-CI.yml
Labels: size:XS

#4971 feat(playground): model selector
  app/src/@types/generative.d.ts
  app/src/constants/generativeConstants.ts
  app/src/pages/playground/ModelConfigButton.tsx
  app/src/pages/playground/ModelPicker.tsx
  app/src/pages/playground/ModelProviderPicker.tsx
  app/src/pages/playground/PlaygroundTemplate.tsx
  app/src/pages/playground/__generated__/ModelConfigButtonDialogQuery.graphql.ts
  app/src/pages/playground/__generated__/ModelPickerFragment.graphql.ts
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/store/playgroundStore.tsx
  app/src/utils/generativeUtils.ts
Labels: size:L

#4943 feat(playground): Implement codemirror based template string editor
  app/package.json
  app/pnpm-lock.yaml
  app/src/components/templateEditor/TemplateEditor.tsx
  app/src/components/templateEditor/index.tsx
  app/src/components/templateEditor/language/__tests__/languageUtils.test.ts
  app/src/components/templateEditor/language/fString/fStringTemplating.syntax.grammar
  app/src/components/templateEditor/language/fString/fStringTemplating.syntax.grammar.d.ts
  app/src/components/templateEditor/language/fString/fStringTemplating.ts
  app/src/components/templateEditor/language/fString/index.ts
  app/src/components/templateEditor/language/languageUtils.ts
  app/src/components/templateEditor/language/mustacheLike/index.ts
  app/src/components/templateEditor/language/mustacheLike/mustacheLikeTemplating.syntax.grammar
  app/src/components/templateEditor/language/mustacheLike/mustacheLikeTemplating.syntax.grammar.d.ts
  app/src/components/templateEditor/language/mustacheLike/mustacheLikeTemplating.ts
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/vite.config.mts
Labels: size:XL

#4970 feat(playground): add credential storage
  app/src/@types/generative.d.ts
  app/src/App.tsx
  app/src/contexts/CredentialsContext.tsx
  app/src/contexts/PlaygroundContext.tsx
  app/src/pages/playground/MessageRolePicker.tsx
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/PlaygroundCredentialsDropdown.tsx
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/constants.tsx
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/playground/schemas.ts
  app/src/store/credentialsStore.tsx
  app/src/store/index.tsx
  app/src/store/playground/index.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
Labels: size:XL

#4982 feat(playground): create llm span for playground runs
  src/phoenix/server/api/subscriptions.py
Labels: size:L

#4978 feat(playground): playground layout
  app/package.json
  app/pnpm-lock.yaml
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundCredentialsDropdown.tsx
  app/src/pages/playground/PlaygroundInstance.tsx
  app/src/pages/playground/PlaygroundTools.tsx
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
Labels: size:L

#4992 fix(playground): Remove unused statements in language grammars
  app/src/components/templateEditor/language/fString/fStringTemplating.syntax.grammar
  app/src/components/templateEditor/language/mustacheLike/mustacheLikeTemplating.syntax.grammar
Labels: size:XS

#5000 feat(playground): copy messages to clipboard
  app/src/pages/playground/PlaygroundChatTemplate.tsx
Labels: size:XS

#4999 fix(playground): plumb through model name and providers
  app/schema.graphql
  app/src/pages/playground/ModelConfigButton.tsx
  app/src/pages/playground/ModelPicker.tsx
  app/src/pages/playground/ModelProviderPicker.tsx
  app/src/pages/playground/PlaygroundCredentialsDropdown.tsx
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/__generated__/ModelConfigButtonDialogQuery.graphql.ts
  app/src/pages/playground/__generated__/ModelPickerFragment.graphql.ts
  app/src/pages/playground/__generated__/ModelProviderPickerFragment.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/subscriptions.py
  src/phoenix/server/api/types/GenerativeProvider.py
  src/phoenix/server/api/types/ModelProvider.py
Labels: size:L

#5001 fix(playground): record model name for llm spans in playground
  src/phoenix/server/api/subscriptions.py
Labels: size:XS

#5003 fix(playground): plumb through credentials
  app/schema.graphql
  app/src/pages/playground/PlaygroundCredentialsDropdown.tsx
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  app/src/store/credentialsStore.tsx
  src/phoenix/server/api/subscriptions.py
Labels: size:L

#4994 feat(playground): Extract and display variables from all message templates as "inputs"
  app/src/components/templateEditor/TemplateEditor.tsx
  app/src/components/templateEditor/constants.ts
  app/src/components/templateEditor/language/fString/fStringTemplating.ts
  app/src/components/templateEditor/language/mustacheLike/mustacheLikeTemplating.ts
  app/src/components/templateEditor/templateEditorUtils.ts
  app/src/components/templateEditor/types.ts
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
Labels: size:L

#5004 feat(playground): toggle for the template language
  app/package.json
  app/pnpm-lock.yaml
  app/src/components/templateEditor/types.ts
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/TemplateLanguageRadioGroup.tsx
  app/src/store/playground/playgroundStore.tsx
Labels: size:M

#5019 chore: bump components to allow for better styling of accordions
  app/package.json
  app/pnpm-lock.yaml
  app/src/pages/playground/Playground.tsx
Labels: size:S

#5002 feat(playground): add tools ui
  app/package.json
  app/pnpm-lock.yaml
  app/src/@types/generative.d.ts
  app/src/components/code/CodeEditorFieldWrapper.tsx
  app/src/components/code/JSONEditor.tsx
  app/src/components/generative/ToolChoiceSelector.tsx
  app/src/components/generative/index.ts
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/PlaygroundTool.tsx
  app/src/pages/playground/PlaygroundTools.tsx
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/schemas/index.ts
  app/src/schemas/toolSchema.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
Labels: size:XL

#5006 feat(playground): Implement editable input variable textareas (#4987)
  app/src/components/code/CodeWrap.tsx
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundInput.tsx
  app/src/pages/playground/VariableEditor.tsx
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
Labels: size:L

#5005 fix(playground): plumb through and record invocation parameters
  app/schema.graphql
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  src/phoenix/db/migrations/versions/10460e46d750_datasets.py
  src/phoenix/db/migrations/versions/3be8647b87d8_add_token_columns_to_spans_table.py
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
  src/phoenix/db/models.py
  src/phoenix/server/api/input_types/InvocationParameters.py
  src/phoenix/server/api/subscriptions.py
  src/phoenix/utilities/json.py
Labels: size:L

#5028 feat: add litellm integrations UI
  app/src/components/project/IntegrationIcons.tsx
  app/src/components/project/Integrations.tsx
Labels: size:S

#5021 feat(playground): parse model name and infer provider form span
  app/src/constants/generativeConstants.ts
  app/src/pages/playground/ModelConfigButton.tsx
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/constants.tsx
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/playground/schemas.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
Labels: size:L

#5042 chore: update pre-commit to remove warnings
  .pre-commit-config.yaml
Labels: size:XS

#5044 ci: skip webkit for playwright tests
  .github/workflows/playwright.yaml
  app/playwright.config.ts
Labels: size:M

#5029 feat(playground): wire up tool calling ui
  app/src/components/generative/ToolChoiceSelector.tsx
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/PlaygroundTool.tsx
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
  src/phoenix/server/api/subscriptions.py
Labels: size:L

#5046 chore: git ignore symbolic links
  .github/workflows/python-CI.yml
  .gitignore
  src/phoenix/evals
  src/phoenix/otel
  tox.ini
Labels: size:M

#5026 docs: update crewai tutorial for 0.63.0+
  tutorials/tracing/crewai_tracing_tutorial.ipynb
Labels: size:M

#4689 docs: add min package versions to llama_index notebook
  tutorials/tracing/llama_index_openai_agent_tracing_tutorial.ipynb
Labels: size:S

#4977 chore: update fixtures to consolidate demo traces
  src/phoenix/trace/fixtures.py
Labels: size:S

#4847 feat(js): Scaffold ts phoenix client
  js/packages/phoenix-client/README.md
  js/packages/phoenix-client/examples/list_datasets.ts
  js/packages/phoenix-client/package.json
  js/packages/phoenix-client/src/__generated__/api/v1.d.ts
  js/packages/phoenix-client/src/config.ts
  js/packages/phoenix-client/src/index.ts
  js/packages/phoenix-client/tsconfig.esm.json
  js/packages/phoenix-client/tsconfig.esnext.json
  js/packages/phoenix-client/tsconfig.json
  js/pnpm-lock.yaml
  js/tsconfig.base.es5.json
  js/tsconfig.base.esm.json
  js/tsconfig.base.esnext.json
  js/tsconfig.base.json
Labels: size:XXL

#4701 chore(main): release arize-phoenix-otel 0.6.0
  .release-please-manifest.json
  packages/phoenix-otel/CHANGELOG.md
  packages/phoenix-otel/pyproject.toml
Labels: autorelease: pending, size:S

#5049 docs: update Agent Project README.md
  examples/agent_framework_comparison/README.md
Labels: size:XS

#4972 ci: parallelize graphql build schema, openai build schema, etc
  .github/workflows/playwright.yaml
  .github/workflows/python-CI.yml
  .github/workflows/python-cron.yml
  app/schema.graphql
  pyproject.toml
  requirements/build-graphql-schema.txt
  requirements/clean-jupyter-notebooks.txt
  requirements/compile-protobuf.txt
  schemas/openapi.json
  src/phoenix/server/api/openapi/main.py
  tox.ini
Labels: size:L

#5051 refactor: Modify imports to be bazel compatible
  src/phoenix/core/model_schema_adapter.py
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  src/phoenix/trace/fixtures.py
  src/phoenix/utilities/client.py
Labels: size:S

#5057 ci: add CI to sessions
  .github/workflows/docker-build-experimental.yml
  .github/workflows/playwright.yaml
  .github/workflows/python-CI.yml
  .github/workflows/python-cron.yml
  .github/workflows/typescript-CI.yml
Labels: size:L

#5056 chore: make symlink operation idempotent
  tox.ini
Labels: size:XS

#5063 chore: isolated python environment for phoenix serve
  app/package.json
  tox.ini
Labels: size:S

#5052 feat(playground): plumb through and apply template variables
  app/schema.graphql
  app/src/components/templateEditor/constants.ts
  app/src/pages/playground/PlaygroundInput.tsx
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  src/phoenix/server/api/subscriptions.py
  src/phoenix/utilities/template_formatters.py
  tests/utilities/test_template_formatters.py
Labels: size:L

#5065 feat(playground): support azure openai
  app/schema.graphql
  app/src/constants/generativeConstants.ts
  app/src/pages/playground/ModelConfigButton.tsx
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  app/src/store/playground/types.ts
  src/phoenix/server/api/subscriptions.py
  tox.ini
Labels: size:L

#5062 fix(playground): make messages collapsible so they can be dragged
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
Labels: size:S

#5072 chore: put dev requirements in text file
  requirements/dev.txt
  tox.ini
Labels: size:XS

#5076 chore: fix gitignore for symlinks
  .gitignore
Labels: size:XS

#5078 ci: run ruff on everything
  .github/workflows/python-CI.yml
Labels: size:XS

#5079 fix(playground): remove toolChoice if no tools provided
  app/src/pages/playground/PlaygroundOutput.tsx
Labels: size:S

#4950 chore(main): release arize-phoenix 5.3.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:M

#5074 fix(playground): add openai as a container dependency
  pyproject.toml
Labels: size:XS

#5081 fix: Re-enable run button on subscription error
  app/src/pages/playground/PlaygroundOutput.tsx
Labels: size:S

#5083 chore(main): release arize-phoenix 5.3.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#5077 fix: increase python upper bound to include python 3.13 for `arize-phoenix-evals` and `arize-phoenix-otel`
  .github/workflows/python-CI.yml
  packages/phoenix-evals/pyproject.toml
  packages/phoenix-otel/pyproject.toml
Labels: size:XS

#5088 chore(main): release arize-phoenix-otel 0.6.1
  .release-please-manifest.json
  packages/phoenix-otel/CHANGELOG.md
  packages/phoenix-otel/pyproject.toml
Labels: autorelease: pending, size:S

#5087 chore(main): release arize-phoenix-evals 0.17.1
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#5080 fix(playground): optional type in playground tool calls
  app/src/pages/playground/PlaygroundOutput.tsx
Labels: size:XS

#5067 fix: Derive playground values instead of storing them in state
  app/src/pages/playground/PlaygroundInput.tsx
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/playground/useDerivedPlaygroundVariables.tsx
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
Labels: size:L

#5094 docs: anthropic tools tracing tutorial and fixture
  src/phoenix/trace/fixtures.py
  tutorials/tracing/anthropic_tracing_tutorial.ipynb
  tutorials/tracing/llama_index_openai_agent_tracing_tutorial.ipynb
Labels: size:L

#5095 chore: expand exclude-paths for release please
  release-please-config.json
Labels: size:S

#5089 feat(playground): return finalized span at end of subscription
  app/schema.graphql
  src/phoenix/server/api/subscriptions.py
Labels: size:M

#5096 refactor: move misplaced unit test file
  tests/unit/utilities/test_template_formatters.py
Labels: size:XS

#4961 feat: add db table for trace sessions
  .github/workflows/python-CI.yml
  app/schema.graphql
  requirements/integration-tests.txt
  src/phoenix/db/insertion/span.py
  src/phoenix/db/migrations/versions/4ded9e43755f_create_trace_session_table.py
  src/phoenix/db/models.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/api/types/ProjectSession.py
  src/phoenix/server/api/types/Trace.py
  tests/integration/_helpers.py
  tests/integration/conftest.py
  tests/integration/db_migrations/conftest.py
  tests/integration/db_migrations/test_up_and_down_migrations.py
  tests/integration/project_sessions/__init__.py
  tests/integration/project_sessions/conftest.py
  tests/integration/project_sessions/test_project_sessions.py
  tests/integration/server/test_launch_app.py
Labels: size:XXL

#5064 fix: allow progress bar to be disabled
  packages/phoenix-evals/src/phoenix/evals/classify.py
  packages/phoenix-evals/src/phoenix/evals/executors.py
Labels: size:S

#5107 chore(main): release arize-phoenix-evals 0.17.2
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#5108 feat(playground): show span details when playground run ends
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/RunMetadataFooter.tsx
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  app/src/pages/playground/__generated__/RunMetadataFooterQuery.graphql.ts
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
Labels: size:L

#5110 feat: add support for secure wss connection
  app/src/RelayEnvironment.ts
  app/src/config.ts
Labels: size:S

#5086 chore(main): release arize-phoenix 5.4.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#5105 feat: Refactor subscription streaming and plumb through anthropic support
  pyproject.toml
  requirements/type-check.txt
  src/phoenix/server/api/subscriptions.py
Labels: size:L

#5115 refactor(playground): switch view trace to be a slideover
  app/src/pages/playground/PlaygroundRunTraceDialog.tsx
  app/src/pages/playground/RunMetadataFooter.tsx
Labels: size:M

#5109 chore: feature flag for playground streaming and datasets
  app/src/contexts/FeatureFlagsContext.tsx
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundStreamToggle.tsx
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
Labels: size:M

#5114 chore(main): release arize-phoenix 5.5.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#5119 fix(UI): bad looking button styles
  app/package.json
  app/pnpm-lock.yaml
  app/src/pages/settings/SettingsPage.tsx
Labels: size:XS

#5121 docs: add more links and integrations to the readme
  README.md
Labels: size:M

#5122 docs: fix endpoint params
  docs/tracing/integrations-tracing/anthropic.md
  docs/tracing/integrations-tracing/bedrock.md
  docs/tracing/integrations-tracing/crewai.md
  docs/tracing/integrations-tracing/dspy.md
  docs/tracing/integrations-tracing/groq.md
  docs/tracing/integrations-tracing/guardrails-ai.md
  docs/tracing/integrations-tracing/haystack.md
  docs/tracing/integrations-tracing/instructor.md
  docs/tracing/integrations-tracing/langchain.md
  docs/tracing/integrations-tracing/litellm.md
  docs/tracing/integrations-tracing/mistralai.md
  docs/tracing/integrations-tracing/openai.md
  docs/tracing/integrations-tracing/prompt-flow.md
  docs/tracing/integrations-tracing/vertexai.md
Labels: size:M

#5120 chore(main): release arize-phoenix 5.5.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#5124 docs: add deployment options link
  docs/deployment/README.md
Labels: size:S

#5128 fix(playground): do nothing on credential form submit
  app/src/pages/playground/PlaygroundCredentialsDropdown.tsx
Labels: size:S

#5125 test(playground): add api test for chat completion subscription
  requirements/unit-tests.txt
  src/phoenix/server/api/subscriptions.py
  tests/unit/conftest.py
  tests/unit/server/api/cassettes/test_subscriptions/TestChatCompletionSubscription.test_openai_text_response_emits_expected_payloads_and_records_expected_span[sqlite].yaml
  tests/unit/server/api/test_subscriptions.py
Labels: size:L

#5141 fix: update llama-index versions in extra
  pyproject.toml
Labels: size:S

#5129 chore(main): release arize-phoenix 5.5.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#5103 feat(playground): add tool role messages to ui
  app/schema.graphql
  app/src/components/trace/SpanKindIcon.tsx
  app/src/pages/playground/ChatMessageToolCallsEditor.tsx
  app/src/pages/playground/MessageContentRadioGroup.tsx
  app/src/pages/playground/MessageRolePicker.tsx
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/PlaygroundTool.tsx
  app/src/pages/playground/PlaygroundTools.tsx
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  app/src/schemas/index.ts
  app/src/schemas/toolSchemas.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
  src/phoenix/server/api/input_types/ChatCompletionMessageInput.py
  src/phoenix/server/api/subscriptions.py
Labels: size:XL

#5143 chore: add embeddings extra to notebook pip installs
  tutorials/credit_card_fraud_tutorial.ipynb
  tutorials/find_cluster_export_and_explore_with_gpt.ipynb
  tutorials/image_classification_tutorial.ipynb
  tutorials/integrations/arize_anyscale_traces_and_embeddings.ipynb
  tutorials/llama_index_search_and_retrieval_tutorial.ipynb
  tutorials/llm_generative_gpt_4.ipynb
  tutorials/llm_ops_overview.ipynb
  tutorials/llm_summarization_tutorial.ipynb
  tutorials/milvus_llamaindex_search_and_retrieval_tutorial.ipynb
  tutorials/mistral/evaluate_rag--mistral.ipynb
  tutorials/qdrant_langchain_instrumentation_search_and_retrieval_tutorial.ipynb
  tutorials/quickstarts/inferences_quickstart.ipynb
  tutorials/ragas_retrieval_evals_tutorial.ipynb
  tutorials/sentiment_classification_tutorial.ipynb
Labels: size:M

#5045 feat: Scaffold model invocation params form (#5040)
  app/src/pages/playground/InvocationParametersForm.tsx
  app/src/pages/playground/ModelConfigButton.tsx
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/constants.tsx
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/playground/schemas.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
Labels: size:L

#5150 fix: remove `embeddings` from core dependencies
  pyproject.toml
Labels: size:XS

#5151 ci: add tox testenv for ruff
  .github/workflows/python-CI.yml
  tox.ini
Labels: size:M

#5104 ci: re-run on failures for integration test
  .github/workflows/python-CI.yml
  requirements/integration-tests.txt
  tests/integration/_helpers.py
  tests/integration/conftest.py
  tests/integration/db_migrations/conftest.py
  tests/integration/db_migrations/test_up_and_down_migrations.py
  tests/integration/server/test_launch_app.py
Labels: size:L

#5149 test(playground): add test for openai tool call response
  app/schema.graphql
  src/phoenix/server/api/subscriptions.py
  tests/unit/conftest.py
  tests/unit/server/api/cassettes/test_subscriptions/TestChatCompletionSubscription.test_openai_tool_call_response_emits_expected_payloads_and_records_expected_span[sqlite].yaml
  tests/unit/server/api/test_subscriptions.py
Labels: size:L

#5152 docs: update autogen tracing tutorial
  tutorials/tracing/autogen_tutorial.ipynb
Labels: size:M

#5133 chore: add fixture notebook to generate trace trees for multi-turn chat sessions
  scripts/fixtures/multi-turn_chat_sessions.ipynb
Labels: size:L

#5156 test(playground): add unit test for tool call messages
  app/schema.graphql
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  src/phoenix/server/api/input_types/ChatCompletionMessageInput.py
  tests/unit/server/api/cassettes/test_subscriptions/TestChatCompletionSubscription.test_openai_tool_call_messages_emits_expected_payloads_and_records_expected_span[sqlite].yaml
  tests/unit/server/api/test_subscriptions.py
Labels: size:L

#5159 test(playground): add api test for anthropic
  requirements/unit-tests.txt
  tests/unit/conftest.py
  tests/unit/server/api/cassettes/test_subscriptions/TestChatCompletionSubscription.test_anthropic_text_response_emits_expected_payloads_and_records_expected_span[sqlite].yaml
  tests/unit/server/api/test_subscriptions.py
Labels: size:L

#5169 chore: add descriptions for `tox list`
  tox.ini
Labels: size:S

#5168 ci: for ruff remove exclusions that are no longer necessary
  pyproject.toml
Labels: size:XS

#5167 chore: ignore additional packages for type check
  pyproject.toml
  src/phoenix/session/session.py
Labels: size:XS

#5171 chore: ignore *.grammar for prettier
  app/.prettierignore
Labels: size:XS

#5170 feat: Add LLMRelationalEvaluator to phoenix experiments
  src/phoenix/experiments/evaluators/llm_evaluators.py
Labels: size:L

#5161 feat(playground): add token counts for anthropic
  src/phoenix/server/api/subscriptions.py
  tests/unit/server/api/test_subscriptions.py
Labels: size:L

#5165 refactor: Render invocation parameters form using data from api
  app/src/pages/playground/InvocationParametersForm.tsx
  app/src/pages/playground/ModelConfigButton.tsx
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/__generated__/InvocationParametersFormQuery.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/playground/schemas.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
Labels: size:XL, DO NOT MERGE

#5173 fix(styles): make prompt section scrollable to the bottom
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundTools.tsx
  app/src/pages/playground/SpanPlaygroundPage.tsx
Labels: size:M

#5175 fix: fix import in chatbot tutorial
  tutorials/human_feedback/chatbot_with_human_feedback.ipynb
Labels: size:XS

#5179 docs: create lamaindex workflows example
  examples/llamaindex-workflows-research-agent/.env.example
  examples/llamaindex-workflows-research-agent/.gitignore
  examples/llamaindex-workflows-research-agent/README.md
  examples/llamaindex-workflows-research-agent/compress.py
  examples/llamaindex-workflows-research-agent/evaluate_traces.ipynb
  examples/llamaindex-workflows-research-agent/report.pdf
  examples/llamaindex-workflows-research-agent/report.py
  examples/llamaindex-workflows-research-agent/requirements.txt
  examples/llamaindex-workflows-research-agent/research_assistant_workflow.html
  examples/llamaindex-workflows-research-agent/run.py
  examples/llamaindex-workflows-research-agent/subquery.py
  examples/llamaindex-workflows-research-agent/tavily.py
  examples/llamaindex-workflows-research-agent/workflow.py
Labels: size:XL

#5176 docs: create langgraph_agent_tracing_tutorial.ipynb
  tutorials/tracing/langgraph_agent_tracing_tutorial.ipynb
Labels: size:XL

#5172 fix: update to properly initialize when brought into view
  app/src/components/code/JSONEditor.tsx
  app/src/components/code/LazyEditorWrapper.tsx
  app/src/components/generative/ToolChoiceSelector.tsx
  app/src/pages/playground/PlaygroundTool.tsx
Labels: size:L

#5188 fix(playground): improve playground error handling
  app/schema.graphql
  app/src/pages/playground/PlaygroundOutput.tsx
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  src/phoenix/server/api/subscriptions.py
  tests/unit/server/api/cassettes/test_subscriptions/TestChatCompletionSubscription.test_openai_emits_expected_payloads_and_records_expected_span_on_error[sqlite].yaml
  tests/unit/server/api/test_subscriptions.py
Labels: size:L
