Repository Arize-ai/phoenix, pull requests merged in 2025-05, with the labels that each got.

#7357 feat(annotations): Paginate between traces on spans table or traces table
  app/src/components/FocusHotkey.tsx
  app/src/components/KeyboardToken.tsx
  app/src/components/content/Keyboard.tsx
  app/src/components/index.tsx
  app/src/components/table/styles.ts
  app/src/components/trace/SpanAnnotationsEditor.tsx
  app/src/constants/searchParams.ts
  app/src/pages/example/ExampleDetailsDialog.tsx
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
  app/src/pages/playground/RunMetadataFooter.tsx
  app/src/pages/playground/SpanPlaygroundPage.tsx
  app/src/pages/project/ProjectSpansPage.tsx
  app/src/pages/project/ProjectTracesPage.tsx
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
  app/src/pages/trace/SessionDetailsTraceList.tsx
  app/src/pages/trace/SpanAside.tsx
  app/src/pages/trace/SpanDetails.tsx
  app/src/pages/trace/SpanNotesEditor.tsx
  app/src/pages/trace/TraceDetails.tsx
  app/src/pages/trace/TraceDetailsPaginator.tsx
  app/src/pages/trace/TracePage.tsx
  app/src/pages/trace/TracePaginationContext.tsx
Labels: size:XL

#7376 feat(components): video for tutorials
  app/src/components/media/Video.tsx
  app/src/components/media/index.tsx
  app/stories/Video.stories.tsx
Labels: size:L

#7379 chore(main): release arize-phoenix 8.31.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7369 chore: use phoenix client in notebook for human feedback
  tutorials/human_feedback/chatbot_with_human_feedback.ipynb
Labels: size:M

#7365 test: ensure 0 score for annotation is not treated as falsey
  tests/integration/client/test_annotations.py
Labels: size:L

#7366 feat: add `get_span_annotations_dataframe` to client
  packages/phoenix-client/src/phoenix/client/resources/spans/__init__.py
  src/phoenix/server/api/routers/v1/annotations.py
Labels: size:L

#7380 feat(onboarding): datasets empty
  app/src/components/button/ExternalLinkButton.tsx
  app/src/components/button/index.tsx
  app/src/components/icon/Icons.tsx
  app/src/components/index.tsx
  app/src/components/table/TableEmpty.tsx
  app/src/components/table/TableEmptyWrap.tsx
  app/src/components/table/index.tsx
  app/src/pages/datasets/DatasetsEmpty.tsx
  app/src/pages/datasets/DatasetsTable.tsx
Labels: size:L

#7384 feat: Stabilize categorical annotation summary pie chart colors
  app/src/RelayEnvironment.ts
  app/src/components/annotation/AnnotationSummaryGroup.tsx
  app/src/components/annotation/__generated__/AnnotationSummaryGroup.graphql.ts
  app/src/components/trace/SpanAnnotationsEditor.tsx
  app/src/components/trace/__generated__/SpanAnnotationsEditorCreateAnnotationMutation.graphql.ts
  app/src/components/trace/__generated__/SpanAnnotationsEditorDeleteAnnotationMutation.graphql.ts
  app/src/components/trace/__generated__/SpanAnnotationsEditorEditAnnotationMutation.graphql.ts
  app/src/pages/project/AnnotationSummary.tsx
  app/src/pages/project/__generated__/AnnotationSummaryQuery.graphql.ts
  app/src/pages/project/__generated__/AnnotationSummaryValueFragment.graphql.ts
  app/src/pages/project/__generated__/AnnotationSummaryValueQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectPageQueriesSpansQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectPageQueriesTracesQuery.graphql.ts
  app/src/pages/project/__generated__/SpansTableSpansQuery.graphql.ts
  app/src/pages/project/__generated__/TracesTableQuery.graphql.ts
  app/src/pages/trace/__generated__/SessionDetailsQuery.graphql.ts
  app/src/pages/trace/__generated__/SpanDetailsQuery.graphql.ts
  app/src/pages/trace/__generated__/TraceHeaderRootSpanAnnotationsQuery.graphql.ts
Labels: size:XXL

#7387 docs: autogen agent notebooks
  tutorials/agents/autogen/autogen_agents_evaluator_optimizer.ipynb
  tutorials/agents/autogen/autogen_agents_orchestrator.ipynb
  tutorials/agents/autogen/autogen_agents_parallelization.ipynb
  tutorials/agents/autogen/autogen_agents_prompt_chaining.ipynb
  tutorials/agents/autogen/autogen_agents_routing.ipynb
Labels: size:XXL

#7342 refactor(annotations): use single unique constraints for identifiers
  packages/phoenix-client/src/phoenix/client/__generated__/v1/.dataclass.txt
  src/phoenix/db/insertion/evaluation.py
  src/phoenix/db/insertion/helpers.py
  src/phoenix/db/migrations/versions/2f9d1a65945f_annotation_config_migration.py
  src/phoenix/db/models.py
  src/phoenix/server/api/input_types/CreateSpanAnnotationInput.py
  src/phoenix/server/api/input_types/CreateTraceAnnotationInput.py
  src/phoenix/server/api/input_types/PatchAnnotationInput.py
  src/phoenix/server/api/mutations/span_annotations_mutations.py
  src/phoenix/server/api/mutations/trace_annotations_mutations.py
  src/phoenix/server/api/routers/v1/spans.py
  src/phoenix/server/api/types/SpanAnnotation.py
  src/phoenix/server/api/types/TraceAnnotation.py
  tests/integration/db_migrations/test_data_migration_2f9d1a65945f_annotation_config_migration.py
  tests/unit/server/api/dataloaders/conftest.py
  tests/unit/server/api/mutations/test_dataset_mutations.py
  tests/unit/server/api/types/test_Project.py
  tests/unit/server/api/types/test_SpanAnnotation.py
  tests/unit/server/api/types/test_TraceAnnotation.py
  tests/unit/trace/dsl/conftest.py
Labels: size:XXL

#7394 feat: Update human feedback notebook with pulling annotations
  packages/phoenix-client/src/phoenix/client/resources/spans/__init__.py
  tutorials/human_feedback/chatbot_with_human_feedback.ipynb
Labels: size:M

#7398 chore: Add hub links to readme
  README.md
Labels: size:XS

#7402 feat: Simple support for message_contents span content in playground
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/playground/schemas.ts
Labels: size:M

#7404 fix: normalize gemini roles
  app/src/constants/generativeConstants.ts
  app/src/hooks/useChatMessageStyles.ts
  app/src/pages/playground/constants.tsx
  app/src/pages/playground/playgroundUtils.ts
Labels: size:M

#7299 chore(main): release arize-phoenix-client 1.4.0
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#7418 fix: Prevent time range context error when opening trace details slideover
  app/src/components/datetime/TimeRangeContext.tsx
  app/src/components/trace/SpanAnnotationsEditor.tsx
Labels: size:S

#7408 fix: quick metadata filters for nested fields
  app/src/pages/project/MetadataTooltip.tsx
Labels: size:XS

#7421 chore: update plpgsql script for span annotations to include identifier and other new columns
  scripts/generate_data_via_plpgsql/generate_span_annotations.py
  scripts/generate_data_via_plpgsql/generate_span_annotations.sql
Labels: size:L

#7423 ci: clean notebook
  .github/workflows/python-CI.yml
  tutorials/human_feedback/chatbot_with_human_feedback.ipynb
Labels: size:S

#7414 fix(annotations): ensure user identifiers are stable
  src/phoenix/server/api/mutations/span_annotations_mutations.py
  src/phoenix/server/api/mutations/trace_annotations_mutations.py
Labels: size:M

#7391 feat: Adding demo_agent project with traces
  src/phoenix/trace/fixtures.py
Labels: size:S

#7427 fix: use leading visual for the icon
  app/src/components/trace/AnnotationConfigList.tsx
Labels: size:XS

#7429 ci: phoenix client ci
  .github/workflows/python-CI.yml
  packages/phoenix-client/src/phoenix/client/resources/spans/__init__.py
Labels: size:S

#7428 fix: handle ssl query params in postgresql connection strings
  internal_docs/vignettes/postgresql_tls/.gitignore
  internal_docs/vignettes/postgresql_tls/README.md
  internal_docs/vignettes/postgresql_tls/docker-compose.yaml
  internal_docs/vignettes/postgresql_tls/generate_pg_certs.py
  internal_docs/vignettes/postgresql_tls/pg_hba.conf
  internal_docs/vignettes/postgresql_tls/postgresql.conf
  internal_docs/vignettes/postgresql_tls/test_connection.py
  requirements/unit-tests.txt
  src/phoenix/db/engines.py
  src/phoenix/db/pg_config.py
  tests/unit/db/test_pg_config.py
Labels: size:XXL

#7432 docs: add google-genai
  README.md
Labels: size:XS

#7442 feat: style keyboard tokens to look more like keys
  app/src/components/KeyboardToken.tsx
  app/stories/KeyboardToken.stories.tsx
Labels: size:M

#7439 fix: Polish annotations UI
  app/src/components/FocusHotkey.tsx
  app/src/components/ShareLinkButton.tsx
  app/src/components/annotation/AnnotationInputExplanation.tsx
  app/src/components/annotation/AnnotationSummaryGroup.tsx
  app/src/components/annotation/ContinuousAnnotationInput.tsx
  app/src/components/icon/Icons.tsx
  app/src/components/trace/SpanAnnotationsEditor.tsx
  app/src/contexts/ViewerContext.tsx
  app/src/pages/settings/AnnotationConfigDialog.tsx
  app/src/pages/settings/AnnotationConfigTable.tsx
  app/src/pages/settings/SettingsAnnotationsPage.tsx
  app/src/pages/settings/__generated__/SettingsAnnotationsPageCreateAnnotationConfigMutation.graphql.ts
  app/src/pages/settings/__generated__/SettingsAnnotationsPageDeleteAnnotationConfigsMutation.graphql.ts
  app/src/pages/settings/__generated__/SettingsAnnotationsPageUpdateAnnotationConfigMutation.graphql.ts
  app/src/pages/trace/SpanAside.tsx
  app/src/pages/trace/SpanDetails.tsx
Labels: size:XL

#7443 fix(annotations): ensure response types for annotation configs are nested under a data key
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py
  schemas/openapi.json
  src/phoenix/server/api/routers/v1/annotation_configs.py
  tests/unit/server/api/routers/v1/test_annotation_configs.py
Labels: size:L

#7444 feat(ui): Group component with refactored pagination buttons
  app/src/components/icon/Icons.tsx
  app/src/components/layout/Group.tsx
  app/src/components/layout/index.tsx
  app/src/pages/trace/TraceDetailsPaginator.tsx
  app/stories/Group.stories.tsx
Labels: size:L

#7445 feat: Add sorting to span annotations table
  app/src/pages/trace/SpanFeedback.tsx
Labels: size:M

#7448 fix(annotations): Write to annotation explanation instead of label for freeform annotations
  app/src/components/annotation/AnnotationSummaryGroup.tsx
  app/src/components/annotation/FreeformAnnotationInput.tsx
  app/src/components/trace/SpanAnnotationInput.tsx
Labels: size:M

#7447 refactor(annotations): revert upsert logic
  src/phoenix/server/api/routers/v1/spans.py
Labels: size:M

#7446 fix: Avoid division by zero
  src/phoenix/server/api/dataloaders/annotation_summaries.py
  tests/unit/server/api/dataloaders/conftest.py
  tests/unit/server/api/dataloaders/test_annotation_summaries.py
Labels: size:L

#7406 feat: Update spans dsl to search for annotation existence
  src/phoenix/trace/dsl/filter.py
  tests/unit/trace/dsl/test_filter.py
  tests/unit/trace/dsl/test_query.py
Labels: size:M

#7452 refactor: use eva share icon
  app/src/components/ShareLinkButton.tsx
  app/src/components/icon/Icons.tsx
Labels: size:M

#7457 fix: button hotkey visuals
  app/src/components/button/styles.tsx
  app/src/components/content/Keyboard.tsx
  app/src/pages/trace/SpanDetails.tsx
  app/src/pages/trace/TraceDetailsPaginator.tsx
Labels: size:M

#7458 fix: pass null user for unauthenticated
  app/src/components/annotation/AnnotationInputExplanation.tsx
  app/src/components/trace/SpanAnnotationsEditor.tsx
  app/src/components/trace/__generated__/SpanAnnotationsEditorCreateAnnotationMutation.graphql.ts
  app/src/components/trace/__generated__/SpanAnnotationsEditorDeleteAnnotationMutation.graphql.ts
  app/src/components/trace/__generated__/SpanAnnotationsEditorEditAnnotationMutation.graphql.ts
Labels: size:M

#7459 fix(annotations): make identifier type non-optional in rest and graphql apis
  app/schema.graphql
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  schemas/openapi.json
  src/phoenix/server/api/input_types/CreateSpanAnnotationInput.py
  src/phoenix/server/api/input_types/CreateTraceAnnotationInput.py
  src/phoenix/server/api/input_types/PatchAnnotationInput.py
  src/phoenix/server/api/mutations/span_annotations_mutations.py
  src/phoenix/server/api/mutations/trace_annotations_mutations.py
  src/phoenix/server/api/routers/v1/spans.py
  src/phoenix/server/api/routers/v1/traces.py
  src/phoenix/server/api/types/SpanAnnotation.py
  src/phoenix/server/api/types/TraceAnnotation.py
  tests/unit/server/api/mutations/test_span_annotation_mutations.py
Labels: size:M

#7461 docs(annotations): add MIGRATION warning
  MIGRATION.md
Labels: size:XS

#7463 fix: bump litellm minimum version
  requirements/unit-tests.txt
Labels: size:XS

#7464 fix: step for number of days should be 1
  app/src/pages/settings/RetentionPolicyForm.tsx
  app/src/pages/trace/__generated__/SpanFeedback_annotations.graphql.ts
Labels: size:XS

#7468 fix: cleanup security warnings for js
  js/package.json
  js/pnpm-lock.yaml
Labels: size:S

#7467 fix: make it clear in the UI that cron expression applies to times in UTC
  app/src/pages/project/ProjectRetentionPolicyCard.tsx
  app/src/pages/settings/RetentionPoliciesTable.tsx
  app/src/pages/settings/RetentionPolicyForm.tsx
  app/src/utils/retentionPolicyUtils.ts
Labels: size:M

#7469 chore: add codeowners
  .github/CODEOWNERS
Labels: size:XS

#7354 docs: fixed typo parent_id => parent_span_id tracing guide
  docs/tracing/concepts-tracing/what-are-traces.md
Labels: size:XS

#7465 fix: add flag for `orphan_span_as_root_span` on client for span query
  scripts/generate_data_via_plpgsql/README.md
  scripts/generate_data_via_plpgsql/generate_spans.sql
  scripts/perf/get_spans_dataframe_for_random_conversation_id.py
  src/phoenix/server/api/routers/v1/spans.py
  src/phoenix/session/client.py
  src/phoenix/trace/dsl/query.py
Labels: size:L

#7436 chore(main): release arize-phoenix 8.32.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7471 fix: replace joinedload with selectinload for retention policy query
  src/phoenix/server/retention.py
  tests/unit/server/test_retention.py
Labels: size:L

#7473 chore: remove stale comment
  src/phoenix/db/migrations/versions/2f9d1a65945f_annotation_config_migration.py
Labels: size:XS

#7472 chore: db migration test helpers
  tests/integration/db_migrations/__init__.py
Labels: size:L

#7475 fix: use server default for identifier
  src/phoenix/db/migrations/versions/2f9d1a65945f_annotation_config_migration.py
  src/phoenix/db/models.py
  tests/integration/db_migrations/test_data_migration_2f9d1a65945f_annotation_config_migration.py
Labels: size:S

#7478 refactor: move share to the top of the page
  app/src/components/ShareLinkButton.tsx
  app/src/components/button/styles.tsx
  app/src/components/content/Keyboard.tsx
  app/src/pages/trace/SpanDetails.tsx
  app/src/pages/trace/TraceDetailsPaginator.tsx
  app/src/pages/trace/TracePage.tsx
Labels: size:M

#7479 refactor: change more places to say annotations
  app/src/components/annotation/AnnotationInputExplanation.tsx
  app/src/components/annotation/AnnotationSummaryPopover.tsx
  app/src/components/counter/Counter.tsx
  app/src/pages/project/AnnotationTooltipFilterActions.tsx
  app/src/pages/project/SpanColumnSelector.tsx
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
  app/src/pages/trace/SpanAside.tsx
  app/src/pages/trace/SpanDetails.tsx
Labels: size:M

#7480 feat(auth): add arize auth, auto trigger login
  app/src/pages/auth/LoginPage.tsx
  app/src/pages/auth/OAuth2Login.tsx
  tox.ini
Labels: size:M

#7484 fix: Improve client semantics 2
  packages/phoenix-client/src/phoenix/client/helpers/sdk/anthropic/messages.py
  packages/phoenix-client/src/phoenix/client/resources/spans/__init__.py
  tutorials/human_feedback/chatbot_with_human_feedback.ipynb
Labels: size:L

#7487 fix(security): fix for code scanning alert no. 42: Workflow does not contain permissions
  .github/workflows/clean_up_caches.yml
  .github/workflows/collect-customer-issues.yaml
  .github/workflows/openapi-schema.yaml
  .github/workflows/playwright.yaml
  .github/workflows/python-CI.yml
  .github/workflows/python-cron.yml
  .github/workflows/typescript-CI.yml
  .github/workflows/typescript-packages-CI.yml
  .github/workflows/typescript-packages-publish.yml
Labels: size:S

#7490 fix: Add pre requisite build to `/app` develop docs
  app/README.md
Labels: size:XS

#7062 fix: updated final questions to run properly in langgraph agent nb
  tutorials/tracing/langgraph_agent_tracing_tutorial.ipynb
Labels: size:M

#7456 fix(annotations): revert bulk insert
  .github/workflows/python-CI.yml
  src/phoenix/db/insertion/document_annotation.py
  src/phoenix/db/insertion/span_annotation.py
  src/phoenix/db/insertion/trace_annotation.py
  src/phoenix/db/insertion/types.py
  src/phoenix/server/api/routers/v1/evaluations.py
  tests/integration/_helpers.py
  tests/integration/client/test_annotations.py
  tests/integration/conftest.py
  tests/unit/server/api/routers/v1/test_annotations.py
Labels: size:XXL

#7407 fix: formatting issues incase of escaped characters
  packages/phoenix-client/src/phoenix/client/utils/template_formatters.py
  packages/phoenix-client/tests/utils/test_template_formatters.py
Labels: size:L

#7497 chore: Bump phoenix-client package version
  js/.changeset/vast-carrots-run.md
Labels: size:XS

#7491 fix: MCP tutorial extended timeout
  tutorials/mcp/tracing_between_mcp_client_and_server/client.py
Labels: size:XS

#7460 docs: new agent notebooks for all OpenAI patterns
  tutorials/agents/openai/openai_agents_basic.ipynb
  tutorials/agents/openai/openai_agents_evaluator_optimizer.ipynb
  tutorials/agents/openai/openai_agents_orchestrator.ipynb
  tutorials/agents/openai/openai_agents_parallelization.ipynb
  tutorials/agents/openai/openai_agents_prompt_chaining.ipynb
  tutorials/agents/openai/openai_agents_routing.ipynb
Labels: size:XXL

#7498 test: annotations client integration tests
  .github/workflows/python-CI.yml
  packages/phoenix-client/src/phoenix/client/helpers/sdk/anthropic/messages.py
  packages/phoenix-client/src/phoenix/client/resources/spans/__init__.py
  tests/integration/client/test_spans.py
Labels: size:L

#7501 fix(annotations): ensure patching an annotation via UI updates source to APP
  app/schema.graphql
  app/src/components/trace/SpanAnnotationsEditor.tsx
  app/src/components/trace/__generated__/SpanAnnotationsEditorEditAnnotationMutation.graphql.ts
  src/phoenix/server/api/input_types/PatchAnnotationInput.py
  src/phoenix/server/api/mutations/span_annotations_mutations.py
Labels: size:S

#7502 ci: fix permissions on CI
  .github/workflows/docker-build-experimental.yml
  .github/workflows/docker-build-nightly.yml
  .github/workflows/docker-build-release.yml
  .github/workflows/pull-requests.yaml
  .github/workflows/typescript-packages-publish.yml
Labels: size:S

#7503 ci: fix perms
  .github/workflows/typescript-packages-publish-experimental.yml
  .github/workflows/typescript-packages-publish.yml
Labels: size:XS

#7485 chore(main): release arize-phoenix 9.0.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:L

#7493 chore(main): release arize-phoenix-client 1.5.0
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#7507 ci: dubug only for experimental docker image variant
  .github/workflows/docker-build-experimental.yml
Labels: size:XS

#7385 chore: add internal vignette for polymorphic user
  internal_docs/vignettes/sqlalchemy/polymorphic_user/README.md
  internal_docs/vignettes/sqlalchemy/polymorphic_user/users.py
Labels: size:XL

#7266 chore: add json vs jsonb demo scripts
  internal_docs/vignettes/json-jsonb-demo/.eslintrc.cjs
  internal_docs/vignettes/json-jsonb-demo/.gitignore
  internal_docs/vignettes/json-jsonb-demo/.prettierrc.json
  internal_docs/vignettes/json-jsonb-demo/README.md
  internal_docs/vignettes/json-jsonb-demo/package.json
  internal_docs/vignettes/json-jsonb-demo/pnpm-lock.yaml
  internal_docs/vignettes/json-jsonb-demo/src/compare.ts
  internal_docs/vignettes/json-jsonb-demo/src/config/db-config.ts
  internal_docs/vignettes/json-jsonb-demo/src/index.ts
  internal_docs/vignettes/json-jsonb-demo/src/performance.ts
  internal_docs/vignettes/json-jsonb-demo/src/query-examples.ts
  internal_docs/vignettes/json-jsonb-demo/src/services/db-service.ts
  internal_docs/vignettes/json-jsonb-demo/src/types/db.types.ts
  internal_docs/vignettes/json-jsonb-demo/tsconfig.json
Labels: size:XXL

#7492 docs: Google genai agent nbs
  tutorials/agents/google-genai/evaluator-optimizer-agent.ipynb
  tutorials/agents/google-genai/orchestration-agent.ipynb
  tutorials/agents/google-genai/parallelization-agent.ipynb
  tutorials/agents/google-genai/routing-agent.ipynb
  tutorials/agents/google-genai/sequential-agent.ipynb
Labels: size:XXL

#7514 fix: pin strawberry
  pyproject.toml
  requirements/build-graphql-schema.txt
  requirements/type-check.txt
Labels: size:S

#7515 chore(main): release arize-phoenix 9.0.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7516 chore: nix uv lockfile
  .gitignore
  uv.lock
Labels: size:XS

#7517 chore: cleanup JSON block
  app/src/components/code/JSONBlock.tsx
  app/src/components/markdown/MarkdownBlock.tsx
  app/src/components/utility/PrettyText.tsx
  app/src/pages/trace/SpanDetails.tsx
Labels: size:L

#7508 fix: content wrap in markdown block
  app/src/components/markdown/styles.ts
Labels: size:XS

#7494 feat: Open span details sections when hotkeys are pressed
  app/src/pages/trace/SpanAside.tsx
Labels: size:S

#7527 fix: remove version lower bound for starlette
  pyproject.toml
  src/phoenix/server/middleware/gzip.py
  tests/unit/server/middleware/__init__.py
  tests/unit/server/middleware/test_gzip.py
Labels: size:L

#7519 feat(arize-phoenix-client): annotation methods
  js/.changeset/ripe-readers-sniff.md
  js/packages/phoenix-client/.cursor/rules/general.mdc
  js/packages/phoenix-client/package.json
  js/packages/phoenix-client/src/spans/addSpanAnnotation.ts
  js/packages/phoenix-client/src/spans/index.ts
  js/packages/phoenix-client/src/spans/logSpanAnnotations.ts
  js/packages/phoenix-client/src/spans/types.ts
  js/packages/phoenix-client/test/spans/addSpanAnnotation.test.ts
  js/packages/phoenix-client/test/spans/logSpanAnnotations.test.ts
Labels: size:L

#7453 feat: List, sort, and filter projects in UI
  app/schema.graphql
  app/src/components/LoadMoreButton.tsx
  app/src/components/content/Heading.tsx
  app/src/components/table/LoadMoreRow.tsx
  app/src/pages/project/SpansTable.tsx
  app/src/pages/projects/NewProjectButton.tsx
  app/src/pages/projects/ProjectActionMenu.tsx
  app/src/pages/projects/ProjectViewModeToggle.tsx
  app/src/pages/projects/ProjectsPage.tsx
  app/src/pages/projects/ProjectsSearch.tsx
  app/src/pages/projects/__generated__/ProjectsPageProjectsFragment.graphql.ts
  app/src/pages/projects/__generated__/ProjectsPageProjectsQuery.graphql.ts
  app/src/pages/projects/__generated__/ProjectsPageQuery.graphql.ts
  app/src/store/preferencesStore.tsx
  src/phoenix/server/api/input_types/ProjectFilter.py
  src/phoenix/server/api/input_types/ProjectSort.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/Project.py
  tests/unit/server/api/types/test_Project.py
Labels: size:XXL

#7518 chore(main): release arize-phoenix 9.1.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7532 docs: add mcp and agno to readme
  README.md
Labels: size:XS

#7368 fix: allow `context.span_id` as column name in pandas dataframe
  packages/phoenix-client/src/phoenix/client/resources/annotations/__init__.py
  packages/phoenix-client/tests/client/resources/annotations/test_annotations.py
Labels: size:L

#7537 feat(ui): agno, mcp, gemini integrations
  app/src/components/project/IntegrationIcons.tsx
  app/src/components/project/Integrations.tsx
  app/src/components/project/PythonProjectGuide.tsx
Labels: size:L

#7535 chore(main): release arize-phoenix 9.2.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7531 docs: update chatbot for annotations
  tutorials/human_feedback/chatbot_with_human_feedback.ipynb
Labels: size:L

#7539 feat: add claude 3.7
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:XS

#7541 feat(ts): experiments run in queues
  js/.changeset/itchy-frogs-burn.md
  js/examples/apps/phoenix-experiment-runner/index.ts
  js/packages/phoenix-client/package.json
  js/packages/phoenix-client/src/experiments/runExperiment.ts
  js/packages/phoenix-client/src/types/experiments.ts
  js/pnpm-lock.yaml
Labels: size:L

#7543 feat(api): expose experiment routes
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py
  schemas/openapi.json
  src/phoenix/server/api/routers/v1/experiment_evaluations.py
  src/phoenix/server/api/routers/v1/experiment_runs.py
Labels: size:XL

#7546 feat(phoenix-client): Record experiment results to Phoenix server
  js/.changeset/big-yaks-relate.md
  js/examples/apps/phoenix-experiment-runner/index.ts
  js/packages/phoenix-client/src/experiments/runExperiment.ts
  js/packages/phoenix-client/src/types/annotations.ts
  js/packages/phoenix-client/src/types/experiments.ts
Labels: size:L

#7542 chore(main): release arize-phoenix 9.3.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7549 chore: Pin changesets action sha
  .github/workflows/typescript-packages-publish.yml
Labels: size:XS

#7554 feat(dashboards): rudamentary routes for dashboards
  app/package.json
  app/pnpm-lock.yaml
  app/src/App.tsx
  app/src/Routes.tsx
  app/src/components/icon/Icons.tsx
  app/src/contexts/FeatureFlagsContext.tsx
  app/src/pages/Layout.tsx
  app/src/pages/dashboard/DashboardPage.tsx
  app/src/pages/dashboard/index.tsx
  app/src/pages/dashboards/DashboardsPage.tsx
  app/src/pages/dashboards/index.tsx
Labels: size:L

#7499 fix: Stabilize label extraction
  packages/phoenix-evals/src/phoenix/evals/classify.py
  packages/phoenix-evals/src/phoenix/evals/evaluators.py
  packages/phoenix-evals/src/phoenix/evals/templates.py
  packages/phoenix-evals/tests/phoenix/evals/functions/test_classify.py
Labels: size:S

#7552 chore: Update runExperiment doc block
  js/packages/phoenix-client/src/experiments/runExperiment.ts
Labels: size:S

#7551 feat(ts-client): add experiment tracing
  js/examples/apps/phoenix-experiment-runner/index.ts
  js/examples/apps/phoenix-experiment-runner/instrumentation.ts
  js/examples/apps/phoenix-experiment-runner/package.json
  js/packages/phoenix-client/package.json
  js/packages/phoenix-client/src/client.ts
  js/packages/phoenix-client/src/experiments/instrumention.ts
  js/packages/phoenix-client/src/experiments/runExperiment.ts
  js/packages/phoenix-client/src/types/experiments.ts
  js/packages/phoenix-client/src/utils/ensureString.ts
  js/packages/phoenix-client/src/utils/objectAsAttributes.ts
  js/pnpm-lock.yaml
Labels: size:XL

#7557 chore: changeset
  js/.changeset/legal-dingos-count.md
Labels: size:XS

#7536 chore(main): release arize-phoenix-client 1.6.0
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#7559 chore: Suppress extraneous node warnings in phoenix runner cli
  js/examples/apps/phoenix-experiment-runner/package.json
Labels: size:XS

#7556 docs: adding crewai workflow tutorials
  tutorials/agents/crewai/crewai_ parallelization_tutorial.ipynb
  tutorials/agents/crewai/crewai_orchestrator_workers_tutorial.ipynb
  tutorials/agents/crewai/crewai_prompt_chaining_tutorial.ipynb
  tutorials/agents/crewai/crewai_routing_tutorial.ipynb
Labels: size:XXL

#7565 fix: correct limit clause placement in span query statement
  src/phoenix/trace/dsl/query.py
Labels: size:XS

#7575 docs: update docstring for description of experiment evaluators
  src/phoenix/experiments/functions.py
Labels: size:S

#7581 fix: check sql validity of filter expression
  src/phoenix/server/api/types/Project.py
  tests/unit/server/api/types/test_Project.py
Labels: size:M

#7564 feat(dashboards): dashboard panel
  app/package.json
  app/pnpm-lock.yaml
  app/src/App.tsx
  app/src/GlobalStyles.tsx
  app/src/Routes.tsx
  app/src/pages/dashboard/DashboardBarChart.tsx
  app/src/pages/dashboard/DashboardPage.tsx
  app/src/pages/dashboard/DashboardPanel.tsx
  app/src/pages/dashboard/ProjectDashboardPage.tsx
  app/src/pages/dashboard/__generated__/projectDashboardLoaderQuery.graphql.ts
  app/src/pages/dashboard/index.tsx
  app/src/pages/dashboard/projectDashboardLoader.tsx
  app/src/pages/dashboards/DashboardsPage.tsx
  app/src/pages/dashboards/DashboardsRoot.tsx
  app/src/pages/dashboards/ProjectDashboardsTable.tsx
  app/src/pages/dashboards/__generated__/ProjectDashboardsTableProjectsQuery.graphql.ts
  app/src/pages/dashboards/__generated__/ProjectDashboardsTable_projects.graphql.ts
  app/src/pages/dashboards/__generated__/dashboardsLoaderQuery.graphql.ts
  app/src/pages/dashboards/dashboardsLoader.tsx
  app/src/pages/dashboards/index.tsx
Labels: size:XXL

#6997 feat: graphql query for hourly span count timeseries
  app/schema.graphql
  packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py
  src/phoenix/server/api/types/Project.py
  tests/__generated__/graphql/__init__.py
  tests/unit/server/api/types/test_Project.py
Labels: size:L

#7510 docs: adding agent pattern example notebooks (Langgraph)
  tutorials/agents/langgraph/langgraph_evaluator.ipynb
  tutorials/agents/langgraph/langgraph_orchestrator.ipynb
  tutorials/agents/langgraph/langgraph_parallel.ipynb
  tutorials/agents/langgraph/langgraph_promptchaining.ipynb
  tutorials/agents/langgraph/langgraph_router.ipynb
Labels: size:XXL

#7576 chore(main): release arize-phoenix 9.5.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7594 feat(experiments): typescript example
  app/src/pages/dataset/RunExperimentButton.tsx
Labels: size:L

#7611 chore(ci): run Playwright tests on changes to src/ or app/ directories
  .github/workflows/playwright.yaml
Labels: size:XS

#7577 feat: Model cost lookup table
  pyproject.toml
  src/phoenix/server/cost_tracking/__init__.py
  src/phoenix/server/cost_tracking/cost_lookup.py
  src/phoenix/server/cost_tracking/model_cost_manifest.json
  tests/unit/server/cost_tracking/test_cost_lookup.py
Labels: size:XXL

#7623 fix: anthropic 3.7 sonnet mis-spelled
  app/src/pages/playground/PlaygroundOutput.tsx
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:XS

#7621 feat(cost): add token prompt details resolver on span node
  app/schema.graphql
  src/phoenix/server/api/types/Span.py
  src/phoenix/server/api/types/TokenCountPromptDetails.py
Labels: size:M

#7630 fix(datasets): support csv + jsonl download of datasets with unicode file names
  src/phoenix/server/api/routers/v1/datasets.py
  tests/unit/server/api/routers/v1/test_datasets.py
Labels: size:M

#7595 chore(main): release arize-phoenix 9.6.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7560 docs: smolagents tutorials
  tutorials/agents/smolagents/smolagents_evaluator_optimizer.ipynb
  tutorials/agents/smolagents/smolagents_orchestrator.ipynb
  tutorials/agents/smolagents/smolagents_parallelization.ipynb
  tutorials/agents/smolagents/smolagents_prompt_chaining.ipynb
  tutorials/agents/smolagents/smolagents_router.ipynb
Labels: size:XXL

#7593 feat: getExperiment, evaluateExperiment, createDataset phoenix client methods
  js/.changeset/famous-onions-camp.md
  js/examples/apps/phoenix-experiment-runner/index.ts
  js/packages/phoenix-client/README.md
  js/packages/phoenix-client/examples/README.md
  js/packages/phoenix-client/examples/evaluate_experiment.ts
  js/packages/phoenix-client/examples/run_experiment.ts
  js/packages/phoenix-client/package.json
  js/packages/phoenix-client/src/datasets/appendDatasetExamples.ts
  js/packages/phoenix-client/src/datasets/createDataset.ts
  js/packages/phoenix-client/src/datasets/getDataset.ts
  js/packages/phoenix-client/src/datasets/getDatasetExamples.ts
  js/packages/phoenix-client/src/datasets/getDatasetInfo.ts
  js/packages/phoenix-client/src/datasets/index.ts
  js/packages/phoenix-client/src/datasets/listDatasets.ts
  js/packages/phoenix-client/src/experiments/getExperiment.ts
  js/packages/phoenix-client/src/experiments/getExperimentInfo.ts
  js/packages/phoenix-client/src/experiments/getExperimentRuns.ts
  js/packages/phoenix-client/src/experiments/index.ts
  js/packages/phoenix-client/src/experiments/runExperiment.ts
  js/packages/phoenix-client/src/types/datasets.ts
  js/packages/phoenix-client/src/types/experiments.ts
  js/packages/phoenix-client/src/utils/getDatasetBySelector.ts
  js/packages/phoenix-client/test/datasets/getDataset.test.ts
  js/packages/phoenix-client/test/experiments/runExperiment.test.ts
Labels: size:XXL

#7628 fix(experiments): make experiment columns resizable
  app/src/components/table/CellWithControlsWrapper.tsx
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/utils/tableUtils.ts
  scripts/data/generate_experiments.py
Labels: size:L

#7641 chore(main): release arize-phoenix 9.6.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7638 fix: fix the onobarding for typescript docs to use the datasetSelector
  app/src/pages/dataset/RunExperimentButton.tsx
Labels: size:XS

#7640 feat: Add URL logging for experiments in TypeScript client
  js/.changeset/chatty-memes-look.md
  js/packages/phoenix-client/src/experiments/runExperiment.ts
  js/packages/phoenix-client/src/utils/urlUtils.ts
Labels: size:L

#7588 chore(main): release arize-phoenix-client 1.7.0
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#7645 chore(main): release arize-phoenix 10.0.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7643 refactor(cost): lazily load token counts
  app/src/components/trace/TokenCount.tsx
  app/src/components/trace/TraceTree.tsx
  app/src/components/trace/__generated__/TokenCount_TokenDetailsQuery.graphql.ts
  app/src/components/trace/types.ts
  app/src/pages/SpanHeader.tsx
  app/src/pages/__generated__/SpanHeader_span.graphql.ts
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
  app/src/pages/playground/RunMetadataFooter.tsx
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableMutation.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableSubscription.graphql.ts
  app/src/pages/playground/__generated__/RunMetadataFooterQuery.graphql.ts
  app/src/pages/project/SessionsTable.tsx
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
  app/src/pages/project/__generated__/ProjectPageQueriesSessionsQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectPageQueriesSpansQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectPageQueriesTracesQuery.graphql.ts
  app/src/pages/project/__generated__/SessionsTableQuery.graphql.ts
  app/src/pages/project/__generated__/SessionsTable_sessions.graphql.ts
  app/src/pages/project/__generated__/SpansTableSpansQuery.graphql.ts
  app/src/pages/project/__generated__/SpansTable_spans.graphql.ts
  app/src/pages/project/__generated__/TracesTableQuery.graphql.ts
  app/src/pages/project/__generated__/TracesTable_spans.graphql.ts
  app/src/pages/trace/SessionDetails.tsx
  app/src/pages/trace/SessionDetailsTraceList.tsx
  app/src/pages/trace/SpanAside.tsx
  app/src/pages/trace/SpanDetails.tsx
  app/src/pages/trace/TraceDetails.tsx
  app/src/pages/trace/__generated__/SessionDetailsQuery.graphql.ts
  app/src/pages/trace/__generated__/SpanAside_span.graphql.ts
  app/src/pages/trace/__generated__/SpanDetailsQuery.graphql.ts
  app/src/pages/trace/__generated__/TraceDetailsQuery.graphql.ts
Labels: size:XXL

#7651 chore: update ERD in README for db
  src/phoenix/db/README.md
Labels: size:M

#7650 fix: graphql error flicker during OIDC redirect
  app/src/RelayEnvironment.ts
  app/src/authFetch.ts
Labels: size:S

#7658 chore(main): release arize-phoenix 10.0.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7656 docs: add_ts_experiment_quickstart_to_docs
  docs/datasets-and-experiments/quickstart-datasets.md
Labels: size:L

#7664 docs: fix ts imports on experiment doc
  docs/datasets-and-experiments/quickstart-datasets.md
Labels: size:M

#7666 fix: increase prompt fetch limit to 200 and update component to be scrollable
  app/src/pages/playground/PromptComboBox.tsx
  app/src/pages/playground/SavePromptForm.tsx
  app/src/pages/playground/__generated__/PromptComboBoxQuery.graphql.ts
  app/src/pages/playground/__generated__/SavePromptFormQuery.graphql.ts
Labels: size:M

#7670 chore(main): release arize-phoenix 10.0.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7677 fix: update strawberry to fix multipart subscription
  pyproject.toml
  requirements/build-graphql-schema.txt
  requirements/type-check.txt
Labels: size:S

#7678 chore(main): release arize-phoenix 10.0.3
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7701 fix: bump evals and otel as part of the install
  pyproject.toml
Labels: size:XS

#7706 feat: Mcp list projects
  js/.changeset/evil-towns-tie.md
  js/packages/phoenix-mcp/README.md
  js/packages/phoenix-mcp/src/index.ts
  js/packages/phoenix-mcp/src/projectTools.ts
Labels: size:M

#7728 chore: remove inadvertently committed file
  packages/phoenix-client/src/phoenix/client/__generated__/v1/.dataclass.txt
  packages/phoenix-client/src/phoenix/client/__generated__/v1/.gitignore
Labels: size:L

#7671 feat(cost): display audio, cache read, and cache write tokens on span token tooltip
  app/src/components/trace/TokenCount.tsx
  app/src/components/trace/__generated__/TokenCount_TokenDetailsQuery.graphql.ts
Labels: size:L

#7729 ci: ignore pandas type error for pyright
  packages/phoenix-client/src/phoenix/client/resources/annotations/__init__.py
Labels: size:XS

#7727 docs: Create tracing_an_agno_agent.ipynb
  tutorials/agents/agno/tracing_an_agno_agent.ipynb
Labels: size:L

#7734 docs: Portkey initial tracing docs
  docs/section-integrations/frameworks/portkey/README.md
  docs/section-integrations/frameworks/portkey/portkey-tracing.md
Labels: size:L

#7662 feat: Port modal / slideover to react-aria-components
  app/src/GlobalStyles.tsx
  app/src/components/annotation/AnnotationInputExplanation.tsx
  app/src/components/annotation/CategoricalAnnotationInput.tsx
  app/src/components/annotation/ContinuousAnnotationInput.tsx
  app/src/components/annotation/types.ts
  app/src/components/dataset/DatasetPicker.tsx
  app/src/components/dataset/DatasetSelect.tsx
  app/src/components/dataset/NewDatasetButton.tsx
  app/src/components/dataset/__generated__/DatasetSelectQuery.graphql.ts
  app/src/components/dataset/index.tsx
  app/src/components/dialog/Dialog.tsx
  app/src/components/dialog/index.tsx
  app/src/components/index.tsx
  app/src/components/overlay/Modal.tsx
  app/src/components/overlay/Popover.tsx
  app/src/components/trace/AnnotationActionMenu.tsx
  app/src/components/trace/EditSpanAnnotationsDialog.tsx
  app/src/components/trace/SpanAnnotationActionMenu.tsx
  app/src/components/trace/SpanAnnotationInput.tsx
  app/src/components/trace/SpanAnnotationsEditor.tsx
  app/src/contexts/NotificationContext.tsx
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundCredentialsDropdown.tsx
  app/src/pages/playground/PlaygroundDatasetSelect.tsx
  app/src/pages/playground/PlaygroundRunTraceDialog.tsx
  app/src/pages/playground/RunMetadataFooter.tsx
  app/src/pages/project/SpanSelectionToolbar.tsx
  app/src/pages/trace/SpanActionMenu.tsx
  app/src/pages/trace/SpanAside.tsx
  app/src/pages/trace/SpanDetails.tsx
  app/src/pages/trace/SpanFeedback.tsx
  app/src/pages/trace/SpanToDatasetExampleDialog.tsx
  app/src/pages/trace/TracePage.tsx
  app/stories/Dialog.stories.tsx
  app/stories/Modal.stories.tsx
Labels: size:XXL

#7663 feat: Replace "my annotations" with Annotation Summaries
  app/src/components/annotation/AnnotationInputLabel.tsx
  app/src/components/annotation/AnnotationSummaryPopover.tsx
  app/src/components/trace/SpanAnnotationsEditor.tsx
  app/src/components/trace/__generated__/SpanAnnotationsEditorCreateAnnotationMutation.graphql.ts
  app/src/components/trace/__generated__/SpanAnnotationsEditorDeleteAnnotationMutation.graphql.ts
  app/src/components/trace/__generated__/SpanAnnotationsEditorEditAnnotationMutation.graphql.ts
  app/src/pages/trace/SpanAside.tsx
  app/src/pages/trace/SpanDetails.tsx
  app/src/pages/trace/__generated__/SpanAsideAnnotationList_span.graphql.ts
  app/src/pages/trace/__generated__/SpanAside_span.graphql.ts
  app/src/pages/trace/__generated__/SpanDetailsQuery.graphql.ts
Labels: size:XL

#7738 chore: add github link with stars
  app/src/components/nav/GitHubStarCount.tsx
  app/src/components/nav/Navbar.tsx
  app/src/pages/Layout.tsx
Labels: size:M

#7555 chore(main): release arize-phoenix-evals 0.20.7
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#7709 chore: bump dependancies
  js/packages/phoenix-mcp/package.json
  js/packages/phoenix-mcp/src/index.ts
  js/pnpm-lock.yaml
Labels: size:S

#7752 fix: docker-workflow-permissions
  .github/workflows/docker-build-release.yml
Labels: size:XS

#7753 chore: do not collect issues from openinference repo
  .github/.scripts/collect-customer-issues.js
Labels: size:S

#7691 docs: Langgraph RAG manual instrumentation example
  tutorials/agents/langgraph/evaluate-langgraph-rag-manual-instrumentation.py
Labels: size:XL

#7757 chore(main): release arize-phoenix-otel 0.10.1
  .release-please-manifest.json
  packages/phoenix-otel/CHANGELOG.md
  packages/phoenix-otel/pyproject.toml
Labels: autorelease: pending, size:S
