Repository Arize-ai/phoenix, pull requests merged in 2025-08, with the labels that each got.

#8860 chore(main): release arize-phoenix-evals 0.26.0
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#8889 feat: add exporter url to typescript guide
  app/src/components/project/IntegrationIcons.tsx
  app/src/components/project/Integrations.tsx
  app/src/components/project/TypeScriptProjectGuide.tsx
  app/src/pages/projects/NewProjectButton.tsx
Labels: size:L

#8896 refactor: remove empty graphics
  app/.eslintrc.js
  app/src/components/Empty.tsx
  app/src/components/exception/BugReportErrorBoundaryFallback.tsx
  app/src/components/trace/SpanAnnotationsEditor.tsx
  app/src/pages/ErrorElement.tsx
  app/src/pages/embedding/EventDetails.tsx
  app/src/pages/playground/NoInstalledProvider.tsx
  app/src/pages/trace/SpanAnnotationsEmpty.tsx
  app/src/pages/trace/SpanDetails.tsx
Labels: size:M

#8903 feat(projects): add the ability to manually create a project
  app/src/components/project/GradientCircle.tsx
  app/src/components/project/GradientCircleRadio.tsx
  app/src/components/project/GradientCircleRadioGroup.tsx
  app/src/components/project/index.ts
  app/src/pages/projects/ManualProjectGuide.tsx
  app/src/pages/projects/NewProjectButton.tsx
  app/src/pages/projects/NewProjectForm.tsx
  app/src/pages/projects/ProjectsPage.tsx
  app/src/pages/projects/__generated__/ManualProjectGuideCreateProjectMutation.graphql.ts
Labels: size:XL

#8904 fix: pnpm update packages
  .pre-commit-config.yaml
  app/package.json
  app/pnpm-lock.yaml
  app/src/components/breadcrumbs/Breadcrumb.tsx
  app/src/components/content/Keyboard.tsx
  app/src/components/field/CredentialInput.tsx
  app/src/components/progress/styles.ts
  app/src/pages/project/ProjectPageHeader.tsx
  app/src/pages/prompt/PromptLatestVersionsList.tsx
Labels: size:L

#8876 chore(main): release arize-phoenix 11.18.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8877 feat: delete span route along with span subtree
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  schemas/openapi.json
  src/phoenix/db/helpers.py
  src/phoenix/server/api/routers/v1/spans.py
  tests/unit/server/api/routers/v1/test_spans.py
  tox.ini
Labels: size:XL

#8909 fix: message role should not be required
  app/src/openInference/tracing/__tests__/types.test.ts
  app/src/openInference/tracing/types.ts
Labels: size:S

#8921 fix: allow click to propagate on token count tooltip
  app/src/components/trace/SpanTokenCount.tsx
Labels: size:S

#8933 fix: Remove reference to experiment evaluators in client docstrings
  packages/phoenix-client/src/phoenix/client/experiments/__init__.py
  packages/phoenix-client/src/phoenix/client/resources/experiments/__init__.py
Labels: size:S

#8939 fix: sanitize invocation parameters before saving
  app/src/pages/playground/fetchPlaygroundPrompt.ts
  app/src/pages/playground/playgroundUtils.ts
Labels: size:S

#8906 chore(main): release arize-phoenix 11.19.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8934 chore(main): release arize-phoenix-client 1.14.2
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#8947 fix: update openinference-instrumentation version lower bound
  packages/phoenix-otel/pyproject.toml
Labels: size:XS

#8944 feat: python phoenix-client delete span method
  packages/phoenix-client/src/phoenix/client/resources/spans/__init__.py
  tests/integration/client/test_spans.py
Labels: size:L

#8891 fix: Update notebooks to use new client
  packages/phoenix-client/src/phoenix/client/client.py
  tutorials/experiments/datasets_and_experiments_quickstart.ipynb
  tutorials/experiments/langchain_email_extraction.ipynb
  tutorials/experiments/summarization.ipynb
  tutorials/experiments/txt2sql.ipynb
Labels: size:XL

#8948 fix(experiments): optimize compare experiments query
  app/schema.graphql
  app/src/pages/experiment/ExperimentCompareMetricsPage.tsx
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/experiment/ExperimentMultiSelector.tsx
  app/src/pages/experiment/__generated__/ExperimentCompareMetricsPage_experiments.graphql.ts
  app/src/pages/experiment/__generated__/ExperimentCompareTableQuery.graphql.ts
  app/src/pages/experiment/__generated__/ExperimentCompareTable_comparisons.graphql.ts
  app/src/pages/experiment/__generated__/ExperimentMultiSelector__data.graphql.ts
  app/src/pages/experiment/__generated__/experimentCompareLoaderQuery.graphql.ts
  app/src/pages/experiment/experimentCompareLoader.ts
  src/phoenix/server/api/types/Dataset.py
Labels: size:L

#8953 feat: Reexport experiment utilities in top-level client module
  packages/phoenix-client/src/phoenix/client/experiments/__init__.py
Labels: size:S

#8923 fix: missing markdown block for text in multi-part messages
  app/src/components/markdown/MarkdownBlock.tsx
  app/src/pages/trace/SpanDetails.tsx
Labels: size:M

#8964 fix(experiments): ensure experiment compare selector can select all experiments for a dataset
  app/src/pages/experiment/ExperimentMultiSelector.tsx
  app/src/pages/experiment/__generated__/ExperimentMultiSelector__data.graphql.ts
  app/src/pages/experiment/__generated__/experimentCompareLoaderQuery.graphql.ts
  app/src/pages/experiment/experimentCompareLoader.ts
Labels: size:L

#8958 chore(main): release arize-phoenix 11.20.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8977 fix: Properly return objects from Anthropic adapter
  packages/phoenix-evals/src/phoenix/evals/llm/adapters/langchain/adapter.py
Labels: size:XS

#8986 chore: cleanup
  tutorials/ai_evals_course/phoenix_overview.ipynb
Labels: size:L

#8842 feat: new evaluator and score abstractions
  packages/phoenix-evals/src/phoenix/evals/__init__.py
  packages/phoenix-evals/src/phoenix/evals/preview/__init__.py
  packages/phoenix-evals/src/phoenix/evals/preview/evaluators.py
  packages/phoenix-evals/src/phoenix/evals/preview/llm/__init__.py
  packages/phoenix-evals/src/phoenix/evals/preview/llm/adapters/__init__.py
  packages/phoenix-evals/src/phoenix/evals/preview/llm/adapters/langchain/__init__.py
  packages/phoenix-evals/src/phoenix/evals/preview/llm/adapters/langchain/adapter.py
  packages/phoenix-evals/src/phoenix/evals/preview/llm/adapters/langchain/factories.py
  packages/phoenix-evals/src/phoenix/evals/preview/llm/adapters/litellm/__init__.py
  packages/phoenix-evals/src/phoenix/evals/preview/llm/adapters/litellm/adapter.py
  packages/phoenix-evals/src/phoenix/evals/preview/llm/adapters/litellm/client.py
  packages/phoenix-evals/src/phoenix/evals/preview/llm/adapters/litellm/factories.py
  packages/phoenix-evals/src/phoenix/evals/preview/llm/adapters/openai/__init__.py
  packages/phoenix-evals/src/phoenix/evals/preview/llm/adapters/openai/adapter.py
  packages/phoenix-evals/src/phoenix/evals/preview/llm/adapters/openai/factories.py
  packages/phoenix-evals/src/phoenix/evals/preview/llm/registries.py
  packages/phoenix-evals/src/phoenix/evals/preview/llm/types.py
  packages/phoenix-evals/src/phoenix/evals/preview/llm/wrapper.py
  packages/phoenix-evals/src/phoenix/evals/preview/metrics/__init__.py
  packages/phoenix-evals/src/phoenix/evals/preview/metrics/exact_match.py
  packages/phoenix-evals/src/phoenix/evals/preview/metrics/hallucination.py
  packages/phoenix-evals/src/phoenix/evals/preview/templating/__init__.py
  packages/phoenix-evals/tests/phoenix/evals/preview/llm/test_wrapper.py
  packages/phoenix-evals/tests/phoenix/evals/preview/test_preview_evaluators.py
  packages/phoenix-evals/tests/phoenix/evals/preview/test_templating.py
Labels: size:XXL

#8985 feat(playground): support gpt-5
  js/.changeset/cyan-worms-help.md
  js/packages/phoenix-client/package.json
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  js/pnpm-lock.yaml
  packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/openai/chat.py
  schemas/openapi.json
  src/phoenix/server/api/helpers/playground_clients.py
  src/phoenix/server/api/helpers/prompts/models.py
  src/phoenix/server/cost_tracking/model_cost_manifest.json
  tests/__generated__/graphql/__init__.py
Labels: size:XL

#8988 chore(main): release arize-phoenix 11.21.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8996 docs: Add opentelemetry integration guide link to readme
  README.md
Labels: size:XS

#8995 fix(experiments): make examples in experiments compare table based off dataset version of base experiment
  src/phoenix/server/api/queries.py
  tests/unit/server/api/test_queries.py
Labels: size:M

#9034 chore(design): filter condition design consistency
  app/src/pages/experiment/ExperimentRunFilterConditionField.tsx
  app/src/pages/project/SpanFilterConditionField.tsx
Labels: size:M

#9006 refactor: Move dataset version history to new tab
  app/src/Routes.tsx
  app/src/pages/dataset/DatasetPage.tsx
  app/src/pages/dataset/index.tsx
  app/src/pages/dataset/versions/DatasetVersionsPage.tsx
  app/src/pages/dataset/versions/__generated__/datasetVersionsLoaderQuery.graphql.ts
  app/src/pages/dataset/versions/__generated__/historyLoaderQuery.graphql.ts
  app/src/pages/dataset/versions/datasetVersionsLoader.tsx
  app/src/pages/dataset/versions/index.tsx
  app/src/pages/index.tsx
Labels: size:XL

#9003 fix(playground): parse Azure deployment from LangChain metadata
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/playgroundUtils.ts
Labels: size:L

#9039 feat(design): add geist mono for values
  app/src/GlobalStyles.tsx
  app/src/components/annotation/MeanScore.tsx
  app/src/components/code/JSONText.tsx
  app/src/components/content/Text.tsx
  app/src/components/table/FloatCell.tsx
  app/src/components/table/IntCell.tsx
  app/src/components/trace/LatencyText.tsx
  app/src/components/trace/TokenCosts.tsx
  app/src/components/trace/TokenCount.tsx
  app/src/pages/project/ProjectPageHeader.tsx
  app/src/pages/projects/ProjectsPage.tsx
  app/stories/Text.stories.tsx
  src/phoenix/server/templates/index.html
Labels: size:L

#9043 feat(js): add optimizationDirection and kind / source
  js/.changeset/fifty-doors-strive.md
  js/packages/phoenix-evals/examples/classifier_example.ts
  js/packages/phoenix-evals/examples/hallucination_example.ts
  js/packages/phoenix-evals/src/default_templates/HALLUCINATION_TEMPLATE.ts
  js/packages/phoenix-evals/src/llm/createClassificationEvaluator.ts
  js/packages/phoenix-evals/src/llm/createClassifierFn.ts
  js/packages/phoenix-evals/src/llm/createDocumentRelevancyEvaluator.ts
  js/packages/phoenix-evals/src/llm/createHallucinationEvaluator.ts
  js/packages/phoenix-evals/src/llm/index.ts
  js/packages/phoenix-evals/src/types/evals.ts
  js/packages/phoenix-evals/test/llm/createClassifierFn.test.ts
  js/packages/phoenix-evals/test/llm/createDocumentRelevancyEvaluator.test.ts
  js/packages/phoenix-evals/test/llm/createHallucinationEvaluator.test.ts
Labels: size:L

#9044 fix: [evals] rename and update evaluator decorator
  packages/phoenix-evals/src/phoenix/evals/preview/__init__.py
  packages/phoenix-evals/src/phoenix/evals/preview/evaluators.py
  packages/phoenix-evals/src/phoenix/evals/preview/metrics/exact_match.py
  packages/phoenix-evals/tests/phoenix/evals/preview/test_preview_evaluators.py
Labels: size:L

#9040 chore(main): release arize-phoenix 11.22.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#9059 fix: Support o4 in Azure
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
Labels: size:XS

#8982 chore(main): release arize-phoenix-evals 0.27.0
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#9070 fix: record end time after span ends
  packages/phoenix-client/src/phoenix/client/resources/experiments/__init__.py
Labels: size:M

#9075 feat(license): switch otel to apache 2
  packages/phoenix-otel/LICENSE
  packages/phoenix-otel/pyproject.toml
Labels: size:XS

#8643 chore(main): release arize-phoenix-otel 0.13.0
  .release-please-manifest.json
  packages/phoenix-otel/CHANGELOG.md
  packages/phoenix-otel/pyproject.toml
Labels: autorelease: pending, size:S

#9080 chore: add missing anthropic instrumentor to tutorials/experiments/summarization.ipynb
  .pre-commit-config.yaml
  tutorials/experiments/summarization.ipynb
Labels: size:S

#9064 chore: add ddl script and update ERD
  scripts/ddl/postgresql_schema.sql
  src/phoenix/db/README.md
Labels: size:XXL

#9071 fix: split `ENV_PHOENIX_POSTGRES_HOST` only if matched (legacy) pattern
  src/phoenix/config.py
  tests/unit/test_config.py
Labels: size:L

#9054 chore(main): release arize-phoenix 11.22.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#9078 chore(main): release arize-phoenix-client 1.15.2
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#9050 feat(projects): transfer traces
  app/src/components/icon/Icons.tsx
  app/src/components/index.tsx
  app/src/components/listbox/ListBox.tsx
  app/src/pages/project/SpanSelectionToolbar.tsx
  app/src/pages/project/TransferTracesButton.tsx
  app/src/pages/project/__generated__/TransferTracesButtonProjectsQuery.graphql.ts
  app/src/pages/project/__generated__/TransferTracesButtonQuery.graphql.ts
  app/src/pages/project/__generated__/TransferTracesButtonTransferMutation.graphql.ts
  app/src/pages/project/__generated__/TransferTracesButton_projects.graphql.ts
Labels: size:XL

#9090 chore(main): release arize-phoenix 11.23.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#9095 chore(main): release arize-phoenix 11.23.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#9098 fix: add AWS to provider dropdown for model edit
  app/src/pages/settings/ModelForm.tsx
Labels: size:XS

#9097 fix: show custom provider in models table
  app/src/pages/settings/ModelsTable.tsx
Labels: size:S

#9099 chore(main): release arize-phoenix 11.23.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#9065 fix: result should be nullable when there's error in experiment run evaluation
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py
  schemas/openapi.json
  src/phoenix/server/api/routers/v1/experiment_evaluations.py
Labels: size:M

#9104 chore(main): release arize-phoenix 11.24.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#9108 fix: remove redundant id in annotation insertables during bulk insert
  src/phoenix/db/insertion/document_annotation.py
  src/phoenix/db/insertion/span_annotation.py
  src/phoenix/db/insertion/trace_annotation.py
  src/phoenix/db/insertion/types.py
Labels: size:S

#9111 fix(playground): #8940 allow bounded slider fields to be unset
  app/src/components/slider/Slider.tsx
  app/src/pages/playground/InvocationParametersFormFields.tsx
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:M

#8992 feat: Dynamic concurrency
  packages/phoenix-evals/src/phoenix/evals/executors.py
  packages/phoenix-evals/src/phoenix/evals/models/anthropic.py
  packages/phoenix-evals/src/phoenix/evals/models/bedrock.py
  packages/phoenix-evals/src/phoenix/evals/models/google_genai.py
  packages/phoenix-evals/src/phoenix/evals/models/mistralai.py
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
  packages/phoenix-evals/src/phoenix/evals/models/rate_limiters.py
  packages/phoenix-evals/src/phoenix/evals/models/vertex.py
  packages/phoenix-evals/tests/phoenix/evals/functions/test_concurrency_controller.py
  packages/phoenix-evals/tests/phoenix/evals/functions/test_executor.py
Labels: size:XL

#8976 docs: Add explicit documentation for missing phoenix.Client methods in API reference
  api_reference/source/api/client.rst
  api_reference/source/index.md
  packages/phoenix-client/docs/source/api/client.rst
Labels: size:L

#9152 docs: session & trace eval notebooks
  tutorials/evals/session_level_evals.ipynb
  tutorials/evals/trace_level_evals.ipynb
Labels: size:XXL

#9143 fix(evals): update `create_evaluator` decorator handle casting function outputs to valid Scores
  packages/phoenix-evals/src/phoenix/evals/preview/evaluators.py
  packages/phoenix-evals/tests/phoenix/evals/preview/test_preview_evaluators.py
Labels: size:L

#9109 fix(evals): make evaluator input schema more explicit and discoverable
  packages/phoenix-evals/pyproject.toml
  packages/phoenix-evals/src/phoenix/evals/preview/__init__.py
  packages/phoenix-evals/src/phoenix/evals/preview/evaluators.py
  packages/phoenix-evals/src/phoenix/evals/preview/metrics/hallucination.py
  packages/phoenix-evals/src/phoenix/evals/preview/metrics/precision_recall.py
  packages/phoenix-evals/src/phoenix/evals/preview/utils.py
  packages/phoenix-evals/tests/phoenix/evals/preview/test_preview_evaluators.py
  packages/phoenix-evals/tests/phoenix/evals/preview/test_preview_utils.py
Labels: size:XXL

#9115 docs: adding hw5_phoenix
  tutorials/ai_evals_course/hw3/README.md
  tutorials/ai_evals_course/hw3/ai_evals_hw3_solution.ipynb
  tutorials/ai_evals_course/hw3/lessons_learned.md
  tutorials/ai_evals_course/hw3/phoenix_methods_guide.md
  tutorials/ai_evals_course/hw3/results/dev_predictions.json
  tutorials/ai_evals_course/hw3/results/final_evaluation.json
  tutorials/ai_evals_course/hw3/results/judge_performance.json
  tutorials/ai_evals_course/hw3/results/judge_prompt.txt
  tutorials/ai_evals_course/hw3/results/judgy_test_data.json
  tutorials/ai_evals_course/hw3/results/test_predictions.json
  tutorials/ai_evals_course/hw3/scripts/develop_judge.py
  tutorials/ai_evals_course/hw3/scripts/evaluate_judge.py
  tutorials/ai_evals_course/hw3/scripts/generate_traces.py
  tutorials/ai_evals_course/hw3/scripts/label_data.py
  tutorials/ai_evals_course/hw3/scripts/run_full_evaluation.py
  tutorials/ai_evals_course/hw3/scripts/split_data.py
  tutorials/ai_evals_course/hw3/utils.py
  tutorials/ai_evals_course/hw5_phoenix/README.md
  tutorials/ai_evals_course/hw5_phoenix/ai_evals_hw5_solution.ipynb
  tutorials/ai_evals_course/hw5_phoenix/evaluators/compose_response_eval.txt
  tutorials/ai_evals_course/hw5_phoenix/evaluators/gen_recipe_args_eval.txt
  tutorials/ai_evals_course/hw5_phoenix/evaluators/gen_web_args_eval.txt
  tutorials/ai_evals_course/hw5_phoenix/evaluators/get_recipes_eval.txt
  tutorials/ai_evals_course/hw5_phoenix/evaluators/get_web_info_eval.txt
  tutorials/ai_evals_course/hw5_phoenix/evaluators/parse_request_eval.txt
  tutorials/ai_evals_course/hw5_phoenix/evaluators/plan_tool_calls_eval.txt
  tutorials/ai_evals_course/hw5_phoenix/generate_traces_phoenix.py
Labels: size:XXL

#9162 chore: cleanup ruff on hw5
  tutorials/ai_evals_course/hw5_phoenix/ai_evals_hw5_solution.ipynb
  tutorials/ai_evals_course/hw5_phoenix/generate_traces_phoenix.py
Labels: size:L

#9160 docs: fix client python docs
  packages/phoenix-client/src/phoenix/client/client.py
  packages/phoenix-client/src/phoenix/client/resources/annotations/__init__.py
  packages/phoenix-client/src/phoenix/client/resources/datasets/__init__.py
  packages/phoenix-client/src/phoenix/client/resources/prompts/__init__.py
  packages/phoenix-client/src/phoenix/client/resources/spans/__init__.py
Labels: size:XL

#9122 fix(metrics): make query errors scrollable
  app/src/pages/project/metrics/ProjectMetricsPage.tsx
Labels: size:XS

#9157 chore(main): release arize-phoenix-evals 0.28.1
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#9107 docs: adding notebook for reasoning & non-reasoning judge model eval test
  tutorials/evals/CoT_explanations_simple_vs_complex_evals.ipynb
Labels: size:XXL

#9159 docs(evals): docs for evals preview module
  docs/evaluation/preview/README.md
  docs/evaluation/preview/evaluators.md
  docs/evaluation/preview/llm.md
  docs/evaluation/preview/metrics.md
  docs/evaluation/preview/templating.md
  packages/phoenix-evals/docs/source/api/preview.llm.adapters.langchain.rst
  packages/phoenix-evals/docs/source/api/preview.llm.adapters.litellm.rst
  packages/phoenix-evals/docs/source/api/preview.llm.adapters.openai.rst
  packages/phoenix-evals/docs/source/api/preview.llm.adapters.rst
  packages/phoenix-evals/docs/source/api/preview.llm.rst
  packages/phoenix-evals/docs/source/api/preview.metrics.rst
  packages/phoenix-evals/docs/source/api/preview.rst
  packages/phoenix-evals/docs/source/api/preview.templating.rst
  packages/phoenix-evals/docs/source/index.md
  tutorials/evals/evals_preview_examples.ipynb
Labels: size:XXL

#9172 docs: fixing cot evals notebook
  tutorials/evals/CoT_explanations_simple_vs_complex_evals.ipynb
Labels: size:XS

#9151 feat: cc support email in disk usage notification
  src/phoenix/server/email/sender.py
  tests/integration/server/test_db_disk_usage_monitor.py
Labels: size:S

#9038 refactor(experiments): place annotations at the bottom
  app/src/GlobalStyles.tsx
  app/src/components/annotation/AnnotationDetailsContent.tsx
  app/src/components/annotation/AnnotationLabel.tsx
  app/src/components/annotation/AnnotationNameAndValue.tsx
  app/src/components/annotation/AnnotationSummaryGroup.tsx
  app/src/components/annotation/AnnotationTooltip.tsx
  app/src/components/annotation/types.ts
  app/src/components/overlay/Popover.tsx
  app/src/pages/experiment/ExperimentCompareTable.tsx
Labels: size:XL

#9175 feat: Handle new OpenAI tool types
  packages/phoenix-client/src/phoenix/client/helpers/sdk/openai/chat.py
Labels: size:S

#9158 fix: Add OpenAI timeout to playground client
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:S

#9182 feat(experiments): eval / annotation quick filters
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/experiment/ExperimentRunAnnotationFiltersList.tsx
Labels: size:M

#9056 feat: special case sqlite:///:memory: in helm
  helm/README.md
  helm/templates/_helpers.tpl
  helm/templates/phoenix/deployment.yaml
  helm/templates/phoenix/pvc.yaml
  helm/values.yaml
Labels: size:M

#9114 refactor(sessions): make project page header resolvers aware of sessions filters
  app/schema.graphql
  src/phoenix/server/api/dataloaders/annotation_summaries.py
  src/phoenix/server/api/dataloaders/latency_ms_quantile.py
  src/phoenix/server/api/dataloaders/record_counts.py
  src/phoenix/server/api/dataloaders/span_cost_summary_by_project.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/session_filters.py
  tests/unit/server/api/dataloaders/test_annotation_summaries.py
  tests/unit/server/api/dataloaders/test_latency_ms_quantiles.py
  tests/unit/server/api/dataloaders/test_record_counts.py
  tests/unit/server/api/types/test_Project.py
Labels: size:XL

#9176 fix: default sqlite usage when postgresql.enabled false
  helm/templates/phoenix/configmap.yaml
Labels: size:XS

#9186 feat(tracing): timeline view
  app/src/components/timeline/TimelineBar.tsx
  app/src/components/trace/SpanKindIcon.tsx
  app/src/components/trace/TraceTree.tsx
  app/src/components/trace/__tests__/utils.test.ts
  app/src/components/trace/types.ts
  app/src/components/trace/useSpanKindColor.ts
  app/src/pages/project/TracesTable.tsx
  app/src/pages/project/__generated__/ProjectPageQueriesTracesQuery.graphql.ts
  app/src/pages/project/__generated__/TracesTableQuery.graphql.ts
  app/src/pages/project/__generated__/TracesTable_spans.graphql.ts
  app/src/pages/trace/TraceDetails.tsx
  app/src/pages/trace/__generated__/TraceDetailsQuery.graphql.ts
Labels: size:XL

#9195 ci: specify start time so sorting is deterministic
  tests/integration/_helpers.py
  tests/integration/server/test_launch_app.py
Labels: size:XS

#9177 docs: simplify main python reference"
  api_reference/source/_static/github-large-banner-phoenix.jpg
  api_reference/source/api/client.resources.prompts.rst
  api_reference/source/api/client.resources.rst
  api_reference/source/api/client.rst
  api_reference/source/api/client.types.prompts.rst
  api_reference/source/api/client.types.rst
  api_reference/source/api/evals.classify.rst
  api_reference/source/api/evals.default_templates.rst
  api_reference/source/api/evals.evaluators.rst
  api_reference/source/api/evals.generate.rst
  api_reference/source/api/evals.models.anthropic.rst
  api_reference/source/api/evals.models.bedrock.rst
  api_reference/source/api/evals.models.litellm.rst
  api_reference/source/api/evals.models.mistralai.rst
  api_reference/source/api/evals.models.openai.rst
  api_reference/source/api/evals.models.rst
  api_reference/source/api/evals.models.vertex.rst
  api_reference/source/api/evals.models.vertexai.rst
  api_reference/source/api/evals.retrievals.rst
  api_reference/source/api/evals.rst
  api_reference/source/api/evals.span_templates.rst
  api_reference/source/api/evals.templates.rst
  api_reference/source/api/evals.utils.rst
  api_reference/source/api/experiments.rst
  api_reference/source/api/inferences_schema.rst
  api_reference/source/api/session.rst
  api_reference/source/conf.py
  api_reference/source/index.md
Labels: size:L

#9212 feat: extra volumes/volume mounts in helm
  helm/README.md
  helm/templates/phoenix/deployment.yaml
  helm/values.yaml
Labels: size:S

#9220 fix: self-hosted database environment variable templating
  helm/templates/phoenix/configmap.yaml
Labels: size:XS

#9214 chore(main): release arize-phoenix 11.27.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#9213 chore: update suppress-tracing.md documentation
  docs/tracing/how-to-tracing/advanced/suppress-tracing.md
Labels: size:XS

#9245 docs: migrate client
  .cursor/rules/client-migration.mdc
  tutorials/demos/.gitignore
  tutorials/demos/demo_llama_index_rag.ipynb
  tutorials/evals/local_llm_evals.ipynb
  tutorials/evals/trace_level_evals.ipynb
  tutorials/experiments/internal/run_experiments.ipynb
  tutorials/experiments/llama-index/answer_and_context_relevancy.ipynb
  tutorials/experiments/llama-index/guideline_eval.ipynb
  tutorials/experiments/llama-index/pairwise_eval.ipynb
  tutorials/experiments/txt2sql.ipynb
  tutorials/hosted_phoenix/hosted_phoenix_answer_and_context_relevancy_experiment.ipynb
  tutorials/hosted_phoenix/hosted_phoenix_llamaindex_tutorial.ipynb
  tutorials/hosted_phoenix/hosted_phoenix_openai_tutorial.ipynb
  tutorials/llm_summarization_tutorial.ipynb
  tutorials/milvus_llamaindex_search_and_retrieval_tutorial.ipynb
  tutorials/prompts/react_prompting.ipynb
  tutorials/tracing/openai_tracing_tutorial.ipynb
Labels: size:XXL

#9247 chore: remove `SpanEvaluations` from tutorials
  .cursor/rules/client-migration.mdc
  .editorconfig
  tutorials/agents/langgraph/evaluate-langgraph-rag-manual-instrumentation.py
  tutorials/agents/langgraph/langgraph_orchestrator.ipynb
  tutorials/agents/langgraph/langgraph_parallel.ipynb
  tutorials/agents/langgraph/langgraph_promptchaining.ipynb
  tutorials/agents/langgraph/langgraph_router.ipynb
  tutorials/ai_evals_course/hw3_phoenix/README.md
  tutorials/ai_evals_course/hw3_phoenix/phoenix_methods_guide.md
  tutorials/ai_evals_course/hw3_phoenix/scripts/label_data.py
  tutorials/ai_evals_course/hw3_phoenix/scripts/run_full_evaluation.py
  tutorials/ai_evals_course/hw5_phoenix/README.md
  tutorials/ai_evals_course/hw5_phoenix/ai_evals_hw5_solution.ipynb
  tutorials/ai_evals_course/phoenix_overview.ipynb
  tutorials/evals/bedrock_tracing_and_evals_tutorial.ipynb
  tutorials/evals/evals_quickstart.ipynb
  tutorials/evals/evaluate_agent.ipynb
  tutorials/evals/evaluate_rag.ipynb
  tutorials/evals/evaluate_rag_haystack.ipynb
  tutorials/evals/evaluate_tool_calling.ipynb
  tutorials/evals/openai_agents_cookbook.ipynb
  tutorials/evals/pydantic-evals.ipynb
  tutorials/evals/session_level_evals.ipynb
  tutorials/evals/trace_level_evals.ipynb
  tutorials/experiments/datasets_and_experiments_quickstart.ipynb
  tutorials/experiments/langchain_email_extraction.ipynb
  tutorials/experiments/summarization.ipynb
  tutorials/experiments/txt2sql.ipynb
  tutorials/integrations/amazon_bedrock_agents_tracing_and_evals.ipynb
  tutorials/integrations/evaluating_traces_cleanlabTLM.ipynb
  tutorials/integrations/tracing_and_evals_weaviate.ipynb
  tutorials/integrations/tracing_and_evals_with_mongodb_and_llama_index.ipynb
  tutorials/llm_application_tracing_evaluating_and_analysis.ipynb
  tutorials/llm_ops_overview.ipynb
  tutorials/mistral/evaluate_rag--mistral.ipynb
  tutorials/prompts/react_prompting.ipynb
  tutorials/quickstarts/evaluating_traces_quickstart.ipynb
  tutorials/ragas_retrieval_evals_tutorial.ipynb
  tutorials/tracing/langchain_tracing_tutorial.ipynb
  tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb
  tutorials/tracing/llama_index_tracing_tutorial.ipynb
  tutorials/tracing/openai_tracing_tutorial.ipynb
  tutorials/tracing/tracing_with_projects_tutorial.ipynb
Labels: size:XXL

#9199 fix(evals): switch from glom to jsonpath-ng for input mapping
  docs/evaluation/preview/evaluators.md
  packages/phoenix-evals/pyproject.toml
  packages/phoenix-evals/src/phoenix/evals/preview/utils.py
  packages/phoenix-evals/tests/phoenix/evals/preview/test_preview_evaluators.py
  packages/phoenix-evals/tests/phoenix/evals/preview/test_preview_utils.py
  requirements/dev.txt
Labels: size:L

#9197 feat(evals): add evaluate_dataframe function
  docs/evaluation/preview/evaluators.md
  packages/phoenix-evals/src/phoenix/evals/preview/evaluators.py
  tutorials/evals/evals_preview_examples.ipynb
Labels: size:XL

#9218 test(experiments): refactor experiment tests for readability
  tests/unit/server/api/types/test_Experiment.py
Labels: size:XL

#9252 docs(evals): update docs and add example notebooks
  docs/evaluation/preview/README.md
  docs/evaluation/preview/evaluators.md
  docs/evaluation/preview/llm.md
  docs/evaluation/preview/templating.md
  tutorials/evals/evals_preview_examples.ipynb
  tutorials/evals/evals_preview_introduction.ipynb
Labels: size:XXL

#9261 chore: sync main to docs
  .cursor/rules/client-migration.mdc
  app/src/components/experiment/useExperimentColors.ts
  app/src/pages/experiment/ExperimentCompareListPage.tsx
  app/src/pages/experiment/__generated__/ExperimentCompareListPage_aggregateData.graphql.ts
  app/src/pages/experiment/__generated__/experimentCompareLoaderQuery.graphql.ts
  app/src/pages/experiment/utils.ts
  app/src/pages/experiments/ExperimentsTable.tsx
  tutorials/experiments/generating_synthetic_datasets.ipynb
Labels: size:XXL

#9251 docs: migrate react prompting notebook
  tutorials/prompts/react_prompting.ipynb
Labels: size:M

#9262 chore(evals): update evals preview notebooks
  tutorials/evals/evals_preview_examples.ipynb
  tutorials/evals/evals_preview_introduction.ipynb
Labels: size:XL

#9242 chore(main): release arize-phoenix 11.28.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#9269 docs: migrate phoenix overview
  tutorials/ai_evals_course/phoenix_overview.ipynb
Labels: size:S

#9270 chore: update development.md with tox-uv install
  DEVELOPMENT.md
Labels: size:M

#9198 refactor(experiments): make aggregate resolvers aware of repetitions
  src/phoenix/server/api/dataloaders/average_experiment_run_latency.py
  src/phoenix/server/api/dataloaders/experiment_annotation_summaries.py
  src/phoenix/server/api/dataloaders/experiment_error_rates.py
  src/phoenix/server/api/types/Dataset.py
  src/phoenix/server/api/types/Experiment.py
  tests/unit/server/api/types/test_Experiment.py
Labels: size:L

#9278 fix(client): use batch span processor for experiments
  js/.changeset/clear-grapes-train.md
  js/packages/phoenix-client/src/experiments/instrumention.ts
  js/packages/phoenix-client/src/experiments/runExperiment.ts
Labels: size:M

#9256 chore: Update evaluate_rag notebook to use new client
  tutorials/evals/evaluate_rag.ipynb
Labels: size:XS

#9283 chore(main): release arize-phoenix 11.29.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#9287 fix(evals): unify sync and async llm
  packages/phoenix-evals/src/phoenix/evals/preview/evaluators.py
  packages/phoenix-evals/src/phoenix/evals/preview/llm/__init__.py
  packages/phoenix-evals/src/phoenix/evals/preview/llm/wrapper.py
  packages/phoenix-evals/src/phoenix/evals/preview/metrics/hallucination.py
  packages/phoenix-evals/tests/phoenix/evals/preview/test_preview_evaluators.py
Labels: size:L

#9280 refactor(experiments): clean experiment aggregate resolver queries
  src/phoenix/server/api/dataloaders/average_experiment_run_latency.py
  src/phoenix/server/api/dataloaders/experiment_annotation_summaries.py
  src/phoenix/server/api/types/Experiment.py
Labels: size:S

#9292 feat: Playground migration experiments record user_id
  src/phoenix/db/migrations/versions/d0690a79ea51_users_on_experiments.py
  src/phoenix/server/api/helpers/playground_users.py
  src/phoenix/server/api/mutations/chat_mutations.py
  src/phoenix/server/api/subscriptions.py
Labels: size:M

#9210 feat: show missing percentage for experiment evaluations
  app/src/pages/experiments/ExperimentsTable.tsx
  app/src/pages/experiments/__generated__/ExperimentsPageQuery.graphql.ts
  app/src/pages/experiments/__generated__/ExperimentsTableFragment.graphql.ts
  app/src/pages/experiments/__generated__/ExperimentsTableQuery.graphql.ts
Labels: size:L

#9304 refactor: more efficient queries
  src/phoenix/server/api/routers/v1/spans.py
  src/phoenix/server/api/routers/v1/traces.py
Labels: size:S

#9305 fix: check bound on num docs for annotations
  src/phoenix/server/api/routers/v1/documents.py
Labels: size:S

#9311 ci: pin version of datamodel-code-generator
  tox.ini
Labels: size:XS

#9291 docs: updating react prompting notebook
  tutorials/prompts/react_prompting.ipynb
Labels: size:M

#9297 chore(main): release arize-phoenix 11.30.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#9317 docs(client): fix python client docs
  packages/phoenix-client/.cursor/rules/general.mdc
  packages/phoenix-client/docs/source/_static/custom.css
  packages/phoenix-client/docs/source/api/annotations.rst
  packages/phoenix-client/docs/source/api/client.rst
  packages/phoenix-client/docs/source/api/datasets.rst
  packages/phoenix-client/docs/source/api/exceptions.rst
  packages/phoenix-client/docs/source/api/experiments.rst
  packages/phoenix-client/docs/source/api/helpers.rst
  packages/phoenix-client/docs/source/api/projects.rst
  packages/phoenix-client/docs/source/api/prompts.rst
  packages/phoenix-client/docs/source/api/spans.rst
  packages/phoenix-client/docs/source/api/types.rst
  packages/phoenix-client/docs/source/api/utils.rst
  packages/phoenix-client/docs/source/index.md
  packages/phoenix-client/src/phoenix/client/experiments/__init__.py
  packages/phoenix-client/src/phoenix/client/helpers/spans/__init__.py
  packages/phoenix-client/src/phoenix/client/resources/annotations/__init__.py
  packages/phoenix-client/src/phoenix/client/resources/datasets/__init__.py
  packages/phoenix-client/src/phoenix/client/resources/experiments/__init__.py
  packages/phoenix-client/src/phoenix/client/resources/projects/__init__.py
  packages/phoenix-client/src/phoenix/client/resources/prompts/__init__.py
  packages/phoenix-client/src/phoenix/client/utils/template_formatters.py
  packages/phoenix-evals/docs/source/_static/custom.css
  packages/phoenix-otel/docs/source/_static/custom.css
Labels: size:XXL

#9319 docs(otel): better docs
  js/packages/phoenix-client/.cursor/rules/general.mdc
  packages/phoenix-otel/docs/source/api/exporters.rst
  packages/phoenix-otel/docs/source/api/otel.rst
  packages/phoenix-otel/docs/source/api/processors.rst
  packages/phoenix-otel/docs/source/api/provider.rst
  packages/phoenix-otel/docs/source/api/register.rst
  packages/phoenix-otel/docs/source/api/settings.rst
  packages/phoenix-otel/docs/source/conf.py
  packages/phoenix-otel/docs/source/index.md
  packages/phoenix-otel/src/phoenix/otel/otel.py
  packages/phoenix-otel/src/phoenix/otel/settings.py
Labels: size:XL

#9326 ci: turn off parallelism for unit and integration tests in ci
  .github/workflows/python-CI.yml
  packages/phoenix-client/src/phoenix/client/client.py
  src/phoenix/db/types/trace_retention.py
Labels: size:S
