Repository Arize-ai/phoenix, pull requests merged in 2025-02, with the labels that each got.

#6220 fix(prompts): normalized tools
  packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/anthropic/messages.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/openai/chat.py
  packages/phoenix-client/tests/canary/sdk/anthropic/test_messages.py
  packages/phoenix-client/tests/canary/sdk/openai/test_chat.py
  schemas/openapi.json
  src/phoenix/db/models.py
  src/phoenix/server/api/helpers/prompts/models.py
  src/phoenix/server/api/input_types/PromptVersionInput.py
  src/phoenix/server/api/mutations/prompt_mutations.py
  src/phoenix/server/api/types/OutputSchema.py
  src/phoenix/server/api/types/PromptVersion.py
  src/phoenix/server/api/types/ToolDefinition.py
  tests/canary/sdk/openai/test_chat_message.py
  tests/unit/server/api/helpers/prompts/test_models.py
  tests/unit/server/api/mutations/test_prompt_mutations.py
  tests/unit/server/api/routers/v1/test_prompts.py
Labels: size:XL

#6227 docs: agentic rag notebook
  tutorials/tracing/agentic_rag_tracing.ipynb
Labels: size:L

#6230 feat: Add OpenAI `o3-mini` support to playground
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:XS

#6218 refactor(prompts): Normalize playground instance messages
  app/package.json
  app/pnpm-lock.yaml
  app/src/components/templateEditor/TemplateEditor.tsx
  app/src/pages/playground/ChatMessageToolCallsEditor.tsx
  app/src/pages/playground/ModelConfigButton.tsx
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/PlaygroundChatTemplateFooter.tsx
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
  app/src/pages/playground/PlaygroundInput.tsx
  app/src/pages/playground/PlaygroundOutputMoveButton.tsx
  app/src/pages/playground/PlaygroundTemplate.tsx
  app/src/pages/playground/PlaygroundTool.tsx
  app/src/pages/playground/UpsertPromptFromTemplateDialog.tsx
  app/src/pages/playground/VariableEditor.tsx
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/playground/useDerivedPlaygroundVariables.tsx
  app/src/pages/prompt/ChatTemplateMessageCard.tsx
  app/src/pages/prompt/PromptPlaygroundPage.tsx
  app/src/store/playground/__tests__/playgroundStore.test.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/selectors.ts
  app/src/store/playground/types.ts
Labels: size:XL

#6228 fix(prompts): fix regex validation logic so it shows up in the form
  app/src/components/combobox/ComboBox.tsx
  app/src/components/field/styles.ts
  app/src/pages/playground/SavePromptForm.tsx
Labels: size:S

#6238 ci: remove outdated canary tests
  .github/workflows/python-CI.yml
  tests/canary/__init__.py
  tests/canary/conftest.py
  tests/canary/sdk/__init__.py
  tests/canary/sdk/anthropic/__init__.py
  tests/canary/sdk/anthropic/conftest.py
  tests/canary/sdk/anthropic/mypy.ini
  tests/canary/sdk/anthropic/pytest.ini
  tests/canary/sdk/anthropic/test_chat_message.py
  tests/canary/sdk/conftest.py
  tests/canary/sdk/openai/__init__.py
  tests/canary/sdk/openai/conftest.py
  tests/canary/sdk/openai/mypy.ini
  tests/canary/sdk/openai/pytest.ini
  tests/canary/sdk/openai/test_chat_message.py
  tests/canary/sdk/vertexai/__init__.py
  tests/canary/sdk/vertexai/conftest.py
  tests/canary/sdk/vertexai/mypy.ini
  tests/canary/sdk/vertexai/pytest.ini
  tests/canary/sdk/vertexai/test_chat_message.py
  tox.ini
Labels: size:XL

#6239 feat: Support OpenAI reasoning models that don't use the "system" role
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
Labels: size:S

#6240 fix(auth): refresh tokens on websockets
  app/src/RelayEnvironment.ts
  app/src/authFetch.ts
  tox.ini
Labels: size:S

#6243 fix: sanitize db urls in launch_app
  src/phoenix/session/session.py
Labels: size:XS

#6242 test(prompts): test materialized chat template
  tests/unit/server/api/helpers/prompts/test_models.py
Labels: size:L

#6244 feat(ui): in playground model config add text field for base url
  app/schema.graphql
  app/src/pages/playground/ModelConfigButton.tsx
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableMutation.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableSubscription.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundOutputMutation.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  app/src/pages/playground/playgroundUtils.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
  src/phoenix/server/api/helpers/playground_clients.py
  src/phoenix/server/api/input_types/GenerativeModelInput.py
Labels: size:M

#6250 fix: Replace corepack with pinned pnpm version in Dockerfile
  Dockerfile
  app/package.json
Labels: size:XS

#6251 chore(main): release arize-phoenix 7.10.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6246 fix(prompts): nest json schema fields in discriminated union
  schemas/openapi.json
  src/phoenix/server/api/helpers/jsonschema.py
  src/phoenix/server/api/helpers/prompts/models.py
  tests/unit/server/api/helpers/prompts/test_models.py
  tests/unit/server/api/helpers/test_models.py
Labels: size:L

#6224 feat: Propagate prompt id to playground spans metadata
  app/schema.graphql
  app/src/pages/playground/UpsertPromptFromTemplateDialog.tsx
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableMutation.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableSubscription.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundOutputMutation.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  app/src/pages/playground/fetchPlaygroundPrompt.ts
  app/src/pages/playground/playgroundUtils.ts
  app/src/store/playground/types.ts
  src/phoenix/server/api/helpers/playground_spans.py
  src/phoenix/server/api/input_types/ChatCompletionInput.py
  src/phoenix/server/api/mutations/chat_mutations.py
Labels: size:M

#6206 feat: Enable overriding executor timeouts per model
  packages/phoenix-evals/src/phoenix/evals/classify.py
  packages/phoenix-evals/src/phoenix/evals/executors.py
  packages/phoenix-evals/src/phoenix/evals/generate.py
  packages/phoenix-evals/src/phoenix/evals/models/anthropic.py
  packages/phoenix-evals/src/phoenix/evals/models/base.py
  packages/phoenix-evals/src/phoenix/evals/models/bedrock.py
  packages/phoenix-evals/src/phoenix/evals/models/mistralai.py
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
  packages/phoenix-evals/src/phoenix/evals/models/vertex.py
Labels: size:M

#6256 fix(playground): disable retry and auth refresh if auth is disabled
  app/src/RelayEnvironment.ts
Labels: size:XS

#6257 chore(main): release arize-phoenix 7.10.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6259 fix(playground): if base url is provided but not api key, use fake api key for openai client
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:XS

#6260 chore(main): release arize-phoenix 7.10.3
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6159 docs: agents-cookbook added to repo
  tutorials/experiments/agents-cookbook.ipynb
Labels: size:XL

#6262 chore: Update web dev docs
  .nvmrc
  DEVELOPMENT.md
Labels: size:M

#6261 fix(prompts): rename output schema to response format
  app/schema.graphql
  app/src/pages/playground/PlaygroundChatTemplateFooter.tsx
  app/src/pages/playground/PlaygroundResponseFormat.tsx
  app/src/pages/playground/__generated__/UpsertPromptFromTemplateDialogCreateMutation.graphql.ts
  app/src/pages/playground/__generated__/UpsertPromptFromTemplateDialogUpdateMutation.graphql.ts
  app/src/pages/playground/__generated__/fetchPlaygroundPromptQuery.graphql.ts
  app/src/pages/playground/fetchPlaygroundPrompt.ts
  app/src/pages/prompt/PromptCodeExportCard.tsx
  app/src/pages/prompt/PromptModelConfigurationCard.tsx
  app/src/pages/prompt/PromptOutputSchema.tsx
  app/src/pages/prompt/PromptResponseFormat.tsx
  app/src/pages/prompt/__generated__/PromptCodeExportCard__main.graphql.ts
  app/src/pages/prompt/__generated__/PromptModelConfigurationCard__main.graphql.ts
  app/src/pages/prompt/__generated__/PromptResponseFormatFragment.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts
  app/src/pages/prompt/promptCodeSnippets.tsx
  schemas/openapi.json
  src/phoenix/db/migrations/versions/bc8fea3c2bc8_add_prompt_tables.py
  src/phoenix/db/models.py
  src/phoenix/server/api/helpers/prompts/models.py
  src/phoenix/server/api/input_types/PromptVersionInput.py
  src/phoenix/server/api/mutations/prompt_mutations.py
  src/phoenix/server/api/routers/v1/prompts.py
  src/phoenix/server/api/types/PromptVersion.py
  src/phoenix/server/api/types/PromptVersionTemplate.py
  src/phoenix/server/api/types/ResponseFormat.py
  tests/unit/server/api/helpers/prompts/test_models.py
  tests/unit/server/api/mutations/test_prompt_mutations.py
  tests/unit/server/api/routers/v1/test_prompts.py
Labels: size:XL

#6248 feat(playground): central ai provider config
  app/schema.graphql
  app/src/Routes.tsx
  app/src/components/generative/GenerativeProviderIcon.tsx
  app/src/components/generative/index.ts
  app/src/pages/playground/PlaygroundCredentialsDropdown.tsx
  app/src/pages/settings/GenerativeProvidersCard.tsx
  app/src/pages/settings/SettingsPage.tsx
  app/src/pages/settings/__generated__/GenerativeProvidersCard_data.graphql.ts
  app/src/pages/settings/__generated__/settingsPageLoaderQuery.graphql.ts
  app/src/pages/settings/index.tsx
  app/src/pages/settings/settingsPageLoader.ts
  src/phoenix/server/api/types/GenerativeProvider.py
Labels: size:XL

#6264 chore(main): release arize-phoenix 7.11.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6252 feat(playground): record url info in playground spans
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/playground/schemas.ts
  src/phoenix/server/api/helpers/playground_clients.py
  src/phoenix/server/api/input_types/GenerativeModelInput.py
  tests/unit/server/api/test_subscriptions.py
Labels: size:L

#6273 chore: Upgrade pnpm version
  .github/workflows/playwright.yaml
  .github/workflows/typescript-CI.yml
  .github/workflows/typescript-packages-CI.yml
  .github/workflows/typescript-packages-publish.yml
  Dockerfile
  app/package.json
  js/package.json
Labels: size:M

#6275 fix: Do not assert all called
  packages/phoenix-evals/tests/phoenix/evals/functions/test_classify.py
Labels: size:XS

#6276 fix: Tweak timeout documentation on OpenAIModel
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
Labels: size:XS

#6127 chore(main): release arize-phoenix-evals 0.20.0
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#6277 chore: Move corepack usage after workdir configuration
  Dockerfile
Labels: size:XS

#6269 chore(main): release arize-phoenix 7.12.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6285 fix: Update parameter filtering logic
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
Labels: size:S

#6286 chore(main): release arize-phoenix-evals 0.20.1
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#6292 ci: fix type check
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:XS

#6287 fix: Use max completion tokens and tool calling check
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
Labels: size:S

#6293 chore(main): release arize-phoenix-evals 0.20.2
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#6189 feat(prompts): Implement Prompts support in phoenix-client typescript
  .github/workflows/typescript-packages-publish-experimental.yml
  js/examples/apps/phoenix-experiment-runner/index.ts
  js/package.json
  js/packages/phoenix-client/README.md
  js/packages/phoenix-client/examples/apply_prompt.ts
  js/packages/phoenix-client/examples/apply_prompt_anthropic.ts
  js/packages/phoenix-client/examples/apply_prompt_openai.ts
  js/packages/phoenix-client/package.json
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  js/packages/phoenix-client/src/client.ts
  js/packages/phoenix-client/src/config.ts
  js/packages/phoenix-client/src/constants.ts
  js/packages/phoenix-client/src/experiments/runExperiment.ts
  js/packages/phoenix-client/src/index.ts
  js/packages/phoenix-client/src/prompts/getPrompt.ts
  js/packages/phoenix-client/src/prompts/index.ts
  js/packages/phoenix-client/src/prompts/sdks/index.ts
  js/packages/phoenix-client/src/prompts/sdks/toAI.ts
  js/packages/phoenix-client/src/prompts/sdks/toAnthropic.ts
  js/packages/phoenix-client/src/prompts/sdks/toOpenAI.ts
  js/packages/phoenix-client/src/prompts/sdks/toSDK.ts
  js/packages/phoenix-client/src/prompts/sdks/types.ts
  js/packages/phoenix-client/src/schemas/llm/index.ts
  js/packages/phoenix-client/src/schemas/llm/jsonLiteralSchema.ts
  js/packages/phoenix-client/src/schemas/llm/messagePartSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/messageSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/promptSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/responseFormatSchema.ts
  js/packages/phoenix-client/src/schemas/llm/toolCallSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/toolChoiceSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/toolSchemas.ts
  js/packages/phoenix-client/src/types/core.ts
  js/packages/phoenix-client/src/types/logger.ts
  js/packages/phoenix-client/src/types/prompts.ts
  js/packages/phoenix-client/src/utils/assertUnreachable.ts
  js/packages/phoenix-client/src/utils/formatPromptMessages.ts
  js/packages/phoenix-client/src/utils/getDatasetLike.ts
  js/packages/phoenix-client/src/utils/getPromptVersionLike.ts
  js/packages/phoenix-client/src/utils/isObject.ts
  js/packages/phoenix-client/src/utils/noopLogger.ts
  js/packages/phoenix-client/src/utils/safelyParseJSON.ts
  js/packages/phoenix-client/src/utils/safelyStringifyJSON.ts
  js/packages/phoenix-client/test/prompts/sdks/data.ts
  js/packages/phoenix-client/test/prompts/sdks/toAnthropic.test.ts
  js/packages/phoenix-client/test/prompts/sdks/toOpenAI.test.ts
  js/packages/phoenix-client/test/utils/formatPromptMessages.test.ts
  js/pnpm-lock.yaml
Labels: size:XXL

#6294 feat(prompts): add description, last updated at to the prompts table
  app/src/pages/prompts/PromptsTable.tsx
  app/src/pages/prompts/__generated__/DeletePromptDialogMutation.graphql.ts
  app/src/pages/prompts/__generated__/PromptsTablePromptsQuery.graphql.ts
  app/src/pages/prompts/__generated__/PromptsTable_prompts.graphql.ts
  app/src/pages/prompts/__generated__/promptsLoaderQuery.graphql.ts
Labels: size:L

#6295 chore(prompts): Clean up commenting and type names
  js/packages/phoenix-client/README.md
  js/packages/phoenix-client/examples/apply_prompt.ts
  js/packages/phoenix-client/examples/apply_prompt_anthropic.ts
  js/packages/phoenix-client/examples/apply_prompt_openai.ts
  js/packages/phoenix-client/src/constants.ts
  js/packages/phoenix-client/src/experiments/runExperiment.ts
  js/packages/phoenix-client/src/prompts/constants.ts
  js/packages/phoenix-client/src/prompts/getPrompt.ts
  js/packages/phoenix-client/src/schemas/llm/messagePartSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/messageSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/toolCallSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/toolChoiceSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/toolSchemas.ts
  js/packages/phoenix-client/src/types/prompts.ts
  js/packages/phoenix-client/src/utils/getPromptVersionLike.ts
Labels: size:L

#6298 fix: stop propagation on playground button
  app/src/pages/prompts/PromptsTable.tsx
Labels: size:S

#6299 feat(prompts): Add support for Vercel AI sdk to TS phoenix-client
  js/packages/phoenix-client/examples/apply_prompt_vercel.ts
  js/packages/phoenix-client/package.json
  js/packages/phoenix-client/src/prompts/sdks/constants.ts
  js/packages/phoenix-client/src/prompts/sdks/toAI.ts
  js/packages/phoenix-client/src/prompts/sdks/toSDK.ts
  js/packages/phoenix-client/src/prompts/sdks/types.ts
  js/packages/phoenix-client/src/schemas/llm/messagePartSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/messageSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/toolChoiceSchemas.ts
  js/packages/phoenix-client/test/prompts/sdks/toAI.test.ts
  js/pnpm-lock.yaml
Labels: size:XL

#6301 feat(prompts): Denormalize tool choice in playground
  app/src/components/generative/ToolChoiceSelector.tsx
  app/src/pages/playground/PlaygroundChatTemplateFooter.tsx
  app/src/pages/playground/PlaygroundTool.tsx
  app/src/pages/playground/PlaygroundTools.tsx
  app/src/pages/playground/fetchPlaygroundPrompt.ts
  app/src/schemas/toolChoiceSchemas.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
Labels: size:L

#6282 feat: update client with response format for openai sdk
  packages/phoenix-client/src/phoenix/client/helpers/sdk/openai/chat.py
  packages/phoenix-client/tests/canary/sdk/openai/test_chat.py
  tests/integration/prompts/test_prompts.py
Labels: size:L

#6283 ci: add integration test for anthropic tools
  tests/integration/prompts/test_prompts.py
Labels: size:S

#6303 fix(prompts): make prompts and configuration collapsible
  app/src/pages/prompt/ChatTemplateMessageCard.tsx
  app/src/pages/prompt/PromptChatMessagesCard.tsx
  app/src/pages/prompt/PromptModelConfigurationCard.tsx
Labels: size:S

#6297 ci: tool choice integration tests
  src/phoenix/server/api/helpers/prompts/conversions/__init__.py
  src/phoenix/server/api/helpers/prompts/conversions/anthropic.py
  src/phoenix/server/api/helpers/prompts/conversions/openai.py
  src/phoenix/server/api/helpers/prompts/models.py
  src/phoenix/server/api/mutations/prompt_mutations.py
  tests/integration/prompts/test_prompts.py
Labels: size:L

#6316 refactor(prompts): Enforce zod schemas match openapi types (3/3)
  js/packages/phoenix-client/src/prompts/sdks/toAI.ts
  js/packages/phoenix-client/src/prompts/sdks/toAnthropic.ts
  js/packages/phoenix-client/src/prompts/sdks/toOpenAI.ts
  js/packages/phoenix-client/src/schemas/llm/anthropic/toolCallSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/anthropic/toolChoiceSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/constants.ts
  js/packages/phoenix-client/src/schemas/llm/converters.ts
  js/packages/phoenix-client/src/schemas/llm/openai/converters.ts
  js/packages/phoenix-client/src/schemas/llm/openai/messageSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/phoenixPrompt/converters.ts
  js/packages/phoenix-client/src/schemas/llm/phoenixPrompt/messagePartSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/phoenixPrompt/messageSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/phoenixPrompt/responseFormatSchema.ts
  js/packages/phoenix-client/src/schemas/llm/phoenixPrompt/toolCallSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/phoenixPrompt/toolChoiceSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/phoenixPrompt/toolSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/schemas.ts
  js/packages/phoenix-client/src/schemas/llm/types.ts
  js/packages/phoenix-client/src/schemas/llm/utils.ts
  js/packages/phoenix-client/src/schemas/llm/vercel/messagePartSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/vercel/messageSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/vercel/toolChoiceSchemas.ts
  js/packages/phoenix-client/src/types/prompts.ts
  js/packages/phoenix-client/src/utils/schemaMatches.ts
  js/packages/phoenix-client/test/prompts/sdks/toOpenAI.test.ts
Labels: size:XL

#6315 feat(prompts): Enhance LLM SDK provider converters and constants (2/3)
  js/packages/phoenix-client/src/prompts/sdks/toAI.ts
  js/packages/phoenix-client/src/prompts/sdks/toAnthropic.ts
  js/packages/phoenix-client/src/prompts/sdks/toOpenAI.ts
  js/packages/phoenix-client/src/schemas/llm/anthropic/converters.ts
  js/packages/phoenix-client/src/schemas/llm/anthropic/toolCallSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/anthropic/toolChoiceSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/constants.ts
  js/packages/phoenix-client/src/schemas/llm/converters.ts
  js/packages/phoenix-client/src/schemas/llm/openai/converters.ts
  js/packages/phoenix-client/src/schemas/llm/openai/messageSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/phoenixPrompt/converters.ts
  js/packages/phoenix-client/src/schemas/llm/phoenixPrompt/messagePartSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/phoenixPrompt/messageSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/phoenixPrompt/responseFormatSchema.ts
  js/packages/phoenix-client/src/schemas/llm/phoenixPrompt/toolCallSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/phoenixPrompt/toolChoiceSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/phoenixPrompt/toolSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/schemas.ts
  js/packages/phoenix-client/src/schemas/llm/types.ts
  js/packages/phoenix-client/src/schemas/llm/utils.ts
  js/packages/phoenix-client/src/schemas/llm/vercel/messagePartSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/vercel/messageSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/vercel/toolChoiceSchemas.ts
  js/packages/phoenix-client/src/types/prompts.ts
  js/packages/phoenix-client/src/utils/schemaMatches.ts
  js/packages/phoenix-client/test/prompts/sdks/toOpenAI.test.ts
Labels: size:XXL

#6319 feat(prompts): edit description
  app/src/GlobalStyles.tsx
  app/src/components/content/Heading.tsx
  app/src/components/field/styles.ts
  app/src/components/index.tsx
  app/src/components/overlay/Modal.tsx
  app/src/components/overlay/index.tsx
  app/src/components/textfield/index.tsx
  app/src/pages/prompt/EditPromptButton.tsx
  app/src/pages/prompt/PromptIndexPage.tsx
  app/src/pages/prompt/__generated__/EditPromptButtonPatchPromptMutation.graphql.ts
  app/src/pages/prompt/__generated__/EditPromptButton_data.graphql.ts
  app/src/pages/prompt/__generated__/PromptIndexPage__aside.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  app/stories/Modal.stories.tsx
Labels: size:XL

#6330 fix(prompts): Restore azure openai params from prompt into playground
  app/schema.graphql
  app/src/pages/playground/ModelSupportedParamsFetcher.tsx
  app/src/pages/playground/__generated__/UpsertPromptFromTemplateDialogCreateMutation.graphql.ts
  app/src/pages/playground/__generated__/UpsertPromptFromTemplateDialogUpdateMutation.graphql.ts
  app/src/pages/playground/__generated__/fetchPlaygroundPromptQuery.graphql.ts
  app/src/pages/playground/fetchPlaygroundPrompt.ts
  app/src/pages/prompt/__generated__/PromptChatMessagesCard__main.graphql.ts
  app/src/pages/prompt/__generated__/PromptCodeExportCard__main.graphql.ts
  app/src/pages/prompt/__generated__/PromptLLM__main.graphql.ts
  app/src/pages/prompt/__generated__/PromptModelConfigurationCard__main.graphql.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
  src/phoenix/server/api/input_types/PromptVersionInput.py
  src/phoenix/server/api/types/PromptVersion.py
Labels: size:M

#6324 fix: allow `prepared_statement_cache_size` for asyncpg
  src/phoenix/db/engines.py
Labels: size:M

#6309 fix(prompts): prompt invocation parameters
  .github/workflows/typescript-packages-CI.yml
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  js/packages/phoenix-client/src/prompts/sdks/toAI.ts
  js/packages/phoenix-client/src/prompts/sdks/toAnthropic.ts
  js/packages/phoenix-client/src/prompts/sdks/toOpenAI.ts
  js/packages/phoenix-client/test/prompts/sdks/data.ts
  js/packages/phoenix-client/test/prompts/sdks/toAI.test.ts
  js/packages/phoenix-client/test/prompts/sdks/toAnthropic.test.ts
  packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/anthropic/messages.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/google_generativeai/generate_content.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/openai/chat.py
  schemas/openapi.json
  src/phoenix/db/models.py
  src/phoenix/server/api/helpers/prompts/models.py
  src/phoenix/server/api/mutations/prompt_mutations.py
  src/phoenix/server/api/routers/v1/prompts.py
  src/phoenix/server/api/types/PromptVersion.py
  tests/integration/db_migrations/test_autoincrement_primary_keys.py
  tests/integration/prompts/test_prompts.py
  tests/unit/server/api/helpers/prompts/test_models.py
  tests/unit/server/api/mutations/test_prompt_mutations.py
  tests/unit/server/api/routers/v1/test_prompts.py
Labels: size:XXL

#6333 fix(prompts): Save tool calls from playground message into prompt
  app/schema.graphql
  app/src/pages/playground/__generated__/UpsertPromptFromTemplateDialogCreateMutation.graphql.ts
  app/src/pages/playground/__generated__/UpsertPromptFromTemplateDialogUpdateMutation.graphql.ts
  app/src/pages/playground/__tests__/fixtures.ts
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/playground/schemas.ts
  app/src/pages/prompt/promptCodeSnippets.tsx
  app/src/schemas/messageSchemas.ts
  app/src/schemas/toolCallSchemas.ts
  app/src/store/playground/types.ts
  src/phoenix/server/api/input_types/PromptVersionInput.py
Labels: size:L

#6339 fix(prompts): Do not wipe playground response format when switching providers
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/playground/schemas.ts
  app/src/schemas/toolSchemas.ts
  app/src/store/playground/playgroundStore.tsx
Labels: size:M

#6342 feat(prompts): use generative provider icon
  app/src/pages/playground/ModelConfigButton.tsx
  app/src/pages/playground/ModelProviderPicker.tsx
Labels: size:S

#6340 chore(components): migrate textfield and textarea
  app/.eslintrc.js
  app/src/components/CopyToClipboardButton.tsx
  app/src/components/auth/CreateAPIKeyDialog.tsx
  app/src/components/auth/OneTimeAPIKeyDialog.tsx
  app/src/components/dataset/DatasetForm.tsx
  app/src/components/field/SearchField.tsx
  app/src/components/field/TextField.tsx
  app/src/components/field/index.tsx
  app/src/components/field/styles.ts
  app/src/components/filter/ReferenceInferencesTimeRange.tsx
  app/src/components/index.tsx
  app/src/components/pointcloud/ClusteringSettings.tsx
  app/src/components/pointcloud/PointCloudParameterSettings.tsx
  app/src/components/settings/UserForm.tsx
  app/src/components/textfield/TextField.tsx
  app/src/components/trace/SpanAnnotationForm.tsx
  app/src/pages/auth/ForgotPasswordForm.tsx
  app/src/pages/auth/LoginForm.tsx
  app/src/pages/auth/ResetPasswordForm.tsx
  app/src/pages/auth/ResetPasswordWithTokenForm.tsx
  app/src/pages/dataset/AddDatasetExampleDialog.tsx
  app/src/pages/dataset/DatasetCodeDropdown.tsx
  app/src/pages/datasets/DatasetFromCSVForm.tsx
  app/src/pages/example/EditExampleDialog.tsx
  app/src/pages/experiment/ExperimentRunFilterConditionField.tsx
  app/src/pages/playground/InvocationParametersFormFields.tsx
  app/src/pages/playground/ModelConfigButton.tsx
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/PlaygroundCredentialsDropdown.tsx
  app/src/pages/playground/SavePromptForm.tsx
  app/src/pages/profile/ViewerAPIKeys.tsx
  app/src/pages/profile/ViewerProfileCard.tsx
  app/src/pages/project/DatasetSelectorPopoverContent.tsx
  app/src/pages/project/SpanFilterConditionField.tsx
  app/src/pages/projects/ProjectActionMenu.tsx
  app/src/pages/projects/RemoveProjectDataForm.tsx
  app/src/pages/prompt/ClonePromptDialog.tsx
  app/src/pages/prompt/NewPromptVersionTagDialog.tsx
  app/src/pages/settings/APIKeysCard.tsx
  app/src/pages/settings/ResetPasswordDialog.tsx
  app/src/pages/settings/SettingsPage.tsx
  app/src/pages/trace/SpanCodeDropdown.tsx
  app/stories/TextField.stories.tsx
Labels: size:XXL

#6347 feat(prompts): POST method for prompts endpoint
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  packages/phoenix-client/pyproject.toml
  packages/phoenix-client/scripts/codegen/transform.py
  packages/phoenix-client/src/phoenix/client/__generated__/v1/.gitignore
  packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py
  packages/phoenix-client/src/phoenix/client/__generated__/v1/models.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/anthropic/messages.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/google_generativeai/generate_content.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/openai/chat.py
  packages/phoenix-client/src/phoenix/client/resources/prompts/__init__.py
  packages/phoenix-client/src/phoenix/client/utils/config.py
  packages/phoenix-client/src/phoenix/client/utils/prompt.py
  packages/phoenix-client/src/phoenix/client/utils/template_formatters.py
  packages/phoenix-client/tests/canary/sdk/openai/test_chat.py
  schemas/openapi.json
  src/phoenix/db/models.py
  src/phoenix/server/api/openapi/schema.py
  src/phoenix/server/api/routers/v1/models.py
  src/phoenix/server/api/routers/v1/prompts.py
  tests/integration/prompts/test_prompts.py
  tox.ini
  tutorials/internal/prompts/hallucination_eval.ipynb
Labels: size:XXL

#6352 fix: restore playwright passing
  .github/workflows/playwright.yaml
  app/global-setup.ts
  app/src/components/field/styles.ts
  app/tests/login.rate-limit.spec.ts
  app/tests/user-management.spec.ts
Labels: size:S

#6351 fix: put tool choice in invocation parameters when sent to graphql
  app/src/components/generative/ToolChoiceSelector.tsx
  app/src/pages/playground/fetchPlaygroundPrompt.ts
  src/phoenix/server/api/helpers/prompts/models.py
  src/phoenix/server/api/types/PromptVersion.py
  tests/unit/server/api/helpers/prompts/test_models.py
  tests/unit/server/api/helpers/test_models.py
Labels: size:M

#6353 fix: eliminate cartesian join in REST endpoint
  src/phoenix/server/api/routers/v1/prompts.py
Labels: size:XS

#6355 fix(prompts): suppress pydantic warning
  src/phoenix/server/api/routers/v1/models.py
Labels: size:XS

#6328 docs(prompts): Add deno notebook example for TS phoenix-client
  .gitignore
  js/examples/notebooks/phoenix_prompts_cross_sdk_tutorial.ipynb
  js/examples/notebooks/phoenix_prompts_openai_tutorial.ipynb
  js/examples/notebooks/phoenix_prompts_vercel_ai_sdk.ipynb
Labels: size:XL

#6331 chore(main): release arize-phoenix 7.12.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6357 fix(prompts): trim leading and trailing whitespace from mustache template variables
  app/src/components/templateEditor/language/__tests__/languageUtils.test.ts
  app/src/components/templateEditor/language/languageUtils.ts
Labels: size:S

#6360 fix: login a11y via autocomplete
  app/src/components/settings/UserForm.tsx
  app/src/pages/auth/LoginForm.tsx
  app/src/pages/auth/ResetPasswordForm.tsx
  app/src/pages/auth/ResetPasswordPage.tsx
  app/src/pages/auth/__generated__/ResetPasswordFormQuery.graphql.ts
  app/src/pages/auth/__generated__/resetPasswordLoaderQuery.graphql.ts
  app/src/pages/auth/resetPasswordLoader.ts
Labels: size:L

#6363 fix(prompts): Perform prompt table sorting on the client
  app/src/pages/prompts/PromptsTable.tsx
Labels: size:XS

#6364 chore(prompts): Update notebook package hashes
  js/examples/notebooks/phoenix_prompts_cross_sdk_tutorial.ipynb
  js/examples/notebooks/phoenix_prompts_openai_tutorial.ipynb
  js/examples/notebooks/phoenix_prompts_vercel_ai_sdk.ipynb
Labels: size:S

#6356 feat(prompts): rudimentary playwright tests for prompts
  .github/workflows/playwright.yaml
  app/playwright.config.ts
  app/src/pages/prompt/PromptChatMessagesCard.tsx
  app/tests/prompt-management.spec.ts
Labels: size:L

#6370 fix: o1-preview does not support developer role
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
Labels: size:XS

#6371 chore(main): release arize-phoenix-evals 0.20.3
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#6362 chore(main): release arize-phoenix 7.12.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6375 fix(prompts): load f-string / none template format in playground from template
  app/src/pages/playground/UpsertPromptFromTemplateDialog.tsx
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/prompt/PromptPlaygroundPage.tsx
  app/src/pages/prompt/promptPlaygroundLoader.tsx
Labels: size:M

#6376 chore(prompts): Fix deno notebook syntax
  js/examples/notebooks/phoenix_prompts_cross_sdk_tutorial.ipynb
  js/examples/notebooks/phoenix_prompts_openai_tutorial.ipynb
  js/examples/notebooks/phoenix_prompts_vercel_ai_sdk.ipynb
Labels: size:XS

#6377 fix(prompts): Fix syntax highlighting in template editors
  app/src/components/templateEditor/TemplateEditor.tsx
Labels: size:XS

#6378 fix: missing slash in examples url printed after dataset upload
  src/phoenix/session/client.py
Labels: size:XS

#6380 refactor: rewrite AST script for OpenAPI codegen for Python client
  packages/phoenix-client/scripts/codegen/transform.py
  packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py
Labels: size:L

#6341 feat(prompts): Add Anthropic code snippets to prompt details
  app/src/pages/prompt/__tests__/fixtures.ts
  app/src/pages/prompt/__tests__/promptCodeSnippets.anthropic.test.ts
  app/src/pages/prompt/__tests__/promptCodeSnippets.openai.test.ts
  app/src/pages/prompt/promptCodeSnippets.tsx
  app/src/schemas/messageSchemas.ts
Labels: size:XXL

#6382 fix: Get prompts was returning 500s
  src/phoenix/server/api/routers/v1/prompts.py
Labels: size:XS

#6383 fix(promts): load invocation parameters for azure openai
  app/src/pages/playground/ModelConfigButton.tsx
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/__generated__/fetchPlaygroundPromptQuery.graphql.ts
  app/src/pages/playground/fetchPlaygroundPrompt.ts
  app/src/pages/prompt/PromptPlaygroundPage.tsx
Labels: size:XL

#6384 chore(prompts): Upgrade vite + vitest
  app/package.json
  app/pnpm-lock.yaml
Labels: size:XS

#6386 fix: remove v1 from examples url printed after uploading a dataset
  src/phoenix/session/client.py
Labels: size:XS

#6391 docs(prompts): Update ts client readme, add changeset
  js/.changeset/wet-glasses-train.md
  js/packages/phoenix-client/README.md
Labels: size:L

#6401 fix(promts): dataset URL
  app/src/pages/dataset/DatasetPage.tsx
Labels: size:XS

#6403 refactor(prompts): unify template format and language
  .github/workflows/typescript-packages-CI.yml
  app/schema.graphql
  app/src/components/templateEditor/TemplateEditor.tsx
  app/src/components/templateEditor/constants.ts
  app/src/components/templateEditor/templateEditorUtils.ts
  app/src/components/templateEditor/types.ts
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
  app/src/pages/playground/PlaygroundInput.tsx
  app/src/pages/playground/TemplateFormatRadioGroup.tsx
  app/src/pages/playground/TemplateLanguageRadioGroup.tsx
  app/src/pages/playground/UpsertPromptFromTemplateDialog.tsx
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableMutation.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableSubscription.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundOutputMutation.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  app/src/pages/playground/__generated__/UpsertPromptFromTemplateDialogCreateMutation.graphql.ts
  app/src/pages/playground/__generated__/UpsertPromptFromTemplateDialogUpdateMutation.graphql.ts
  app/src/pages/playground/__generated__/fetchPlaygroundPromptQuery.graphql.ts
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/playground/useDerivedPlaygroundVariables.tsx
  app/src/pages/prompt/ChatTemplateMessageCard.tsx
  app/src/pages/prompt/PromptChatMessagesCard.tsx
  app/src/pages/prompt/PromptPlaygroundPage.tsx
  app/src/pages/prompt/__generated__/PromptChatMessagesCard__main.graphql.ts
  app/src/pages/prompt/__generated__/PromptChatMessages__main.graphql.ts
  app/src/pages/prompt/__generated__/PromptCodeExportCard__main.graphql.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
  cspell.json
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  js/packages/phoenix-client/src/utils/formatPromptMessages.ts
  js/packages/phoenix-client/test/utils/formatPromptMessages.test.ts
  packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/anthropic/messages.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/google_generativeai/generate_content.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/openai/chat.py
  packages/phoenix-client/src/phoenix/client/types/prompts.py
  packages/phoenix-client/src/phoenix/client/utils/template_formatters.py
  schemas/openapi.json
  src/phoenix/db/migrations/versions/bc8fea3c2bc8_add_prompt_tables.py
  src/phoenix/db/models.py
  src/phoenix/server/api/helpers/prompts/models.py
  src/phoenix/server/api/input_types/ChatCompletionInput.py
  src/phoenix/server/api/input_types/PromptTemplateOptions.py
  src/phoenix/server/api/input_types/TemplateOptions.py
  src/phoenix/server/api/mutations/chat_mutations.py
  src/phoenix/server/api/subscriptions.py
  src/phoenix/server/api/types/TemplateLanguage.py
  tests/__generated__/graphql/__init__.py
  tests/integration/prompts/test_prompts.py
  tests/unit/server/api/mutations/test_chat_mutations.py
  tests/unit/server/api/test_subscriptions.py
Labels: size:XL

#6409 feat(prompts): client prompt creation
  js/.changeset/tasty-maps-remember.md
  js/packages/phoenix-client/README.md
  js/packages/phoenix-client/examples/create_prompt_openai.ts
  js/packages/phoenix-client/src/prompts/createPrompt.ts
  js/packages/phoenix-client/src/prompts/index.ts
  js/packages/phoenix-client/src/types/prompts.ts
  js/packages/phoenix-client/src/utils/formatPromptMessages.ts
  js/packages/phoenix-client/test/prompts/createPrompt.test.ts
  js/packages/phoenix-client/test/utils/formatPromptMessages.test.ts
Labels: size:L

#6416 refactor: use openai data model for normalized tool function and response format
  js/packages/phoenix-client/examples/apply_prompt_vercel.ts
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  js/packages/phoenix-client/src/prompts/sdks/toAI.ts
  js/packages/phoenix-client/src/schemas/llm/phoenixPrompt/converters.ts
  js/packages/phoenix-client/src/schemas/llm/phoenixPrompt/responseFormatSchema.ts
  js/packages/phoenix-client/src/schemas/llm/phoenixPrompt/toolChoiceSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/phoenixPrompt/toolSchemas.ts
  js/packages/phoenix-client/test/prompts/sdks/data.ts
  js/packages/phoenix-client/test/prompts/sdks/toAI.test.ts
  js/packages/phoenix-client/test/prompts/sdks/toAnthropic.test.ts
  js/packages/phoenix-client/test/prompts/sdks/toOpenAI.test.ts
  packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/anthropic/messages.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/google_generativeai/generate_content.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/openai/chat.py
  packages/phoenix-client/src/phoenix/client/resources/prompts/__init__.py
  packages/phoenix-client/src/phoenix/client/types/prompts.py
  packages/phoenix-client/tests/canary/sdk/anthropic/test_messages.py
  packages/phoenix-client/tests/canary/sdk/openai/test_chat.py
  schemas/openapi.json
  src/phoenix/server/api/helpers/prompts/conversions/anthropic.py
  src/phoenix/server/api/helpers/prompts/conversions/openai.py
  src/phoenix/server/api/helpers/prompts/models.py
  tests/__generated__/graphql/__init__.py
  tests/integration/prompts/test_prompts.py
  tests/unit/server/api/helpers/prompts/test_models.py
  tests/unit/server/api/helpers/test_models.py
  tests/unit/server/api/mutations/test_prompt_mutations.py
  tests/unit/server/api/routers/v1/test_prompts.py
  tutorials/internal/prompts/hallucination_eval.ipynb
  tutorials/prompts/from_anthropic.ipynb
  tutorials/prompts/from_openai.ipynb
  tutorials/prompts/hallucination_eval.ipynb
Labels: size:XXL

#6415 fix(prompts): Ignore whitespace in template variable names
  js/packages/phoenix-client/src/utils/formatPromptMessages.ts
  js/packages/phoenix-client/test/utils/formatPromptMessages.test.ts
Labels: size:M

#6418 chore: clean up pip install in notebook
  tutorials/prompts/hallucination_eval.ipynb
Labels: size:XS

#6421 refactor: rename google helper classmethod to explicitly include sdk name
  packages/phoenix-client/src/phoenix/client/types/prompts.py
Labels: size:XS

#6432 ci: add integration tests on prompt client for sdk round-tripping
  packages/phoenix-client/src/phoenix/client/helpers/sdk/anthropic/messages.py
  tests/integration/prompts/test_prompts.py
Labels: size:XL

#6433 chore: add register to send_spans
  scripts/testing/send_spans.py
Labels: size:XS

#6407 feat: enable one-line instrumentation with phoenix.otel.register
  packages/phoenix-otel/src/phoenix/otel/otel.py
Labels: size:S

#6410 chore(main): release arize-phoenix-otel 0.8.0
  .release-please-manifest.json
  packages/phoenix-otel/CHANGELOG.md
  packages/phoenix-otel/pyproject.toml
Labels: autorelease: pending, size:S

#6437 chore: fix pip install in notebooks
  tutorials/prompts/from_anthropic.ipynb
  tutorials/prompts/from_openai.ipynb
Labels: size:XS

#6443 fix: record user id when creating prompts via post
  src/phoenix/server/api/routers/v1/prompts.py
  tests/integration/prompts/test_prompts.py
Labels: size:S

#6441 feat(prompts): add code snippets using the phoenix-clients
  app/src/components/code/PythonBlock.tsx
  app/src/components/code/TypeScriptBlock.tsx
  app/src/pages/prompt/PromptCodeExportCard.tsx
  app/src/pages/prompt/__generated__/EditPromptButtonPatchPromptMutation.graphql.ts
  app/src/pages/prompt/__generated__/PromptCodeExportCard__main.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts
  app/src/pages/prompt/__tests__/fixtures.ts
  app/src/pages/prompt/__tests__/promptCodeSnippets.anthropic.test.ts
  app/src/pages/prompt/__tests__/promptCodeSnippets.openai.test.ts
  app/src/pages/prompt/promptCodeSnippets.tsx
Labels: size:L

#6444 fix(prompts): unterminated quote
  app/src/pages/prompt/promptCodeSnippets.tsx
Labels: size:XS

#6445 fix: strip leading and trailing whitespace characters from environment variables
  src/phoenix/config.py
  src/phoenix/server/api/helpers/playground_clients.py
  src/phoenix/server/api/types/GenerativeProvider.py
Labels: size:L

#6446 fix: request.user exception when auth is not enabled
  src/phoenix/server/api/routers/v1/prompts.py
  src/phoenix/server/app.py
Labels: size:XS

#6448 chore: use px.client.Client in tutorials for prompts
  tutorials/prompts/from_anthropic.ipynb
  tutorials/prompts/from_openai.ipynb
Labels: size:L

#6447 chore(main): release arize-phoenix 7.12.3
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6449 refactor(client): make most attributes private and add docstrings
  packages/phoenix-client/src/phoenix/client/client.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/anthropic/messages.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/openai/chat.py
  packages/phoenix-client/src/phoenix/client/resources/prompts/__init__.py
  packages/phoenix-client/src/phoenix/client/types/prompts.py
  packages/phoenix-client/src/phoenix/client/utils/config.py
  tests/integration/prompts/test_prompts.py
Labels: size:L

#6436 ci: additional integration tests on client for sdk round-tripping
  tests/integration/prompts/test_prompts.py
Labels: size:M

#6455 fix(prompts): Make tool schema properties field optional
  app/src/schemas/toolSchemas.ts
Labels: size:S

#6454 fix(prompts): Parse tool result json correctly
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/playgroundUtils.ts
Labels: size:M

#6450 fix(client): handle azure openai invocation parameters
  packages/phoenix-client/src/phoenix/client/helpers/sdk/anthropic/messages.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/google_generativeai/generate_content.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/openai/chat.py
  packages/phoenix-client/src/phoenix/client/types/prompts.py
  tests/integration/prompts/test_prompts.py
Labels: size:L

#6458 fix: reject sting templates in post requests
  src/phoenix/server/api/routers/v1/prompts.py
Labels: size:XS

#6462 chore: remove alpha status for python client
  release-please-config.json
Labels: size:XS

#6463 docs(js): fix readme compat table
  js/packages/phoenix-client/README.md
Labels: size:XS

#6461 chore(main): release arize-phoenix-client 1.0.0
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#6460 chore(main): release arize-phoenix 8.0.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:L

#6465 fix: phoenix client version
  packages/phoenix-client/pyproject.toml
Labels: size:XS

#6466 chore(main): release arize-phoenix-client 1.0.1
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending

#6468 fix: also reject on template_type
  src/phoenix/server/api/routers/v1/prompts.py
Labels: size:XS

#6464 chore(main): release arize-phoenix 8.0.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6470 fix(client): Remove runtime dependency on vercel ai
  js/.changeset/plenty-camels-end.md
  js/examples/notebooks/phoenix_prompts_cross_sdk_tutorial.ipynb
  js/examples/notebooks/phoenix_prompts_openai_tutorial.ipynb
  js/examples/notebooks/phoenix_prompts_vercel_ai_sdk.ipynb
  js/packages/phoenix-client/src/prompts/sdks/toAI.ts
  js/packages/phoenix-client/src/schemas/llm/constants.ts
  js/packages/phoenix-client/src/schemas/llm/converters.ts
  js/packages/phoenix-client/src/schemas/llm/openai/converters.ts
  js/packages/phoenix-client/src/schemas/llm/types.ts
  js/packages/phoenix-client/src/schemas/llm/utils.ts
  js/packages/phoenix-client/src/schemas/llm/vercel/toolSchemas.ts
Labels: size:M

#6473 fix: remove jsonschema dependency
  pyproject.toml
  src/phoenix/server/api/helpers/jsonschema.py
Labels: size:L

#6476 chore: update sphinx for phoenix client
  api_reference/source/api/client.resources.prompts.rst
  api_reference/source/api/client.resources.rst
  api_reference/source/api/client.rst
  api_reference/source/api/client.types.prompts.rst
  api_reference/source/api/client.types.rst
  api_reference/source/conf.py
  packages/phoenix-client/src/phoenix/client/resources/prompts/__init__.py
  packages/phoenix-client/src/phoenix/client/types/prompts.py
Labels: size:L

#6422 feat: Allow configuration of postgres username/password/db/host using standard env vars
  src/phoenix/config.py
  tests/unit/test_config.py
Labels: size:L

#6474 chore(main): release arize-phoenix 8.1.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6482 feat(performance): don't fetch new traces when the traces slideover is visible
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
Labels: size:M

#6493 fix: Use container-aware system resource usage metrics if possible
  src/phoenix/server/prometheus.py
Labels: size:L

#6506 fix: handle nan for graphql in annotation score
  src/phoenix/server/api/types/Annotation.py
Labels: size:XS

#6472 docs: prompt optimization use case example
  docs/Makefile
  docs/prompt-engineering/use-cases-prompts/prompt-optimization.md
  tutorials/prompts/prompt-optimization.ipynb
Labels: size:XXL

#6490 fix(perf): add graphql dataloaders for Span(Node) fields
  .github/workflows/docker-build-experimental.yml
  app/schema.graphql
  src/phoenix/db/models.py
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/span_by_id.py
  src/phoenix/server/api/dataloaders/span_descendants.py
  src/phoenix/server/api/dataloaders/span_fields.py
  src/phoenix/server/api/dataloaders/trace_root_spans.py
  src/phoenix/server/api/mutations/chat_mutations.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/subscriptions.py
  src/phoenix/server/api/types/DatasetExample.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/api/types/ProjectSession.py
  src/phoenix/server/api/types/Span.py
  src/phoenix/server/api/types/SpanIOValue.py
  src/phoenix/server/api/types/Trace.py
  src/phoenix/server/app.py
  src/phoenix/trace/attributes.py
  tests/unit/server/api/test_subscriptions.py
  tests/unit/server/api/types/test_Span.py
Labels: size:XXL, feature branch

#6483 chore(main): release arize-phoenix 8.2.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6507 docs(prompts): add prompt create to deno notebook
  js/examples/notebooks/phoenix_prompts_openai_tutorial.ipynb
Labels: size:M

#6510 fix: wrap annotation summaries in an error boundary
  app/src/components/ErrorBoundary.tsx
  app/src/components/exception/BugReportErrorBoundaryFallback.tsx
  app/src/components/exception/ErrorBoundary.tsx
  app/src/components/exception/TextErrorBoundaryFallback.tsx
  app/src/components/exception/index.tsx
  app/src/components/exception/types.ts
  app/src/components/index.tsx
  app/src/pages/project/ProjectPageHeader.tsx
  app/src/pages/trace/SessionPage.tsx
  app/src/pages/trace/SpanDetails.tsx
Labels: size:L

#6511 fix: suppress token icons in trace tree when count is zero
  app/src/components/trace/TraceTree.tsx
Labels: size:XS

#6512 chore(main): release arize-phoenix 8.2.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6513 fix: don't flex the trace tree toolbar
  app/src/components/trace/TraceTree.tsx
Labels: size:XS

#6537 fix: return None for graphql for null input output values on spans
  src/phoenix/server/api/types/Span.py
  tests/unit/server/api/types/test_Span.py
Labels: size:L

#6514 chore(main): release arize-phoenix 8.2.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6544 fix: remove unused span annotations in span details query
  app/src/pages/trace/TraceDetails.tsx
  app/src/pages/trace/TraceHeaderRootSpanAnnotations.tsx
  app/src/pages/trace/__generated__/TraceDetailsQuery.graphql.ts
  app/src/pages/trace/__generated__/TraceHeaderRootSpanAnnotationsQuery.graphql.ts
Labels: size:L

#6548 fix(ui): sort root spans in trace details
  app/src/components/trace/utils.ts
Labels: size:XS

#6547 docs: Add docstrings for new env vars
  src/phoenix/config.py
Labels: size:M

#6538 chore: Update github bug issue template
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: size:L

#6504 feat(client): typedoc docs gen for phoenix-client
  .github/workflows/typescript-packages-publish.yml
  .gitignore
  js/package.json
  js/packages/phoenix-client/package.json
  js/packages/phoenix-client/src/client.ts
  js/packages/phoenix-client/src/experiments/runExperiment.ts
  js/packages/phoenix-client/src/prompts/constants.ts
  js/packages/phoenix-client/src/prompts/createPrompt.ts
  js/packages/phoenix-client/src/prompts/getPrompt.ts
  js/packages/phoenix-client/src/prompts/sdks/toSDK.ts
  js/packages/phoenix-client/src/utils/getDatasetBySelector.ts
  js/packages/phoenix-client/src/utils/getPromptBySelector.ts
  js/packages/phoenix-client/typedoc.jsonc
  js/pnpm-lock.yaml
Labels: size:L

#6552 ci: gh pages publish of tsdocs
  .github/workflows/gh_pages.yml
Labels: size:M

#6553 fix: update playground for anthropic 0.47
  pyproject.toml
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:XS

#6549 refactor: remove sql join to traces table when not required
  app/schema.graphql
  app/src/Routes.tsx
  app/src/components/trace/TraceTree.tsx
  app/src/components/trace/__tests__/utils.test.ts
  app/src/components/trace/types.ts
  app/src/components/trace/utils.ts
  app/src/pages/example/ExampleDetailsDialog.tsx
  app/src/pages/example/ExampleExperimentRunsTable.tsx
  app/src/pages/example/__generated__/ExampleDetailsDialogQuery.graphql.ts
  app/src/pages/example/__generated__/ExampleExperimentRunsTableFragment.graphql.ts
  app/src/pages/example/__generated__/ExampleExperimentRunsTableQuery.graphql.ts
  app/src/pages/playground/RunMetadataFooter.tsx
  app/src/pages/playground/SpanPlaygroundPage.tsx
  app/src/pages/playground/__generated__/RunMetadataFooterQuery.graphql.ts
  app/src/pages/playground/__generated__/spanPlaygroundPageLoaderQuery.graphql.ts
  app/src/pages/playground/__tests__/fixtures.ts
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/spanPlaygroundPageLoader.ts
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
  app/src/pages/project/__generated__/ProjectPageQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectPageSpansQuery.graphql.ts
  app/src/pages/project/__generated__/SpansTableSpansQuery.graphql.ts
  app/src/pages/project/__generated__/SpansTable_spans.graphql.ts
  app/src/pages/project/__generated__/TracesTableQuery.graphql.ts
  app/src/pages/project/__generated__/TracesTable_spans.graphql.ts
  app/src/pages/trace/SessionDetails.tsx
  app/src/pages/trace/SessionDetailsTraceList.tsx
  app/src/pages/trace/SpanDetails.tsx
  app/src/pages/trace/TraceDetails.tsx
  app/src/pages/trace/__generated__/SessionDetailsQuery.graphql.ts
  app/src/pages/trace/__generated__/SpanDetailsQuery.graphql.ts
  app/src/pages/trace/__generated__/TraceDetailsQuery.graphql.ts
  src/phoenix/db/models.py
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/table_fields.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/Experiment.py
  src/phoenix/server/api/types/ExperimentRun.py
  src/phoenix/server/api/types/ExperimentRunAnnotation.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/api/types/ProjectSession.py
  src/phoenix/server/api/types/Span.py
  src/phoenix/server/api/types/Trace.py
  src/phoenix/server/app.py
  tests/__generated__/graphql/__init__.py
Labels: size:XL

#6550 fix: Add max_completion_tokens to openai param validation
  js/.changeset/brown-months-shout.md
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/openai/chat.py
  packages/phoenix-client/tests/canary/sdk/openai/test_chat.py
  schemas/openapi.json
  src/phoenix/server/api/helpers/prompts/models.py
  tests/integration/prompts/test_prompts.py
Labels: size:M

#6555 chore: Add npm badge to phoenix-client ts readme
  js/packages/phoenix-client/README.md
Labels: size:XS

#6517 chore(main): release arize-phoenix-client 1.0.2
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#6546 chore(main): release arize-phoenix 8.3.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6571 fix(perf): remove double fetching of spans
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
Labels: size:S

#6575 fix(ui): fix lack of scrolling on trace tree
  app/src/components/trace/TraceTree.tsx
Labels: size:XS

#6560 feat: graphql query to get byte size of each db table
  app/schema.graphql
  src/phoenix/server/api/queries.py
  tests/__generated__/graphql/__init__.py
  tests/unit/server/api/test_queries.py
Labels: size:L

#6577 fix(ui): broken textfields for span code dropdown
  app/src/pages/trace/SpanCodeDropdown.tsx
Labels: size:XS
