Repository Arize-ai/phoenix, pull requests merged in 2025-07, with the labels that each got.

#8345 chore: cleanup notebooks
  docs/section-cookbooks/datasets-and-experiments/text2sql.md
  tutorials/experiments/txt2sql.ipynb
Labels: size:L

#8366 chore(main): release arize-phoenix 11.2.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8367 docs: add local auth instructions
  app/README.md
Labels: size:S

#8376 fix(experiments): Clear the selectedSpanNodeId when closing trace view
  app/src/pages/experiment/ExperimentCompareTable.tsx
Labels: size:S

#8373 fix: remove extra join in query for span cost summary
  src/phoenix/server/api/dataloaders/span_cost_summary_by_project.py
Labels: size:S

#8372 chore(main): release arize-phoenix 11.2.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8317 fix: (soft) delete obsolete built-in models only if they're childless
  src/phoenix/db/facilitator.py
Labels: size:XS

#8353 docs: Adding templates for agent tool selection and parameter extraction
  packages/phoenix-evals/src/phoenix/evals/default_templates.py
Labels: size:L

#8388 chore(main): release arize-phoenix-evals 0.21.1
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#8387 feat: Add optional labels to vertex client
  packages/phoenix-evals/src/phoenix/evals/models/vertex.py
Labels: size:XS

#8371 feat: Add link back to customizable Management URL
  app/schema.graphql
  app/src/components/icon/Icons.tsx
  app/src/components/nav/Navbar.tsx
  app/src/contexts/ViewerContext.tsx
  app/src/contexts/__generated__/ViewerContextRefetchQuery.graphql.ts
  app/src/contexts/__generated__/ViewerContext_viewer.graphql.ts
  app/src/pages/Layout.tsx
  app/src/pages/__generated__/authenticatedRootLoaderQuery.graphql.ts
  app/src/window.d.ts
  src/phoenix/config.py
  src/phoenix/server/api/types/User.py
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  src/phoenix/server/templates/index.html
Labels: size:L

#8386 chore(main): release arize-phoenix 11.3.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8398 fix(helm): improve labels consistency
  helm/templates/phoenix/ingress.yaml
  helm/templates/phoenix/secret.yaml
  helm/templates/phoenix/service.yaml
Labels: size:S

#8394 fix: Support ISO8601 strings during experiment eval upsert
  pyproject.toml
  requirements/type-check.txt
  src/phoenix/server/api/routers/v1/experiment_evaluations.py
Labels: size:XS

#8397 refactor: refactor to use an mcp client
  js/packages/phoenix-mcp/package.json
  js/packages/phoenix-mcp/src/supportTools.ts
  js/pnpm-lock.yaml
Labels: size:L

#8395 feat: add phoenix-support tool to mcp
  js/packages/phoenix-mcp/README.md
  js/packages/phoenix-mcp/package.json
  js/packages/phoenix-mcp/src/index.ts
  js/packages/phoenix-mcp/src/supportTools.ts
  js/pnpm-lock.yaml
Labels: size:L

#8404 refactor: migrate AnnotationTooltip to phoenix component
  app/src/components/annotation/AnnotationSummaryGroup.tsx
  app/src/components/annotation/AnnotationTooltip.tsx
Labels: size:M

#8271 ci(cost): sync cost manifest
  .github/.scripts/sync_models.py
  .github/workflows/cost-sync.yml
  src/phoenix/db/facilitator.py
  src/phoenix/server/cost_tracking/model_cost_manifest.json
  tests/unit/db/test_facilitator.py
  tox.ini
Labels: size:XXL

#8212 chore(main): release arize-phoenix-client 1.12.0
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#8400 chore(main): release arize-phoenix 11.4.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8414 Feat: Update to postgres 16 in kustomize manifest
  kustomize/base/postgres.yaml
Labels: size:XS

#8449 refactor: Migrate AnnotationSummary tooltips and Metadata tooltip to new component
  app/src/components/annotation/AnnotationTooltip.tsx
  app/src/components/tooltip/RichTooltip.tsx
  app/src/components/tooltip/Tooltip.tsx
  app/src/components/tooltip/TriggerWrap.tsx
  app/src/components/tooltip/index.tsx
  app/src/components/tooltip/styles.ts
  app/src/pages/project/AnnotationSummary.tsx
  app/src/pages/project/MetadataTooltip.tsx
Labels: size:L

#8451 fix(experiments): paginate sql query on compare experiments page
  src/phoenix/server/api/queries.py
Labels: size:M

#8402 feat: add database disk usage monitor
  pyproject.toml
  src/phoenix/config.py
  src/phoenix/server/api/auth.py
  src/phoenix/server/api/routers/v1/annotation_configs.py
  src/phoenix/server/api/routers/v1/datasets.py
  src/phoenix/server/api/routers/v1/evaluations.py
  src/phoenix/server/api/routers/v1/experiment_runs.py
  src/phoenix/server/api/routers/v1/experiments.py
  src/phoenix/server/api/routers/v1/projects.py
  src/phoenix/server/api/routers/v1/prompts.py
  src/phoenix/server/api/routers/v1/spans.py
  src/phoenix/server/api/routers/v1/traces.py
  src/phoenix/server/api/routers/v1/users.py
  src/phoenix/server/app.py
  src/phoenix/server/authorization.py
  src/phoenix/server/bearer_auth.py
  src/phoenix/server/daemons/db_disk_usage_monitor.py
  src/phoenix/server/email/sender.py
  src/phoenix/server/email/templates/db_disk_usage_notification.html
  src/phoenix/server/email/types.py
  src/phoenix/server/grpc_server.py
  src/phoenix/server/prometheus.py
  src/phoenix/server/types.py
  tests/integration/_helpers.py
  tests/integration/auth/conftest.py
  tests/integration/auth/test_auth.py
  tests/integration/client/conftest.py
  tests/integration/client/test_annotations.py
  tests/integration/client/test_datasets.py
  tests/integration/client/test_projects.py
  tests/integration/client/test_prompts.py
  tests/integration/client/test_spans.py
  tests/integration/client/test_users.py
  tests/integration/conftest.py
  tests/integration/db_migrations/__init__.py
  tests/integration/db_migrations/conftest.py
  tests/integration/db_migrations/test_autoincrement_primary_keys.py
  tests/integration/db_migrations/test_change_jsonb_to_json_for_prompts.py
  tests/integration/db_migrations/test_data_migration_2f9d1a65945f_annotation_config_migration.py
  tests/integration/db_migrations/test_data_migration_4ded9e43755f_create_project_sessions_table.py
  tests/integration/db_migrations/test_data_migration_6a88424799fe_update_users_with_auth_method.py
  tests/integration/db_migrations/test_db_schema_2f9d1a65945f_annotation_config_migration.py
  tests/integration/db_migrations/test_db_schema_6a88424799fe_update_users_with_auth_method.py
  tests/integration/db_migrations/test_db_schema_a20694b15f82_cost.py
  tests/integration/db_migrations/test_up_and_down_migrations.py
  tests/integration/project_sessions/conftest.py
  tests/integration/project_sessions/test_project_sessions.py
  tests/integration/server/test_db_disk_usage_monitor.py
  tests/integration/server/test_launch_app.py
Labels: size:XXL

#8422 chore(main): release arize-phoenix 11.5.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8461 feat(experiments): add baseline to compare experiments page
  app/schema.graphql
  app/src/Routes.tsx
  app/src/pages/experiment/ExperimentComparePage.tsx
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/experiment/ExperimentMultiSelector.tsx
  app/src/pages/experiment/__generated__/ExperimentCompareTableQuery.graphql.ts
  app/src/pages/experiment/__generated__/ExperimentCompareTable_comparisons.graphql.ts
  app/src/pages/experiment/__generated__/ExperimentMultiSelector__data.graphql.ts
  app/src/pages/experiment/__generated__/ExperimentMultiSelector__experiments.graphql.ts
  app/src/pages/experiment/__generated__/experimentCompareLoaderQuery.graphql.ts
  app/src/pages/experiment/experimentCompareLoader.ts
  app/src/pages/experiments/ExperimentSelectionToolbar.tsx
  app/src/pages/experiments/ExperimentsTable.tsx
  app/src/pages/playground/PlaygroundDatasetSection.tsx
  src/phoenix/server/api/queries.py
  tests/unit/server/api/test_queries.py
Labels: size:XXL

#8464 feat(evals): typescript types and generateClassification
  js/packages/phoenix-evals/examples/classification_example.ts
  js/packages/phoenix-evals/package.json
  js/packages/phoenix-evals/src/index.ts
  js/packages/phoenix-evals/src/llm/generateClassification.ts
  js/packages/phoenix-evals/src/llm/index.ts
  js/packages/phoenix-evals/src/types/evals.ts
  js/packages/phoenix-evals/src/types/index.ts
  js/packages/phoenix-evals/src/types/prompts.ts
  js/pnpm-lock.yaml
Labels: size:L

#8459 ci: fix flaky integration test
  tests/integration/_helpers.py
  tests/integration/auth/conftest.py
  tests/integration/auth/test_auth.py
  tests/integration/client/conftest.py
  tests/integration/client/test_annotations.py
  tests/integration/client/test_spans.py
Labels: size:XL

#8492 fix: change postgresql query for db disk usage monitoring
  src/phoenix/server/api/queries.py
  src/phoenix/server/daemons/db_disk_usage_monitor.py
Labels: size:S

#8490 fix(cost): incorrect regex match method for model name
  src/phoenix/server/cost_tracking/cost_model_lookup.py
Labels: size:XS

#8491 fix: remove regex anchors for model names
  .github/.scripts/sync_models.py
  src/phoenix/server/cost_tracking/model_cost_manifest.json
Labels: size:L

#8484 docs(evals): spec
  internal_docs/specs/evals.md
Labels: size:M

#8495 fix(ui): spans table column for cumulative cost summary
  app/schema.graphql
  app/src/components/trace/SpanCumulativeTokenCosts.tsx
  app/src/components/trace/SpanCumulativeTokenCostsDetails.tsx
  app/src/components/trace/__generated__/SpanCumulativeTokenCostsDetailsQuery.graphql.ts
  app/src/pages/project/SessionsTable.tsx
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
  app/src/pages/project/__generated__/ProjectPageQueriesSpansQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectPageQueriesTracesQuery.graphql.ts
  app/src/pages/project/__generated__/SpansTableSpansQuery.graphql.ts
  app/src/pages/project/__generated__/SpansTable_spans.graphql.ts
  app/src/pages/project/__generated__/TracesTableQuery.graphql.ts
  app/src/pages/project/__generated__/TracesTable_spans.graphql.ts
  app/src/pages/trace/SessionDetailsTraceList.tsx
  app/src/pages/trace/__generated__/SessionDetailsQuery.graphql.ts
  app/src/pages/trace/__generated__/SessionDetailsTraceListRefetchQuery.graphql.ts
  app/src/pages/trace/__generated__/SessionDetailsTraceList_traces.graphql.ts
  src/phoenix/server/api/types/Span.py
Labels: size:XXL

#8506 fix(experiments): restore routing for comparing experiments
  app/src/Routes.tsx
  app/src/pages/experiment/ExperimentComparePage.tsx
  app/src/pages/experiment/__generated__/experimentCompareLoaderQuery.graphql.ts
  app/src/pages/experiment/experimentCompareLoader.ts
  app/src/pages/experiments/ExperimentSelectionToolbar.tsx
  app/src/pages/experiments/ExperimentsTable.tsx
  app/src/pages/playground/PlaygroundDatasetSection.tsx
Labels: size:L

#8508 chore(main): release arize-phoenix 11.6.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8515 fix: restore backward compatibility for locked mode
  src/phoenix/server/api/auth.py
Labels: size:XS

#8516 chore(main): release arize-phoenix 11.6.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8523 refactor: migrate more tooltips to phoenix library
  app/src/components/CopyToClipboardButton.tsx
  app/src/components/filter/PrimaryInferencesTimeRange.tsx
  app/src/components/filter/ReferenceInferencesTimeRange.tsx
  app/src/components/pointcloud/CanvasModeRadioGroup.tsx
  app/src/components/pointcloud/PointCloud.tsx
  app/src/components/trace/AnnotationConfigList.tsx
  app/src/pages/embedding/MetricSelector.tsx
  app/src/pages/project/SpanFilterConditionField.tsx
  app/src/pages/trace/SessionDetails.tsx
Labels: size:L

#8541 ci: fix monkey patching of opentelemetry exporter retry parameter
  requirements/integration-tests.txt
  tests/integration/conftest.py
Labels: size:S

#8550 fix: remove version upperbound on protobuf
  pyproject.toml
Labels: size:XS

#8551 ci(helm): fix helm permissions
  .github/workflows/helm-release.yaml
Labels: size:XS

#8554 feat(metrics): timeseries bar chart
  app/src/GlobalStyles.tsx
  app/src/components/chart/colors.tsx
  app/src/pages/project/ProjectMetricsPage.tsx
  app/src/pages/project/TraceCountTimeSeries.tsx
  app/stories/Colors.stories.tsx
  app/stories/StackedTimeSeriesBarChart.stories.tsx
  app/stories/chartColors.stories.tsx
  app/stories/constants/colorConstants.ts
Labels: size:XL

#8552 chore(main): release arize-phoenix 11.7.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8575 feat(storybook): split mode
  app/.storybook/preview-body.html
  app/.storybook/preview.tsx
Labels: size:M

#8583 ci: allow cursoragent in cla
  .github/workflows/cla.yml
Labels: size:XS

#8571 fix: Improve error message for missing email scope
  src/phoenix/server/api/routers/oauth2.py
Labels: size:S

#8592 ci: Update chromatic.yml to only run on PRs
  .github/workflows/chromatic.yml
Labels: size:XS

#8594 docs: add typescript evals readme
  README.md
  js/packages/phoenix-evals/README.md
Labels: size:M

#8595 docs: add typescript sub-packages
  docs/section-sdk-api-reference/typescript-packages/arizeai-phoenix-client.md
  docs/section-sdk-api-reference/typescript-packages/arizeai-phoenix-evals.md
Labels: size:L

#8589 fix: update phoenix support to search
  js/.changeset/thick-clowns-cheer.md
  js/packages/phoenix-mcp/src/supportTools.ts
Labels: size:S

#8597 feat(evals): add telemetry controls, tests
  js/.changeset/ten-parts-return.md
  js/packages/phoenix-evals/src/llm/createClassifier.ts
  js/packages/phoenix-evals/src/llm/createHallucinationEvaluator.ts
  js/packages/phoenix-evals/src/types/evals.ts
  js/packages/phoenix-evals/test/llm/createClassifier.test.ts
  js/packages/phoenix-evals/test/llm/createHallucinationEvaluator.test.ts
Labels: size:L

#8591 feat: Experiment enhancements
  packages/phoenix-client/src/phoenix/client/experiments/__init__.py
  packages/phoenix-client/src/phoenix/client/resources/experiments/__init__.py
  tests/integration/client/test_experiments.py
Labels: size:XXL

#8602 feat: add environment variable for support email to be included in error messages
  src/phoenix/config.py
  src/phoenix/server/api/auth.py
  src/phoenix/server/api/exceptions.py
  src/phoenix/server/app.py
  src/phoenix/server/authorization.py
  src/phoenix/server/email/sender.py
  src/phoenix/server/email/templates/db_disk_usage_notification.html
  tests/integration/server/test_db_disk_usage_monitor.py
Labels: size:L

#8475 feat: scaffold phoenix-cli
  js/.changeset/purple-grapes-taste.md
  js/packages/phoenix-cli/DEVELOPMENT.md
  js/packages/phoenix-cli/LICENSE
  js/packages/phoenix-cli/README.md
  js/packages/phoenix-cli/package.json
  js/packages/phoenix-cli/pnpm-lock.yaml
  js/packages/phoenix-cli/src/cli.ts
  js/packages/phoenix-cli/src/commands/index.ts
  js/packages/phoenix-cli/src/index.ts
  js/packages/phoenix-cli/src/utils/index.ts
  js/packages/phoenix-cli/test/cli.test.ts
  js/packages/phoenix-cli/tsconfig.esm.json
  js/packages/phoenix-cli/tsconfig.json
  js/packages/phoenix-mcp/pnpm-lock.yaml
  js/pnpm-lock.yaml
Labels: size:L

#8606 fix: Do not access API for experiment evaluations in dry_run mode
  packages/phoenix-client/src/phoenix/client/experiments/__init__.py
  packages/phoenix-client/src/phoenix/client/resources/experiments/__init__.py
  packages/phoenix-client/src/phoenix/client/resources/experiments/types.py
  tests/integration/client/test_experiments.py
Labels: size:L

#8587 feat: prompt variables skip parse
  packages/phoenix-evals/src/phoenix/evals/templates.py
  packages/phoenix-evals/tests/phoenix/evals/functions/test_executor.py
Labels: size:XS

#8620 chore(main): release arize-phoenix-client 1.13.1
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#8621 chore(main): release arize-phoenix-evals 0.23.0
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#8615 feat(design): categorical chart colors
  app/src/components/chart/colors.tsx
  app/stories/CategoricalChartColors.stories.tsx
Labels: size:L

#8623 chore: upgrade recharts
  app/package.json
  app/pnpm-lock.yaml
Labels: size:XS

#8586 fix(cost): ensure token counts are recorded in span costs table even if the model name does not match
  app/schema.graphql
  app/src/components/trace/SessionTokenCostsDetails.tsx
  app/src/components/trace/SpanTokenCostsDetails.tsx
  app/src/components/trace/TraceTokenCostsDetails.tsx
  app/src/components/trace/__generated__/SessionTokenCostsDetailsQuery.graphql.ts
  app/src/components/trace/__generated__/SpanTokenCostsDetailsQuery.graphql.ts
  app/src/components/trace/__generated__/TraceTokenCostsDetailsQuery.graphql.ts
  app/src/pages/settings/CloneModelButton.tsx
  app/src/pages/settings/EditModelButton.tsx
  app/src/pages/settings/ModelsTable.tsx
  app/src/pages/settings/__generated__/CloneModelButtonMutation.graphql.ts
  app/src/pages/settings/__generated__/CloneModelButtonQuery.graphql.ts
  app/src/pages/settings/__generated__/DeleteModelButtonMutation.graphql.ts
  app/src/pages/settings/__generated__/EditModelButtonMutation.graphql.ts
  app/src/pages/settings/__generated__/EditModelButtonQuery.graphql.ts
  app/src/pages/settings/__generated__/ModelsTable_generativeModels.graphql.ts
  app/src/pages/settings/__generated__/NewModelButtonCreateModelMutation.graphql.ts
  app/src/pages/settings/__generated__/SettingsModelsPageQuery.graphql.ts
  app/src/pages/settings/__generated__/settingsModelsLoaderQuery.graphql.ts
  app/src/pages/trace/SessionDetails.tsx
  app/src/pages/trace/__generated__/SessionDetailsQuery.graphql.ts
  src/phoenix/server/api/dataloaders/span_cost_summary_by_experiment.py
  src/phoenix/server/api/types/CostBreakdown.py
  src/phoenix/server/cost_tracking/cost_details_calculator.py
  src/phoenix/server/daemons/span_cost_calculator.py
  tests/unit/server/cost_tracking/test_cost_details_calculator.py
Labels: size:L

#8629 revert: recharts upgrade
  app/package.json
  app/pnpm-lock.yaml
Labels: size:XS

#8632 docs: update docs with java, dify integration links
  README.md
Labels: size:S

#8634 docs: Update data masking documentation
  docs/tracing/how-to-tracing/advanced/masking-span-attributes.md
Labels: size:XS

#8539 fix: paginate spans by trace start time when rendering span/trace table without filtering
  app/src/pages/project/SpansTable.tsx
  src/phoenix/server/api/types/Project.py
  tests/unit/server/api/types/test_Project.py
Labels: size:XL

#8578 chore(main): release arize-phoenix 11.8.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:M

#8608 refactor: migrate progress bar
  app/.eslintrc.js
  app/src/components/index.tsx
  app/src/components/progress/ProgressBar.tsx
  app/src/components/progress/ProgressCircle.tsx
  app/src/components/progress/index.tsx
  app/src/components/progress/styles.ts
  app/src/components/progress/types.ts
  app/src/components/progressCircle/types.ts
  app/src/pages/experiments/ExperimentsTable.tsx
  app/stories/ProgressBar.stories.tsx
  app/stories/ProgressCircle.stories.tsx
Labels: size:L

#8628 fix: Allow executors to run in background threads
  packages/phoenix-client/src/phoenix/client/utils/executors.py
  packages/phoenix-client/tests/client/utils/test_executors.py
Labels: size:M

#8640 chore(main): release arize-phoenix-client 1.13.2
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#8645 feat(traces): Implement trace project transfer API
  app/schema.graphql
  src/phoenix/db/insertion/span.py
  src/phoenix/server/api/mutations/trace_mutations.py
  tests/unit/server/api/mutations/test_trace_transfer_mutations.py
Labels: size:L

#8653 refactor: query for project only when trace is new during span ingestion
  src/phoenix/db/insertion/span.py
Labels: size:S

#8656 feat(charing): axis colors
  app/.cursor/rules/charting.mdc
  app/src/GlobalStyles.tsx
  app/src/components/chart/defaults.tsx
  app/src/pages/dashboard/DashboardBarChart.tsx
  app/src/pages/project/TraceCountTimeSeries.tsx
  app/stories/StackedTimeSeriesBarChart.stories.tsx
Labels: size:M

#8655 ci: remove timeout from span exporter fixtures
  tests/integration/_helpers.py
Labels: size:XS

#8616 refactor: breadcrumbs component
  app/.eslintrc.js
  app/src/components/breadcrumbs/Breadcrumb.tsx
  app/src/components/breadcrumbs/Breadcrumbs.tsx
  app/src/components/breadcrumbs/index.tsx
  app/src/components/index.tsx
  app/src/components/nav/NavBreadcrumb.tsx
  app/stories/Breadcrumbs.stories.tsx
Labels: size:L

#8650 feat: add trace errors chart + generic bar chart component
  app/src/pages/project/ProjectMetricsPage.tsx
  app/src/pages/project/TraceErrorsTimeSeries.tsx
Labels: size:L

#8660 feat: createProject GraphQL mutation
  app/schema.graphql
  src/phoenix/server/api/input_types/CreateProjectInput.py
  src/phoenix/server/api/mutations/project_mutations.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/server/dml_event.py
  tests/unit/server/api/mutations/test_project_mutations.py
Labels: size:L

#8659 ci: collect customer issues at 8am EDT
  .github/workflows/collect-customer-issues.yaml
Labels: size:XS

#8590 chore: add hallucination eval benchmark notebook
  scripts/benchmarks/hallucination_eval_benchmark.ipynb
Labels: size:L

#8674 refactor: migrate List component
  app/.eslintrc.js
  app/src/components/button/IconButton.tsx
  app/src/components/index.tsx
  app/src/components/list/List.tsx
  app/src/components/list/ListItem.tsx
  app/src/components/list/index.ts
  app/src/components/list/styles.ts
  app/src/components/list/types.ts
  app/src/components/progress/types.ts
  app/src/pages/embedding/ExportSelectionButton.tsx
  app/src/pages/prompt/PromptInvocationParameters.tsx
  app/src/pages/prompt/PromptLLM.tsx
  app/src/pages/trace/SpanDetails.tsx
  app/stories/List.stories.tsx
Labels: size:L

#8698 chore: fix style regressions in the UI
  app/src/pages/experiment/ExperimentRunFilterConditionField.tsx
  app/src/pages/project/DatasetSelectorPopoverContent.tsx
  app/src/pages/project/SpanFilterConditionField.tsx
Labels: size:M

#8648 feat: [ts] get dataset by version
  js/.changeset/wise-beds-rush.md
  js/packages/phoenix-client/src/datasets/getDataset.ts
  js/packages/phoenix-client/src/datasets/getDatasetExamples.ts
  js/packages/phoenix-client/src/datasets/getDatasetInfo.ts
  js/packages/phoenix-client/src/datasets/index.ts
  js/packages/phoenix-client/src/types/datasets.ts
  js/packages/phoenix-client/test/datasets/getDataset.test.ts
Labels: size:L

#8702 fix(design): textfield regressions
  app/src/components/field/styles.ts
Labels: size:S

#8706 fix: get response from tool calls function argument
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
Labels: size:S

#8707 chore(main): release arize-phoenix-evals 0.23.1
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#8704 feat(design): add icon button figma link
  app/.storybook/main.ts
  app/package.json
  app/pnpm-lock.yaml
  app/src/components/button/IconButton.tsx
  app/stories/CredentialField.stories.tsx
  app/stories/IconButton.stories.tsx
Labels: size:S

#8708 docs: adding annotations tutorial
  tutorials/annotations/custom-annotations-tool-for-eval-driven-development.ipynb
Labels: size:XL

#8715 feat: display allocated db capacity
  app/src/pages/settings/DBUsagePieChart.tsx
Labels: size:S

#8719 chore(main): release arize-phoenix 11.10.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8717 feat(design): floating toolbar
  app/.storybook/preview-body.html
  app/src/GlobalStyles.tsx
  app/src/components/index.tsx
  app/src/components/layout/Group.tsx
  app/src/components/toolbar/FloatingToolbarContainer.tsx
  app/src/components/toolbar/Separator.tsx
  app/src/components/toolbar/Toolbar.tsx
  app/src/components/toolbar/index.tsx
  app/src/pages/examples/ExampleSelectionToolbar.tsx
  app/src/pages/experiments/ExperimentSelectionToolbar.tsx
  app/src/pages/project/DatasetSelectorPopoverContent.tsx
  app/src/pages/project/SpanSelectionToolbar.tsx
  app/stories/Dialog.stories.tsx
  app/stories/Table.stories.tsx
  app/stories/Toolbar.stories.tsx
Labels: size:XXL

#8607 refactor: dialog-container on exampleToolSelection
  app/.eslintrc.js
  app/src/pages/examples/ExampleSelectionToolbar.tsx
Labels: size:M

#8736 refactor: playgroundDatasetExample remove dialogContainer
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
Labels: size:M

#8741 chore: remove console errors
  app/src/components/experiment/ExperimentRunTokenCosts.tsx
  app/src/components/markdown/styles.ts
  app/src/components/radio/RadioGroup.tsx
  app/src/components/toggleButtonGroup/ToggleButtonGroup.tsx
  app/src/components/tooltip/TriggerWrap.tsx
  app/src/components/trace/TraceTree.tsx
  app/src/components/utils/styleProps.ts
  app/src/contexts/FeatureFlagsContext.tsx
  app/src/pages/project/ProjectPageHeader.tsx
  app/src/pages/trace/TraceDetails.tsx
Labels: size:L

#8750 fix: format x axis labels on tops bar charts consistently with tooltips
  app/src/pages/project/TopModelsByCost.tsx
  app/src/pages/project/TopModelsByToken.tsx
Labels: size:XS

#8763 fix: make span event list scrollable
  app/src/pages/trace/SpanDetails.tsx
Labels: size:XS

#8720 chore(main): release arize-phoenix 11.11.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8768 feat(metrics): tooltip syncing
  app/src/GlobalStyles.tsx
  app/src/components/chart/ChartTooltip.tsx
  app/src/components/chart/colors.tsx
  app/src/pages/project/LLMSpanCountTimeSeries.tsx
  app/src/pages/project/LLMSpanErrorsTimeSeries.tsx
  app/src/pages/project/ProjectMetricsPage.tsx
  app/src/pages/project/SpanAnnotationScoreTimeSeries.tsx
  app/src/pages/project/ToolSpanCountTimeSeries.tsx
  app/src/pages/project/ToolSpanErrorsTimeSeries.tsx
  app/src/pages/project/TopModelsByCost.tsx
  app/src/pages/project/TraceCountTimeSeries.tsx
  app/src/pages/project/TraceErrorsTimeSeries.tsx
  app/src/pages/project/TraceLatencyPercentilesTimeSeries.tsx
  app/src/pages/project/TraceTokenCostTimeSeries.tsx
  app/src/pages/project/TraceTokenCountTimeSeries.tsx
  app/src/utils/numberFormatUtils.ts
Labels: size:L

#8781 feat: Update container tags with semver
  .github/workflows/docker-build-release.yml
Labels: size:XS

#8764 chore(main): release arize-phoenix 11.12.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8786 chore(main): release arize-phoenix 11.13.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8788 chore(main): release arize-phoenix 11.13.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8792 fix: sql group by clause in query for top models
  src/phoenix/server/api/types/Project.py
Labels: size:XS

#8793 fix: Add error boundaries to project metrics
  app/src/pages/project/metrics/ProjectMetricsPage.tsx
  app/src/pages/project/metrics/SpanAnnotationScoreTimeSeries.tsx
  app/src/pages/project/metrics/TraceLatencyPercentilesTimeSeries.tsx
Labels: size:L

#8794 chore(main): release arize-phoenix 11.13.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8803 ci: add tests for top models queries
  tests/unit/server/api/types/test_Project.py
Labels: size:L

#8810 docs: updated agent notebooks to new phoenix cloud set up
  tutorials/agents/agno/tracing_an_agno_agent.ipynb
  tutorials/agents/autogen/autogen_agents_evaluator_optimizer.ipynb
  tutorials/agents/autogen/autogen_agents_orchestrator.ipynb
  tutorials/agents/autogen/autogen_agents_parallelization.ipynb
  tutorials/agents/autogen/autogen_agents_prompt_chaining.ipynb
  tutorials/agents/autogen/autogen_agents_routing.ipynb
  tutorials/agents/crewai/crewai_ parallelization_tutorial.ipynb
  tutorials/agents/crewai/crewai_orchestrator_workers_tutorial.ipynb
  tutorials/agents/crewai/crewai_prompt_chaining_tutorial.ipynb
  tutorials/agents/crewai/crewai_routing_tutorial.ipynb
  tutorials/agents/google-genai/evaluator-optimizer-agent.ipynb
  tutorials/agents/google-genai/orchestration-agent.ipynb
  tutorials/agents/google-genai/parallelization-agent.ipynb
  tutorials/agents/google-genai/routing-agent.ipynb
  tutorials/agents/google-genai/sequential-agent.ipynb
  tutorials/agents/langgraph/evaluate-langgraph-rag-manual-instrumentation.py
  tutorials/agents/langgraph/langgraph_evaluator.ipynb
  tutorials/agents/langgraph/langgraph_orchestrator.ipynb
  tutorials/agents/langgraph/langgraph_parallel.ipynb
  tutorials/agents/langgraph/langgraph_promptchaining.ipynb
  tutorials/agents/langgraph/langgraph_router.ipynb
  tutorials/agents/openai/openai_agents_basic.ipynb
  tutorials/agents/openai/openai_agents_evaluator_optimizer.ipynb
  tutorials/agents/openai/openai_agents_orchestrator.ipynb
  tutorials/agents/openai/openai_agents_parallelization.ipynb
  tutorials/agents/openai/openai_agents_prompt_chaining.ipynb
  tutorials/agents/openai/openai_agents_routing.ipynb
  tutorials/agents/smolagents/smolagents_evaluator_optimizer.ipynb
  tutorials/agents/smolagents/smolagents_orchestrator.ipynb
  tutorials/agents/smolagents/smolagents_parallelization.ipynb
  tutorials/agents/smolagents/smolagents_prompt_chaining.ipynb
  tutorials/agents/smolagents/smolagents_router.ipynb
Labels: size:L

#8809 refactor: eslint dialogContainer
  app/.eslintrc.js
Labels: size:S

#8784 refactor: migrate card component (pt 1)
  app/src/GlobalStyles.tsx
  app/src/components/card/Card.tsx
  app/src/components/card/index.ts
  app/src/components/card/styles.ts
  app/src/components/card/types.ts
  app/src/components/dataset/NewDatasetButton.tsx
  app/src/components/index.tsx
  app/src/components/trace/SpanAnnotationsEditor.tsx
  app/src/pages/dataset/AddDatasetExampleDialog.tsx
  app/src/pages/example/EditExampleDialog.tsx
  app/src/pages/example/ExampleDetailsDialog.tsx
  app/stories/Card.stories.tsx
Labels: size:L

#8811 refactor(experiments): feature flag for experiment compare layouts
  app/src/components/experiment/ExperimentCompareViewSelect.tsx
  app/src/constants/timeConstants.ts
  app/src/contexts/FeatureFlagsContext.tsx
  app/src/pages/experiment/ExperimentCompareGridPage.tsx
  app/src/pages/experiment/ExperimentCompareMetricsPage.tsx
  app/src/pages/experiment/ExperimentComparePage.tsx
  app/src/pages/projects/ProjectsPage.tsx
  app/src/utils/__tests__/numberFormatUtils.test.ts
  app/src/utils/numberFormatUtils.ts
Labels: size:XL

#8829 chore(main): release arize-phoenix-client 1.14.0
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#8804 chore(main): release arize-phoenix 11.14.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8823 feat: allow external resource environment variable
  helm/README.md
  helm/templates/phoenix/configmap.yaml
  helm/values.yaml
  src/phoenix/config.py
  src/phoenix/server/app.py
  src/phoenix/server/templates/index.html
  tests/unit/test_config.py
Labels: size:M

#8835 docs: Update docs for air-gapped env var
  docs/section-self-hosting/configuration.md
  docs/section-self-hosting/misc/frequently-asked-questions.md
Labels: size:M

#8836 docs: Update documentation for span feedback context manager
  docs/tracing/how-to-tracing/feedback-and-annotations/annotating-auto-instrumented-spans.md
Labels: size:M

#8646 feat(helm): Add OIDC environment variable support to Helm
  helm/templates/phoenix/configmap.yaml
  helm/templates/phoenix/deployment.yaml
  helm/templates/phoenix/secret.yaml
  helm/values.yaml
Labels: size:M

#8819 feat: delete route for span
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  schemas/openapi.json
  src/phoenix/server/api/routers/v1/traces.py
  src/phoenix/server/dml_event_handler.py
  tests/unit/server/api/routers/v1/test_traces.py
Labels: size:L

#8798 feat(evals): adding support for Gemini API libraries
  packages/phoenix-evals/src/phoenix/evals/__init__.py
  packages/phoenix-evals/src/phoenix/evals/exceptions.py
  packages/phoenix-evals/src/phoenix/evals/models/__init__.py
  packages/phoenix-evals/src/phoenix/evals/models/google_genai.py
  packages/phoenix-evals/src/phoenix/evals/utils.py
  packages/phoenix-evals/tests/phoenix/evals/models/test_google_genai.py
  requirements/packages/phoenix-evals.txt
  tox.ini
Labels: size:L

#8779 chore(main): release arize-phoenix-evals 0.24.0
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#8846 fix(design): default text color
  app/src/GlobalStyles.tsx
Labels: size:XS

#8845 fix: use experiment project name for playground run on datasets
  src/phoenix/server/api/mutations/chat_mutations.py
  src/phoenix/server/api/routers/v1/experiments.py
  src/phoenix/server/api/subscriptions.py
  src/phoenix/server/experiments/__init__.py
  src/phoenix/server/experiments/utils.py
  tests/unit/server/api/mutations/test_chat_mutations.py
  tests/unit/server/api/test_subscriptions.py
Labels: size:M

#8850 chore: ai eval course hw1 and 2
  tox.ini
  tutorials/ai_evals_course/ai_evals_hw1_solution.ipynb
  tutorials/ai_evals_course/ai_evals_hw2_solution.ipynb
Labels: size:XXL

#8840 chore(main): release arize-phoenix-evals 0.25.0
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#8826 feat: document relevancy evaluator
  js/packages/phoenix-evals/benchmark/document_relevancy_benchmark.ts
  js/packages/phoenix-evals/src/default_templates/DOCUMENT_RELEVANCY_TEMPLATE.ts
  js/packages/phoenix-evals/src/default_templates/index.ts
  js/packages/phoenix-evals/src/llm/createClassifier.ts
  js/packages/phoenix-evals/src/llm/createDocumentRelevancyEvaluator.ts
  js/packages/phoenix-evals/src/llm/createHallucinationEvaluator.ts
  js/packages/phoenix-evals/src/llm/index.ts
  js/packages/phoenix-evals/src/types/evals.ts
  js/packages/phoenix-evals/test/llm/createDocumentRelevancyEvaluator.test.ts
Labels: size:XL

#8858 docs: Update docs for GoogleGenAI support
  docs/evaluation/how-to-evals/evaluation-models.md
  packages/phoenix-evals/docs/source/api/evals.rst
Labels: size:L

#8828 docs: adding custom evaluator notebook
  tutorials/evals/build_benchmark_dataset_and_custom_evaluator.ipynb
Labels: size:XL

#8178 feat: Add environment variable setting for default retention policy
  src/phoenix/config.py
  src/phoenix/db/facilitator.py
Labels: size:S

#8871 chore(main): release arize-phoenix-client 1.14.1
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#8825 ci: remove mutation on system user
  tests/integration/server/test_db_disk_usage_monitor.py
Labels: size:S

#8863 feat: trace delete route by relay id
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  schemas/openapi.json
  src/phoenix/server/api/routers/v1/traces.py
  tests/unit/server/api/routers/v1/test_traces.py
Labels: size:L

#8884 feat: Enable specifying object generation method
  packages/phoenix-evals/src/phoenix/evals/llm/adapters/langchain/adapter.py
  packages/phoenix-evals/src/phoenix/evals/llm/adapters/litellm/adapter.py
  packages/phoenix-evals/src/phoenix/evals/llm/adapters/openai/adapter.py
  packages/phoenix-evals/src/phoenix/evals/llm/types.py
Labels: size:XL

#8887 fix: Add emoji guard to experimental module warning
  packages/phoenix-evals/src/phoenix/evals/__init__.py
  packages/phoenix-evals/src/phoenix/evals/llm/registries.py
  packages/phoenix-evals/src/phoenix/evals/utils.py
Labels: size:M

#8886 refactor: card migration pt 3
  app/.eslintrc.js
  app/src/components/card/Card.tsx
  app/src/components/card/styles.ts
  app/src/components/card/types.ts
  app/src/pages/settings/AnnotationConfigDialog.tsx
  app/src/pages/settings/AnnotationConfigSelectionToolbar.tsx
  app/src/pages/settings/GenerativeProvidersCard.tsx
  app/src/pages/settings/GlobalRetentionPolicyCard.tsx
  app/src/pages/settings/SettingsAnnotationsPage.tsx
  app/src/pages/settings/SettingsDataPage.tsx
  app/src/pages/settings/SettingsGeneralPage.tsx
  app/src/pages/settings/SettingsModelsPage.tsx
  app/src/pages/settings/UsersCard.tsx
  app/src/pages/trace/SpanDetails.tsx
  app/src/pages/trace/SpanToDatasetExampleDialog.tsx
  app/stories/Card.stories.tsx
  app/stories/Disclosure.stories.tsx
  app/stories/RadioGroup.stories.tsx
  app/stories/Slider.stories.tsx
  app/stories/Tabs.stories.tsx
  app/stories/TitledPanel.stories.tsx
  app/stories/ToggleButtonGroup.stories.tsx
  app/stories/Token.stories.tsx
Labels: size:XXL
