Repository Arize-ai/phoenix, pull requests merged in 2025-09, with the labels that each got.

#9329 refactor(client): rename internal functions for dataframe validation for clarity
  packages/phoenix-client/src/phoenix/client/resources/annotations/__init__.py
  packages/phoenix-client/tests/client/resources/annotations/test_annotations.py
Labels: size:L

#9357 chore: add deprecation warning for using_project from inside phoenix.trace
  MIGRATION.md
  packages/phoenix-otel/pyproject.toml
  src/phoenix/trace/projects.py
Labels: size:M

#9354 refactor(evals): make evaluator a class, add ability to parse out variables
  js/packages/phoenix-evals/src/llm/ClassificationEvaluator.ts
  js/packages/phoenix-evals/src/llm/LLMEvaluator.ts
  js/packages/phoenix-evals/src/llm/createClassificationEvaluator.ts
  js/packages/phoenix-evals/src/llm/createHallucinationEvaluator.ts
  js/packages/phoenix-evals/src/template/getTemplateVariables.ts
  js/packages/phoenix-evals/src/template/index.ts
  js/packages/phoenix-evals/src/types/evals.ts
  js/packages/phoenix-evals/test/llm/createHallucinationEvaluator.test.ts
  js/packages/phoenix-evals/test/template/getTemplateVariables.test.ts
Labels: size:L

#9359 chore: remove use of using_project
  docs/tracing/how-to-tracing/setup-tracing/setup-projects.md
  scripts/demos/playground_demo.ipynb
  scripts/fixtures/multi-turn_chat_sessions.ipynb
  tutorials/ai_evals_course/phoenix_overview.ipynb
  tutorials/ragas_retrieval_evals_tutorial.ipynb
  tutorials/tracing/tracing_with_projects_tutorial.ipynb
Labels: size:XL

#9361 chore: sync main to docs
  MIGRATION.md
  docs/evaluation/preview/evaluators.md
  docs/tracing/how-to-tracing/setup-tracing/setup-projects.md
  js/packages/phoenix-evals/src/llm/ClassificationEvaluator.ts
  js/packages/phoenix-evals/src/llm/LLMEvaluator.ts
  js/packages/phoenix-evals/src/llm/createClassificationEvaluator.ts
  js/packages/phoenix-evals/src/llm/createHallucinationEvaluator.ts
  js/packages/phoenix-evals/src/template/getTemplateVariables.ts
  js/packages/phoenix-evals/src/template/index.ts
  js/packages/phoenix-evals/src/types/evals.ts
  js/packages/phoenix-evals/test/llm/createHallucinationEvaluator.test.ts
  js/packages/phoenix-evals/test/template/getTemplateVariables.test.ts
  packages/phoenix-evals/src/phoenix/evals/preview/evaluators.py
  packages/phoenix-evals/src/phoenix/evals/preview/llm/wrapper.py
  packages/phoenix-otel/pyproject.toml
  scripts/demos/playground_demo.ipynb
  scripts/fixtures/multi-turn_chat_sessions.ipynb
  src/phoenix/trace/projects.py
  tutorials/ai_evals_course/phoenix_overview.ipynb
  tutorials/ragas_retrieval_evals_tutorial.ipynb
  tutorials/tracing/tracing_with_projects_tutorial.ipynb
Labels: size:XXL

#9352 feat: add methods to log_document_annotations
  app/schema.graphql
  app/src/pages/trace/__generated__/SpanDetailsQuery.graphql.ts
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  packages/phoenix-client/examples/annotations/log_document_annotations_example.py
  packages/phoenix-client/examples/annotations/log_span_annotations_example.py
  packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py
  packages/phoenix-client/src/phoenix/client/client.py
  packages/phoenix-client/src/phoenix/client/resources/annotations/__init__.py
  packages/phoenix-client/src/phoenix/client/resources/spans/__init__.py
  packages/phoenix-client/src/phoenix/client/utils/annotation_helpers.py
  packages/phoenix-client/tests/client/resources/annotations/__init__.py
  packages/phoenix-client/tests/client/resources/annotations/test_annotations.py
  packages/phoenix-client/tests/client/utils/test_annotation_hepers.py
  schemas/openapi.json
  src/phoenix/server/api/dataloaders/document_evaluations.py
  src/phoenix/server/api/routers/v1/annotations.py
  src/phoenix/server/api/routers/v1/documents.py
  src/phoenix/server/api/routers/v1/spans.py
  src/phoenix/server/api/routers/v1/traces.py
  src/phoenix/server/api/types/DocumentAnnotation.py
  src/phoenix/server/api/types/Evaluation.py
  src/phoenix/server/api/types/Span.py
  src/phoenix/server/api/types/TraceAnnotation.py
  tests/integration/_helpers.py
  tests/integration/auth/test_auth.py
  tests/integration/client/test_annotations.py
  tests/integration/client/test_spans.py
  tests/unit/server/api/routers/v1/test_traces.py
  tests/unit/server/api/types/test_TraceAnnotation.py
Labels: size:XXL

#9323 chore(main): release arize-phoenix 11.31.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#9367 docs: fix doctring on document annotations
  packages/phoenix-client/src/phoenix/client/resources/spans/__init__.py
Labels: size:XS

#9371 chore: fix ai_evals_hw4_solution.ipynb
  tutorials/ai_evals_course/ai_evals_hw4_solution.ipynb
Labels: size:XL

#9375 chore(main): release arize-phoenix-client 1.17.1
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#9353 feat(experiments): experiment lists page frontend improvements
  app/src/pages/experiment/ExperimentCompareListPage.tsx
  app/src/pages/experiment/__generated__/ExperimentCompareListPageQuery.graphql.ts
  app/src/pages/experiment/__generated__/ExperimentCompareListPage_comparisons.graphql.ts
  app/src/pages/experiment/__generated__/experimentCompareLoaderQuery.graphql.ts
  scripts/experiments/generate_data_for_experiment_compare_page.py
Labels: size:L

#9379 refactor: update experiment compare list page typing
  app/src/pages/experiment/ExperimentCompareListPage.tsx
Labels: size:M

#9370 feat: inside run_experiment paginate get experiment runs
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py
  packages/phoenix-client/src/phoenix/client/resources/experiments/__init__.py
  schemas/openapi.json
  src/phoenix/experiments/functions.py
  src/phoenix/server/api/routers/v1/experiment_runs.py
  tests/unit/server/api/routers/v1/test_experiments.py
Labels: size:XL

#9369 feat: client methods for adding trace and session annotations
  app/schema.graphql
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py
  packages/phoenix-client/src/phoenix/client/client.py
  packages/phoenix-client/src/phoenix/client/resources/sessions/__init__.py
  packages/phoenix-client/src/phoenix/client/resources/traces/__init__.py
  packages/phoenix-client/src/phoenix/client/utils/annotation_helpers.py
  schemas/openapi.json
  src/phoenix/db/bulk_inserter.py
  src/phoenix/db/helpers.py
  src/phoenix/db/insertion/helpers.py
  src/phoenix/db/insertion/session_annotation.py
  src/phoenix/db/insertion/types.py
  src/phoenix/server/api/routers/v1/__init__.py
  src/phoenix/server/api/routers/v1/annotations.py
  src/phoenix/server/api/routers/v1/sessions.py
  src/phoenix/server/api/routers/v1/traces.py
  src/phoenix/server/api/types/ProjectSession.py
  src/phoenix/server/api/types/ProjectSessionAnnotation.py
  tests/integration/client/test_annotations.py
Labels: size:XXL

#9388 chore(main): release arize-phoenix 11.32.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#9360 feat: dataset split and examples migration
  MIGRATION.md
  src/phoenix/db/migrations/versions/0d25cd7dee22_add_dataset_splits_and_crosswalk_table.py
  src/phoenix/db/models.py
Labels: size:L

#9395 chore: script to extract DDL from PostgreSQL
  scripts/ddl/generate_ddl_postgresql.py
  scripts/ddl/postgresql_schema.sql
  tox.ini
Labels: size:XXL

#9373 feat(experiments): minimal refactoring of experiment compare details
  app/src/pages/experiment/ExperimentCompareDetails.tsx
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/experiment/ExperimentRunLatency.tsx
  app/src/pages/experiment/ExperimentRunMetadata.tsx
  app/stories/ExperimentTable.stories.tsx
Labels: size:XL

#9394 docs: text2cypher multilingual
  tutorials/evals/multilingual_text2cypher_evals.ipynb
Labels: size:XL

#9406 feat: experiment-tags on experiment and datasets
  src/phoenix/db/migrations/versions/0d25cd7dee22_add_dataset_splits_and_crosswalk_table.py
  src/phoenix/db/migrations/versions/699f655af132_experiment_tags.py
  src/phoenix/db/models.py
Labels: size:L

#9438 refactor: convert dataset selector to be an autocomplete
  app/src/components/listbox/ListBox.tsx
  app/src/pages/project/DatasetSelectorPopoverContent.tsx
  app/src/pages/project/SpanSelectionToolbar.tsx
  app/src/pages/project/TransferTracesButton.tsx
  app/src/pages/project/__generated__/DatasetSelectorPopoverContentDatasetsQuery.graphql.ts
  app/src/pages/project/__generated__/DatasetSelectorPopoverContentQuery.graphql.ts
  app/src/pages/project/__generated__/DatasetSelectorPopoverContent_datasets.graphql.ts
Labels: size:L

#9443 feat!: switch to the vercel ai sdk 5
  js/.changeset/heavy-horses-count.md
  js/packages/phoenix-client/package.json
  js/packages/phoenix-client/src/prompts/sdks/toAI.ts
  js/packages/phoenix-client/src/schemas/llm/openai/converters.ts
  js/packages/phoenix-client/src/schemas/llm/vercel/messagePartSchemas.ts
  js/packages/phoenix-client/src/schemas/llm/vercel/toolSchemas.ts
  js/packages/phoenix-client/test/prompts/sdks/toAI.test.ts
  js/pnpm-lock.yaml
Labels: size:L

#9455 docs: Document default admin password env var
  docs/section-self-hosting/configuration.md
  docs/section-self-hosting/features/authentication.md
Labels: size:S

#9452 chore: add deprecation warnings for legacy client and session methods
  src/phoenix/inferences/inferences.py
  src/phoenix/session/client.py
  src/phoenix/session/data_extractor.py
  src/phoenix/session/evaluation.py
  src/phoenix/session/session.py
  src/phoenix/trace/projects.py
  src/phoenix/utilities/deprecation.py
  tests/integration/client/test_annotations.py
  tests/integration/pyrightconfig.json
Labels: size:L

#9453 docs: missing version number in deprecation docstring
  packages/phoenix-client/src/phoenix/client/resources/annotations/__init__.py
Labels: size:M

#9318 chore(main): release arize-phoenix-otel 0.13.1
  .release-please-manifest.json
  packages/phoenix-otel/CHANGELOG.md
  packages/phoenix-otel/pyproject.toml
Labels: autorelease: pending, size:S

#9459 chore: enhance ddl extractor script
  scripts/ddl/generate_ddl_postgresql.py
  tox.ini
Labels: size:XL

#9462 chore: update cursor rule for document annotations
  .cursor/rules/client-migration.mdc
Labels: size:L

#9464 fix(client): handle multi-index for document annotations dataframe
  packages/phoenix-client/src/phoenix/client/utils/annotation_helpers.py
  packages/phoenix-client/tests/client/utils/test_annotation_hepers.py
Labels: size:XL

#9457 chore(main): release arize-phoenix-client 1.18.1
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#9467 chore: remove inline comments and abbreviate docstrings
  packages/phoenix-client/src/phoenix/client/utils/annotation_helpers.py
Labels: size:XL

#9468 feat: show prompt labels in prompt details
  app/schema.graphql
  app/src/pages/prompt/PromptIndexPage.tsx
  app/src/pages/prompt/PromptLabels.tsx
  app/src/pages/prompt/__generated__/EditPromptButtonPatchPromptMutation.graphql.ts
  app/src/pages/prompt/__generated__/PromptIndexPage__aside.graphql.ts
  app/src/pages/prompt/__generated__/PromptLabels.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  src/phoenix/server/api/types/Prompt.py
  src/phoenix/server/api/types/PromptLabel.py
Labels: size:L

#9495 fix(experiments): explode repetitions on experiment compare list page
  app/schema.graphql
  app/src/pages/experiment/ExperimentCompareListPage.tsx
  app/src/pages/experiment/__generated__/ExperimentCompareListPageQuery.graphql.ts
  app/src/pages/experiment/__generated__/ExperimentCompareListPage_comparisons.graphql.ts
  app/src/pages/experiment/__generated__/experimentCompareLoaderQuery.graphql.ts
  app/src/pages/experiment/experimentCompareLoader.ts
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/dataset_examples_and_versions_by_experiment_run.py
  src/phoenix/server/api/dataloaders/experiment_repeated_run_groups.py
  src/phoenix/server/api/types/DatasetExample.py
  src/phoenix/server/api/types/Experiment.py
  src/phoenix/server/api/types/ExperimentRun.py
  src/phoenix/server/app.py
  tests/unit/server/api/types/test_Experiment.py
Labels: size:XXL

#9503 feat(experiments): enable paging experiment compare details
  app/src/pages/experiment/ExampleDetailsPaginator.tsx
  app/src/pages/experiment/ExperimentCompareTable.tsx
Labels: size:L

#9497 feat(prompts): add prompt labels
  app/schema.graphql
  app/src/Routes.tsx
  app/src/components/ColorSwatch.tsx
  app/src/components/annotation/AnnotationColorSwatch.tsx
  app/src/components/color/ColorField.tsx
  app/src/components/color/ColorSwatch.tsx
  app/src/components/color/ColorSwatchPicker.tsx
  app/src/components/color/index.tsx
  app/src/components/dialog/Dialog.tsx
  app/src/components/index.tsx
  app/src/components/label/NewLabelForm.tsx
  app/src/components/label/index.tsx
  app/src/components/listbox/ListBox.tsx
  app/src/components/overlay/Modal.tsx
  app/src/components/prompt/NewPromptLabelButton.tsx
  app/src/components/prompt/NewPromptLabelDialog.tsx
  app/src/components/prompt/__generated__/NewPromptLabelDialogMutation.graphql.ts
  app/src/components/prompt/index.tsx
  app/src/pages/experiment/ExperimentCompareMetricsPage.tsx
  app/src/pages/experiment/ExperimentMultiSelector.tsx
  app/src/pages/project/RetrievalEvaluationLabel.tsx
  app/src/pages/project/TransferTracesButton.tsx
  app/src/pages/prompt/DeletePromptVersionTagButton.tsx
  app/src/pages/prompt/EditPromptButton.tsx
  app/src/pages/prompt/PromptIndexPage.tsx
  app/src/pages/prompt/PromptLabelConfigButton.tsx
  app/src/pages/prompt/PromptLabels.tsx
  app/src/pages/prompt/__generated__/EditPromptButtonPatchPromptMutation.graphql.ts
  app/src/pages/prompt/__generated__/PromptIndexPage__aside.graphql.ts
  app/src/pages/prompt/__generated__/PromptLabelConfigButtonQuery.graphql.ts
  app/src/pages/prompt/__generated__/PromptLabelConfigButtonSetLabelsMutation.graphql.ts
  app/src/pages/prompt/__generated__/PromptLabelConfigButtonUnsetLabelsMutation.graphql.ts
  app/src/pages/prompt/__generated__/PromptLabelConfigButton_allLabels.graphql.ts
  app/src/pages/prompt/__generated__/PromptLabelConfigButton_promptLabels.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  app/src/pages/prompts/PromptsTable.tsx
  app/src/pages/prompts/__generated__/DeletePromptDialogMutation.graphql.ts
  app/src/pages/prompts/__generated__/PromptsTablePromptsQuery.graphql.ts
  app/src/pages/prompts/__generated__/PromptsTable_prompts.graphql.ts
  app/src/pages/prompts/__generated__/promptsLoaderQuery.graphql.ts
  app/src/pages/settings/CreateRetentionPolicy.tsx
  app/src/pages/settings/SettingsPage.tsx
  app/src/pages/settings/index.tsx
  app/src/pages/settings/prompts/DeletePromptLabelButton.tsx
  app/src/pages/settings/prompts/PromptLabelsSettingsCard.tsx
  app/src/pages/settings/prompts/PromptLabelsTable.tsx
  app/src/pages/settings/prompts/SettingsPromptsPage.tsx
  app/src/pages/settings/prompts/__generated__/DeletePromptLabelButtonMutation.graphql.ts
  app/src/pages/settings/prompts/__generated__/PromptLabelsSettingsCardFragment.graphql.ts
  app/src/pages/settings/prompts/__generated__/PromptLabelsTableFragment.graphql.ts
  app/src/pages/settings/prompts/__generated__/SettingsPromptsPageQuery.graphql.ts
  app/src/pages/settings/prompts/index.tsx
  app/src/pages/trace/index.tsx
  src/phoenix/server/api/mutations/prompt_label_mutations.py
Labels: size:XXL

#9396 chore(main): release arize-phoenix 11.33.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#9513 feat(experiments): add experiment compare details slideover to list view
  app/src/pages/experiment/ExperimentCompareDetailsDialog.tsx
  app/src/pages/experiment/ExperimentCompareListPage.tsx
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/experiment/__generated__/ExperimentCompareDetailsDialogQuery.graphql.ts
  app/src/pages/experiment/__generated__/ExperimentCompareListPage_aggregateData.graphql.ts
  app/src/pages/experiment/__generated__/experimentCompareLoaderQuery.graphql.ts
Labels: size:XL

#9506 refactor(playground): virtualize playground dataset examples table
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
Labels: size:L

#9471 fix(js): allow the passthrough of tracer providers, switch to phoenix-evals in notebooks
  js/.changeset/hip-flowers-talk.md
  js/examples/notebooks/deno_datasets_and_experiments_quickstart.ipynb
  js/packages/phoenix-client/examples/dataset_and_experiments_quickstart.ts
  js/packages/phoenix-client/package.json
  js/packages/phoenix-client/src/experiments/runExperiment.ts
  js/packages/phoenix-client/src/types/experiments.ts
  js/pnpm-lock.yaml
Labels: size:L

#9518 chore: bump relay to latest
  app/package.json
  app/pnpm-lock.yaml
Labels: size:XS

#9520 feat(js): add more support for generics in evals
  js/.changeset/upset-areas-study.md
  js/packages/phoenix-client/examples/dataset_and_experiments_quickstart.ts
  js/packages/phoenix-client/src/types/experiments.ts
  js/packages/phoenix-evals/src/llm/ClassificationEvaluator.ts
  js/packages/phoenix-evals/src/llm/LLMEvaluator.ts
  js/packages/phoenix-evals/src/llm/createClassificationEvaluator.ts
  js/packages/phoenix-evals/src/llm/createClassifierFn.ts
  js/packages/phoenix-evals/src/llm/createDocumentRelevancyEvaluator.ts
  js/packages/phoenix-evals/src/llm/createHallucinationEvaluator.ts
  js/packages/phoenix-evals/test/llm/createClassificationEvaluator.test.ts
Labels: size:L

#9522 docs: ignore examples in ts
  js/typedoc.jsonc
Labels: size:XS

#9525 fix: higher buckets for insertion time histogram
  src/phoenix/server/prometheus.py
Labels: size:XS

#9516 chore(main): release arize-phoenix 11.34.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#9275 chore: Update langgraph ochestrator notebook to use new client
  tutorials/agents/langgraph/langgraph_orchestrator.ipynb
Labels: size:XS

#9482 feat(helm): add IPv6 support
  helm/values.yaml
Labels: size:XS

#9536 fix: improper sqlite sqlalchemy URL
  helm/templates/_helpers.tpl
Labels: size:XS

#9290 chore(main): release arize-phoenix-evals 2.0.0
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:L

#9538 docs: fix docs preview import paths
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/README.md
  packages/phoenix-evals/docs/source/api/evals.rst
  packages/phoenix-evals/docs/source/api/legacy.rst
  packages/phoenix-evals/docs/source/api/preview.rst
  packages/phoenix-evals/docs/source/index.md
Labels: size:XL

#9492 chore(main): release arize-phoenix-client 1.19.0
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#9485 feat(helm): allow image registry configuration
  helm/templates/phoenix/deployment.yaml
  helm/values.yaml
Labels: size:XS

#9553 ci: remove MacOS from integration tests
  .github/workflows/python-CI.yml
Labels: size:XS

#9465 fix: update llama-index pin
  pyproject.toml
Labels: size:XS

#9558 chore: sync docs to main
  docs/datasets-and-experiments/how-to-datasets/creating-datasets.md
  docs/datasets-and-experiments/how-to-experiments/run-experiments.md
  docs/datasets-and-experiments/quickstart-datasets.md
  docs/evaluation/how-to-evals/running-pre-tested-evals/tool-calling-eval.md
  docs/prompt-engineering/how-to-prompts/README.md
  docs/retrieval/quickstart-retrieval.md
  docs/section-cookbooks/.gitbook/assets/Screenshot 2025-08-28 at 1.31.26 PM.png
  docs/section-cookbooks/.gitbook/assets/What is Prompt Learning_ (1).png
  docs/section-cookbooks/.gitbook/assets/image.png
  docs/section-cookbooks/README.md
  docs/section-cookbooks/SUMMARY.md
  docs/section-cookbooks/evaluation/cookbooks.md
  docs/section-cookbooks/human-in-the-loop-workflows-annotations/aligning-llm-evals-with-human-annotations-typescript.md
  docs/section-cookbooks/human-in-the-loop-workflows-annotations/creating-a-custom-llm-evaluator-with-a-benchmark-dataset.md
  docs/section-cookbooks/human-in-the-loop-workflows-annotations/using-human-annotations-for-eval-driven-development.md
  docs/section-cookbooks/prompt-engineering/prompt-learning-optimizing-prompts-for-classification.md
  docs/section-cookbooks/retrieval-and-inferences/cookbooks.md
  docs/section-cookbooks/tracing/agentic-rag-tracing.md
  docs/section-cookbooks/tracing/cookbooks.md
  docs/section-cookbooks/tracing/generating-synthetic-datasets-for-llm-evaluators-and-agents.md
  docs/section-cookbooks/tracing/product-recommendation-agent-google-agent-engine-and-langgraph.md
  docs/section-cookbooks/tracing/structured-data-extraction.md
  docs/section-integrations/SUMMARY.md
  docs/section-integrations/frameworks/autogen/autogen-tracing.md
  docs/section-integrations/frameworks/google-adk/README.md
  docs/section-integrations/frameworks/google-adk/google-adk-tracing.md
  docs/section-integrations/frameworks/mastra/mastra-tracing.md
  docs/section-release-notes/08.2025/08.28.2025-new-arize-phoenix-client-package.md
  docs/section-release-notes/09.2025/09.03.2025-add-methods-to-log-document-annotations.md
  docs/section-release-notes/09.2025/09.04.2025-experiment-lists-page-frontend-enhancements.md
  docs/section-release-notes/09.2025/09.08.2025-experiment-annotation-popover-in-detail-view.md
  docs/section-release-notes/09.2025/09.12.2025-enable-paging-in-experiment-compare-details.md
  docs/section-release-notes/09.2025/09.15.2025-prompt-labels.md
  docs/section-release-notes/09.2025/README.md
  docs/section-release-notes/README.md
  docs/section-release-notes/SUMMARY.md
  tutorials/evals/google_adk_financial_advisor.ipynb
  tutorials/evals/multilingual_text2cypher_evals.ipynb
  tutorials/tracing/llama_index_tracing_tutorial.ipynb
Labels: size:XL

#9561 fix: nix llama-index extra
  pyproject.toml
  tutorials/tracing/project_sessions_llama_index_query_engine.ipynb
Labels: size:XS

#9276 docs(spec): server evaluator
  internal_docs/specs/server_evaluators.md
Labels: size:L

#9568 feat(phoenix-client): paginate through runs when experiments are re-run
  js/packages/phoenix-client/src/experiments/getExperimentRuns.ts
  js/packages/phoenix-client/test/experiments/getExperimentRuns.test.ts
Labels: size:L

#9605 feat: Add Azure provider support
  packages/phoenix-evals/src/phoenix/evals/llm/adapters/openai/adapter.py
  packages/phoenix-evals/src/phoenix/evals/llm/adapters/openai/factories.py
  packages/phoenix-evals/src/phoenix/evals/llm/wrapper.py
Labels: size:M

#9617 fix(playground): disable button for save to default on parse error for custom headers
  app/src/pages/playground/ModelConfigButton.tsx
Labels: size:M

#9606 feat: Assign examples to dataset splits
  app/src/components/dataset/NewDatasetSplitDialog.tsx
  app/src/components/datasetSplit/DatasetSplits.tsx
  app/src/components/datasetSplit/ManageDatasetSplitsDialog.tsx
  app/src/components/datasetSplit/NewDatasetSplitForm.tsx
  app/src/components/datasetSplit/__generated__/ManageDatasetSplitsDialogQuery.graphql.ts
  app/src/pages/dataset/DatasetPage.tsx
  app/src/pages/examples/ExampleSelectionToolbar.tsx
  app/src/pages/examples/ExamplesTable.tsx
  app/src/pages/examples/__generated__/ExampleSelectionToolbarAddDatasetExamplesToDatasetSplitsMutation.graphql.ts
  app/src/pages/examples/__generated__/ExampleSelectionToolbarAddExamplesToDatasetSplitMutation.graphql.ts
  app/src/pages/examples/__generated__/ExampleSelectionToolbarRemoveDatasetExamplesFromDatasetSplitMutation.graphql.ts
Labels: size:XL

#9609 feat: add junction table for taking snapshots of examples for experiments
  scripts/ddl/postgresql_schema.sql
  src/phoenix/db/facilitator.py
  src/phoenix/db/helpers.py
  src/phoenix/db/migrations/versions/deb2c81c0bb2_dataset_splits.py
  src/phoenix/db/migrations/versions/e76cbd66ffc3_add_experiments_dataset_examples.py
  src/phoenix/db/models.py
  src/phoenix/server/api/dataloaders/table_fields.py
  src/phoenix/server/api/mutations/chat_mutations.py
  src/phoenix/server/api/routers/v1/experiments.py
  src/phoenix/server/api/subscriptions.py
  tests/integration/db_migrations/test_data_migration_e76cbd66ffc3_add_experiments_dataset_examples.py
  tests/unit/_helpers.py
  tests/unit/db/test_helpers.py
  tests/unit/server/api/routers/v1/test_experiments.py
  tests/unit/server/api/test_subscriptions.py
Labels: size:XXL

#9636 feat: use composite primary key for crosswalk tables
  scripts/ddl/postgresql_schema.sql
  src/phoenix/db/migrations/versions/deb2c81c0bb2_dataset_splits.py
  src/phoenix/db/models.py
Labels: size:M

#9514 feat(playground): add repetitions to playground
  app/schema.graphql
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/experiment/ExperimentRepetitionSelector.tsx
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundConfigButton.tsx
  app/src/pages/playground/PlaygroundCredentialsDropdown.tsx
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
  app/src/pages/playground/PlaygroundDatasetExamplesTableContext.tsx
  app/src/pages/playground/PlaygroundStreamToggle.tsx
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableMutation.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableSubscription.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundOutputMutation.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  app/src/pages/playground/playgroundUtils.ts
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
  src/phoenix/server/api/helpers/playground_spans.py
  src/phoenix/server/api/input_types/ChatCompletionInput.py
  src/phoenix/server/api/mutations/chat_mutations.py
  src/phoenix/server/api/subscriptions.py
  src/phoenix/server/api/types/ChatCompletionSubscriptionPayload.py
  tests/unit/server/api/mutations/test_chat_mutations.py
  tests/unit/server/api/test_subscriptions.py
Labels: size:XL

#9610 feat(evals): add utility to format dataframe evaluations as annotations for logging to Phoenix
  docs/evaluation/preview/evaluators.md
  packages/phoenix-evals/src/phoenix/evals/__init__.py
  packages/phoenix-evals/src/phoenix/evals/evaluators.py
  packages/phoenix-evals/src/phoenix/evals/utils.py
  packages/phoenix-evals/tests/phoenix/evals/test_evaluators.py
  packages/phoenix-evals/tests/phoenix/evals/test_utils.py
  tutorials/evals/evals-2/evals_2.0_rag_demo.ipynb
  tutorials/evals/evals-2/evals_introduction.ipynb
Labels: size:XXL

#9646 chore(evals): update rag notebook
  tutorials/evals/evals-2/evals_2.0_rag_demo.ipynb
Labels: size:XS

#9652 docs: fix log evaluations documentation
  docs/tracing/how-to-tracing/feedback-and-annotations/llm-evaluations.md
Labels: size:M

#9629 chore(main): release arize-phoenix 11.38.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#9656 docs: fix broken demo link in docs
  docs/tracing/llm-traces-1/README.md
Labels: size:XS

#9648 feat(db): add row for viewer role
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  schemas/openapi.json
  src/phoenix/db/models.py
  src/phoenix/server/api/routers/v1/users.py
Labels: size:S

#9662 refactor: use composite primary key on datasets_dataset_labels crosswalk
  scripts/ddl/postgresql_schema.sql
  src/phoenix/db/migrations/versions/58228d933c91_dataset_labels.py
  src/phoenix/db/models.py
Labels: size:S

#9669 feat(experiments): show repetitions in the table
  app/src/pages/experiments/ExperimentsTable.tsx
  app/src/pages/experiments/__generated__/ExperimentsPageQuery.graphql.ts
  app/src/pages/experiments/__generated__/ExperimentsTableFragment.graphql.ts
  app/src/pages/experiments/__generated__/ExperimentsTableQuery.graphql.ts
Labels: size:M

#9667 refactor: remove color from experiment_tags
  src/phoenix/db/migrations/versions/699f655af132_experiment_tags.py
  src/phoenix/db/models.py
Labels: size:XS

#9666 feat: pin the minimum version of the client
  pyproject.toml
Labels: size:XS

#9670 docs(evals): update BYO evaluator markdown
  docs/evaluation/how-to-evals/bring-your-own-evaluator.md
  docs/evaluation/preview/templating.md
Labels: size:L

#9661 feat(evals): add document relevance evaluator
  packages/phoenix-evals/src/phoenix/evals/metrics/__init__.py
  packages/phoenix-evals/src/phoenix/evals/metrics/document_relevance.py
  packages/phoenix-evals/src/phoenix/evals/metrics/hallucination.py
Labels: size:L

#9644 chore(main): release arize-phoenix-evals 2.2.0
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#9674 chore: cleanup css on experiment compare
  app/src/components/table/IndeterminateCheckboxCell.tsx
  app/src/components/table/styles.ts
  app/src/pages/experiment/ExampleDetailsPaginator.tsx
  app/src/pages/experiment/ExperimentCompareDetailsDialog.tsx
  app/src/pages/trace/TracePage.tsx
Labels: size:L

#9668 refactor: hard-delete dataset splits
  scripts/ddl/postgresql_schema.sql
  src/phoenix/db/migrations/versions/deb2c81c0bb2_dataset_splits.py
  src/phoenix/db/models.py
  src/phoenix/server/api/dataloaders/dataset_example_splits.py
  src/phoenix/server/api/mutations/dataset_split_mutations.py
  src/phoenix/server/api/queries.py
Labels: size:L

#9671 docs(evals): drop multimodal evals page and update tracing docs
  docs/evaluation/how-to-evals/multimodal-evals.md
  docs/tracing/how-to-tracing/feedback-and-annotations/evaluating-phoenix-traces.md
  docs/tracing/how-to-tracing/feedback-and-annotations/llm-evaluations.md
Labels: size:L

#9700 feat: support Claude Sonnet 4.5
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:XS

#9707 fix: missing root path for logout
  src/phoenix/server/api/routers/auth.py
  src/phoenix/server/api/routers/oauth2.py
  src/phoenix/server/app.py
  src/phoenix/server/utils.py
  tests/unit/server/test_utils.py
Labels: size:L

#9699 chore(main): release arize-phoenix 12.1.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#9708 docs: evals on traces
  docs/tracing/how-to-tracing/feedback-and-annotations/evaluating-phoenix-traces.md
  docs/tracing/how-to-tracing/feedback-and-annotations/llm-evaluations.md
Labels: size:L

#9709 feat(evals): pass function doc strings through decorator
  packages/phoenix-evals/src/phoenix/evals/evaluators.py
Labels: size:XS

#9531 feat: Reverse-proxy support: added root_path parameter in launch_app
  src/phoenix/session/session.py
  tests/unit/session/test_root_path.py
Labels: size:M

#9682 feat: Add Menu component from react-aria
  app/src/components/index.tsx
  app/src/components/menu/Menu.tsx
  app/src/components/menu/index.tsx
  app/stories/Menu.stories.tsx
Labels: size:L
