Repository Arize-ai/phoenix, pull requests merged in 2025-06, with the labels that each got.

#7830 fix: Do not return notes from GET /span_annotations
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  packages/phoenix-client/src/phoenix/client/resources/spans/__init__.py
  schemas/openapi.json
  src/phoenix/server/api/routers/v1/annotations.py
  tests/integration/client/test_spans.py
  tests/unit/server/api/routers/v1/test_annotations.py
Labels: size:XL

#7889 feat(ui): credentials field
  app/src/components/field/CredentialContext.tsx
  app/src/components/field/CredentialField.tsx
  app/src/components/field/CredentialInput.tsx
  app/src/components/field/index.tsx
  app/src/components/icon/Icons.tsx
  app/src/pages/playground/PlaygroundCredentialsDropdown.tsx
  app/stories/CredentialField.stories.tsx
Labels: size:L

#7893 ci: enable ci on feature branches
  .github/workflows/python-CI.yml
  .github/workflows/typescript-CI.yml
  .github/workflows/typescript-packages-CI.yml
Labels: size:XS

#7688 feat: Add `get_spans` to phoenix client
  .gitignore
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py
  packages/phoenix-client/src/phoenix/client/resources/annotations/__init__.py
  packages/phoenix-client/src/phoenix/client/resources/spans/__init__.py
  schemas/openapi.json
  src/phoenix/server/api/routers/v1/spans.py
  tests/integration/client/test_spans.py
  tests/unit/server/api/routers/v1/test_spans.py
  tox.ini
Labels: size:XXL

#7847 chore(cost): add cost-related tables
  src/phoenix/db/migrations/versions/a20694b15f82_cost.py
  src/phoenix/db/models.py
Labels: size:L

#7902 chore(main): release arize-phoenix-otel 0.10.2
  .release-please-manifest.json
  packages/phoenix-otel/CHANGELOG.md
  packages/phoenix-otel/pyproject.toml
Labels: autorelease: pending, size:S

#7854 chore(main): release arize-phoenix 10.6.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: tagged, size:S

#7879 fix(helm): helm cleanup
  .github/workflows/docker-build-release.yml
  helm/Chart.lock
  helm/Chart.yaml
  helm/README.md
  helm/templates/_helpers.tpl
  helm/templates/database/deployment.yaml
  helm/templates/database/pvc.yaml
  helm/templates/database/service.yaml
  helm/templates/phoenix/configmap.yaml
  helm/templates/phoenix/ingress.yaml
  helm/values.yaml
Labels: size:L

#7905 chore: increment helm chart major version
  helm/Chart.yaml
Labels: size:XS

#7907 fix(helm): update Chart.lock and ensure chart dependencies are installed before packaging
  .github/workflows/helm-release.yaml
  helm/Chart.lock
Labels: size:XS

#7908 chore(main): release arize-phoenix 10.6.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7894 feat(playground): add support for multiple credential kv pairs - frontend only
  app/src/@types/generative.d.ts
  app/src/constants/__tests__/generativeConstants.test.ts
  app/src/constants/generativeConstants.ts
  app/src/pages/playground/PlaygroundCredentialsDropdown.tsx
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/settings/GenerativeProvidersCard.tsx
  app/src/store/credentialsStore.tsx
  app/src/utils/generativeUtils.ts
Labels: size:L

#7913 feat: server side playground credentials
  app/schema.graphql
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableMutation.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableSubscription.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundOutputMutation.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/settings/GenerativeProvidersCard.tsx
  app/src/pages/settings/__generated__/GenerativeProvidersCard_data.graphql.ts
  app/src/pages/settings/__generated__/settingsAIProvidersPageLoaderQuery.graphql.ts
  src/phoenix/server/api/helpers/playground_clients.py
  src/phoenix/server/api/helpers/playground_spans.py
  src/phoenix/server/api/input_types/ChatCompletionInput.py
  src/phoenix/server/api/input_types/GenerativeCredentialInput.py
  src/phoenix/server/api/mutations/chat_mutations.py
  src/phoenix/server/api/subscriptions.py
  src/phoenix/server/api/types/GenerativeProvider.py
  tests/unit/server/api/mutations/test_chat_mutations.py
Labels: size:L

#7915 fix: Ensure "load next" button works on projects page
  app/src/pages/projects/ProjectsPage.tsx
Labels: size:XS

#7921 ci: fix mypy types for opentelemetry-sdk==1.34.0
  src/phoenix/experiments/functions.py
  src/phoenix/experiments/tracing.py
  src/phoenix/server/telemetry.py
  src/phoenix/trace/projects.py
  tests/integration/_helpers.py
Labels: size:M

#7923 chore(main): release arize-phoenix-otel 0.10.3
  .release-please-manifest.json
  packages/phoenix-otel/CHANGELOG.md
  packages/phoenix-otel/pyproject.toml
Labels: autorelease: pending, size:S

#7924 fix: Sets a lower pin on phoenix-otel to support latest Otel
  pyproject.toml
Labels: size:XS

#7885 chore(main): release arize-phoenix-client 1.10.0
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#7927 fix: set Uvicorn logger level with PHOENIX_LOGGING_LEVEL
  src/phoenix/server/main.py
Labels: size:XS

#7933 chore: split otel docs
  packages/phoenix-otel/.readthedocs.yaml
  packages/phoenix-otel/docs/requirements.txt
Labels: size:XS

#7934 docs: promote the sub-packages higher
  api_reference/source/index.md
Labels: size:S

#7697 chore: switch kustomize to PG base
  kustomize/README.md
  kustomize/backends/postgres/kustomization.yaml
  kustomize/backends/postgres/patches.yaml
  kustomize/base/kustomization.yaml
  kustomize/base/phoenix.yaml
  kustomize/base/postgres.yaml
Labels: size:M

#7951 docs: update Kubernetes deployment docs to reflect PostgreSQL as defa…
  docs/section-self-hosting/deployment-options/kubernetes.md
Labels: size:L

#7955 docs: update main readthedoc
  api_reference/source/index.md
Labels: size:S

#7899 docs: Add mastra experiments example
  tutorials/agents/mastra/example-agent/.gitignore
  tutorials/agents/mastra/example-agent/README.md
  tutorials/agents/mastra/example-agent/package-lock.json
  tutorials/agents/mastra/example-agent/package.json
  tutorials/agents/mastra/example-agent/src/mastra/agents/weather-agent.ts
  tutorials/agents/mastra/example-agent/src/mastra/experiments/run_experiment.ts
  tutorials/agents/mastra/example-agent/src/mastra/index.ts
  tutorials/agents/mastra/example-agent/src/mastra/tools/calculator-tool.ts
  tutorials/agents/mastra/example-agent/src/mastra/tools/time-tool.ts
  tutorials/agents/mastra/example-agent/src/mastra/tools/weather-tool.ts
  tutorials/agents/mastra/example-agent/tsconfig.json
  tutorials/agents/mastra/mastra.db
Labels: size:XL

#7964 feat(experiments): make experiments table resizable
  app/src/pages/experiments/ExperimentsTable.tsx
  app/src/pages/project/SpansTable.tsx
Labels: size:L

#7952 chore(main): release arize-phoenix 10.8.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7977 chore: update dialogs
  app/src/pages/models/EditModelButton.tsx
  app/src/pages/models/ModelsTable.tsx
  app/src/pages/models/NewModelButton.tsx
Labels: size:L

#7978 feat(experiments): experiment progress chart
  app/src/hooks/useWordColor.ts
  app/src/pages/experiments/ExperimentsChart.tsx
  app/src/pages/experiments/ExperimentsLineChart.tsx
  app/src/pages/experiments/ExperimentsPage.tsx
  app/src/pages/experiments/ExperimentsTable.tsx
  app/src/pages/experiments/__generated__/ExperimentsLineChartQuery.graphql.ts
  app/src/pages/experiments/__generated__/experimentsLoaderQuery.graphql.ts
  app/src/pages/experiments/experimentsLoader.tsx
  app/src/utils/colorUtils.ts
Labels: size:XL

#7980 refactor(auth): Perform logout over GET instead of POST
  app/src/pages/Layout.tsx
  src/phoenix/server/api/routers/auth.py
  tests/integration/_helpers.py
  tests/integration/auth/test_auth.py
Labels: size:M

#7987 docs: fix js readme
  app/README.md
Labels: size:XS

#7988 chore(main): release arize-phoenix 10.9.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7992 docs: add js documentation
  js/README.MD
  js/packages/phoenix-client/DEVELOPMENT.md
Labels: size:M

#7993 chore: refactor dataset code to a slideover
  app/src/pages/dataset/DatasetCodeButton.tsx
  app/src/pages/dataset/DatasetCodeDropdown.tsx
  app/src/pages/dataset/DatasetHistoryButton.tsx
  app/src/pages/dataset/DatasetPage.tsx
  app/src/pages/experiments/ExperimentsLineChart.tsx
Labels: size:L

#8003 feat: Upgrade relay to v19
  app/package.json
  app/pnpm-lock.yaml
Labels: size:S

#8007 chore(main): release arize-phoenix 10.10.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8017 docs: correct typo error
  docs/tracing/integrations-tracing/langchain.md
Labels: size:XS

#8029 docs: updates phoenix-evals README
  packages/phoenix-evals/README.md
Labels: size:M

#8034 chore: clear type ignore
  packages/phoenix-otel/src/phoenix/otel/__init__.py
  packages/phoenix-otel/src/phoenix/otel/otel.py
Labels: size:XS

#8014 chore: Upgrade playwright and its runners
  .github/workflows/playwright.yaml
  app/package.json
  app/playwright.config.ts
  app/pnpm-lock.yaml
  app/src/components/media/Video.tsx
  app/tests/prompt-management.spec.ts
  app/tests/utils/testServer.mjs
  pyproject.toml
Labels: size:M

#8056 ci: add retries in span fixture setup for integration tests
  tests/integration/client/conftest.py
Labels: size:S

#8059 feat: publish major and minor version tags to docker
  .github/workflows/docker-build-release.yml
Labels: size:S

#7967 docs: Update llm_ops_overview.ipynb
  tutorials/llm_ops_overview.ipynb
Labels: size:S

#8070 chore: add missing border
  app/src/pages/datasets/DatasetsPage.tsx
Labels: size:XS

#8073 chore: sync docs to main
  docs/section-integrations/frameworks/hugging-face-smolagents/smolagents-tracing.md
  docs/tracing/integrations-tracing/hfsmolagents.md
  phoenix-integrations/.gitbook/includes/sign-up-for-phoenix-sign-up....md
Labels: size:L

#8071 feat(cost): move models config
  app/src/Routes.tsx
  app/src/components/table/styles.ts
  app/src/pages/Layout.tsx
  app/src/pages/models/ModelsPage.tsx
  app/src/pages/settings/CloneModelButton.tsx
  app/src/pages/settings/DeleteModelButton.tsx
  app/src/pages/settings/EditModelButton.tsx
  app/src/pages/settings/ModelForm.tsx
  app/src/pages/settings/ModelsTable.tsx
  app/src/pages/settings/NewModelButton.tsx
  app/src/pages/settings/SettingsModelsPage.tsx
  app/src/pages/settings/SettingsPage.tsx
  app/src/pages/settings/__generated__/CloneModelButtonMutation.graphql.ts
  app/src/pages/settings/__generated__/CloneModelButtonQuery.graphql.ts
  app/src/pages/settings/__generated__/DeleteModelButtonMutation.graphql.ts
  app/src/pages/settings/__generated__/EditModelButtonMutation.graphql.ts
  app/src/pages/settings/__generated__/EditModelButtonQuery.graphql.ts
  app/src/pages/settings/__generated__/ModelsTableModelsQuery.graphql.ts
  app/src/pages/settings/__generated__/ModelsTable_models.graphql.ts
  app/src/pages/settings/__generated__/NewModelButtonCreateModelMutation.graphql.ts
  app/src/pages/settings/__generated__/settingsModelsLoaderQuery.graphql.ts
  app/src/pages/settings/settingsModelsLoader.ts
  app/stories/ModelForm.stories.tsx
Labels: size:L

#8072 feat(helm): enable zero downtime rollouts
  helm/README.md
  helm/templates/phoenix/deployment.yaml
  helm/values.yaml
Labels: size:L

#8005 feat: Add `log_spans` to client and REST API
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py
  packages/phoenix-client/src/phoenix/client/exceptions/__init__.py
  packages/phoenix-client/src/phoenix/client/helpers/spans/__init__.py
  packages/phoenix-client/src/phoenix/client/resources/spans/__init__.py
  schemas/openapi.json
  src/phoenix/server/api/routers/v1/spans.py
  tests/integration/client/test_spans.py
Labels: size:XXL

#8075 chore(main): release arize-phoenix 10.12.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8100 chore: Add symlinks automatically when running dev cmd
  app/package.json
Labels: size:XS

#8109 fix(cost): allow custom providers in model form
  app/schema.graphql
  app/src/pages/settings/CloneModelButton.tsx
  app/src/pages/settings/EditModelButton.tsx
  app/src/pages/settings/ModelForm.tsx
  app/src/pages/settings/NewModelButton.tsx
  app/src/pages/settings/__generated__/CloneModelButtonMutation.graphql.ts
  app/src/pages/settings/__generated__/EditModelButtonMutation.graphql.ts
  app/src/pages/settings/__generated__/NewModelButtonCreateModelMutation.graphql.ts
  app/src/utils/generativeUtils.ts
  app/stories/ModelForm.stories.tsx
  src/phoenix/server/api/mutations/model_mutations.py
Labels: size:L

#8112 fix(cost): adjust model crud mutations to allow for arbitrary cost types
  app/schema.graphql
  app/src/pages/settings/CloneModelButton.tsx
  app/src/pages/settings/EditModelButton.tsx
  app/src/pages/settings/NewModelButton.tsx
  app/src/pages/settings/__generated__/CloneModelButtonMutation.graphql.ts
  app/src/pages/settings/__generated__/EditModelButtonMutation.graphql.ts
  app/src/pages/settings/__generated__/NewModelButtonCreateModelMutation.graphql.ts
  src/phoenix/server/api/mutations/model_mutations.py
Labels: size:L

#8093 feat(cost): metrics tab behind a feature flag
  app/src/Routes.tsx
  app/src/contexts/FeatureFlagsContext.tsx
  app/src/pages/project/ProjectMetricsPage.tsx
  app/src/pages/project/ProjectPage.tsx
  app/src/pages/project/index.tsx
Labels: size:L

#8118 test(cost): add unit tests for model crud mutations
  tests/unit/server/api/mutations/test_model_mutations.py
Labels: size:L

#8018 refactor: dialog migration
  app/.eslintrc.js
  app/src/components/ConfirmNavigation.tsx
  app/src/components/auth/CreateAPIKeyDialog.tsx
  app/src/components/auth/DeleteAPIKeyButton.tsx
  app/src/components/auth/OneTimeAPIKeyDialog.tsx
  app/src/components/experiment/ExperimentActionMenu.tsx
  app/src/contexts/FeatureFlagsContext.tsx
  app/src/pages/dataset/AddDatasetExampleButton.tsx
  app/src/pages/dataset/AddDatasetExampleDialog.tsx
  app/src/pages/dataset/DatasetHistoryButton.tsx
  app/src/pages/dataset/DatasetHistoryDialog.tsx
  app/src/pages/dataset/RunExperimentButton.tsx
  app/src/pages/datasets/DatasetActionMenu.tsx
  app/src/pages/datasets/DatasetsPage.tsx
  app/src/pages/datasets/DeleteDatasetDialog.tsx
  app/src/pages/datasets/EditDatasetDialog.tsx
  app/src/pages/dimension/DimensionPage.tsx
  app/src/pages/embedding/ExportSelectionButton.tsx
  app/src/pages/embedding/PointSelectionPanelContent.tsx
  app/src/pages/example/EditExampleDialog.tsx
  app/src/pages/example/ExampleDetailsDialog.tsx
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/experiments/ExperimentSelectionToolbar.tsx
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
  app/src/pages/playground/PlaygroundExperimentRunDetailsDialog.tsx
  app/src/pages/playground/PlaygroundTemplate.tsx
  app/src/pages/playground/SavePromptForm.tsx
  app/src/pages/playground/UpsertPromptFromTemplateDialog.tsx
  app/src/pages/profile/ViewerAPIKeys.tsx
  app/src/pages/profile/__generated__/ViewerAPIKeysCreateUserAPIKeyMutation.graphql.ts
  app/src/pages/project/ProjectTableEmpty.tsx
  app/src/pages/project/SessionsTableEmpty.tsx
  app/src/pages/projects/NewProjectButton.tsx
  app/src/pages/projects/ProjectActionMenu.tsx
  app/src/pages/prompt/ClonePromptDialog.tsx
  app/src/pages/prompt/NewPromptVersionTagDialog.tsx
  app/src/pages/prompt/PromptLayout.tsx
  app/src/pages/prompt/TagPromptVersionButton.tsx
  app/src/pages/prompts/DeletePromptDialog.tsx
  app/src/pages/prompts/PromptActionMenu.tsx
  app/src/pages/settings/APIKeysCard.tsx
  app/src/pages/settings/DeleteUserDialog.tsx
  app/src/pages/settings/GenerativeProvidersCard.tsx
  app/src/pages/settings/ResetPasswordDialog.tsx
  app/src/pages/settings/RetentionPolicyActionMenu.tsx
  app/src/pages/settings/SystemAPIKeysTable.tsx
  app/src/pages/settings/UserActionMenu.tsx
  app/src/pages/settings/UserRoleChangeDialog.tsx
  app/src/pages/settings/__generated__/APIKeysCardCreateSystemAPIKeyMutation.graphql.ts
  app/src/pages/settings/__generated__/APIKeysCardQuery.graphql.ts
  app/src/pages/settings/__generated__/SystemAPIKeysTableFragment.graphql.ts
  app/src/pages/settings/__generated__/SystemAPIKeysTableQuery.graphql.ts
  app/src/pages/trace/EditSpanAnnotationsButton.tsx
  app/src/pages/trace/SessionPage.tsx
  app/src/pages/trace/SpanDetails.tsx
  app/stories/AnnotationInputs.stories.tsx
  app/stories/ChatUI.stories.tsx
  app/tests/member-access.spec.ts
Labels: size:XXL

#8094 chore(main): release arize-phoenix 10.13.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8125 ci: fix docker build by removing missing split function
  .github/workflows/docker-build-release.yml
Labels: size:S

#8127 docs: add google adk
  README.md
Labels: size:XS

#8128 chore(main): release arize-phoenix 10.13.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8027 docs: Google adk docs
  docs/section-integrations/SUMMARY.md
  docs/section-integrations/llm-providers/google-gen-ai/google-adk-tracing.md
Labels: size:XS

#8110 fix: span prompt template export
  app/tests/member-access.spec.ts
  src/phoenix/server/api/helpers/dataset_helpers.py
  tests/unit/server/api/helpers/test_dataset_helpers.py
Labels: size:S

#8126 chore: clean up cost manifest
  src/phoenix/server/cost_tracking/model_cost_manifest.json
Labels: size:L

#8133 fix: chunk deletion of project sessions
  src/phoenix/server/api/mutations/project_mutations.py
  tests/unit/server/api/mutations/test_project_mutations.py
Labels: size:L

#8132 chore(main): release arize-phoenix 10.13.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8131 fix: Do not try to fetch admin fragment when creating API keys
  .github/workflows/playwright.yaml
  app/package.json
  app/playwright.config.ts
  app/src/pages/profile/ViewerAPIKeys.tsx
  app/src/pages/profile/__generated__/ViewerAPIKeysCreateUserAPIKeyMutation.graphql.ts
  app/tests/member-access.spec.ts
  app/tests/utils/testServer.mjs
Labels: size:L

#8140 fix(cost): display cost for playground runs over a dataset
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableMutation.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableSubscription.graphql.ts
Labels: size:M

#8141 fix: Ensure experiment and example dialogs have consistent behavior / styles
  app/src/pages/example/EditExampleButton.tsx
  app/src/pages/example/ExampleDetailsDialog.tsx
  app/src/pages/example/ExamplePage.tsx
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/playground/PlaygroundExamplePage.tsx
Labels: size:L

#8095 feat: read OTEL_EXPORTER_OTLP_ENDPOINT when PHOENIX_COLLECTOR_ENDPOINT is missing
  packages/phoenix-client/src/phoenix/client/constants.py
  packages/phoenix-client/src/phoenix/client/utils/config.py
  packages/phoenix-client/tests/phoenix/client/utils/test_config.py
  packages/phoenix-otel/src/phoenix/otel/settings.py
  packages/phoenix-otel/tests/test_settings.py
  src/phoenix/config.py
  src/phoenix/tests/test_config.py
Labels: size:M

#7945 chore(main): release arize-phoenix-otel 0.11.0
  .release-please-manifest.json
  packages/phoenix-otel/CHANGELOG.md
  packages/phoenix-otel/pyproject.toml
Labels: autorelease: pending, size:S

#8142 fix(cost): raise error on model name collision
  src/phoenix/server/api/mutations/model_mutations.py
  tests/unit/server/api/mutations/test_model_mutations.py
Labels: size:M

#8144 feat: playground move metrics to top
  app/src/components/table/CellTop.tsx
  app/src/components/table/index.tsx
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
Labels: size:M

#8107 refactor: migrate exp picker
  app/src/components/select/Select.tsx
  app/src/components/select/styles.ts
  app/src/pages/experiment/ExperimentMultiSelector.tsx
Labels: size:L

#7953 chore(main): release arize-phoenix-client 1.11.0
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#8161 chore: make storybook stable
  app/stories/ChatUI.stories.tsx
  app/stories/TimeRangeForm.stories.tsx
  app/stories/TimeRangeSelector.stories.tsx
Labels: size:S

#8148 chore: Add recommended vscode extensions / settings
  .gitignore
  .vscode/extensions.json
  DEVELOPMENT.md
Labels: size:M

#8166 chore: ignore graphql schema from formatting
  .prettierignore
Labels: size:XS

#8162 fix: De-duplicate dialog code in model delete dialog
  app/src/pages/settings/DeleteModelButton.tsx
Labels: size:S

#8167 fix(cost): validate regex before creating or updating generative model
  app/schema.graphql
  src/phoenix/server/api/mutations/model_mutations.py
  src/phoenix/server/api/queries.py
  tests/unit/server/api/mutations/test_model_mutations.py
Labels: size:M

#8169 feat(cost): add last used at column to models table
  app/schema.graphql
  app/src/pages/settings/ModelsTable.tsx
  app/src/pages/settings/__generated__/ModelsTableModelsQuery.graphql.ts
  app/src/pages/settings/__generated__/ModelsTable_generativeModels.graphql.ts
  app/src/pages/settings/__generated__/settingsModelsLoaderQuery.graphql.ts
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/last_used_times_by_generative_model_id.py
  src/phoenix/server/api/types/GenerativeModel.py
  src/phoenix/server/app.py
Labels: size:M

#8151 feat(cost): move actions into the headers in playground
  app/src/GlobalStyles.tsx
  app/src/components/button/IconButton.tsx
  app/src/components/button/index.tsx
  app/src/components/table/CellTop.tsx
  app/src/components/table/styles.ts
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
  app/src/pages/playground/PlaygroundErrorWrap.tsx
  app/src/pages/playground/PlaygroundToolCall.tsx
  app/stories/IconButton.stories.tsx
Labels: size:XL

#8170 fix: make welcome email just send you to the instance
  src/phoenix/server/email/sender.py
  tests/integration/auth/test_auth.py
Labels: size:XS

#8171 feat(cost): add build-in vs custom indicator
  app/src/pages/settings/CloneModelButton.tsx
  app/src/pages/settings/DeleteModelButton.tsx
  app/src/pages/settings/EditModelButton.tsx
  app/src/pages/settings/ModelsTable.tsx
Labels: size:M

#8174 chore: re-label urls to say localhost so that it mitigates confusion
  src/phoenix/server/main.py
Labels: size:S

#8138 chore(main): release arize-phoenix 10.14.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8179 feat(cost): sort sessions table by cost
  app/schema.graphql
  app/src/pages/project/__generated__/SessionsTableQuery.graphql.ts
  src/phoenix/server/api/input_types/ProjectSessionSort.py
  src/phoenix/server/api/types/Project.py
Labels: size:S

#8185 fix(cost): fix sort spans by cost
  src/phoenix/server/api/input_types/SpanSort.py
  src/phoenix/server/api/types/Project.py
Labels: size:XS

#8146 feat: ExperimentRun and Experiment cost resolvers
  app/schema.graphql
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/span_cost_summary_by_experiment.py
  src/phoenix/server/api/dataloaders/span_cost_summary_by_experiment_run.py
  src/phoenix/server/api/types/Experiment.py
  src/phoenix/server/api/types/ExperimentRun.py
  src/phoenix/server/app.py
Labels: size:L

#8186 chore: Update docker-build-experimental.yml
  .github/workflows/docker-build-experimental.yml
Labels: size:XS

#8176 feat(cost): Dynamic cost definitions in model form
  .github/workflows/docker-build-experimental.yml
  app/schema.graphql
  app/src/components/field/NumberField.tsx
  app/src/components/trace/TokenCosts.tsx
  app/src/pages/settings/CloneModelButton.tsx
  app/src/pages/settings/EditModelButton.tsx
  app/src/pages/settings/ModelForm.tsx
  app/src/pages/settings/ModelTokenCostControlTable.tsx
  app/src/pages/settings/ModelTokenTypeComboBox.tsx
  app/src/pages/settings/ModelsTable.tsx
  app/src/pages/settings/NewModelButton.tsx
  app/src/pages/settings/__generated__/CloneModelButtonMutation.graphql.ts
  app/src/pages/settings/__generated__/CloneModelButtonQuery.graphql.ts
  app/src/pages/settings/__generated__/EditModelButtonMutation.graphql.ts
  app/src/pages/settings/__generated__/EditModelButtonQuery.graphql.ts
  app/src/pages/settings/__generated__/ModelsTableModelsQuery.graphql.ts
  app/src/pages/settings/__generated__/ModelsTable_generativeModel.graphql.ts
  app/src/pages/settings/__generated__/ModelsTable_generativeModels.graphql.ts
  app/src/pages/settings/__generated__/NewModelButtonCreateModelMutation.graphql.ts
  app/src/pages/settings/__generated__/settingsModelsLoaderQuery.graphql.ts
  app/stories/ModelForm.stories.tsx
  app/stories/NumberField.stories.tsx
  src/phoenix/server/api/mutations/model_mutations.py
  src/phoenix/server/api/types/GenerativeModel.py
  src/phoenix/server/api/types/TokenCost.py
  src/phoenix/server/api/types/TokenPrice.py
Labels: size:XXL

#8202 ci(cost): fix model mutations tests
  tests/unit/server/api/mutations/test_model_mutations.py
Labels: size:L

#8210 fix: Fix audio and image message roles for OpenAI
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
Labels: size:XS

#8214 ci: restrict chromatic
  .github/workflows/chromatic.yml
Labels: size:XS

#8203 feat: mcp add span annotation
  js/packages/phoenix-client/src/spans/getSpanAnnotations.ts
  js/packages/phoenix-client/src/spans/index.ts
  js/packages/phoenix-client/test/spans/getSpanAnnotations.test.ts
  js/packages/phoenix-mcp/README.md
  js/packages/phoenix-mcp/src/index.ts
  js/packages/phoenix-mcp/src/spanTools.ts
Labels: size:XL

#8217 feat(cost): plumb through cost and tokens
  app/src/pages/experiments/ExperimentsTable.tsx
  app/src/pages/experiments/__generated__/ExperimentsTableFragment.graphql.ts
  app/src/pages/experiments/__generated__/ExperimentsTableQuery.graphql.ts
  app/src/pages/experiments/__generated__/experimentsLoaderQuery.graphql.ts
Labels: size:L

#8221 fix: Use correct join conditions for experiment cost resolvers
  src/phoenix/server/api/dataloaders/span_cost_summary_by_experiment.py
  src/phoenix/server/api/dataloaders/span_cost_summary_by_experiment_run.py
  src/phoenix/server/api/types/Experiment.py
  src/phoenix/server/api/types/ExperimentRun.py
Labels: size:S

#8222 feat(cost): add tooltip, add it to icon buttons
  app/src/GlobalStyles.tsx
  app/src/components/tooltip/Tooltip.tsx
  app/src/components/tooltip/TooltipArrow.tsx
  app/src/components/tooltip/index.tsx
  app/src/components/tooltip/styles.ts
  app/src/components/tooltip/types.tsx
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/experiments/ExperimentsTable.tsx
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
  app/src/pages/settings/ModelsTable.tsx
  app/stories/Tooltip.stories.tsx
Labels: size:XL

#8225 fix(costs): Bump minimum displayed costs to $0.01
  app/src/utils/numberFormatUtils.ts
Labels: size:XS

#8227 fix(cost): order custom models first
  src/phoenix/server/api/queries.py
Labels: size:XS

#8211 chore(main): release arize-phoenix 10.15.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8239 refactor(cost): use BigInteger for primary keys
  src/phoenix/db/migrations/versions/a20694b15f82_cost.py
  src/phoenix/db/models.py
  tests/integration/db_migrations/test_up_and_down_migrations.py
Labels: size:S

#8234 feat(cost): compute cumulative token counts for spans and add to traces table
  app/schema.graphql
  app/src/components/trace/SpanCumulativeTokenCosts.tsx
  app/src/components/trace/SpanCumulativeTokenCostsDetails.tsx
  app/src/components/trace/__generated__/SpanCumulativeTokenCostsDetailsQuery.graphql.ts
  app/src/pages/project/TracesTable.tsx
  app/src/pages/project/__generated__/ProjectPageQueriesTracesQuery.graphql.ts
  app/src/pages/project/__generated__/TracesTableQuery.graphql.ts
  app/src/pages/project/__generated__/TracesTable_spans.graphql.ts
  src/phoenix/server/api/types/Span.py
Labels: size:XL

#8244 feat(costs): Validate user-provided regular expressions against API
  app/src/components/RegexField.tsx
  app/src/components/__generated__/RegexFieldQuery.graphql.ts
  app/src/components/field/FieldDangerIcon.tsx
  app/src/components/field/FieldSuccessIcon.tsx
  app/src/components/field/styles.ts
  app/src/pages/settings/ModelForm.tsx
  app/stories/TextField.stories.tsx
Labels: size:L

#8256 feat(costs): Implement rich token count and cost breakdowns
  app/src/components/RichTokenCostBreakdown.tsx
  app/src/components/chart/SegmentChart.tsx
  app/src/components/chart/colors.tsx
  app/src/pages/project/ProjectPageHeader.tsx
  app/src/utils/numberFormatUtils.ts
Labels: size:L

#8269 chore: "feat(otel): support tracer provider arguments"
  packages/phoenix-otel/pyproject.toml
  packages/phoenix-otel/src/phoenix/otel/otel.py
  packages/phoenix-otel/tests/test_otel.py
Labels: size:L

#8265 fix(cost): revise cost model matching logic so a model with missing provider value matches any provider including None
  src/phoenix/datetime_utils.py
  src/phoenix/db/facilitator.py
  src/phoenix/db/migrations/versions/a20694b15f82_cost.py
  src/phoenix/db/models.py
  src/phoenix/server/api/mutations/chat_mutations.py
  src/phoenix/server/api/mutations/model_mutations.py
  src/phoenix/server/api/subscriptions.py
  src/phoenix/server/api/types/GenerativeModel.py
  src/phoenix/server/cost_tracking/cost_model_lookup.py
  src/phoenix/server/cost_tracking/model_cost_manifest.json
  src/phoenix/server/cost_tracking/regex_specificity.py
  src/phoenix/server/daemons/generative_model_store.py
  src/phoenix/server/daemons/span_cost_calculator.py
  tests/unit/server/api/mutations/test_model_mutations.py
  tests/unit/server/cost_tracking/test_cost_model_lookup.py
  tests/unit/test_datetime_utils.py
Labels: size:XL

#8277 chore(main): release arize-phoenix-otel 0.12.1
  .release-please-manifest.json
  packages/phoenix-otel/CHANGELOG.md
  packages/phoenix-otel/pyproject.toml
Labels: autorelease: pending, size:S

#8267 feat: Update playground tokens
  src/phoenix/server/api/helpers/playground_clients.py
  tests/unit/server/api/test_subscriptions.py
Labels: size:L

#8280 feat(cost): More clearly represent the relationship between model and provider during model configuration
  app/src/components/token/Token.tsx
  app/src/pages/settings/ModelForm.tsx
  app/src/pages/settings/ModelsTable.tsx
Labels: size:L

#8281 feat(cost): synchronize models and costs in database to manifest file via facilitator
  src/phoenix/db/facilitator.py
  tests/unit/db/test_facilitator.py
Labels: size:XL

#8279 refactor: simplify insert step for span costs
  src/phoenix/server/daemons/span_cost_calculator.py
Labels: size:S

#8283 fix(cost): database revisions
  src/phoenix/db/facilitator.py
  src/phoenix/db/migrations/versions/a20694b15f82_cost.py
  src/phoenix/db/models.py
  src/phoenix/server/api/mutations/model_mutations.py
  src/phoenix/server/api/types/GenerativeModel.py
  src/phoenix/server/cost_tracking/cost_model_lookup.py
  src/phoenix/server/cost_tracking/regex_specificity.py
  tests/integration/db_migrations/test_db_schema_a20694b15f82_cost.py
  tests/unit/db/test_facilitator.py
  tests/unit/server/api/mutations/test_model_mutations.py
  tests/unit/server/cost_tracking/test_cost_model_lookup.py
Labels: size:XL

#8286 fix(cost): clean manifest
  src/phoenix/server/cost_tracking/model_cost_manifest.json
Labels: size:L

#8287 fix(cost): disable sorting on trace cost
  app/src/pages/project/TracesTable.tsx
  src/phoenix/server/cost_tracking/model_cost_manifest.json
Labels: size:S

#8290 feat(cost)!: release cost
  src/phoenix/config.py
Labels: size:XS

#8292 docs: migration guide
  MIGRATION.md
Labels: size:XS

#8295 fix(cost): fallback to input/output base rate for unrecognized token types
  src/phoenix/server/cost_tracking/cost_details_calculator.py
  tests/unit/server/cost_tracking/test_cost_details_calculator.py
Labels: size:L

#8247 chore(main): release arize-phoenix 11.0.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8304 fix(cost): display cumulative cost on spans table when root spans only mode is selected
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/__generated__/ProjectPageQueriesSpansQuery.graphql.ts
  app/src/pages/project/__generated__/SpansTableSpansQuery.graphql.ts
  app/src/pages/project/__generated__/SpansTable_spans.graphql.ts
Labels: size:L

#8300 feat(helm): add support for imagePullSecrets to the helm chart
  helm/README.md
  helm/templates/phoenix/deployment.yaml
  helm/templates/phoenix/serviceaccount.yaml
  helm/values.yaml
Labels: size:S

#8312 docs(cost): add cost docs to nav
  docs/SUMMARY.md
Labels: size:XS

#8311 chore(main): release arize-phoenix 11.1.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8318 chore: add attribution to docs
  docs/section-cookbooks/datasets-and-experiments/text2sql.md
  tutorials/courses/evals/evals_that_work/evals_that_work.ipynb
  tutorials/experiments/txt2sql.ipynb
Labels: size:S

#8321 chore: clean nb
  tutorials/courses/evals/evals_that_work/evals_that_work.ipynb
  tutorials/experiments/txt2sql.ipynb
Labels: size:S

#8316 fix: add models for gemini 2.5
  src/phoenix/server/cost_tracking/model_cost_manifest.json
Labels: size:S

#8322 chore(main): release arize-phoenix 11.1.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8320 feat: Redirect from otel ids
  app/schema.graphql
  app/src/Routes.tsx
  app/src/pages/redirects/__generated__/sessionRedirectLoaderQuery.graphql.ts
  app/src/pages/redirects/__generated__/spanRedirectLoaderQuery.graphql.ts
  app/src/pages/redirects/__generated__/traceRedirectLoaderQuery.graphql.ts
  app/src/pages/redirects/sessionRedirectLoader.ts
  app/src/pages/redirects/spanRedirectLoader.ts
  app/src/pages/redirects/traceRedirectLoader.ts
  src/phoenix/server/api/queries.py
Labels: size:XL

#8327 chore(main): release arize-phoenix 11.2.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#8338 chore: add cc licenses
  tutorials/courses/evals/evals_that_work/evals_that_work.ipynb
  tutorials/experiments/txt2sql.ipynb
Labels: size:S
