Repository Arize-ai/phoenix, pull requests merged in 2025-03, with the labels that each got.

#6634 ci: use tox for notebook ci
  .github/workflows/python-CI.yml
  examples/llamaindex-workflows-research-agent/evaluate_traces.ipynb
  js/examples/notebooks/langchain/tracing_langchain_node_tutorial.ipynb
  js/examples/notebooks/phoenix_prompts_openai_tutorial.ipynb
  js/examples/notebooks/tracing_openai_node_tutorial.ipynb
  js/examples/notebooks/tracing_openai_sessions_tutorial.ipynb
  tox.ini
  tutorials/demos/demo_llama_index_rag.ipynb
  tutorials/experiments/langchain_email_extraction.ipynb
  tutorials/experiments/run_experiments_with_llama_index.ipynb
  tutorials/experiments/summarization.ipynb
  tutorials/experiments/txt2sql.ipynb
  tutorials/hosted_phoenix/hosted_phoenix_answer_and_context_relevancy_experiment.ipynb
  tutorials/hosted_phoenix/hosted_phoenix_llamaindex_tutorial.ipynb
  tutorials/hosted_phoenix/hosted_phoenix_openai_tutorial.ipynb
  tutorials/human_feedback/chatbot_with_human_feedback.ipynb
  tutorials/integrations/bedrock_tracing_tutorial.ipynb
  tutorials/integrations/tracing_and_evals_with_mongodb_and_llama_index.ipynb
  tutorials/mistral/evaluate_rag--mistral.ipynb
  tutorials/multi_modal/image_classification_tutorial.ipynb
  tutorials/multi_modal/tracing_with_images_tutorial.ipynb
  tutorials/prompts/prompt-optimization.ipynb
  tutorials/quickstarts/evals_quickstart.ipynb
  tutorials/quickstarts/evaluating_traces_quickstart.ipynb
  tutorials/quickstarts/tracing_quickstart_openai.ipynb
Labels: size:XXL

#6635 ci: remove hatch environments
  pyproject.toml
Labels: size:L

#6632 chore(main): release arize-phoenix 8.8.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6637 docs: update python developer guide to use tox
  CONTRIBUTING.md
  DEVELOPMENT.md
Labels: size:L

#6641 chore(js): update packages
  js/package.json
  js/packages/phoenix-client/package.json
  js/pnpm-lock.yaml
Labels: size:M

#6649 chore(ui): remove codemirror deps
  app/package.json
  app/pnpm-lock.yaml
  app/src/components/code/JSONBlock.tsx
  app/src/components/code/JSONEditor.tsx
Labels: size:S

#6655 chore(ui): upgrade resizable panels
  app/package.json
  app/pnpm-lock.yaml
  app/src/pages/trace/TraceDetails.tsx
Labels: size:XS

#6666 docs: update tool calling notebook
  tutorials/evals/evaluate_tool_calling.ipynb
Labels: size:L

#6665 feat(traces): make trace tree more readable on smaller sizes
  app/package.json
  app/pnpm-lock.yaml
  app/src/components/layout/Flex.tsx
  app/src/components/trace/LatencyText.tsx
  app/src/components/trace/TokenCount.tsx
  app/src/components/trace/TraceTree.tsx
  app/src/pages/trace/TraceDetails.tsx
Labels: size:L

#6664 feat: add environment variable for database storage capacity
  app/schema.graphql
  src/phoenix/config.py
  src/phoenix/server/api/queries.py
Labels: size:M

#6659 feat: add anthropic thinking config param for python client
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/anthropic/messages.py
  schemas/openapi.json
  src/phoenix/server/api/helpers/prompts/models.py
  tests/integration/prompts/test_prompts.py
  tests/unit/server/api/helpers/test_models.py
Labels: size:L

#6679 feat(components): ToggleButton
  app/src/components/button/Button.tsx
  app/src/components/button/index.tsx
  app/src/components/button/styles.tsx
  app/src/components/toggleButtonGroup/ToggleButton.tsx
  app/src/components/toggleButtonGroup/ToggleButtonGroup.tsx
  app/src/contexts/SizeContext.tsx
  app/src/contexts/index.tsx
  app/stories/Gallery.stories.tsx
  app/stories/ToggleButton.stories.tsx
Labels: size:L

#6686 fix: respect read only mode for prompt mutations
  src/phoenix/server/api/mutations/prompt_label_mutations.py
  src/phoenix/server/api/mutations/prompt_mutations.py
  src/phoenix/server/api/mutations/prompt_version_tag_mutations.py
Labels: size:S

#6688 feat: Add SimpleSpanProcessor warning
  packages/phoenix-otel/src/phoenix/otel/otel.py
Labels: size:S

#6670 feat: Add thinking budget invocation parameter
  app/schema.graphql
  app/src/pages/playground/__generated__/ModelSupportedParamsFetcherQuery.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableMutation.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableSubscription.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundOutputMutation.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  app/src/pages/playground/__generated__/fetchPlaygroundPromptSupportedInvocationParametersQuery.graphql.ts
  app/src/pages/playground/__generated__/spanPlaygroundPageLoaderQuery.graphql.ts
  src/phoenix/server/api/helpers/playground_clients.py
  src/phoenix/server/api/input_types/InvocationParameters.py
Labels: size:M

#6642 feat: experiment json downloads
  app/src/pages/experiments/DownloadExperimentActionMenu.tsx
  app/src/pages/experiments/ExperimentsTable.tsx
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  schemas/openapi.json
  src/phoenix/server/api/routers/v1/experiments.py
Labels: size:L

#6695 docs: Prompts Use Cases
  tutorials/prompts/chain_of_thought_prompting.ipynb
  tutorials/prompts/few_shot_prompting.ipynb
  tutorials/prompts/react_prompting.ipynb
Labels: size:XXL

#6697 fix: ensure fetch requests include base path prefix
  app/src/pages/dataset/DatasetPage.tsx
  app/src/pages/datasets/DatasetFromCSVForm.tsx
Labels: size:S

#6704 fix(traces): broken selection of spans in trace details"
  app/src/pages/project/TracesTable.tsx
Labels: size:XS

#6705 fix: broken url from session to trace
  app/src/pages/trace/SessionDetails.tsx
  app/src/pages/trace/SessionDetailsTraceList.tsx
  app/src/pages/trace/__generated__/SessionDetailsQuery.graphql.ts
Labels: size:S

#6639 chore(main): release arize-phoenix 8.9.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6708 fix: ensure type is correct on run_experiment
  src/phoenix/experiments/types.py
Labels: size:XS

#6681 feat: delete selected traces
  app/schema.graphql
  app/src/pages/project/SpanSelectionToolbar.tsx
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
  app/src/pages/project/__generated__/SpanSelectionToolbarDeleteTracesMutation.graphql.ts
  src/phoenix/server/api/mutations/__init__.py
  src/phoenix/server/api/mutations/trace_mutations.py
  tests/unit/server/api/mutations/test_trace_mutations.py
Labels: size:XL

#6680 docs: agent demos
  examples/code_gen_agent/.gitkeep
  examples/code_gen_agent/README.md
  examples/code_gen_agent/agent.py
  examples/code_gen_agent/app.py
  examples/code_gen_agent/requirements.txt
  examples/code_gen_agent/tools.py
  examples/computer_use_agent/Dockerfile
  examples/computer_use_agent/README.md
  examples/computer_use_agent/agent.py
  examples/computer_use_agent/app.py
  examples/computer_use_agent/image/.config/tint2/applications/firefox-custom.desktop
  examples/computer_use_agent/image/.config/tint2/applications/gedit.desktop
  examples/computer_use_agent/image/.config/tint2/applications/terminal.desktop
  examples/computer_use_agent/image/.config/tint2/tint2rc
  examples/computer_use_agent/image/.streamlit/config.toml
  examples/computer_use_agent/image/entrypoint.sh
  examples/computer_use_agent/image/http_server.py
  examples/computer_use_agent/image/index.html
  examples/computer_use_agent/image/mutter_startup.sh
  examples/computer_use_agent/image/novnc_startup.sh
  examples/computer_use_agent/image/start_all.sh
  examples/computer_use_agent/image/static_content/index.html
  examples/computer_use_agent/image/tint2_startup.sh
  examples/computer_use_agent/image/x11vnc_startup.sh
  examples/computer_use_agent/image/xvfb_startup.sh
  examples/computer_use_agent/instrumentor.py
  examples/computer_use_agent/requirements.txt
  examples/computer_use_agent/tools/__init__.py
  examples/computer_use_agent/tools/base.py
  examples/computer_use_agent/tools/bash.py
  examples/computer_use_agent/tools/collection.py
  examples/computer_use_agent/tools/computer.py
  examples/computer_use_agent/tools/edit.py
  examples/computer_use_agent/tools/run.py
  examples/computer_use_agent/utils.py
  examples/rag_agent/.gitkeep
  examples/rag_agent/README.md
  examples/rag_agent/agent.py
  examples/rag_agent/app.py
  examples/rag_agent/rag.py
  examples/rag_agent/requirements.txt
  examples/rag_agent/tools.py
Labels: size:XXL

#6720 fix: ignore top_p if extended thinking is enabled for playground
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:S

#6722 feat(admin): show percent used of DB
  app/src/pages/settings/DBUsagePieChart.tsx
  app/src/pages/settings/__generated__/DBUsagePieChart_data.graphql.ts
  app/src/pages/settings/__generated__/settingsPageLoaderQuery.graphql.ts
  app/src/utils/storageSizeFormatUtils.ts
  tox.ini
Labels: size:M

#6712 chore(main): release arize-phoenix 8.10.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6725 docs: agents updates
  examples/code_gen_agent/app.py
  examples/rag_agent/app.py
Labels: size:XS

#6726 feat: Specialized UI for thinking budget parameter
  app/src/pages/playground/AnthropicReasoningConfigField.tsx
  app/src/pages/playground/InvocationParametersFormFields.tsx
Labels: size:M

#6727 fix: typo in variable reference
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:XS

#6724 chore(main): release arize-phoenix 8.11.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6737 chore(ui): change delete to danger
  app/src/pages/project/SpanSelectionToolbar.tsx
Labels: size:XS

#6738 fix: apply constraints related to extended thinking on anthropic invocation parameters
  app/src/pages/playground/AnthropicReasoningConfigField.tsx
  app/src/pages/playground/fetchPlaygroundPrompt.ts
  app/src/pages/playground/playgroundUtils.ts
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:L

#6717 ci: ensure graphql mutations are decorated with permission classes
  .github/workflows/python-CI.yml
  scripts/ci/ensure_graphql_mutations_have_permission_classes.py
  tox.ini
Labels: size:L

#6675 chore(main): release arize-phoenix-client 1.1.0
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#6718 feat(ui): high contrast ui
  app/package.json
  app/pnpm-lock.yaml
  app/src/GlobalStyles.tsx
  app/src/components/ExternalLink.tsx
  app/src/components/Link.tsx
  app/src/components/button/styles.tsx
  app/src/components/code/JSONBlock.tsx
  app/src/components/code/JSONEditor.tsx
  app/src/components/code/PythonBlock.tsx
  app/src/components/code/TypeScriptBlock.tsx
  app/src/components/markdown/MarkdownModeRadioGroup.tsx
  app/src/components/nav/Navbar.tsx
  app/src/components/templateEditor/TemplateEditor.tsx
  app/src/components/toggleButtonGroup/ToggleButton.tsx
  app/src/components/trace/SpanKindIcon.tsx
  app/src/components/trace/TraceTree.tsx
  app/src/pages/embedding/ExportSelectionButton.tsx
  app/src/pages/experiment/ExperimentRunFilterConditionField.tsx
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/VariableEditor.tsx
  app/src/pages/project/SessionSearchField.tsx
  app/src/pages/project/SpanFilterConditionField.tsx
  app/src/pages/projects/ProjectActionMenu.tsx
  app/src/pages/projects/ProjectsPage.tsx
  app/src/pages/prompt/PromptCodeExportCard.tsx
  app/src/pages/prompts/PromptsPage.tsx
  app/src/pages/trace/SpanDetails.tsx
Labels: size:L

#6740 fix: add none as option for anthropic tool choice
  app/src/components/generative/ToolChoiceSelector.tsx
  app/src/schemas/toolChoiceSchemas.ts
  pyproject.toml
  requirements/canary/sdk/anthropic.txt
  requirements/ci.txt
  requirements/dev.txt
  requirements/packages/phoenix-client.txt
  requirements/type-check.txt
  requirements/unit-tests.txt
  src/phoenix/server/api/helpers/prompts/conversions/anthropic.py
Labels: size:M

#6741 chore: cleanup ui inconsistancies
  app/src/pages/experiment/ExperimentRunFilterConditionField.tsx
  app/src/pages/project/SessionSearchField.tsx
  app/src/pages/project/SpanFilterConditionField.tsx
Labels: size:XS

#6743 refactor(components): switch label for token
  app/.eslintrc.js
  app/src/components/experiment/SequenceNumberLabel.tsx
  app/src/components/experiment/SequenceNumberToken.tsx
  app/src/components/experiment/index.tsx
  app/src/components/form/DimensionPicker.tsx
  app/src/components/generative/ToolChoiceSelector.tsx
  app/src/components/trace/SpanKindLabel.tsx
  app/src/components/trace/SpanKindToken.tsx
  app/src/pages/embedding/EventDetails.tsx
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/experiment/ExperimentMultiSelector.tsx
  app/src/pages/experiments/ExperimentsTable.tsx
  app/src/pages/project/SpanSelectionToolbar.tsx
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
  app/src/pages/prompt/PromptVersionSummary.tsx
  app/src/pages/prompt/PromptVersionTagsList.tsx
  app/src/pages/trace/SpanDetails.tsx
Labels: size:L

#6744 fix: add annotations to experiment json download
  src/phoenix/db/models.py
  src/phoenix/server/api/routers/v1/experiments.py
  tests/unit/server/api/routers/v1/test_experiments.py
Labels: size:L

#6739 chore(main): release arize-phoenix 8.12.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6750 fix: be more careful about metadata structure
  app/src/pages/project/MetadataTableCell.tsx
  app/src/pages/project/MetadataTooltip.tsx
  app/src/utils/__tests__/jsonUtils.test.ts
  app/src/utils/__tests__/pythonUtils.test.ts
  app/src/utils/jsonUtils.ts
  app/src/utils/pythonUtils.ts
Labels: size:M

#6751 chore(main): release arize-phoenix 8.12.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6752 chore: change delete prompt tag to a modal
  app/package.json
  app/pnpm-lock.yaml
  app/src/components/button/styles.tsx
  app/src/components/overlay/Modal.tsx
  app/src/pages/projects/ProjectsPage.tsx
  app/src/pages/prompt/DeletePromptVersionTagButton.tsx
  app/stories/Button.stories.tsx
  app/stories/Modal.stories.tsx
Labels: size:L

#6756 feat(perf): make the spans table the default tab
  app/.eslintrc.js
  app/package.json
  app/src/components/counter/Counter.tsx
  app/src/components/counter/index.tsx
  app/src/components/experiment/SequenceNumberToken.tsx
  app/src/components/index.tsx
  app/src/components/table/TextCell.tsx
  app/src/components/trace/SpanKindToken.tsx
  app/src/pages/dataset/DatasetPage.tsx
  app/src/pages/embedding/EmbeddingPage.tsx
  app/src/pages/embedding/EventDetails.tsx
  app/src/pages/playground/PlaygroundTools.tsx
  app/src/pages/project/ProjectIndexPage.tsx
  app/src/pages/project/ProjectPage.tsx
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/__generated__/ProjectPageQueriesSpansQuery.graphql.ts
  app/src/pages/project/__generated__/SpansTableSpansQuery.graphql.ts
  app/src/pages/project/__generated__/SpansTable_spans.graphql.ts
  app/src/pages/prompt/PromptLayout.tsx
  app/src/pages/trace/SpanDetails.tsx
  app/stories/Counter.stories.tsx
Labels: size:L

#6765 fix(ui): annotation button color
  app/src/components/trace/EditSpanAnnotationsDialog.tsx
Labels: size:M

#6766 chore: show provider icon in span details
  app/src/openInference/tracing/types.ts
  app/src/pages/trace/SpanDetails.tsx
Labels: size:S

#6767 fix: cleanup type ignores
  src/phoenix/db/migrations/versions/10460e46d750_datasets.py
  src/phoenix/db/migrations/versions/3be8647b87d8_add_token_columns_to_spans_table.py
  src/phoenix/db/migrations/versions/bc8fea3c2bc8_add_prompt_tables.py
  src/phoenix/db/migrations/versions/cf03bd6bae1d_init.py
  src/phoenix/db/models.py
Labels: size:S

#6768 fix: codegen for js
  js/packages/phoenix-client/src/__generated__/api/v1.ts
Labels: size:XS

#6770 fix: Tighten padding and height tolerances for Slider component
  app/src/components/slider/Slider.tsx
Labels: size:S

#6771 feat(components): Add react-aria Tabs components
  app/.eslintrc.js
  app/src/components/counter/Counter.tsx
  app/src/components/index.tsx
  app/src/components/project/PythonProjectGuide.tsx
  app/src/components/tabs/Tabs.tsx
  app/src/components/tabs/index.tsx
  app/src/pages/apis/APIsPage.tsx
  app/src/pages/dataset/DatasetCodeDropdown.tsx
  app/src/pages/dataset/DatasetPage.tsx
  app/src/pages/embedding/EmbeddingPage.tsx
  app/src/pages/embedding/PointSelectionPanelContent.tsx
  app/src/pages/model/ModelPage.tsx
  app/src/pages/project/ProjectPage.tsx
  app/src/pages/prompt/PromptLayout.tsx
  app/src/pages/settings/APIKeysCard.tsx
  app/src/pages/trace/SpanDetails.tsx
  app/stories/Tabs.stories.tsx
Labels: size:XL

#6773 feat(trace): move info out of side
  app/src/GlobalStyles.tsx
  app/src/components/button/LinkButton.tsx
  app/src/components/button/styles.tsx
  app/src/components/icon/Icon.tsx
  app/src/components/trace/LatencyText.tsx
  app/src/components/trace/SpanKindToken.tsx
  app/src/components/trace/SpanStatusCodeIcon.tsx
  app/src/components/trace/TraceTree.tsx
  app/src/pages/SpanHeader.tsx
  app/src/pages/__generated__/SpanHeader_span.graphql.ts
  app/src/pages/trace/SpanActionMenu.tsx
  app/src/pages/trace/SpanAside.tsx
  app/src/pages/trace/SpanCodeDropdown.tsx
  app/src/pages/trace/SpanDetails.tsx
  app/src/pages/trace/__generated__/SpanDetailsQuery.graphql.ts
Labels: size:XL

#6775 fix(playground): ai message size
  app/src/pages/playground/MessageContentRadioGroup.tsx
Labels: size:XS

#6757 chore(main): release arize-phoenix 8.13.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6776 fix(ui): heading size
  app/src/components/types/style.ts
  app/src/pages/SpanHeader.tsx
  app/src/pages/trace/TraceDetails.tsx
  app/src/pages/trace/TraceHeaderRootSpanAnnotations.tsx
  app/src/pages/trace/__generated__/TraceHeaderRootSpanAnnotationsQuery.graphql.ts
  app/stories/Text.stories.tsx
Labels: size:L

#6777 chore(main): release arize-phoenix 8.13.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6503 fix: Migrate from Bedrock invoke_model API to converse API
  packages/phoenix-evals/src/phoenix/evals/models/bedrock.py
  packages/phoenix-evals/src/phoenix/evals/models/mistralai.py
  packages/phoenix-evals/tests/phoenix/evals/models/test_bedrock.py
Labels: size:L

#6781 fix(onboarding): add space between link and text in new project guide
  app/src/components/project/PythonProjectGuide.tsx
Labels: size:XS

#6778 docs: fix typo in documentation
  docs/tracing/features-tracing/how-to-annotate-traces.md
Labels: size:XS

#6788 fix: make azure api key optional for playground
  pyproject.toml
  requirements/ci.txt
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:M

#6782 chore(main): release arize-phoenix 8.13.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6792 feat: Split settings page into tabs
  app/global-setup.ts
  app/src/Routes.tsx
  app/src/components/project/PythonProjectGuide.tsx
  app/src/components/project/TypeScriptProjectGuide.tsx
  app/src/pages/Layout.tsx
  app/src/pages/dataset/RunExperimentButton.tsx
  app/src/pages/playground/PlaygroundCredentialsDropdown.tsx
  app/src/pages/settings/SettingsAIProvidersPage.tsx
  app/src/pages/settings/SettingsGeneralPage.tsx
  app/src/pages/settings/SettingsPage.tsx
  app/src/pages/settings/__generated__/settingsAIProvidersPageLoaderQuery.graphql.ts
  app/src/pages/settings/__generated__/settingsGeneralPageLoaderQuery.graphql.ts
  app/src/pages/settings/index.tsx
  app/src/pages/settings/settingsAIProvidersPageLoader.ts
  app/src/pages/settings/settingsGeneralPageLoader.ts
  app/src/pages/settings/settingsPageLoader.ts
  app/tests/admin-access.ts
  app/tests/user-management.spec.ts
Labels: size:XL

#6796 feat: Add resize capability to Span, Trace, and Session table
  app/src/pages/project/MetadataTableCell.tsx
  app/src/pages/project/SessionsTable.tsx
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
  app/src/store/tracingStore.tsx
Labels: size:XL

#6805 docs: prompt notebooks
  docs/Makefile
  docs/prompt-engineering/use-cases-prompts/chain-of-thought-prompting.md
  docs/prompt-engineering/use-cases-prompts/few-shot-prompting.md
  docs/prompt-engineering/use-cases-prompts/prompt-optimization.md
  docs/prompt-engineering/use-cases-prompts/react-prompting.md
  tutorials/prompts/chain_of_thought_prompting.ipynb
  tutorials/prompts/few_shot_prompting.ipynb
  tutorials/prompts/react_prompting.ipynb
Labels: size:XXL

#6810 docs: add agents sdk to readme
  README.md
Labels: size:XS

#6811 docs: add beeai to readme
  README.md
Labels: size:S

#6814 fix(langgraph): don't aggregate status
  app/src/pages/project/TracesTable.tsx
  app/src/pages/project/__generated__/ProjectPageQueriesTracesQuery.graphql.ts
  app/src/pages/project/__generated__/TracesTableQuery.graphql.ts
  app/src/pages/project/__generated__/TracesTable_spans.graphql.ts
  app/src/pages/trace/TraceDetails.tsx
  app/src/pages/trace/__generated__/TraceDetailsQuery.graphql.ts
Labels: size:L

#6797 ci: automatically update phoenix version in kustomize
  .github/workflows/docker-build-release.yml
Labels: size:S

#6800 chore(main): release arize-phoenix 8.14.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6819 fix: remove shadow on button group
  app/src/components/toggleButtonGroup/ToggleButton.tsx
Labels: size:XS

#6831 fix: styles for markdown
  app/src/GlobalStyles.tsx
  app/src/components/markdown/MarkdownBlock.tsx
  app/src/components/markdown/styles.ts
  app/src/components/trace/SpanKindToken.tsx
  app/src/components/utility/PrettyText.tsx
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/PlaygroundRunTraceDialog.tsx
  app/src/pages/trace/SpanDetails.tsx
Labels: size:L

#6821 chore(main): release arize-phoenix 8.14.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6833 ci: fix type check for new `File` typed dict in openai 1.66
  packages/phoenix-client/src/phoenix/client/helpers/sdk/openai/chat.py
  requirements/canary/sdk/openai.txt
Labels: size:XS

#6835 fix(ui): cleanup query block padding
  app/src/pages/trace/SpanDetails.tsx
Labels: size:XS

#6844 feat: add integrations
  app/src/components/code/JSONBlock.tsx
  app/src/components/code/PythonBlock.tsx
  app/src/components/code/TypeScriptBlock.tsx
  app/src/components/code/styles.tsx
  app/src/components/project/IntegrationIcons.tsx
  app/src/components/project/Integrations.tsx
Labels: size:L

#6841 fix: update clear data button text
  app/src/pages/projects/ProjectActionMenu.tsx
Labels: size:XS

#6846 fix: temporarily stop showing table names in db stats for SQLite
  src/phoenix/server/api/queries.py
  tests/unit/server/api/test_queries.py
Labels: size:S

#6836 chore(main): release arize-phoenix 8.15.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6806 chore: added cleanlab integration example
  tutorials/integrations/evaluating_traces_cleanlabTLM.ipynb
Labels: size:L

#6849 ci: update kustomize update flow
  .github/workflows/docker-build-release.yml
Labels: size:XS

#6850 fix(annotation-configs): make read-only
  src/phoenix/server/api/mutations/annotation_config_mutations.py
Labels: size:S

#6754 feat: add delete experiment to action menu
  app/src/components/experiment/ExperimentActionMenu.tsx
  app/src/components/experiment/__generated__/ExperimentActionMenuDeleteExperimentMutation.graphql.ts
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/experiments/ExperimentsTable.tsx
Labels: size:L

#6852 chore(main): release arize-phoenix 8.16.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6851 feat: environment variable for inserting admin users at startup
  pyproject.toml
  src/phoenix/config.py
  src/phoenix/db/facilitator.py
  tests/unit/db/test_facilitator.py
  tests/unit/test_config.py
Labels: size:L

#6858 feat(perf): smaller page sizes
  app/schema.graphql
  app/src/pages/project/SessionsTable.tsx
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
  app/src/pages/project/__generated__/ProjectPageQueriesSessionsQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectPageQueriesSpansQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectPageQueriesTracesQuery.graphql.ts
  app/src/pages/project/__generated__/SessionsTableQuery.graphql.ts
  app/src/pages/project/__generated__/SessionsTable_sessions.graphql.ts
  app/src/pages/project/__generated__/SpansTableSpansQuery.graphql.ts
  app/src/pages/project/__generated__/SpansTable_spans.graphql.ts
  app/src/pages/project/__generated__/TracesTableQuery.graphql.ts
  app/src/pages/project/__generated__/TracesTable_spans.graphql.ts
  app/src/pages/project/constants.ts
  src/phoenix/server/api/types/Project.py
Labels: size:L

#6867 fix: Remove sticky project nav history
  app/src/pages/project/ProjectIndexPage.tsx
  app/src/pages/projects/ProjectsPage.tsx
Labels: size:XS

#6855 chore(main): release arize-phoenix 8.17.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6882 fix(UI): close time selector on duplicate selection
  app/src/components/datetime/TimeRangeSelector.tsx
Labels: size:XS

#6847 fix: Improve performance on projects page
  app/src/components/Loading.tsx
  app/src/pages/projects/ProjectsPage.tsx
  app/src/pages/projects/__generated__/ProjectsPageProjectMetricsQuery.graphql.ts
  app/src/pages/projects/__generated__/ProjectsPageProjectsFragment.graphql.ts
  app/src/pages/projects/__generated__/ProjectsPageProjectsQuery.graphql.ts
  app/src/pages/projects/__generated__/ProjectsPageQuery.graphql.ts
Labels: size:XL

#6886 fix(annotations): show metadata
  app/src/pages/trace/SpanFeedback.tsx
  app/src/pages/trace/__generated__/SpanDetailsQuery.graphql.ts
  app/src/pages/trace/__generated__/SpanFeedback_annotations.graphql.ts
Labels: size:M

#6887 fix(feedback): show full metadata
  app/src/pages/trace/SpanFeedback.tsx
  scripts/testing/send_spans.py
Labels: size:S

#6884 chore(main): release arize-phoenix 8.17.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6834 feat: Add timeout option to helper query functions
  src/phoenix/trace/dsl/helpers.py
Labels: size:XS

#6519 chore(main): release arize-phoenix-otel 0.9.0
  .release-please-manifest.json
  packages/phoenix-otel/CHANGELOG.md
  packages/phoenix-otel/pyproject.toml
Labels: autorelease: pending, size:S

#6891 feat(ui): use skeleton loader
  app/src/GlobalStyles.tsx
  app/src/components/index.tsx
  app/src/components/loading/Loading.tsx
  app/src/components/loading/Skeleton.tsx
  app/src/components/loading/index.tsx
  app/src/components/pointcloud/PointCloudDisplaySettings.tsx
  app/src/components/types/sizing.ts
  app/src/pages/project/ProjectTracesPage.tsx
  app/src/pages/projects/ProjectsPage.tsx
  app/src/stories/Skeleton.stories.tsx
  app/stories/Skeleton.stories.tsx
Labels: size:L

#6892 chore(main): release arize-phoenix 8.18.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6894 refactor: move projects page to use a loader
  app/src/Routes.tsx
  app/src/pages/projects/ProjectsPage.tsx
  app/src/pages/projects/__generated__/projectsPageLoaderQuery.graphql.ts
  app/src/pages/projects/index.tsx
  app/src/pages/projects/projectsPageLoader.ts
Labels: size:L

#6899 chore: move skeleton into the main directory
  app/stories/Skeleton.stories.tsx
Labels: size:XS

#6896 feat: Upgrade react-router, vite, vitest
  app/package.json
  app/pnpm-lock.yaml
  app/src/Routes.tsx
  app/src/components/Link.tsx
  app/src/components/auth/CreateAPIKeyDialog.tsx
  app/src/components/button/LinkButton.tsx
  app/src/components/nav/Navbar.tsx
  app/src/pages/AuthenticatedRoot.tsx
  app/src/pages/ModelRoot.tsx
  app/src/pages/auth/LoginPage.tsx
  app/src/pages/auth/ResetPasswordPage.tsx
  app/src/pages/auth/ResetPasswordWithTokenPage.tsx
  app/src/pages/authenticatedRootLoader.ts
  app/src/pages/dataset/DatasetPage.tsx
  app/src/pages/dataset/datasetLoader.ts
  app/src/pages/dimension/DimensionPage.tsx
  app/src/pages/examples/ExamplesPage.tsx
  app/src/pages/examples/examplesLoader.tsx
  app/src/pages/experiment/ExperimentComparePage.tsx
  app/src/pages/experiment/ExperimentRunFilterConditionField.tsx
  app/src/pages/experiment/experimentCompareLoader.ts
  app/src/pages/experiments/ExperimentsPage.tsx
  app/src/pages/experiments/experimentsLoader.tsx
  app/src/pages/home/homeLoader.ts
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
  app/src/pages/playground/PlaygroundDatasetPicker.tsx
  app/src/pages/playground/PlaygroundExamplePage.tsx
  app/src/pages/playground/SpanPlaygroundPage.tsx
  app/src/pages/project/projectLoader.ts
  app/src/pages/prompt/PromptConfigPage.tsx
  app/src/pages/prompt/PromptPlaygroundPage.tsx
  app/src/pages/prompt/PromptVersionDetailsPage.tsx
  app/src/pages/prompt/PromptVersionsList.tsx
  app/src/pages/prompt/promptLoader.tsx
  app/src/pages/prompt/promptPlaygroundLoader.tsx
  app/src/pages/prompt/promptVersionLoader.tsx
  app/src/pages/prompt/promptVersionsLoader.tsx
  app/src/pages/prompts/PromptsPage.tsx
  app/src/pages/prompts/PromptsTable.tsx
  app/src/pages/prompts/promptsLoader.ts
  app/src/pages/settings/SettingsAIProvidersPage.tsx
  app/src/pages/settings/SettingsGeneralPage.tsx
  app/src/pages/trace/SessionPage.tsx
  app/src/pages/trace/SpanDetails.tsx
  app/src/pages/trace/TraceDetails.tsx
  app/src/pages/trace/sessionLoader.ts
  app/tsconfig.json
  app/vite.config.mts
Labels: size:L

#6901 fix: Rename missing import
  app/src/pages/projects/ProjectsPage.tsx
Labels: size:XS

#6902 chore: allow migrations to be skipped
  src/phoenix/config.py
  src/phoenix/db/engines.py
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  src/phoenix/settings.py
  tox.ini
Labels: size:S

#6856 feat(annotations): Annotation Config UI
  app/src/Routes.tsx
  app/src/components/annotation/AnnotationLabel.tsx
  app/src/components/radio/RadioGroup.tsx
  app/src/pages/settings/AnnotationConfigDialog.tsx
  app/src/pages/settings/AnnotationConfigSelectionToolbar.tsx
  app/src/pages/settings/AnnotationConfigTable.tsx
  app/src/pages/settings/SettingsAnnotationsPage.tsx
  app/src/pages/settings/SettingsPage.tsx
  app/src/pages/settings/__generated__/AnnotationConfigTableFragment.graphql.ts
  app/src/pages/settings/__generated__/SettingsAnnotationsPageCreateCategoricalAnnotationConfigMutation.graphql.ts
  app/src/pages/settings/__generated__/SettingsAnnotationsPageCreateContinuousAnnotationConfigMutation.graphql.ts
  app/src/pages/settings/__generated__/SettingsAnnotationsPageCreateFreeformAnnotationConfigMutation.graphql.ts
  app/src/pages/settings/__generated__/SettingsAnnotationsPageDeleteAnnotationConfigMutation.graphql.ts
  app/src/pages/settings/__generated__/SettingsAnnotationsPageFragment.graphql.ts
  app/src/pages/settings/__generated__/SettingsAnnotationsPageUpdateCategoricalAnnotationConfigMutation.graphql.ts
  app/src/pages/settings/__generated__/SettingsAnnotationsPageUpdateContinuousAnnotationConfigMutation.graphql.ts
  app/src/pages/settings/__generated__/SettingsAnnotationsPageUpdateFreeformAnnotationConfigMutation.graphql.ts
  app/src/pages/settings/__generated__/settingsAnnotationsPageLoaderQuery.graphql.ts
  app/src/pages/settings/settingsAnnotationsPageLoader.ts
  app/src/pages/settings/types.ts
Labels: size:XXL

#6889 feat: mutation to remove project annotation config association
  app/schema.graphql
  src/phoenix/server/api/mutations/annotation_config_mutations.py
  src/phoenix/server/api/types/AnnotationConfig.py
Labels: size:M

#6518 chore(main): release arize-phoenix-evals 0.20.4
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#6857 feat(tracing): add a config tab
  app/src/Routes.tsx
  app/src/contexts/ProjectContext.tsx
  app/src/contexts/index.tsx
  app/src/pages/project/ProjectConfigPage.tsx
  app/src/pages/project/ProjectIndexPage.tsx
  app/src/pages/project/ProjectPage.tsx
  app/src/pages/project/ProjectPageQueries.tsx
  app/src/pages/project/ProjectRoot.tsx
  app/src/pages/project/ProjectSpansPage.tsx
  app/src/pages/project/__generated__/ProjectConfigPageProjectConfigCardQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectConfigPageRefetchQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectConfigPage_project.graphql.ts
  app/src/pages/project/__generated__/ProjectConfigPage_projectConfigCard.graphql.ts
  app/src/pages/project/__generated__/ProjectPageQueriesProjectConfigQuery.graphql.ts
  app/src/pages/projects/ProjectsAutoRefreshToggle.tsx
  app/src/pages/projects/ProjectsPage.tsx
  app/src/pages/projects/__generated__/projectsLoaderQuery.graphql.ts
  app/src/pages/projects/index.tsx
  app/src/pages/projects/projectsPageLoader.ts
  app/src/pages/settings/SettingsPage.tsx
  app/src/store/projectStore.ts
Labels: size:XXL

#6904 fix: use correlated subquery for orphan spans
  app/schema.graphql
  scripts/perf/postgres/paste_queries_here.sql
  scripts/perf/postgres/postgres_explain_analyze.py
  src/phoenix/server/api/types/Project.py
  src/phoenix/trace/dsl/query.py
  tests/__generated__/graphql/__init__.py
  tests/unit/_helpers.py
  tests/unit/server/api/types/test_Project.py
Labels: size:XL

#6900 chore(main): release arize-phoenix 8.19.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6909 fix: Prevent toggle button text from wrapping
  app/src/components/toggleButtonGroup/ToggleButton.tsx
Labels: size:XS

#6703 feat!: db table for trace data retention policies
  requirements/unit-tests.txt
  src/phoenix/db/constants.py
  src/phoenix/db/facilitator.py
  src/phoenix/db/migrations/versions/bb8139330879_create_project_trace_retention_policies_table.py
  src/phoenix/db/models.py
  src/phoenix/db/types/trace_retention.py
  src/phoenix/server/app.py
  src/phoenix/server/retention.py
  src/phoenix/utilities/__init__.py
  tests/integration/db_migrations/__init__.py
  tests/integration/db_migrations/test_up_and_down_migrations.py
  tests/unit/db/test_facilitator.py
  tests/unit/db/types/test_trace_retention.py
  tests/unit/utilities/test_datetime.py
Labels: size:XXL

#6790 refactor: migrate alert component
  app/.cursor/rules/organization.mdc
  app/.cursor/rules/stories.mdc
  app/.cursor/rules/styling.mdc
  app/.eslintrc.js
  app/src/components/alert/Alert.tsx
  app/src/components/alert/getSeverityIcon.tsx
  app/src/components/alert/index.tsx
  app/src/components/auth/OneTimeAPIKeyDialog.tsx
  app/src/components/dataset/NewDatasetButton.tsx
  app/src/components/index.tsx
  app/src/components/pointcloud/PointCloudDisplaySettings.tsx
  app/src/components/trace/EditSpanAnnotationsDialog.tsx
  app/src/components/types/index.ts
  app/src/components/types/severity.ts
  app/src/pages/apis/APIsPage.tsx
  app/src/pages/auth/ForgotPasswordForm.tsx
  app/src/pages/auth/LoginForm.tsx
  app/src/pages/auth/LoginPage.tsx
  app/src/pages/auth/ResetPasswordWithTokenForm.tsx
  app/src/pages/dataset/AddDatasetExampleDialog.tsx
  app/src/pages/embedding/ExportSelectionButton.tsx
  app/src/pages/example/EditExampleDialog.tsx
  app/src/pages/experiment/ExperimentComparePage.tsx
  app/src/pages/playground/SpanPlaygroundPage.tsx
  app/src/pages/prompt/NewPromptVersionTagDialog.tsx
  app/src/pages/trace/SpanDetails.tsx
  app/src/pages/trace/SpanToDatasetExampleDialog.tsx
  app/src/stories/Skeleton.stories.tsx
  app/stories/Alert.stories.tsx
Labels: size:XL

#6922 fix(perf): add a toggle to treat orphans as root
  app/src/pages/project/ProjectFilterConfigButton.tsx
  app/src/pages/project/ProjectPage.tsx
  app/src/pages/project/ProjectPageQueries.tsx
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/__generated__/ProjectPageQueriesSpansQuery.graphql.ts
  app/src/pages/project/__generated__/SpansTableSpansQuery.graphql.ts
  app/src/pages/project/__generated__/SpansTable_spans.graphql.ts
  app/src/store/projectStore.ts
Labels: size:L

#6911 chore(main): release arize-phoenix 8.19.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6784 docs: evaluating agents nb
  tutorials/evals/evaluate_agent.ipynb
Labels: size:XXL

#6928 refactor(ui): change the span aside to be a resizable panel
  app/src/pages/trace/SpanAside.tsx
  app/src/pages/trace/SpanDetails.tsx
  app/src/store/preferencesStore.tsx
Labels: size:L

#6936 fix(perf): disable streaming when dialog is open
  app/src/pages/project/StreamToggle.tsx
Labels: size:S

#6941 ci: fix strawberry and fastapi
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  pyproject.toml
  requirements/build-graphql-schema.txt
  requirements/type-check.txt
  schemas/openapi.json
Labels: size:M

#6939 fix: use CTE for orphan span query
  src/phoenix/server/api/types/Project.py
  tests/unit/server/api/types/test_Project.py
Labels: size:L

#6932 chore(main): release arize-phoenix 8.20.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6940 feat(ui): add chat / message components for note taking
  app/src/components/chat/MessageBar.tsx
  app/src/components/chat/MessageBubble.tsx
  app/src/components/chat/index.tsx
  app/src/components/icon/Icons.tsx
  app/src/components/user/UserPicture.tsx
  app/stories/ChatUI.stories.tsx
Labels: size:L

#6937 feat: Move Span Annotation Editor into Span Aside
  app/src/components/disclosure/Disclosure.tsx
  app/src/components/disclosure/styles.tsx
  app/src/components/react-resizable-panels/TitledPanel.tsx
  app/src/components/react-resizable-panels/index.ts
  app/src/components/tabs/Tabs.tsx
  app/src/components/trace/AnnotationActionMenu.tsx
  app/src/components/trace/SpanAnnotationForm.tsx
  app/src/components/trace/SpanAnnotationsEditor.tsx
  app/src/contexts/index.tsx
  app/src/pages/trace/SpanAside.tsx
  app/src/pages/trace/SpanDetails.tsx
  app/src/pages/trace/TraceDetails.tsx
  app/src/pages/trace/__generated__/SpanAsideSpanQuery.graphql.ts
  app/src/pages/trace/__generated__/SpanAside_span.graphql.ts
  app/src/pages/trace/__generated__/SpanDetailsQuery.graphql.ts
  app/src/store/preferencesStore.tsx
  app/stories/TitledPanel.stories.tsx
Labels: size:XL

#6955 chore: sync main with docs
  docs/.gitbook/assets/Screenshot 2025-03-17 at 4.06.52 PM.png
  docs/.gitbook/assets/Screenshot 2025-03-17 at 4.14.43 PM.png
  docs/.gitbook/assets/Screenshot 2025-03-17 at 4.15.31 PM.png
  docs/.gitbook/assets/Screenshot 2025-03-17 at 4.24.19 PM.png
  docs/.gitbook/assets/agent_image.png
  docs/.gitbook/assets/compuse_Agent.png
  docs/.gitbook/assets/copilot_Agent.png
  docs/.gitbook/assets/rag_agent.png
  docs/README.md
  docs/SUMMARY.md
  docs/datasets-and-experiments/use-cases-datasets/README.md
  docs/integrations/cleanlab.md
  docs/prompt-engineering/quickstart-prompts/quickstart-prompts-python.md
  docs/prompt-engineering/use-cases-prompts/chain-of-thought-prompting.md
  docs/prompt-engineering/use-cases-prompts/few-shot-prompting.md
  docs/prompt-engineering/use-cases-prompts/prompt-optimization.md
  docs/prompt-engineering/use-cases-prompts/react-prompting.md
  docs/reference/release-notes.md
  docs/tracing/how-to-tracing/README.md
  docs/tracing/how-to-tracing/feedback-and-annotations/llm-evaluations.md
  docs/tracing/how-to-tracing/importing-and-exporting-traces/extract-data-from-spans.md
  docs/tracing/how-to-tracing/setup-tracing/custom-spans.md
  docs/tracing/integrations-tracing/README.md
  docs/tracing/integrations-tracing/autogen-support.md
  docs/tracing/integrations-tracing/guardrails-ai.md
  docs/tracing/integrations-tracing/prompt-flow.md
Labels: size:XL

#6951 feat(ui): select
  app/src/GlobalStyles.tsx
  app/src/components/button/Button.tsx
  app/src/components/button/styles.tsx
  app/src/components/combobox/ComboBox.tsx
  app/src/components/combobox/styles.tsx
  app/src/components/datetime/TimeRangeSelector.tsx
  app/src/components/icon/Icons.tsx
  app/src/components/icon/SelectChevronUpDownIcon.tsx
  app/src/components/icon/index.tsx
  app/src/components/index.tsx
  app/src/components/listbox/ListBox.tsx
  app/src/components/overlay/Popover.tsx
  app/src/components/select/Select.tsx
  app/src/components/select/SelectItem.tsx
  app/src/components/select/SelectValue.tsx
  app/src/components/select/index.tsx
  app/stories/Gallery.stories.tsx
  app/stories/Select.stories.tsx
Labels: size:L

#6945 chore: add timeout to query perf script
  scripts/perf/postgres/postgres_explain_analyze.py
Labels: size:XL
