Repository Arize-ai/phoenix, pull requests merged in 2025-04, with the labels that each got.

#6957 feat: Add input for configuring global retention policy
  app/src/components/field/NumberField.tsx
  app/src/pages/settings/GlobalRetentionPolicyCard.tsx
  app/src/pages/settings/SettingsGeneralPage.tsx
  app/src/pages/settings/__generated__/GlobalRetentionPolicyCardMutation.graphql.ts
  app/src/pages/settings/__generated__/GlobalRetentionPolicyCardQuery.graphql.ts
Labels: size:XL

#6969 fix: Re-enable project stream toggle
  app/src/pages/project/StreamToggle.tsx
Labels: size:XS

#6971 refactor(annotaitons): add a annotationConfigBase interface
  app/schema.graphql
  src/phoenix/server/api/types/AnnotationConfig.py
Labels: size:M

#6974 refactor(annotations): make continuous annotations inherit from base
  app/schema.graphql
  app/src/pages/project/__generated__/ProjectAnnotationConfigCardContentQuery.graphql.ts
  src/phoenix/server/api/types/AnnotationConfig.py
Labels: size:L

#6973 perf: Cache project table results when toggling details slide over
  app/src/pages/project/SessionsTable.tsx
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/StreamToggle.tsx
  app/src/pages/project/TracesTable.tsx
Labels: size:XS

#6970 feat(annotations): project annotation config
  app/src/components/loading/ContentSkeleton.tsx
  app/src/components/loading/index.tsx
  app/src/components/trace/__generated__/EditSpanAnnotationsDialogEditAnnotationMutation.graphql.ts
  app/src/components/trace/__generated__/EditSpanAnnotationsDialogNewAnnotationQuery.graphql.ts
  app/src/components/trace/__generated__/EditSpanAnnotationsDialogQuery.graphql.ts
  app/src/components/trace/__generated__/EditSpanAnnotationsDialogSpanAnnotationsQuery.graphql.ts
  app/src/components/trace/__generated__/EditSpanAnnotationsDialog_spanAnnotations.graphql.ts
  app/src/pages/project/ProjectAnnotationConfigCard.tsx
  app/src/pages/project/ProjectConfigPage.tsx
  app/src/pages/project/ProjectPageQueries.tsx
  app/src/pages/project/__generated__/ProjectAnnotationConfigCardContentAddAnnotationConfigToProjectMutation.graphql.ts
  app/src/pages/project/__generated__/ProjectAnnotationConfigCardContentProjectAnnotationsQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectAnnotationConfigCardContentQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectAnnotationConfigCardContentRemoveAnnotationConfigFromProjectMutation.graphql.ts
  app/src/pages/project/__generated__/ProjectAnnotationConfigCardContent_project_annotations.graphql.ts
  app/src/pages/project/__generated__/ProjectPageQueriesProjectConfigQuery.graphql.ts
  app/stories/Skeleton.stories.tsx
Labels: size:XXL

#6950 chore(main): release arize-phoenix 8.21.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6985 docs: mention symlink step (tox run -e add_symlinks) in DEVELOPMENT.md
  DEVELOPMENT.md
Labels: size:S

#6987 chore: merge docs branch into main
  DEVELOPMENT.md
  docs/README.md
  docs/SUMMARY.md
  docs/integrations/flowise.md
  docs/notebooks.md
  docs/quickstart.md
  docs/reference/release-notes.md
  docs/tracing/how-to-tracing/README.md
  docs/tracing/how-to-tracing/importing-and-exporting-traces/extract-data-from-spans.md
  docs/tracing/how-to-tracing/setup-tracing/README.md
  docs/tracing/how-to-tracing/setup-tracing/javascript.md
  docs/tracing/how-to-tracing/setup-tracing/setup-using-phoenix-otel.md
  docs/tracing/llm-traces-1/README.md
  docs/tracing/llm-traces-1/quickstart-tracing-python.md
  docs/tracing/llm-traces-1/quickstart-tracing-ts.md
  docs/tracing/llm-traces.md
  docs/user-guide.md
Labels: size:XL

#6984 feat: add REST endpoints to list or create prompt version tags
  app/schema.graphql
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py
  packages/phoenix-client/src/phoenix/client/resources/prompts/__init__.py
  schemas/openapi.json
  src/phoenix/db/insertion/helpers.py
  src/phoenix/db/types/identifier.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/routers/v1/prompts.py
  src/phoenix/server/api/types/PromptVersionTag.py
  tests/__generated__/graphql/__init__.py
  tests/integration/_helpers.py
  tests/integration/prompts/test_prompts.py
Labels: size:XXL

#6989 chore(main): release arize-phoenix 8.22.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6809 chore(main): release arize-phoenix-client 1.2.0
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#6995 fix: add aiohttp to container for azure-identity
  pyproject.toml
Labels: size:XS

#6996 chore(main): release arize-phoenix 8.22.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6978 docs: create tracing_and_evals_weaviate.ipynb
  tutorials/integrations/tracing_and_evals_weaviate.ipynb
Labels: size:XL

#7027 feat: dataset and experiment tools
  js/packages/phoenix-mcp/src/tools/datasetTools.ts
  js/packages/phoenix-mcp/src/tools/experimentTools.ts
  js/packages/phoenix-mcp/src/tools/index.ts
Labels: size:M

#7028 feat(mcp): Add all readme files as resources
  js/packages/phoenix-mcp/package.json
  js/packages/phoenix-mcp/src/index.ts
  js/packages/phoenix-mcp/src/resources/index.ts
  js/packages/phoenix-mcp/src/resources/readme.ts
  js/pnpm-lock.yaml
Labels: size:L

#7029 feat: Add some dataset tools
  js/packages/phoenix-mcp/src/index.ts
  js/packages/phoenix-mcp/src/tools/datasetTools.ts
Labels: size:M

#7033 feat(mcp): Add readmes as tools
  js/packages/phoenix-mcp/package.json
  js/packages/phoenix-mcp/src/index.ts
  js/packages/phoenix-mcp/src/resources/index.ts
  js/packages/phoenix-mcp/src/resources/readme.ts
  js/packages/phoenix-mcp/src/tools/index.ts
  js/packages/phoenix-mcp/src/tools/promptTools.ts
Labels: size:L

#7034 feat(mcp): Release CI for mcp
  .github/workflows/typescript-packages-publish-experimental.yml
  js/.changeset/mighty-beans-wish.md
  js/packages/phoenix-mcp/LICENSE
  js/packages/phoenix-mcp/package.json
  js/packages/phoenix-mcp/src/index.ts
Labels: size:S

#6991 feat: mcp server
  .github/workflows/typescript-packages-publish-experimental.yml
  js/.changeset/mighty-beans-wish.md
  js/.prettierignore
  js/packages/phoenix-mcp/.env.example
  js/packages/phoenix-mcp/.gitignore
  js/packages/phoenix-mcp/.gitigore
  js/packages/phoenix-mcp/LICENSE
  js/packages/phoenix-mcp/README.md
  js/packages/phoenix-mcp/package.json
  js/packages/phoenix-mcp/pnpm-lock.yaml
  js/packages/phoenix-mcp/src/index.ts
  js/packages/phoenix-mcp/src/resources/index.ts
  js/packages/phoenix-mcp/src/resources/readme.ts
  js/packages/phoenix-mcp/src/tools/datasetTools.ts
  js/packages/phoenix-mcp/src/tools/experimentTools.ts
  js/packages/phoenix-mcp/src/tools/index.ts
  js/packages/phoenix-mcp/src/tools/promptSchemas.ts
  js/packages/phoenix-mcp/src/tools/promptTools.ts
  js/packages/phoenix-mcp/tsconfig.json
  js/pnpm-lock.yaml
Labels: size:XL, feature branch

#7037 fix(mcp): flatten structure
  .github/workflows/typescript-packages-publish-experimental.yml
  js/packages/phoenix-mcp/package.json
  js/packages/phoenix-mcp/src/datasetTools.ts
  js/packages/phoenix-mcp/src/experimentTools.ts
  js/packages/phoenix-mcp/src/index.ts
  js/packages/phoenix-mcp/src/promptSchemas.ts
  js/packages/phoenix-mcp/src/promptTools.ts
  js/packages/phoenix-mcp/src/readmeResource.ts
  js/packages/phoenix-mcp/src/resources/index.ts
  js/packages/phoenix-mcp/src/tools/index.ts
Labels: size:S

#7038 feat(mcp): release
  js/.changeset/wild-areas-march.md
Labels: size:XS

#7040 feat: make mcp executable
  js/.changeset/two-ears-dress.md
  js/packages/phoenix-mcp/src/index.ts
Labels: size:XS

#7042 docs: fix readmes for MCP
  README.md
  js/packages/phoenix-mcp/LICENSE
  js/packages/phoenix-mcp/README.md
Labels: size:M

#7044 docs: add nice headers
  js/packages/phoenix-client/README.md
  packages/phoenix-client/README.md
  packages/phoenix-otel/README.md
Labels: size:M

#7045 chore(main): release arize-phoenix-client 1.2.1
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#7046 chore(main): release arize-phoenix-otel 0.9.1
  .release-please-manifest.json
  packages/phoenix-otel/CHANGELOG.md
  packages/phoenix-otel/pyproject.toml
Labels: autorelease: pending, size:S

#7050 feat(mcp): add prompt descriptions and tagging endpoints
  js/packages/phoenix-mcp/src/promptSchemas.ts
  js/packages/phoenix-mcp/src/promptTools.ts
Labels: size:L

#7052 docs: LLM as a judge prompt optimization notebook
  tutorials/evals/optimizing_llm_as_a_judge_prompts.ipynb
Labels: size:XL

#7051 feat: add PHOENIX_ALLOWED_ORIGINS env to phoenix server
  src/phoenix/config.py
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  tox.ini
Labels: size:M

#7061 feat: Enhance MCP tool descriptions and add a tool for creating synthetic dataset examples
  js/packages/phoenix-mcp/src/datasetTools.ts
  js/packages/phoenix-mcp/src/experimentTools.ts
  js/packages/phoenix-mcp/src/promptTools.ts
Labels: size:L

#7067 fix: Don't close model settings dialog when picking azure version
  app/src/pages/playground/ModelConfigButton.tsx
Labels: size:XS

#7069 fix: Allow scrolling the entire experiment compare table
  app/src/pages/experiment/ExperimentCompareTable.tsx
Labels: size:L

#7068 docs: adding ragas phoenix notebook
  tutorials/integrations/ragas_agents_cookbook_phoenix.ipynb
Labels: size:XL

#7072 fix(session): improve PostgreSQL error message in launch_app
  src/phoenix/session/session.py
Labels: size:S

#7066 fix: Make time range selector more accessible
  app/src/components/datetime/TimeRangeSelector.tsx
Labels: size:L

#7073 docs: google agents example nb
  tutorials/tracing/google_agent_engine_tracing_tutorial.ipynb
Labels: size:XL

#7076 feat(annotations): add timestamps to annotation gql type
  src/phoenix/server/api/types/Annotation.py
  src/phoenix/server/api/types/SpanAnnotation.py
Labels: size:XS

#7081 feat(tracing): make feedback table scroll
  app/src/components/trace/AnnotatorKindToken.tsx
  app/src/components/trace/SpanAnnotationsEditor.tsx
  app/src/pages/trace/SpanFeedback.tsx
Labels: size:L

#7085 feat(tracing): delete annotation from the table
  app/src/components/trace/AnnotationActionMenu.tsx
  app/src/components/trace/SpanAnnotationActionMenu.tsx
  app/src/pages/trace/SpanFeedback.tsx
  app/src/pages/trace/__generated__/SpanDetailsQuery.graphql.ts
  app/src/pages/trace/__generated__/SpanFeedback_annotations.graphql.ts
Labels: size:L

#7043 chore(main): release arize-phoenix 8.23.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7064 feat: allow project name as identifier in REST path
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py
  packages/phoenix-client/src/phoenix/client/resources/projects/__init__.py
  packages/phoenix-client/src/phoenix/client/resources/prompts/__init__.py
  packages/phoenix-client/src/phoenix/client/utils/encode_path_param.py
  schemas/openapi.json
  src/phoenix/config.py
  src/phoenix/db/helpers.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/routers/v1/projects.py
  src/phoenix/server/api/subscriptions.py
  tests/integration/projects/test_projects.py
  tests/unit/server/api/routers/v1/test_projects.py
Labels: size:XXL

#6982 feat: send welcome email after user creation
  app/schema.graphql
  app/src/pages/settings/NewUserDialog.tsx
  app/src/pages/settings/__generated__/NewUserDialogMutation.graphql.ts
  src/phoenix/config.py
  src/phoenix/db/facilitator.py
  src/phoenix/server/api/context.py
  src/phoenix/server/api/mutations/user_mutations.py
  src/phoenix/server/app.py
  src/phoenix/server/email/sender.py
  src/phoenix/server/email/templates/welcome.html
  src/phoenix/server/email/types.py
  src/phoenix/server/main.py
  tests/__generated__/graphql/__init__.py
  tests/integration/_helpers.py
  tests/integration/auth/test_auth.py
  tests/unit/db/test_facilitator.py
  tests/unit/test_config.py
Labels: size:XL

#7086 chore(main): release arize-phoenix 8.24.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7056 chore(main): release arize-phoenix-client 1.3.0
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#7089 fix: route user to forgot-password page in welcome email url
  src/phoenix/server/email/sender.py
  src/phoenix/server/email/templates/welcome.html
  tests/integration/auth/test_auth.py
Labels: size:S

#7095 ci: always recreate tox env for codegen
  tox.ini
Labels: size:XS

#7092 chore(main): release arize-phoenix 8.24.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7097 feat(annotations): full annotations table
  app/src/components/trace/AnnotatorKindToken.tsx
  app/src/pages/trace/SpanFeedback.tsx
  app/src/pages/trace/SpanNotesEditor.tsx
  app/src/pages/trace/__generated__/SpanDetailsQuery.graphql.ts
  app/src/pages/trace/__generated__/SpanFeedback_annotations.graphql.ts
  app/src/pages/trace/__generated__/SpanNotesEditorQuery.graphql.ts
Labels: size:L

#7098 feat(retention): Add capability based access to retention policy
  app/src/components/auth/AuthGuard.tsx
  app/src/pages/settings/SettingsGeneralPage.tsx
Labels: size:S

#7101 ci: fix tests
  src/phoenix/db/facilitator.py
  tests/unit/db/test_facilitator.py
Labels: size:XS

#7107 fix: restore streaming
  app/src/pages/project/SessionsTable.tsx
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
Labels: size:XS

#7105 chore(main): release arize-phoenix 8.24.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7114 feat: Display tool call and tool result Ids in span details
  app/src/components/disclosure/Disclosure.tsx
  app/src/openInference/tracing/types.ts
  app/src/pages/trace/SpanDetails.tsx
Labels: size:L

#7115 chore: Update phoenix mcp readme
  js/packages/phoenix-mcp/README.md
Labels: size:S

#7116 chore(phoenix-mcp): bump readme
  js/.changeset/true-islands-grow.md
Labels: size:XS

#7109 feat(annotations): span annotation filters
  app/schema.graphql
  src/phoenix/server/api/input_types/SpanAnnotationFilter.py
  src/phoenix/server/api/types/Span.py
  tests/unit/server/api/input_types/test_SpanAnnotationFilter.py
Labels: size:L

#7113 chore: Update Bug and Enhancement request forms
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: size:M

#7121 docs: amazon bedrock agents example
  tutorials/integrations/amazon_bedrock_agents_tracing_and_evals.ipynb
Labels: size:L

#7123 chore: git ignore scratch work
  .gitignore
Labels: size:XS

#7130 feat(admin): system level retention policies table
  app/package.json
  app/pnpm-lock.yaml
  app/src/Routes.tsx
  app/src/pages/settings/RetentionPoliciesTable.tsx
  app/src/pages/settings/SettingsDataPage.tsx
  app/src/pages/settings/SettingsPage.tsx
  app/src/pages/settings/__generated__/RetentionPoliciesTablePoliciesQuery.graphql.ts
  app/src/pages/settings/__generated__/RetentionPoliciesTable_policies.graphql.ts
  app/src/pages/settings/__generated__/settingsDataPageLoaderQuery.graphql.ts
  app/src/pages/settings/settingsDataPageLoader.tsx
Labels: size:XL

#7139 fix: redirect GET v1/* to home
  app/src/Routes.tsx
Labels: size:XS

#7141 fix(otel): ensure arize-phoenix-otel has no type issues on import when installed as a standalone package
  packages/phoenix-otel/src/phoenix/otel/py.typed
Labels: size:XS

#7143 chore(main): release arize-phoenix-otel 0.9.2
  .release-please-manifest.json
  packages/phoenix-otel/CHANGELOG.md
  packages/phoenix-otel/pyproject.toml
Labels: autorelease: pending, size:S

#7146 fix: update gpt models for playground
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:XS

#7111 chore(main): release arize-phoenix 8.25.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7150 docs: openAI agents SDK cookbook
  tutorials/evals/openai_agents_cookbook.ipynb
Labels: size:XL

#7129 feat: graphql query for annotation summaries per span
  app/schema.graphql
  src/phoenix/server/api/dataloaders/annotation_summaries.py
  src/phoenix/server/api/types/AnnotationSummary.py
  src/phoenix/server/api/types/Span.py
  tests/unit/server/api/types/test_Span.py
Labels: size:L

#7132 feat(tracing): add load more and loading state to the infinite scroll
  app/src/components/table/LoadMoreRow.tsx
  app/src/components/table/index.tsx
  app/src/pages/project/SpansTable.tsx
Labels: size:M

#7145 feat(admin): create retention policy UI
  app/package.json
  app/pnpm-lock.yaml
  app/src/pages/settings/CreateRetentionPolicy.tsx
  app/src/pages/settings/RetentionPoliciesTable.tsx
  app/src/pages/settings/RetentionPolicyForm.tsx
  app/src/pages/settings/SettingsDataPage.tsx
  app/src/pages/settings/__generated__/CreateRetentionPolicyMutation.graphql.ts
  app/src/pages/settings/__generated__/RetentionPoliciesTablePoliciesQuery.graphql.ts
  app/src/pages/settings/__generated__/RetentionPoliciesTable_policies.graphql.ts
  app/src/pages/settings/__generated__/settingsDataPageLoaderQuery.graphql.ts
Labels: size:XXL

#6943 fix: Formatting of additionalModelRequestFields based on model
  packages/phoenix-evals/src/phoenix/evals/models/bedrock.py
Labels: size:S

#7151 feat: add PHOENIX_ADMIN_SECRET environment variable
  src/phoenix/config.py
  src/phoenix/db/facilitator.py
  src/phoenix/server/bearer_auth.py
  tests/integration/auth/conftest.py
  tests/integration/auth/test_auth.py
  tests/integration/prompts/conftest.py
  tests/integration/prompts/test_prompts.py
  tests/unit/server/test_bearer_auth.py
  tests/unit/test_config.py
Labels: size:L

#7165 fix: disallow an admin user to change their own role because they may be the last admin user in the system
  src/phoenix/server/api/mutations/user_mutations.py
  tests/integration/auth/test_auth.py
Labels: size:S

#7167 fix(ui): hide menu for changing role for self in UsersTable
  app/src/pages/settings/UsersTable.tsx
Labels: size:S

#7166 chore(main): release arize-phoenix 8.26.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7163 chore(main): release arize-phoenix-evals 0.20.5
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#7144 fix: azure max tokens update
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
Labels: size:S

#7172 fix: remove WebSocket dependency
  app/package.json
  app/pnpm-lock.yaml
  app/src/RelayEnvironment.ts
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundStreamToggle.tsx
  app/src/window.d.ts
  pyproject.toml
  src/phoenix/config.py
  src/phoenix/server/app.py
  src/phoenix/server/main.py
  src/phoenix/server/middleware/__init__.py
  src/phoenix/server/middleware/gzip.py
  src/phoenix/services.py
  src/phoenix/session/session.py
  tests/unit/conftest.py
Labels: size:L

#7175 chore(main): release arize-phoenix 8.26.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7173 chore(main): release arize-phoenix-evals 0.20.6
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#7159 docs: updating ragas
  tutorials/integrations/ragas_agents_cookbook_phoenix.ipynb
Labels: size:XS

#7162 feat(admin): project retention policy for admins
  app/src/components/auth/AuthGuard.tsx
  app/src/components/retention/ProjectTraceRetentionPolicySelect.tsx
  app/src/components/retention/__generated__/ProjectTraceRetentionPolicySelectFragment.graphql.ts
  app/src/contexts/ViewerContext.tsx
  app/src/contexts/index.tsx
  app/src/pages/project/ProjectConfigPage.tsx
  app/src/pages/project/ProjectPageQueries.tsx
  app/src/pages/project/ProjectRetentionPolicyCard.tsx
  app/src/pages/project/__generated__/ProjectConfigPageProjectRetentionPolicyCardQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectConfigPage_projectRetentionPolicyCard.graphql.ts
  app/src/pages/project/__generated__/ProjectPageQueriesProjectConfigQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectRetentionPolicyCardQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectRetentionPolicyCardSetProjectRetentionPolicyMutation.graphql.ts
  app/src/pages/project/__generated__/ProjectRetentionPolicyCard_policy.graphql.ts
  app/src/pages/project/__generated__/ProjectRetentionPolicyCard_query.graphql.ts
  app/src/pages/settings/RetentionPolicyForm.tsx
  app/src/utils/retentionPolicyUtils.ts
Labels: size:XXL

#7181 docs: updated openai agents sdk notebook
  tutorials/evals/openai_agents_cookbook.ipynb
Labels: size:S

#7185 docs: adding bedrock tracing & evals tutorial
  tutorials/evals/bedrock_tracing_and_evals_tutorial.ipynb
Labels: size:L

#7187 docs: MCP tracing example
  tutorials/mcp/tracing_between_mcp_client_and_server/README.md
  tutorials/mcp/tracing_between_mcp_client_and_server/client.py
  tutorials/mcp/tracing_between_mcp_client_and_server/requirements.txt
  tutorials/mcp/tracing_between_mcp_client_and_server/server.py
Labels: size:L

#7199 fix: require starlette>=0.46.0
  pyproject.toml
Labels: size:XS

#7200 chore(main): release arize-phoenix 8.26.3
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7082 feat: Upsert on annotation identifier conflict
  src/phoenix/db/migrations/versions/2f9d1a65945f_annotation_config_migration.py
  src/phoenix/db/migrations/versions/8c9ff7c78bce_add_annotation_indexes.py
  src/phoenix/db/migrations/versions/bb8139330879_create_project_trace_retention_policies_table.py
  src/phoenix/db/models.py
  src/phoenix/server/api/mutations/span_annotations_mutations.py
  src/phoenix/server/api/mutations/trace_annotations_mutations.py
  src/phoenix/server/api/routers/v1/spans.py
  tests/integration/db_migrations/test_up_and_down_migrations.py
  tests/unit/server/api/dataloaders/conftest.py
  tests/unit/server/api/mutations/test_span_annotation_mutations.py
Labels: size:XL

#7220 fix: forbid deletion of default policy
  src/phoenix/server/api/mutations/project_trace_retention_policy_mutations.py
  tests/unit/server/api/mutations/test_project_trace_retention_policy_mutations.py
Labels: size:M

#7209 refactor(annotations): use json column for annotation configs
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  schemas/openapi.json
  src/phoenix/db/migrations/versions/2f9d1a65945f_annotation_config_migration.py
  src/phoenix/db/models.py
  src/phoenix/db/types/annotation_configs.py
  src/phoenix/db/types/db_models.py
  src/phoenix/server/api/helpers/prompts/models.py
  src/phoenix/server/api/mutations/annotation_config_mutations.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/routers/v1/annotation_configs.py
  src/phoenix/server/api/types/AnnotationConfig.py
  src/phoenix/server/api/types/Project.py
Labels: size:XL

#7229 docs: adding files for aws deployment tutorial
  tutorials/deployment/AWS Cloudformation/app.yml
  tutorials/deployment/AWS Cloudformation/permissions.json
  tutorials/deployment/AWS Cloudformation/phoenix-auth.yml
  tutorials/deployment/AWS Cloudformation/phoenix-network.yml
Labels: size:XL

#7221 fix: forbid renaming of default policy
  src/phoenix/server/api/mutations/project_trace_retention_policy_mutations.py
  tests/unit/server/api/mutations/test_project_trace_retention_policy_mutations.py
Labels: size:L

#7227 feat(tracing): scroll selected span into view when navigating to a trace
  app/src/components/trace/TraceTree.tsx
Labels: size:S

#7238 fix: Unique annotation per user
  src/phoenix/server/api/mutations/span_annotations_mutations.py
  src/phoenix/server/api/mutations/trace_annotations_mutations.py
  tests/unit/server/api/types/test_SpanAnnotation.py
  tests/unit/server/api/types/test_TraceAnnotation.py
Labels: size:M

#7237 test: OpenID Connect (OIDC) signup flow
  tests/integration/_helpers.py
  tests/integration/auth/conftest.py
  tests/integration/auth/test_auth.py
Labels: size:L

#7251 fix(annotations): Truncate long category names in annotation config table
  app/src/pages/settings/AnnotationConfigTable.tsx
Labels: size:XS

#7248 fix(annotations): ensure create annotation mutations do not upsert
  src/phoenix/server/api/mutations/span_annotations_mutations.py
  src/phoenix/server/api/mutations/trace_annotations_mutations.py
  tests/unit/server/api/mutations/test_span_annotation_mutations.py
  tests/unit/server/api/types/test_SpanAnnotation.py
  tests/unit/server/api/types/test_TraceAnnotation.py
Labels: size:S

#7236 refactor(annotations): allow batch deletion of annotation configs
  app/schema.graphql
  app/src/pages/settings/SettingsAnnotationsPage.tsx
  app/src/pages/settings/__generated__/SettingsAnnotationsPageDeleteAnnotationConfigsMutation.graphql.ts
  src/phoenix/server/api/mutations/annotation_config_mutations.py
Labels: size:L

#7253 fix(annotations): Allow all settings pages to overflow
  app/src/pages/settings/SettingsPage.tsx
Labels: size:XS

#7252 test(annotations): add tests for graphql mutations for annotation configs
  app/schema.graphql
  src/phoenix/server/api/mutations/annotation_config_mutations.py
  src/phoenix/server/api/types/AnnotationConfig.py
  tests/unit/server/api/mutations/test_annotation_config_mutations.py
Labels: size:XL

#7260 feat: Add span comment mutation
  app/schema.graphql
  src/phoenix/server/api/input_types/CreateSpanAnnotationInput.py
  src/phoenix/server/api/mutations/span_annotations_mutations.py
Labels: size:M

#7262 feat: Add /readyz endpoint to confirm database connectivity
  src/phoenix/server/app.py
Labels: size:S

#7274 feat: Reserve note annotation name
  src/phoenix/server/api/mutations/annotation_config_mutations.py
  src/phoenix/server/api/mutations/span_annotations_mutations.py
  src/phoenix/server/api/routers/v1/annotation_configs.py
  src/phoenix/server/api/routers/v1/spans.py
Labels: size:M

#7280 feat(admin): add a link to retention policies"
  app/src/pages/settings/GlobalRetentionPolicyCard.tsx
Labels: size:L

#7281 feat(annotations): more clear project annotation configs
  app/src/components/alert/Alert.tsx
  app/src/pages/project/ProjectAnnotationConfigCard.tsx
Labels: size:L

#7207 chore: mustache formatting & fixed prompt versioning flow
  tutorials/self-improving_agent.ipynb
Labels: size:L

#7284 fix: Allow scroll on settings pages
  app/src/pages/settings/SettingsPage.tsx
Labels: size:XS

#7285 chore(main): release arize-phoenix 8.27.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7289 fix: db migrate from JSONB to JSON
  src/phoenix/db/migrations/versions/8a3764fe7f1a_change_jsonb_to_json_for_prompts.py
  src/phoenix/db/models.py
  tests/integration/db_migrations/test_change_jsonb_to_json_for_prompts.py
  tests/integration/db_migrations/test_up_and_down_migrations.py
Labels: size:L

#7276 feat: Span note resolver
  app/schema.graphql
  src/phoenix/server/api/types/Span.py
Labels: size:S

#7282 refactor(annotations): consolidate annotation migrations
  src/phoenix/db/migrations/versions/2f9d1a65945f_annotation_config_migration.py
  src/phoenix/db/migrations/versions/8c9ff7c78bce_add_annotation_indexes.py
  src/phoenix/db/migrations/versions/bb8139330879_create_project_trace_retention_policies_table.py
  tests/integration/db_migrations/test_up_and_down_migrations.py
Labels: size:L

#7293 docs: update sessions notebook
  tutorials/tracing/openai_sessions_tutorial.ipynb
Labels: size:M

#7290 docs(client): add general rules for the client
  packages/phoenix-client/.cursor/rules/general.mdc
Labels: size:M

#7292 refactor(annotations): consolidate rest routes
  js/packages/phoenix-client/src/__generated__/api/v1.ts
  schemas/openapi.json
  src/phoenix/server/api/routers/v1/annotation_configs.py
Labels: size:XXL

#7300 chore: sync docs
  docs/SUMMARY.md
  docs/evaluation/llm-evals/agent-evaluation.md
  docs/prompt-engineering/overview-prompts/prompt-management.md
Labels: size:XS

#7305 feat: gracefully handle ctrl-c
  src/phoenix/server/main.py
Labels: size:XS

#7312 chore: sync docs to main
  docs/SUMMARY.md
  docs/settings/access-control-rbac.md
  docs/settings/api-keys.md
  docs/settings/data-retention.md
Labels: size:M

#7311 chore(main): release arize-phoenix 8.28.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7302 fix(annotations): paginate list annotation configs route
  src/phoenix/server/api/routers/v1/annotation_configs.py
Labels: size:M

#7317 chore: Mermaid diagram of ERD
  src/phoenix/db/README.md
Labels: size:L

#7321 fix: Improve browser compatibility for Table sizing features
  app/src/components/table/styles.ts
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
  app/src/pages/project/SessionsTable.tsx
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
Labels: size:M

#7336 fix: simplify homeLoaderQuery
  app/schema.graphql
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/Functionality.py
Labels: size:XS

#7322 chore(main): release arize-phoenix 8.28.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7340 chore(main): release arize-phoenix 8.29.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7344 fix(admin): make retention days step 1
  app/src/pages/settings/RetentionPolicyForm.tsx
Labels: size:XS

#7346 feat: Summarize dynamic annotation columns
  app/src/pages/project/AnnotationSummary.tsx
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
  app/src/pages/project/__generated__/ProjectPageQueriesTracesQuery.graphql.ts
  app/src/pages/project/__generated__/TracesTableQuery.graphql.ts
  app/src/pages/project/__generated__/TracesTable_spans.graphql.ts
  app/src/pages/project/tableUtils.ts
  src/phoenix/server/api/mutations/span_annotations_mutations.py
Labels: size:L

#7349 feat(api): add RBAC primitives for fastAPI / REST
  src/phoenix/server/authorization.py
  tests/unit/server/test_authorization.py
Labels: size:L

#7071 feat: Add `SpanQuery` DSL to phoenix client and include `get_spans_dataframe` to client
  packages/phoenix-client/src/phoenix/client/client.py
  packages/phoenix-client/src/phoenix/client/resources/spans/__init__.py
  packages/phoenix-client/src/phoenix/client/types/spans.py
  packages/phoenix-client/tests/test_spans.py
  requirements/packages/phoenix-client.txt
  src/phoenix/session/client.py
  tests/unit/conftest.py
  tests/unit/datasets/test_experiments.py
  tests/unit/server/api/routers/v1/test_annotations.py
  tests/unit/server/api/routers/v1/test_spans.py
  tests/unit/trace/dsl/test_helpers.py
Labels: size:XL

#7356 fix: firefox table css compat
  app/src/pages/project/SpansTable.tsx
  app/src/pages/project/TracesTable.tsx
Labels: size:XS

#7358 feat: Add "copy name" button to project menu
  app/src/pages/projects/ProjectActionMenu.tsx
Labels: size:S

#7353 fix(playground): log playground subscription errors
  src/phoenix/server/api/helpers/playground_spans.py
Labels: size:XS

#7371 fix(annotations): Show 0 scores in summary labels
  app/src/components/annotation/AnnotationSummaryPopover.tsx
  app/src/components/trace/SpanAnnotationInput.tsx
Labels: size:XS

#7370 feat: separate TLS enabled flags for HTTP and gRPC
  src/phoenix/config.py
  src/phoenix/server/grpc_server.py
  src/phoenix/server/main.py
  tests/unit/test_config.py
Labels: size:L

#7372 refactor(annotations): Use dedicated createSpanNote mutation in note editor
  app/src/pages/trace/SpanNotesEditor.tsx
  app/src/pages/trace/__generated__/SpanNotesEditorAddNoteMutation.graphql.ts
Labels: size:M

#7350 chore(main): release arize-phoenix 8.30.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#7373 refactor: use leading visual for icons
  app/src/pages/settings/AnnotationConfigDialog.tsx
Labels: size:S
