Repository Arize-ai/phoenix, pull requests merged in 2025-01, with the labels that each got.

#5854 feat: Replace dummy data and wire up connections to database
  app/schema.graphql
  app/src/pages/prompt/__generated__/PromptLatestVersionsListFragment.graphql.ts
  app/src/pages/prompt/__generated__/PromptVersionsList__main.graphql.ts
  app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts
  src/phoenix/server/api/helpers/prompts/models.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/Prompt.py
  src/phoenix/server/api/types/PromptVersion.py
  src/phoenix/server/api/types/PromptVersionTemplate.py
  src/phoenix/server/api/types/ToolDefinition.py
Labels: size:L

#5876 feat: show a breakdown of tokens in the project header
  app/src/pages/project/ProjectPageHeader.tsx
  app/src/pages/project/__generated__/ProjectPageHeaderQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectPageHeader_stats.graphql.ts
  app/src/pages/project/__generated__/ProjectPageQuery.graphql.ts
Labels: size:L

#5874 fix: skip json parse if tool call function arguments attribute doesn't exist
  app/src/pages/trace/SpanDetails.tsx
Labels: size:S

#5830 chore(main): release arize-phoenix 7.4.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#5875 feat(prompts): display prompt vesion tags in the promt versions list
  app/src/GlobalStyles.tsx
  app/src/components/index.tsx
  app/src/components/tag/Tag.tsx
  app/src/components/tag/TagGroup.tsx
  app/src/components/tag/TagList.tsx
  app/src/components/tag/index.tsx
  app/src/pages/prompt/PromptVersionsList.tsx
  app/src/pages/prompt/__generated__/PromptVersionsList__main.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  app/stories/ComboBox.stories.tsx
  app/stories/Gallery.stories.tsx
  app/stories/TagGroup.stories.tsx
Labels: size:L

#5873 feat(components): Disclosure (fka Accordion)
  app/.eslintrc.js
  app/src/components/StopPropagation.tsx
  app/src/components/button/styles.tsx
  app/src/components/disclosure/Disclosure.tsx
  app/src/components/disclosure/index.ts
  app/src/components/disclosure/styles.tsx
  app/src/components/index.tsx
  app/src/pages/embedding/EventDetails.tsx
  app/src/pages/embedding/ExportSelectionButton.tsx
  app/src/pages/model/ModelPage.tsx
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundResponseFormat.tsx
  app/src/pages/playground/PlaygroundTools.tsx
  app/src/pages/trace/SpanFeedback.tsx
  app/stories/Disclosure.stories.tsx
  app/stories/Gallery.stories.tsx
Labels: size:XXL

#5889 fix(components): Add class names to Disclosure for backwards compatibility with Accordion
  app/src/components/disclosure/Disclosure.tsx
  app/src/components/index.tsx
  app/src/pages/playground/Playground.tsx
Labels: size:M

#5892 fix: coerce to string when output.value is not None (e.g. bool)
  src/phoenix/server/api/types/Span.py
Labels: size:S

#5878 chore(main): release arize-phoenix 7.5.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#5896 fix(docs): make experiment code snippet clearer
  docs/datasets-and-experiments/how-to-experiments/run-experiments.md
Labels: size:XS

#5894 fix(prompts): add types for create prompt mutation input
  app/schema.graphql
  src/phoenix/db/migrations/versions/bc8fea3c2bc8_add_prompt_tables.py
  src/phoenix/db/models.py
  src/phoenix/server/api/helpers/prompts/models.py
  src/phoenix/server/api/input_types/PromptVersionInput.py
  src/phoenix/server/api/mutations/prompt_mutations.py
  tests/integration/db_migrations/test_autoincrement_primary_keys.py
  tests/unit/server/api/mutations/test_prompt_mutations.py
Labels: size:L

#5897 fix: default prompt / completion tokens to 0
  src/phoenix/server/api/dataloaders/token_counts.py
Labels: size:XS

#5899 chore(main): release arize-phoenix 7.5.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#5893 feat(prompts): Load prompt into playground via url
  app/src/Routes.tsx
  app/src/components/combobox/ComboBox.tsx
  app/src/pages/playground/PlaygroundTemplate.tsx
  app/src/pages/playground/PromptComboBox.tsx
  app/src/pages/playground/__generated__/fetchPlaygroundPromptQuery.graphql.ts
  app/src/pages/playground/fetchPlaygroundPrompt.ts
  app/src/pages/prompt/PromptPlaygroundPage.tsx
  app/src/pages/prompt/promptLoader.tsx
  app/src/pages/prompt/promptPlaygroundLoader.tsx
  app/src/store/playground/playgroundStore.tsx
  app/src/store/playground/types.ts
  src/phoenix/server/api/queries.py
Labels: size:XL

#5877 fix: Allow ClassificationTemplate w/o explanation template
  packages/phoenix-evals/src/phoenix/evals/templates.py
  packages/phoenix-evals/tests/phoenix/evals/templates/test_template.py
Labels: size:S

#5904 fix(prompts): Fix code disclosure width on prompts ui
  app/src/pages/prompt/PromptCodeExportCard.tsx
Labels: size:XS

#5898 chore: add popover for using in prompt version tagging
  app/src/components/button/Button.tsx
  app/src/components/button/styles.tsx
  app/src/components/icon/Icons.tsx
  app/src/components/index.tsx
  app/src/components/overlay/Popover.tsx
  app/src/components/overlay/PopoverArrow.tsx
  app/src/components/overlay/index.tsx
  app/src/components/tag/Tag.tsx
  app/src/components/view/View.tsx
  app/src/pages/prompt/PromptCodeExportCard.tsx
  app/src/pages/prompt/PromptVersionDetailsPage.tsx
  app/src/pages/prompt/TagPromptVersionButton.tsx
  app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts
  app/src/pages/prompt/promptVersionLoader.tsx
  app/stories/Popover.stories.tsx
Labels: size:L

#5901 feat(prompts): create prompt version mutation
  app/schema.graphql
  src/phoenix/server/api/mutations/prompt_mutations.py
  src/phoenix/server/api/types/Prompt.py
  tests/unit/server/api/mutations/test_prompt_mutations.py
Labels: size:L

#5911 feat(prompts): show version timestamp
  app/schema.graphql
  app/src/pages/prompt/PromptLatestVersionsList.tsx
  app/src/pages/prompt/PromptVersionsList.tsx
  app/src/pages/prompt/__generated__/PromptLatestVersionsListFragment.graphql.ts
  app/src/pages/prompt/__generated__/PromptVersionsList__main.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  src/phoenix/server/api/types/PromptVersion.py
Labels: size:L

#5913 feat(prompts): show the tags that can be set on a promt version
  app/schema.graphql
  app/src/pages/prompt/TagPromptVersionButton.tsx
  app/src/pages/prompt/__generated__/TagPromptVersionButtonTagsQuery.graphql.ts
  src/phoenix/server/api/types/Prompt.py
Labels: size:L

#5907 feat(prompts): REST endpoint to get prompt version by tag name
  schemas/openapi.json
  src/phoenix/server/api/routers/v1/__init__.py
  src/phoenix/server/api/routers/v1/prompts.py
  tests/unit/server/api/routers/v1/test_prompts.py
Labels: size:XL

#5888 fix: Force wrapping when a word is wider than the element
  app/src/components/utility/PrettyText.tsx
Labels: size:XS

#5916 fix(prompts): record user who mutates prompt
  app/schema.graphql
  app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts
  app/src/pages/prompt/promptVersionLoader.tsx
  src/phoenix/server/api/mutations/prompt_mutations.py
  src/phoenix/server/api/types/PromptVersion.py
  tests/integration/auth/test_auth.py
  tests/unit/server/api/mutations/test_prompt_mutations.py
Labels: size:L

#5918 ci: check backward compatibility for OpenAPI schema
  .github/workflows/openapi-schema.yaml
Labels: size:S

#5919 fix: add id fields to annotations so that relay caches anotations correctly
  app/src/pages/project/TracesTable.tsx
  app/src/pages/project/__generated__/ProjectPageQuery.graphql.ts
  app/src/pages/project/__generated__/TracesTableQuery.graphql.ts
  app/src/pages/project/__generated__/TracesTable_spans.graphql.ts
  app/src/pages/trace/SpanDetails.tsx
  app/src/pages/trace/SpanFeedback.tsx
  app/src/pages/trace/TraceDetails.tsx
  app/src/pages/trace/__generated__/SpanDetailsQuery.graphql.ts
  app/src/pages/trace/__generated__/SpanFeedback_annotations.graphql.ts
  app/src/pages/trace/__generated__/TraceDetailsQuery.graphql.ts
Labels: size:M

#5905 chore(main): release arize-phoenix-evals 0.18.1
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#5920 chore(main): release arize-phoenix 7.5.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#5915 feat(prompts): REST endpoint to get prompt version by prompt version ID
  schemas/openapi.json
  src/phoenix/server/api/routers/v1/prompts.py
  tests/unit/server/api/routers/v1/test_prompts.py
Labels: size:L

#5927 feat(playground): Support anyOf json schema
  app/src/schemas/toolSchemas.ts
Labels: size:M

#5926 feat(prompts): Display tool definitions on prompt page
  app/src/components/SectionHeading.tsx
  app/src/components/disclosure/Disclosure.tsx
  app/src/components/index.tsx
  app/src/pages/prompt/PromptChatMessagesCard.tsx
  app/src/pages/prompt/PromptIndexPage.tsx
  app/src/pages/prompt/PromptModelConfigurationCard.tsx
  app/src/pages/prompt/PromptTools.tsx
  app/src/pages/prompt/PromptVersionDetailsPage.tsx
  app/src/pages/prompt/__generated__/PromptChatMessagesCard__main.graphql.ts
  app/src/pages/prompt/__generated__/PromptIndexPage__main.graphql.ts
  app/src/pages/prompt/__generated__/PromptModelConfigurationCard__main.graphql.ts
  app/src/pages/prompt/__generated__/PromptTools__main.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts
  app/src/pages/prompt/promptVersionLoader.tsx
  app/src/schemas/toolSchemas.ts
Labels: size:XL

#5936 ci: remove prerelease label in github releases for arize-phoenix-otel
  release-please-config.json
Labels: size:XS

#5935 feat: Add delete Prompt and delete PromptVersionTag mutations
  app/schema.graphql
  src/phoenix/server/api/input_types/PromptVersionTagInput.py
  src/phoenix/server/api/mutations/prompt_mutations.py
  src/phoenix/server/api/mutations/prompt_version_tag_mutations.py
Labels: size:M

#5937 feat(prompts): UI for setting tags
  app/src/pages/prompt/NewPromptVersionTagDialog.tsx
  app/src/pages/prompt/TagPromptVersionButton.tsx
  app/src/pages/prompt/__generated__/NewPromptVersionTagDialogMutation.graphql.ts
  app/src/pages/prompt/__generated__/TagPromptVersionButtonSetTagMutation.graphql.ts
  app/src/pages/prompt/__generated__/TagPromptVersionButtonTagsQuery.graphql.ts
Labels: size:XL

#5940 ci: update release please for arize-phoenix-client
  .release-please-manifest.json
  release-please-config.json
Labels: size:XS

#5934 feat: initial Python package skeleton for `arize-phoenix-client`
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/IP_NOTICE
  packages/phoenix-client/LICENSE
  packages/phoenix-client/README.md
  packages/phoenix-client/SECURITY
  packages/phoenix-client/pyproject.toml
  packages/phoenix-client/src/phoenix/client/__init__.py
  packages/phoenix-client/src/phoenix/client/py.typed
  packages/phoenix-client/tests/conftest.py
Labels: size:L

#5941 chore(main): release arize-phoenix-client 0.1.0-alpha.1
  .release-please-manifest.json
  packages/phoenix-client/CHANGELOG.md
  packages/phoenix-client/pyproject.toml
Labels: autorelease: pending, size:S

#5943 chore: add symlink for arize-phoenix-client
  .gitignore
  pyproject.toml
  tox.ini
Labels: size:XS

#5944 ci: update github workflow for arize-phoenix-client
  .github/workflows/python-CI.yml
  tox.ini
Labels: size:M

#5946 feat(prompts): update prompt version tags on set
  app/src/pages/prompt/NewPromptVersionTagDialog.tsx
  app/src/pages/prompt/PromptVersionDetailsPage.tsx
  app/src/pages/prompt/PromptVersionTagsList.tsx
  app/src/pages/prompt/PromptVersionsList.tsx
  app/src/pages/prompt/TagPromptVersionButton.tsx
  app/src/pages/prompt/__generated__/NewPromptVersionTagDialogMutation.graphql.ts
  app/src/pages/prompt/__generated__/PromptVersionTagsList_data.graphql.ts
  app/src/pages/prompt/__generated__/PromptVersionsList__main.graphql.ts
  app/src/pages/prompt/__generated__/TagPromptVersionButtonSetTagMutation.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts
  app/src/pages/prompt/promptVersionLoader.tsx
Labels: size:XL

#5942 feat(prompts): Save and load invocation parameters from/into playground
  app/src/components/SectionHeading.tsx
  app/src/components/disclosure/Disclosure.tsx
  app/src/components/disclosure/styles.tsx
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/PlaygroundResponseFormat.tsx
  app/src/pages/playground/PlaygroundTemplate.tsx
  app/src/pages/playground/PlaygroundTools.tsx
  app/src/pages/playground/__generated__/fetchPlaygroundPromptQuery.graphql.ts
  app/src/pages/playground/__generated__/fetchPlaygroundPromptSupportedInvocationParametersQuery.graphql.ts
  app/src/pages/playground/__tests__/fetchPlaygroundPrompt.test.ts
  app/src/pages/playground/fetchPlaygroundPrompt.ts
  app/src/pages/prompt/PromptModelConfigurationCard.tsx
  app/src/pages/prompt/PromptOutputSchema.tsx
  app/src/pages/prompt/PromptTools.tsx
  app/src/pages/prompt/__generated__/PromptModelConfigurationCard__main.graphql.ts
  app/src/pages/prompt/__generated__/PromptOutputSchemaFragment.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts
  app/src/pages/prompt/promptCodeSnippets.tsx
  app/src/pages/prompt/promptPlaygroundLoader.tsx
Labels: size:XXL

#5945 ci: update uv ruff mypy pytest
  .github/workflows/playwright.yaml
  .github/workflows/python-CI.yml
  requirements/ci.txt
  tox.ini
Labels: size:M

#5933 feat: Add `previous_version` resolver on `PromptVersion`
  app/schema.graphql
  src/phoenix/server/api/types/PromptVersion.py
Labels: size:S

#5949 fix: Manually check for conflicts in setPromptVersionTag mutation
  src/phoenix/server/api/mutations/prompt_version_tag_mutations.py
Labels: size:M

#5948 feat(prompts): prompt version tags config
  app/src/Routes.tsx
  app/src/components/overlay/Popover.tsx
  app/src/pages/prompt/DeletePromptVersionTagButton.tsx
  app/src/pages/prompt/PromptConfigPage.tsx
  app/src/pages/prompt/PromptLayout.tsx
  app/src/pages/prompt/PromptVersionTagsConfigCard.tsx
  app/src/pages/prompt/__generated__/DeletePromptVersionTagButtonMutation.graphql.ts
  app/src/pages/prompt/__generated__/PromptVersionTagsConfigCard_data.graphql.ts
  app/src/pages/prompt/__generated__/promptConfigLoaderQuery.graphql.ts
  app/src/pages/prompt/index.tsx
  app/src/pages/prompt/promptConfigLoader.ts
Labels: size:XL

#5962 fix: return 200 for POST v1/traces
  src/phoenix/server/api/routers/v1/traces.py
Labels: size:XS

#5928 chore(main): release arize-phoenix 7.6.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#5976 fix: Coerce incoming span token counts to int
  src/phoenix/db/insertion/span.py
  src/phoenix/trace/otel.py
  tests/unit/trace/test_otel.py
Labels: size:M

#5977 refactor(components): only use css stylable props
  app/src/components/button/Button.tsx
  app/src/components/disclosure/Disclosure.tsx
  app/src/components/types/style.ts
  app/src/pages/prompt/DeletePromptVersionTagButton.tsx
  app/src/pages/prompt/TagPromptVersionButton.tsx
  app/stories/Button.stories.tsx
Labels: size:M

#5979 chore(components): make combobox consistent
  app/src/components/combobox/styles.tsx
  app/src/components/field/styles.ts
  app/stories/ComboBox.stories.tsx
  app/stories/Gallery.stories.tsx
Labels: size:L

#5980 feat(prompts): default tags for prod / staging / dev
  app/src/constants/index.ts
  app/src/constants/promptConstants.ts
  app/src/pages/prompt/PromptVersionTagsConfigCard.tsx
  app/src/pages/prompt/TagPromptVersionButton.tsx
  app/src/pages/prompt/__generated__/DeletePromptVersionTagButtonMutation.graphql.ts
  app/src/pages/prompt/__generated__/PromptVersionTagsConfigCard_data.graphql.ts
  app/src/pages/prompt/__generated__/promptConfigLoaderQuery.graphql.ts
Labels: size:L

#5695 feat: Add authorization overlays
  kustomize/auth/kustomization.yaml
  kustomize/auth/patches.yaml
Labels: size:S

#6001 ci: update unit tests dependency respx>=0.22 for httpx>=0.28
  requirements/unit-tests.txt
Labels: size:XS

#6004 ci: pin upper bound on litellm to prevent windows break
  pyproject.toml
  requirements/unit-tests.txt
Labels: size:XS

#6003 ci: exit if there is a diff to build artifacts, changesets
  .github/workflows/typescript-packages-CI.yml
  .github/workflows/typescript-packages-publish.yml
Labels: size:M

#5988 refactor(prompts): validate jsonschema using third-party library
  pyproject.toml
  requirements/type-check.txt
  requirements/unit-tests.txt
  src/phoenix/server/api/helpers/jsonschema.py
  src/phoenix/server/api/helpers/prompts/models.py
  tests/unit/server/api/helpers/test_models.py
  tests/unit/server/api/mutations/test_prompt_mutations.py
Labels: size:XL

#6008 ci: ignore pnpm-store
  .gitignore
Labels: size:XS

#6009 chore(js): ignore example experiment runner package
  js/.changeset/config.json
Labels: size:XS

#6011 feat: Add sequence number fields to prompt versions
  app/schema.graphql
  src/phoenix/server/api/context.py
  src/phoenix/server/api/dataloaders/__init__.py
  src/phoenix/server/api/dataloaders/prompt_version_sequence_number.py
  src/phoenix/server/api/types/Prompt.py
  src/phoenix/server/api/types/PromptVersion.py
  src/phoenix/server/app.py
Labels: size:M

#6013 ci: unpin litellm
  pyproject.toml
  requirements/unit-tests.txt
Labels: size:XS

#5993 feat(prompts): Add "Clone Prompt" flow to prompts UI
  app/.storybook/main.ts
  app/schema.graphql
  app/src/pages/playground/UpsertPromptFromTemplateDialog.tsx
  app/src/pages/prompt/ClonePromptDialog.tsx
  app/src/pages/prompt/PromptInvocationParameters.tsx
  app/src/pages/prompt/PromptLayout.tsx
  app/src/pages/prompt/__generated__/ClonePromptDialogMutation.graphql.ts
  app/src/pages/prompt/__generated__/PromptLayout__main.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  app/src/utils/__tests__/errorUtils.test.ts
  app/src/utils/errorUtils.ts
  src/phoenix/server/api/mutations/prompt_mutations.py
  tests/unit/server/api/mutations/test_prompt_mutations.py
Labels: size:XL

#6017 feat: `phoenix.otel` infers GRPC port from env
  packages/phoenix-otel/README.md
  packages/phoenix-otel/src/phoenix/otel/otel.py
  packages/phoenix-otel/src/phoenix/otel/settings.py
Labels: size:S

#6010 feat: Add Prompt to setPromptVersionTag mutation
  app/schema.graphql
  src/phoenix/server/api/mutations/prompt_version_tag_mutations.py
Labels: size:M

#6024 fix: Update schema.py to make extensions a list, not chain
  src/phoenix/server/api/schema.py
Labels: size:XS

#6026 feat: Resolve source prompts
  app/schema.graphql
  src/phoenix/server/api/types/Prompt.py
Labels: size:S

#6028 refactor(components): use storybook builtins for theming
  app/.storybook/main.ts
  app/.storybook/preview-body.html
  app/.storybook/preview.tsx
  app/package.json
  app/pnpm-lock.yaml
  app/src/components/index.tsx
  app/stories/Button.stories.tsx
  app/stories/Colors.stories.tsx
  app/stories/ComboBox.stories.tsx
  app/stories/Disclosure.stories.tsx
  app/stories/Gallery.stories.tsx
  app/stories/Heading.stories.tsx
  app/stories/Icons.stories.tsx
  app/stories/Popover.stories.tsx
  app/stories/TagGroup.stories.tsx
  app/stories/Text.stories.tsx
  app/stories/TextField.stories.tsx
  app/stories/components/ThemeSplitView.tsx
  app/stories/components/ThemeToggleWrap.tsx
  app/stories/components/ThemeWrapper.tsx
Labels: size:XL

#6031 fix: Resolve source prompts properly
  src/phoenix/server/api/types/Prompt.py
Labels: size:XS

#5974 chore(main): release arize-phoenix 7.7.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6037 fix: don't lock on delete dataset
  src/phoenix/server/api/mutations/dataset_mutations.py
Labels: size:XS

#6038 fix: don't lock delete dataset mutation
  src/phoenix/auth.py
Labels: size:XS

#6039 chore(main): release arize-phoenix 7.7.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6025 feat: Add patchPromptDescription mutation
  app/schema.graphql
  src/phoenix/server/api/mutations/prompt_mutations.py
Labels: size:M

#6045 fix: allow import of LLMRelationalEvaluator
  src/phoenix/experiments/evaluators/__init__.py
Labels: size:XS

#6048 chore(main): release arize-phoenix 7.7.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6053 ci: Update docker-build-experimental.yml
  .github/workflows/docker-build-experimental.yml
Labels: size:XS

#6049 feat: Prettify mutations with user facing errors
  app/src/components/dataset/CreateDatasetForm.tsx
  app/src/components/dataset/NewDatasetButton.tsx
  app/src/pages/dataset/AddDatasetExampleDialog.tsx
  app/src/pages/datasets/DatasetsPage.tsx
  app/src/pages/datasets/DatasetsTable.tsx
  app/src/pages/examples/ExampleSelectionToolbar.tsx
  app/src/pages/experiments/ExperimentSelectionToolbar.tsx
  app/src/pages/project/SpanSelectionToolbar.tsx
  app/src/pages/settings/DeleteUserDialog.tsx
  app/src/pages/settings/SystemAPIKeysTable.tsx
  app/src/pages/settings/UserAPIKeysTable.tsx
  app/src/pages/settings/UsersCard.tsx
  app/src/pages/trace/SpanToDatasetExampleDialog.tsx
Labels: size:M

#5616 feat: Audio evals & data processor for llm_classify()
  packages/phoenix-evals/pyproject.toml
  packages/phoenix-evals/src/phoenix/evals/classify.py
  packages/phoenix-evals/src/phoenix/evals/default_audio_templates.py
  packages/phoenix-evals/src/phoenix/evals/default_templates.py
  packages/phoenix-evals/src/phoenix/evals/exceptions.py
  packages/phoenix-evals/src/phoenix/evals/models/openai.py
  packages/phoenix-evals/src/phoenix/evals/templates.py
  packages/phoenix-evals/src/phoenix/evals/utils.py
  packages/phoenix-evals/tests/phoenix/evals/functions/test_classify.py
  packages/phoenix-evals/tests/phoenix/evals/test_utils.py
Labels: size:XL

#6033 feat: Resolve versions on Prompt
  app/schema.graphql
  src/phoenix/server/api/types/Prompt.py
Labels: size:S

#6069 feat: Support image template parts in `phoenix-evals`
  packages/phoenix-evals/src/phoenix/evals/templates.py
Labels: size:XS

#6068 chore(main): release arize-phoenix-evals 0.19.0
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#6027 feat(prompts): Break message content into parts
  .github/workflows/python-CI.yml
  app/schema.graphql
  app/src/pages/playground/UpsertPromptFromTemplateDialog.tsx
  app/src/pages/playground/__generated__/UpsertPromptFromTemplateDialogCreateMutation.graphql.ts
  app/src/pages/playground/__generated__/UpsertPromptFromTemplateDialogUpdateMutation.graphql.ts
  app/src/pages/playground/__generated__/fetchPlaygroundPromptQuery.graphql.ts
  app/src/pages/playground/fetchPlaygroundPrompt.ts
  app/src/pages/prompt/PromptChatMessagesCard.tsx
  app/src/pages/prompt/PromptCodeExportCard.tsx
  app/src/pages/prompt/__generated__/PromptChatMessagesCard__main.graphql.ts
  app/src/pages/prompt/__generated__/PromptCodeExportCard__main.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts
  requirements/canary/sdk/anthropic.txt
  requirements/canary/sdk/common.txt
  requirements/canary/sdk/openai.txt
  requirements/canary/sdk/vertexai.txt
  schemas/openapi.json
  src/phoenix/server/api/helpers/prompts/models.py
  src/phoenix/server/api/input_types/PromptVersionInput.py
  src/phoenix/server/api/types/PromptVersionTemplate.py
  tests/canary/__init__.py
  tests/canary/conftest.py
  tests/canary/sdk/__init__.py
  tests/canary/sdk/anthropic/__init__.py
  tests/canary/sdk/anthropic/conftest.py
  tests/canary/sdk/anthropic/mypy.ini
  tests/canary/sdk/anthropic/pytest.ini
  tests/canary/sdk/anthropic/test_chat_message.py
  tests/canary/sdk/conftest.py
  tests/canary/sdk/openai/__init__.py
  tests/canary/sdk/openai/conftest.py
  tests/canary/sdk/openai/mypy.ini
  tests/canary/sdk/openai/pytest.ini
  tests/canary/sdk/openai/test_chat_message.py
  tests/canary/sdk/vertexai/__init__.py
  tests/canary/sdk/vertexai/conftest.py
  tests/canary/sdk/vertexai/mypy.ini
  tests/canary/sdk/vertexai/pytest.ini
  tests/canary/sdk/vertexai/test_chat_message.py
  tests/integration/auth/test_auth.py
  tests/unit/server/api/mutations/test_prompt_mutations.py
  tests/unit/server/api/routers/v1/test_prompts.py
  tox.ini
  uv.lock
Labels: size:XXL

#6081 fix(playground): remove gpt-3.5-turbo-instruct
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:XS

#6073 feat(prompts): delete prompt
  app/schema.graphql
  app/src/pages/prompts/DeletePromptDialog.tsx
  app/src/pages/prompts/PromptActionMenu.tsx
  app/src/pages/prompts/PromptsTable.tsx
  app/src/pages/prompts/__generated__/DeletePromptDialogMutation.graphql.ts
  src/phoenix/server/api/mutations/prompt_mutations.py
Labels: size:XL

#6066 fix(prompts): refetch tags after set
  app/src/constants/promptConstants.ts
  app/src/pages/prompt/TagPromptVersionButton.tsx
  app/src/pages/prompt/__generated__/TagPromptVersionButtonSetTagMutation.graphql.ts
  app/src/pages/prompts/PromptsPage.tsx
Labels: size:L

#6087 refactor(prompts): add `Identifier` scalar with regex validation
  app/relay.config.js
  app/schema.graphql
  src/phoenix/db/models.py
  src/phoenix/db/types/__init__.py
  src/phoenix/db/types/identifier.py
  src/phoenix/server/api/mutations/prompt_mutations.py
  src/phoenix/server/api/mutations/prompt_version_tag_mutations.py
  src/phoenix/server/api/routers/v1/prompts.py
  src/phoenix/server/api/types/Identifier.py
  src/phoenix/server/api/types/Prompt.py
  src/phoenix/server/api/types/PromptVersionTag.py
  tests/integration/db_migrations/test_autoincrement_primary_keys.py
  tests/unit/db/types/__init__.py
  tests/unit/db/types/test_identifier.py
  tests/unit/server/api/mutations/test_prompt_mutations.py
  tests/unit/server/api/routers/v1/test_prompts.py
Labels: size:L

#6084 feat(prompts): Save and display playground instances as multi-part content prompts
  app/src/pages/playground/PlaygroundChatTemplate.tsx
  app/src/pages/playground/UpsertPromptFromTemplateDialog.tsx
  app/src/pages/playground/__generated__/fetchPlaygroundPromptQuery.graphql.ts
  app/src/pages/playground/__tests__/playgroundUtils.test.ts
  app/src/pages/playground/fetchPlaygroundPrompt.ts
  app/src/pages/playground/playgroundUtils.ts
  app/src/pages/prompt/ChatTemplateMessage.tsx
  app/src/pages/prompt/ChatTemplateMessageCard.tsx
  app/src/pages/prompt/PromptChatMessagesCard.tsx
  app/src/pages/prompt/__generated__/PromptChatMessagesCard__main.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts
  app/src/schemas/promptSchemas.ts
  app/src/schemas/toolCallSchemas.ts
  app/src/utils/promptUtils.ts
Labels: size:XL

#6091 refactor(prompts): Use query parameters for datasetId and exampleId
  app/src/Routes.tsx
  app/src/pages/example/ExampleDetailsDialog.tsx
  app/src/pages/experiment/ExperimentCompareTable.tsx
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundDatasetExamplesTable.tsx
  app/src/pages/playground/PlaygroundDatasetPicker.tsx
  app/src/pages/playground/PlaygroundExamplePage.tsx
Labels: size:M

#6083 fix(components): fix button size and variance props
  app/src/components/button/Button.tsx
  app/src/components/types/sizing.ts
  app/src/components/types/variance.ts
Labels: size:S, size:M

#6071 feat: Add GET /prompts route to REST API
  schemas/openapi.json
  src/phoenix/server/api/routers/v1/prompts.py
Labels: size:L

#6093 feat(prompts): Improve post-save prompt ux
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PromptComboBox.tsx
  app/src/pages/playground/UpsertPromptFromTemplateDialog.tsx
Labels: size:M

#6097 feat(prompts): display author, tags, etc. in version list
  app/src/components/disclosure/styles.tsx
  app/src/hooks/useChatMessageStyles.ts
  app/src/pages/playground/PlaygroundTemplate.tsx
  app/src/pages/prompt/PromptChatMessagesCard.tsx
  app/src/pages/prompt/PromptIndexPage.tsx
  app/src/pages/prompt/PromptInvocationParameters.tsx
  app/src/pages/prompt/PromptLatestVersionsList.tsx
  app/src/pages/prompt/PromptOutputSchema.tsx
  app/src/pages/prompt/PromptTools.tsx
  app/src/pages/prompt/PromptVersionDetailsPage.tsx
  app/src/pages/prompt/PromptVersionSummary.tsx
  app/src/pages/prompt/PromptVersionTagsList.tsx
  app/src/pages/prompt/PromptVersionsList.tsx
  app/src/pages/prompt/__generated__/PromptLatestVersionsListFragment.graphql.ts
  app/src/pages/prompt/__generated__/PromptVersionSummaryFragment.graphql.ts
  app/src/pages/prompt/__generated__/PromptVersionsList__main.graphql.ts
  app/src/pages/prompt/__generated__/TagPromptVersionButtonSetTagMutation.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  app/stories/Disclosure.stories.tsx
Labels: size:XL

#6104 feat(prompts): Display basic LLM details on Prompt Details pages
  app/src/pages/prompt/PromptLLM.tsx
  app/src/pages/prompt/PromptModelConfigurationCard.tsx
  app/src/pages/prompt/__generated__/PromptLLM__main.graphql.ts
  app/src/pages/prompt/__generated__/PromptModelConfigurationCard__main.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts
Labels: size:L

#6103 fix: correct errors in run experiment python code snippet
  app/src/pages/dataset/RunExperimentButton.tsx
Labels: size:XS

#6064 chore(main): release arize-phoenix 7.8.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6116 fix: reduce query memory usage in DatasetExampleRevisionsDataLoader
  src/phoenix/server/api/dataloaders/dataset_example_revisions.py
Labels: size:M

#6117 chore(main): release arize-phoenix 7.8.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6121 docs: add smolagents to the readme
  README.md
Labels: size:XS

#6126 chore(components): move to having design tokens in-app
  app/.storybook/preview.tsx
  app/src/App.tsx
  app/src/GlobalStyles.tsx
Labels: size:XXL

#6102 fix: local variable 'prompt_message' referenced before assignment
  packages/phoenix-evals/src/phoenix/evals/templates.py
Labels: triage, size:XS

#6110 feat: Add support for o1 dev messages + reasoning param
  app/schema.graphql
  app/src/pages/playground/__generated__/ModelSupportedParamsFetcherQuery.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableMutation.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundDatasetExamplesTableSubscription.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundOutputMutation.graphql.ts
  app/src/pages/playground/__generated__/PlaygroundOutputSubscription.graphql.ts
  app/src/pages/playground/__generated__/spanPlaygroundPageLoaderQuery.graphql.ts
  src/phoenix/server/api/helpers/playground_clients.py
  src/phoenix/server/api/input_types/InvocationParameters.py
  tox.ini
Labels: size:M

#6128 chore: Add regression test for alternate delimiters
  packages/phoenix-evals/tests/phoenix/evals/templates/test_template.py
Labels: size:S

#6036 feat(components): date and time fields
  app/src/GlobalStyles.tsx
  app/src/components/combobox/styles.tsx
  app/src/components/datetime/DateField.tsx
  app/src/components/datetime/TimeField.tsx
  app/src/components/datetime/index.tsx
  app/src/components/field/styles.ts
  app/src/components/index.tsx
  app/stories/DateField.stories.tsx
  app/stories/Gallery.stories.tsx
  app/stories/TimeField.stories.tsx
Labels: size:L

#6132 feat(prompts): Convert from Prompt message schema to LLM Provider schema for code snippets
  app/src/pages/prompt/PromptCodeExportCard.tsx
  app/src/pages/prompt/__generated__/PromptCodeExportCard__main.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts
  app/src/pages/prompt/promptCodeSnippets.tsx
  app/src/schemas/messageSchemas.ts
Labels: size:XL

#6120 chore(main): release arize-phoenix 7.9.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6067 feat: Explicit OTEL protocol override
  packages/phoenix-otel/README.md
  packages/phoenix-otel/src/phoenix/otel/otel.py
Labels: size:L

#6134 fix: Allow experiment table resize for large inputs
  app/src/pages/experiment/ExperimentCompareTable.tsx
Labels: size:XS

#6146 fix: Handle default protocol
  packages/phoenix-otel/src/phoenix/otel/otel.py
Labels: size:XS

#6135 fix: handle span events as ndarray for `TraceDataset.to_span`
  src/phoenix/trace/trace_dataset.py
  tests/unit/trace/test_trace_dataset.py
Labels: size:M

#6147 feat: Add tags with prompt version create
  app/schema.graphql
  app/src/pages/playground/__generated__/UpsertPromptFromTemplateDialogUpdateMutation.graphql.ts
  src/phoenix/server/api/mutations/prompt_mutations.py
  src/phoenix/server/api/mutations/prompt_version_tag_mutations.py
Labels: size:M

#6154 refactor(gql): make start and end times optional for graphql TimeRange input
  app/schema.graphql
  app/src/pages/dimension/__generated__/DimensionCardinalityTimeSeriesQuery.graphql.ts
  app/src/pages/dimension/__generated__/DimensionCountTimeSeriesQuery.graphql.ts
  app/src/pages/dimension/__generated__/DimensionDriftBreakdownSegmentBarChartQuery.graphql.ts
  app/src/pages/dimension/__generated__/DimensionDriftTimeSeriesQuery.graphql.ts
  app/src/pages/dimension/__generated__/DimensionPageQuery.graphql.ts
  app/src/pages/dimension/__generated__/DimensionPercentEmptyTimeSeriesQuery.graphql.ts
  app/src/pages/dimension/__generated__/DimensionQuantilesTimeSeriesQuery.graphql.ts
  app/src/pages/embedding/__generated__/EmbeddingPageUMAPQuery.graphql.ts
  app/src/pages/embedding/__generated__/MetricTimeSeriesQuery.graphql.ts
  app/src/pages/project/__generated__/AnnotationSummaryQuery.graphql.ts
  app/src/pages/project/__generated__/AnnotationSummaryValueQuery.graphql.ts
  app/src/pages/project/__generated__/DocumentEvaluationSummaryQuery.graphql.ts
  app/src/pages/project/__generated__/DocumentEvaluationSummaryValueQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectPageHeaderQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectPageQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectPageSessionsQuery.graphql.ts
  app/src/pages/project/__generated__/ProjectPageSpansQuery.graphql.ts
  app/src/pages/project/__generated__/SessionsTableQuery.graphql.ts
  app/src/pages/project/__generated__/SpansTableSpansQuery.graphql.ts
  app/src/pages/project/__generated__/TracesTableQuery.graphql.ts
  app/src/pages/projects/__generated__/ProjectsPageProjectsQuery.graphql.ts
  app/src/pages/projects/__generated__/ProjectsPageQuery.graphql.ts
  src/phoenix/server/api/input_types/Granularity.py
  src/phoenix/server/api/input_types/TimeRange.py
  src/phoenix/server/api/types/Dimension.py
  src/phoenix/server/api/types/EmbeddingDimension.py
  src/phoenix/server/api/types/Model.py
  src/phoenix/server/api/types/TimeSeries.py
  tests/unit/server/api/input_types/test_TimeRange.py
Labels: size:L

#6144 chore(main): release arize-phoenix 7.9.1
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6155 docs: fix typo in readme
  README.md
Labels: size:XS

#6161 fix: incorporate headers from environment for experiment trace span exporter
  src/phoenix/config.py
  src/phoenix/experiments/functions.py
  src/phoenix/utilities/client.py
  src/phoenix/utilities/re.py
Labels: size:M

#5991 docs: extend documentation with keycloak
  docs/deployment/authentication.md
Labels: size:S

#6157 chore(main): release arize-phoenix 7.9.2
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6109 feat(prompts): client helpers for openai and anthropic prompts
  .github/workflows/python-CI.yml
  .gitignore
  packages/phoenix-client/examples/prompts/prompts_for_various_SDKs.ipynb
  packages/phoenix-client/pyproject.toml
  packages/phoenix-client/scripts/codegen/transform.py
  packages/phoenix-client/src/phoenix/client/__generated__/__init__.py
  packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py
  packages/phoenix-client/src/phoenix/client/__init__.py
  packages/phoenix-client/src/phoenix/client/client.py
  packages/phoenix-client/src/phoenix/client/constants.py
  packages/phoenix-client/src/phoenix/client/helpers/__init__.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/__init__.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/anthropic/__init__.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/anthropic/messages.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/openai/__init__.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/openai/chat.py
  packages/phoenix-client/src/phoenix/client/resources/__init__.py
  packages/phoenix-client/src/phoenix/client/resources/prompts/__init__.py
  packages/phoenix-client/src/phoenix/client/types/__init__.py
  packages/phoenix-client/src/phoenix/client/utils/__init__.py
  packages/phoenix-client/src/phoenix/client/utils/config.py
  packages/phoenix-client/src/phoenix/client/utils/parse_env_headers.py
  packages/phoenix-client/src/phoenix/client/utils/prompt.py
  packages/phoenix-client/src/phoenix/client/utils/template_formatters.py
  packages/phoenix-client/tests/__init__.py
  packages/phoenix-client/tests/canary/__init__.py
  packages/phoenix-client/tests/canary/sdk/__init__.py
  packages/phoenix-client/tests/canary/sdk/anthropic/__init__.py
  packages/phoenix-client/tests/canary/sdk/anthropic/conftest.py
  packages/phoenix-client/tests/canary/sdk/anthropic/test_messages.py
  packages/phoenix-client/tests/canary/sdk/openai/__init__.py
  packages/phoenix-client/tests/canary/sdk/openai/conftest.py
  packages/phoenix-client/tests/canary/sdk/openai/test_chat.py
  packages/phoenix-client/tests/canary/sdk/vertexai/__init__.py
  packages/phoenix-client/tests/canary/sdk/vertexai/conftest.py
  requirements/canary/sdk/common.txt
  requirements/canary/sdk/openai.txt
  requirements/packages/phoenix-client.txt
  tox.ini
Labels: size:XXL

#6143 feat(components): Port RadioGroup and ToggleButtonGroup from react aria
  app/.eslintrc.js
  app/src/components/code/CodeLanguageRadioGroup.tsx
  app/src/components/index.tsx
  app/src/components/markdown/MarkdownModeRadioGroup.tsx
  app/src/components/pointcloud/CanvasModeRadioGroup.tsx
  app/src/components/pointcloud/SelectionDisplayRadioGroup.tsx
  app/src/components/pointcloud/SelectionGridSizeRadioGroup.tsx
  app/src/components/radio/Radio.tsx
  app/src/components/radio/RadioGroup.tsx
  app/src/components/radio/index.ts
  app/src/components/toggleButtonGroup/index.ts
  app/src/components/toggleButtonGroup/toggleButton.tsx
  app/src/components/toggleButtonGroup/toggleButtonGroup.tsx
  app/src/pages/playground/MessageContentRadioGroup.tsx
  app/src/pages/playground/Playground.tsx
  app/src/pages/playground/PlaygroundOperationTypeRadioGroup.tsx
  app/src/pages/playground/TemplateLanguageRadioGroup.tsx
  app/src/pages/prompt/PromptCodeExportCard.tsx
  app/stories/RadioGroup.stories.tsx
  app/stories/ToggleButtonGroup.stories.tsx
Labels: size:XL

#6140 fix: use openinference tracer provider in phoenix.otel.register
  packages/phoenix-otel/pyproject.toml
  packages/phoenix-otel/src/phoenix/otel/otel.py
Labels: size:XS

#6162 chore(main): release arize-phoenix-otel 0.7.1
  .release-please-manifest.json
  packages/phoenix-otel/CHANGELOG.md
  packages/phoenix-otel/pyproject.toml
Labels: autorelease: pending, size:S

#6145 feat: Add label color and version metadata
  app/schema.graphql
  src/phoenix/db/migrations/versions/bc8fea3c2bc8_add_prompt_tables.py
  src/phoenix/db/models.py
  src/phoenix/server/api/types/PromptVersion.py
Labels: size:XS

#6100 feat: PromptLabel gql interface
  app/schema.graphql
  src/phoenix/db/migrations/versions/bc8fea3c2bc8_add_prompt_tables.py
  src/phoenix/db/models.py
  src/phoenix/server/api/mutations/__init__.py
  src/phoenix/server/api/mutations/prompt_label_mutations.py
  src/phoenix/server/api/queries.py
  src/phoenix/server/api/types/PromptLabel.py
Labels: size:L

#6165 docs(inernal): add on_call guide
  internal_docs/README.md
  internal_docs/on_call.md
Labels: size:M

#6178 chore: re-build graphql
  app/schema.graphql
  app/src/pages/playground/__generated__/fetchPlaygroundPromptSupportedInvocationParametersQuery.graphql.ts
Labels: size:S

#6184 chore: add description for on call priority levels for bug fixes
  internal_docs/on_call.md
Labels: size:XS

#6167 feat: client get latest prompt version
  packages/phoenix-client/src/phoenix/client/resources/prompts/__init__.py
Labels: size:M

#6181 fix(prompts): drop support for pydantic v1
  pyproject.toml
  src/phoenix/server/api/routers/v1/datasets.py
  src/phoenix/server/api/routers/v1/experiment_evaluations.py
  src/phoenix/server/api/routers/v1/experiment_runs.py
  src/phoenix/server/api/routers/v1/experiments.py
  src/phoenix/server/api/routers/v1/models.py
  src/phoenix/server/api/routers/v1/prompts.py
  src/phoenix/server/api/routers/v1/pydantic_compat.py
  src/phoenix/server/api/routers/v1/spans.py
  src/phoenix/server/api/routers/v1/traces.py
  src/phoenix/server/api/routers/v1/utils.py
  tests/unit/server/api/routers/v1/test_pydantic_compat.py
Labels: size:L

#6185 feat(prompts): add open in playground action button on the table
  app/src/Routes.tsx
  app/src/pages/prompts/PromptsTable.tsx
Labels: size:M

#6156 feat(components): time range form
  app/package.json
  app/pnpm-lock.yaml
  app/src/@types/time.d.ts
  app/src/components/datetime/DateField.tsx
  app/src/components/datetime/TimeRangeForm.tsx
  app/src/components/datetime/index.tsx
  app/src/components/overlay/Popover.tsx
  app/src/components/textfield/TextField.tsx
  app/src/utils/timeFormatUtils.ts
  app/stories/Popover.stories.tsx
  app/stories/TimeRangeForm.stories.tsx
Labels: size:L

#6177 fix(prompts): sqlalchemy types
  app/schema.graphql
  app/src/pages/playground/__generated__/UpsertPromptFromTemplateDialogCreateMutation.graphql.ts
  app/src/pages/playground/__generated__/UpsertPromptFromTemplateDialogUpdateMutation.graphql.ts
  app/src/pages/playground/__generated__/fetchPlaygroundPromptQuery.graphql.ts
  app/src/pages/prompt/__generated__/PromptCodeExportCard__main.graphql.ts
  app/src/pages/prompt/__generated__/PromptOutputSchemaFragment.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
  app/src/pages/prompt/__generated__/promptVersionLoaderQuery.graphql.ts
  packages/phoenix-client/src/phoenix/client/__generated__/v1/__init__.py
  schemas/openapi.json
  src/phoenix/db/models.py
  src/phoenix/server/api/helpers/prompts/models.py
  src/phoenix/server/api/input_types/PromptVersionInput.py
  src/phoenix/server/api/mutations/prompt_mutations.py
  src/phoenix/server/api/routers/v1/prompts.py
  src/phoenix/server/api/types/JSONSchema.py
  src/phoenix/server/api/types/OutputSchema.py
  src/phoenix/server/api/types/PromptVersion.py
  src/phoenix/server/api/types/PromptVersionTemplate.py
  tests/integration/db_migrations/test_autoincrement_primary_keys.py
  tests/unit/server/api/mutations/test_prompt_mutations.py
  tests/unit/server/api/routers/v1/test_prompts.py
Labels: size:L

#6098 feat: Add prompt verions REST route `/prompts/{id}/versions`
  schemas/openapi.json
  src/phoenix/server/api/helpers/playground_clients.py
  src/phoenix/server/api/routers/v1/prompts.py
Labels: size:L

#6203 fix(prompts): exclude empty list of tools in sdk helper functions
  packages/phoenix-client/src/phoenix/client/helpers/sdk/anthropic/messages.py
  packages/phoenix-client/src/phoenix/client/helpers/sdk/openai/chat.py
  tutorials/internal/prompts/hallucination_eval.ipynb
Labels: size:L

#6196 fix(prompts): remove template type from input for create prompt mutations
  app/schema.graphql
  app/src/pages/playground/__generated__/UpsertPromptFromTemplateDialogCreateMutation.graphql.ts
  app/src/pages/playground/__generated__/UpsertPromptFromTemplateDialogUpdateMutation.graphql.ts
  app/src/pages/playground/fetchPlaygroundPrompt.ts
  src/phoenix/server/api/input_types/PromptVersionInput.py
  src/phoenix/server/api/mutations/prompt_mutations.py
  tests/integration/auth/test_auth.py
  tests/unit/server/api/mutations/test_prompt_mutations.py
Labels: size:M

#6204 feat: add regex rule for identifier pattern on ui forms for prompt and tag names
  app/src/pages/playground/SavePromptForm.tsx
  app/src/pages/prompt/NewPromptVersionTagDialog.tsx
  app/src/utils/identifierUtils.ts
  src/phoenix/db/types/identifier.py
  tests/unit/db/types/test_identifier.py
  tests/unit/server/api/routers/v1/test_prompts.py
Labels: size:S

#6205 fix(prompts): use discriminated union for content parts
  schemas/openapi.json
  src/phoenix/server/api/helpers/prompts/models.py
  src/phoenix/server/api/input_types/PromptVersionInput.py
  src/phoenix/server/api/mutations/prompt_mutations.py
  tests/integration/db_migrations/test_autoincrement_primary_keys.py
  tests/unit/server/api/routers/v1/test_prompts.py
Labels: size:L

#6209 Chore: Upgrade wrapt to 1.17.2 for cross-platform compatibility
  pyproject.toml
Labels: size:XS

#6210 chore(main): release arize-phoenix 7.9.3
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6212 fix: add default values for TimeRange graphql input
  app/schema.graphql
  src/phoenix/server/api/input_types/TimeRange.py
Labels: size:XS

#6214 feat: time range selector
  app/schema.graphql
  app/src/GlobalStyles.tsx
  app/src/components/datetime/ConnectedLastNTimeRangePicker.tsx
  app/src/components/datetime/ConnectedTimeRangeSelector.tsx
  app/src/components/datetime/LastNTimeRangeContext.tsx
  app/src/components/datetime/LastNTimeRangePicker.tsx
  app/src/components/datetime/TimeRangeContext.tsx
  app/src/components/datetime/TimeRangeForm.tsx
  app/src/components/datetime/TimeRangeSelector.tsx
  app/src/components/datetime/constants.ts
  app/src/components/datetime/index.tsx
  app/src/components/datetime/types.ts
  app/src/components/datetime/utils.ts
  app/src/components/index.tsx
  app/src/components/listbox/ListBox.tsx
  app/src/components/listbox/index.tsx
  app/src/pages/ProjectsRoot.tsx
  app/src/pages/project/AnnotationSummary.tsx
  app/src/pages/project/DocumentEvaluationSummary.tsx
  app/src/pages/project/ProjectPage.tsx
  app/src/pages/project/ProjectTableEmpty.tsx
  app/src/pages/projects/NewProjectButton.tsx
  app/src/pages/projects/ProjectsPage.tsx
  app/src/utils/timeFormatUtils.ts
  app/stories/ListBox.stories.tsx
  app/stories/TimeRangeSelector.stories.tsx
  src/phoenix/server/api/input_types/TimeRange.py
  src/phoenix/server/api/types/Project.py
Labels: size:XL

#6215 ci: fix type checks by adding anthropic CitationEvent
  pyproject.toml
  requirements/dev.txt
  requirements/type-check.txt
  requirements/unit-tests.txt
  src/phoenix/server/api/helpers/playground_clients.py
Labels: size:S

#6217 fix: Prevent error when parsing invalid json out of tool calls
  app/src/pages/trace/SpanDetails.tsx
Labels: size:S

#6213 chore(main): release arize-phoenix 7.9.4
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:S

#6219 feat(components): Link button
  app/.storybook/preview.tsx
  app/src/components/LinkButton.tsx
  app/src/components/button/Button.tsx
  app/src/components/button/LinkButton.tsx
  app/src/components/button/index.tsx
  app/src/components/button/types.tsx
  app/src/components/index.tsx
  app/src/pages/embedding/PointSelectionTable.tsx
  app/src/pages/example/ExampleDetailsDialog.tsx
  app/src/pages/profile/ViewerProfileCard.tsx
  app/src/pages/prompts/PromptsPage.tsx
  app/src/pages/prompts/PromptsTable.tsx
  app/stories/LinkButton.stories.tsx
Labels: size:L

#6225 feat(prompts): display the cloned prompt in header
  app/src/GlobalStyles.tsx
  app/src/pages/prompt/ClonePromptDialog.tsx
  app/src/pages/prompt/PromptLayout.tsx
  app/src/pages/prompt/__generated__/PromptLayout__main.graphql.ts
  app/src/pages/prompt/__generated__/promptLoaderQuery.graphql.ts
Labels: size:M
