Repository Arize-ai/phoenix, pull requests merged in 2025-10, with the labels that each got.

#9729 chore(main): release arize-phoenix-evals 2.3.0
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#9719 docs: add evals migration cursor rule
  .cursor/rules/evals-migration.mdc
Labels: size:L

#9728 docs(client): fix docstring for get_dataset
  packages/phoenix-client/src/phoenix/client/resources/datasets/__init__.py
Labels: size:S

#9726 feat: dataset label gql update
  app/schema.graphql
  src/phoenix/server/api/mutations/dataset_label_mutations.py
Labels: size:M

#9731 docs: migrating eval notebooks
  tutorials/evals/build_benchmark_dataset_and_custom_evaluator.ipynb
  tutorials/evals/optimizing_llm_as_a_judge_prompts.ipynb
  tutorials/evals/trace_level_evals.ipynb
Labels: size:XL

#9734 chore: Fix dev scripts on linux
  app/package.json
  js/packages/phoenix-mcp/package.json
Labels: size:XS

#9747 feat: dataset label feature flag
  app/src/contexts/FeatureFlagsContext.tsx
Labels: size:XS

#9696 docs(evals): migrate phoenix overview to use new evals 2
  tutorials/ai_evals_course/phoenix_overview.ipynb
Labels: size:L

#9751 docs: point llm ops to phoenix overview
  docs/section-cookbooks/README.md
Labels: size:XS

#9760 refactor: migrate to new span methods
  tutorials/agents/langgraph/evaluate-langgraph-rag-manual-instrumentation.py
  tutorials/agents/langgraph/langgraph_orchestrator.ipynb
  tutorials/agents/langgraph/langgraph_parallel.ipynb
  tutorials/agents/langgraph/langgraph_promptchaining.ipynb
  tutorials/agents/langgraph/langgraph_router.ipynb
  tutorials/ai_evals_course/hw3_phoenix/phoenix_methods_guide.md
  tutorials/ai_evals_course/hw3_phoenix/scripts/label_data.py
  tutorials/ai_evals_course/hw3_phoenix/scripts/run_full_evaluation.py
  tutorials/ai_evals_course/hw5_phoenix/README.md
  tutorials/ai_evals_course/hw5_phoenix/ai_evals_hw5_solution.ipynb
  tutorials/ai_evals_course/phoenix_overview.ipynb
  tutorials/evals/bedrock_tracing_and_evals_tutorial.ipynb
  tutorials/evals/evals_quickstart.ipynb
  tutorials/evals/evaluate_agent.ipynb
  tutorials/evals/evaluate_rag.ipynb
  tutorials/evals/evaluate_rag_haystack.ipynb
  tutorials/evals/legacy/bedrock_tracing_and_evals_tutorial.ipynb
  tutorials/evals/legacy/evals_quickstart.ipynb
  tutorials/evals/legacy/evaluate_agent.ipynb
  tutorials/evals/legacy/evaluate_rag.ipynb
  tutorials/evals/legacy/evaluate_rag_haystack.ipynb
  tutorials/evals/legacy/openai_agents_cookbook.ipynb
  tutorials/evals/legacy/pydantic-evals.ipynb
  tutorials/evals/legacy/session_level_evals.ipynb
  tutorials/evals/legacy/trace_level_evals.ipynb
  tutorials/evals/openai_agents_cookbook.ipynb
  tutorials/evals/pydantic-evals.ipynb
  tutorials/evals/session_level_evals.ipynb
  tutorials/evals/trace_level_evals.ipynb
  tutorials/integrations/amazon_bedrock_agents_tracing_and_evals.ipynb
  tutorials/integrations/evaluating_traces_cleanlabTLM.ipynb
  tutorials/integrations/tracing_and_evals_weaviate.ipynb
  tutorials/llm_application_tracing_evaluating_and_analysis.ipynb
  tutorials/llm_ops_overview.ipynb
  tutorials/ragas_retrieval_evals_tutorial.ipynb
  tutorials/tracing/langchain_tracing_tutorial.ipynb
  tutorials/tracing/langchain_vertex_ai_tracing_tutorial.ipynb
Labels: size:XXL

#9716 feat: UI cleanup - reduce re-renders
  app/schema.graphql
  app/src/components/dataset/NewDatasetSplitDialog.tsx
  app/src/components/dataset/__generated__/NewDatasetSplitDialogCreateSplitMutation.graphql.ts
  app/src/components/dataset/__generated__/NewDatasetSplitDialogCreateSplitWithExamplesMutation.graphql.ts
  app/src/components/datasetSplit/ManageDatasetSplitsDialog.tsx
  app/src/pages/examples/ExampleSelectionToolbar.tsx
  app/src/pages/examples/__generated__/ExampleSelectionToolbarAddDatasetExamplesToDatasetSplitsMutation.graphql.ts
  app/src/pages/examples/__generated__/ExampleSelectionToolbarRemoveDatasetExamplesFromDatasetSplitMutation.graphql.ts
  src/phoenix/server/api/mutations/dataset_split_mutations.py
  src/phoenix/server/api/types/DatasetExample.py
Labels: size:XL

#9739 chore(main): release arize-phoenix-evals 2.4.0
  .release-please-manifest.json
  packages/phoenix-evals/CHANGELOG.md
  packages/phoenix-evals/pyproject.toml
Labels: autorelease: pending, size:S

#9612 feat: Improve binding ergonomics
  packages/phoenix-evals/src/phoenix/evals/evaluators.py
Labels: size:S

#9732 fix: break up notification circular imports
  app/src/App.tsx
  app/src/Routes.tsx
  app/src/components/toast/Toast.tsx
  app/src/components/toast/ToastRegion.tsx
  app/src/contexts/NotificationContext/NotificationContext.tsx
  app/src/pages/RootLayout.tsx
  app/src/pages/playground/playgroundUtils.ts
  app/stories/Toast.stories.tsx
  app/stories/ToastRegion.stories.tsx
Labels: size:L

#9701 feat: support more providers with LLM
  packages/phoenix-evals/src/phoenix/evals/llm/adapters/litellm/adapter.py
  packages/phoenix-evals/src/phoenix/evals/llm/adapters/litellm/factories.py
  packages/phoenix-evals/src/phoenix/evals/llm/adapters/openai/factories.py
Labels: size:M

#9777 refactor: change view experiment to link button
  app/src/pages/playground/PlaygroundDatasetSection.tsx
Labels: size:S

#9775 fix: erroneous dedup key for annotations
  src/phoenix/db/insertion/document_annotation.py
  src/phoenix/db/insertion/session_annotation.py
  src/phoenix/db/insertion/span_annotation.py
  src/phoenix/db/insertion/trace_annotation.py
  src/phoenix/db/insertion/types.py
  tests/integration/client/test_annotations.py
Labels: size:L

#9717 chore(main): release arize-phoenix 12.2.0
  .release-please-manifest.json
  CHANGELOG.md
  src/phoenix/version.py
Labels: autorelease: pending, size:M

#9781 chore: Upgrade react-aria and react-aria-components
  app/package.json
  app/pnpm-lock.yaml
  app/src/pages/playground/ModelProviderSelect.tsx
  app/src/pages/settings/UsersTable.tsx
Labels: size:S

#9788 feat: datasets table label column
  app/src/pages/datasets/DatasetsTable.tsx
  app/src/pages/datasets/__generated__/DatasetsPageQuery.graphql.ts
  app/src/pages/datasets/__generated__/DatasetsTableDatasetsQuery.graphql.ts
  app/src/pages/datasets/__generated__/DatasetsTable_datasets.graphql.ts
Labels: size:L

#9789 fix: datasets table feature flag typing
  app/src/pages/datasets/DatasetsTable.tsx
Labels: size:XS

#9763 fix: improve error handling for OIDC
  src/phoenix/server/api/routers/oauth2.py
  src/phoenix/server/oauth2.py
Labels: size:M

#9800 feat: Add groundhog2k postgres repo
  .github/workflows/helm-release.yaml
Labels: size:XS

#9817 fix: allow new project for v1/spans ingestion
  src/phoenix/server/api/routers/v1/spans.py
  tests/integration/client/test_spans.py
Labels: size:M

#9816 refactor: use numeric http status code to avoid deprecation warnings
  src/phoenix/server/api/routers/auth.py
  src/phoenix/server/api/routers/oauth2.py
  src/phoenix/server/api/routers/v1/__init__.py
  src/phoenix/server/api/routers/v1/annotation_configs.py
  src/phoenix/server/api/routers/v1/annotations.py
  src/phoenix/server/api/routers/v1/datasets.py
  src/phoenix/server/api/routers/v1/documents.py
  src/phoenix/server/api/routers/v1/evaluations.py
  src/phoenix/server/api/routers/v1/experiment_evaluations.py
  src/phoenix/server/api/routers/v1/experiment_runs.py
  src/phoenix/server/api/routers/v1/experiments.py
  src/phoenix/server/api/routers/v1/projects.py
  src/phoenix/server/api/routers/v1/prompts.py
  src/phoenix/server/api/routers/v1/sessions.py
  src/phoenix/server/api/routers/v1/spans.py
  src/phoenix/server/api/routers/v1/traces.py
  src/phoenix/server/api/routers/v1/users.py
  src/phoenix/server/api/routers/v1/utils.py
  src/phoenix/server/app.py
  src/phoenix/server/authorization.py
  src/phoenix/server/bearer_auth.py
  tests/unit/server/api/routers/v1/test_annotation_configs.py
  tests/unit/server/test_authorization.py
Labels: size:XL

#9450 chore: create subsections for ERD
  src/phoenix/db/README.md
Labels: size:XL

#9826 docs: updating notebooks to phoenix cloud
  tutorials/evals/bedrock_tracing_and_evals_tutorial.ipynb
  tutorials/evals/evaluate_agent.ipynb
  tutorials/evals/evaluate_rag_haystack.ipynb
  tutorials/evals/openai_agents_cookbook.ipynb
  tutorials/evals/pydantic-evals.ipynb
  tutorials/experiments/agents-cookbook.ipynb
  tutorials/experiments/generating_synthetic_datasets.ipynb
Labels: size:XXL

#9545 feat: add PKCE for Oauth2 OIDC
  pyproject.toml
  requirements/type-check.txt
  src/phoenix/auth.py
  src/phoenix/config.py
  src/phoenix/server/api/routers/oauth2.py
  src/phoenix/server/oauth2.py
  tests/integration/_helpers.py
  tests/integration/auth/conftest.py
  tests/integration/auth/test_auth.py
  tests/unit/server/api/routers/test_oauth2.py
  tests/unit/server/test_oauth2.py
  tests/unit/test_config.py
Labels: size:XXL

#9831 feat: Support invocation params in ClassificationEvaluators
  packages/phoenix-evals/src/phoenix/evals/evaluators.py
Labels: size:XS
